/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model.impl;

import com.ifl.rapid.customer.model.CRM_Trn_Phone;
import com.ifl.rapid.customer.model.CRM_Trn_PhoneModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CRM_Trn_Phone service. Represents a row in the &quot;CRM_Trn_Phone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifl.rapid.customer.model.CRM_Trn_PhoneModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CRM_Trn_PhoneImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CRM_Trn_PhoneImpl
 * @see com.ifl.rapid.customer.model.CRM_Trn_Phone
 * @see com.ifl.rapid.customer.model.CRM_Trn_PhoneModel
 * @generated
 */
public class CRM_Trn_PhoneModelImpl extends BaseModelImpl<CRM_Trn_Phone>
	implements CRM_Trn_PhoneModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a c r m_ trn_ phone model instance should use the {@link com.ifl.rapid.customer.model.CRM_Trn_Phone} interface instead.
	 */
	public static final String TABLE_NAME = "CRM_Trn_Phone";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PhoneId", Types.INTEGER },
			{ "ContactId", Types.INTEGER },
			{ "PhoneType", Types.INTEGER },
			{ "PhoneNumber", Types.VARCHAR },
			{ "CreatedBy", Types.VARCHAR },
			{ "CreatedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "IsActive", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CRM_Trn_Phone (PhoneId INTEGER not null primary key IDENTITY,ContactId INTEGER,PhoneType INTEGER,PhoneNumber VARCHAR(75) null,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null,IsActive VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CRM_Trn_Phone";
	public static final String ORDER_BY_JPQL = " ORDER BY crm_Trn_Phone.PhoneId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CRM_Trn_Phone.PhoneId ASC";
	public static final String DATA_SOURCE = "servicesDataSourceService";
	public static final String SESSION_FACTORY = "servicesSessionFactoryService";
	public static final String TX_MANAGER = "servicesTransactionManagerService";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifl.rapid.customer.model.CRM_Trn_Phone"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifl.rapid.customer.model.CRM_Trn_Phone"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ifl.rapid.customer.model.CRM_Trn_Phone"),
			true);
	public static long CONTACTID_COLUMN_BITMASK = 1L;
	public static long PHONEID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifl.rapid.customer.model.CRM_Trn_Phone"));

	public CRM_Trn_PhoneModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _PhoneId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setPhoneId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PhoneId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CRM_Trn_Phone.class;
	}

	@Override
	public String getModelClassName() {
		return CRM_Trn_Phone.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PhoneId", getPhoneId());
		attributes.put("ContactId", getContactId());
		attributes.put("PhoneType", getPhoneType());
		attributes.put("PhoneNumber", getPhoneNumber());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("CreatedDate", getCreatedDate());
		attributes.put("ModifiedBy", getModifiedBy());
		attributes.put("ModifiedDate", getModifiedDate());
		attributes.put("IsActive", getIsActive());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer PhoneId = (Integer)attributes.get("PhoneId");

		if (PhoneId != null) {
			setPhoneId(PhoneId);
		}

		Integer ContactId = (Integer)attributes.get("ContactId");

		if (ContactId != null) {
			setContactId(ContactId);
		}

		Integer PhoneType = (Integer)attributes.get("PhoneType");

		if (PhoneType != null) {
			setPhoneType(PhoneType);
		}

		String PhoneNumber = (String)attributes.get("PhoneNumber");

		if (PhoneNumber != null) {
			setPhoneNumber(PhoneNumber);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date CreatedDate = (Date)attributes.get("CreatedDate");

		if (CreatedDate != null) {
			setCreatedDate(CreatedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}

		String IsActive = (String)attributes.get("IsActive");

		if (IsActive != null) {
			setIsActive(IsActive);
		}
	}

	@Override
	public int getPhoneId() {
		return _PhoneId;
	}

	@Override
	public void setPhoneId(int PhoneId) {
		_columnBitmask |= PHONEID_COLUMN_BITMASK;

		if (!_setOriginalPhoneId) {
			_setOriginalPhoneId = true;

			_originalPhoneId = _PhoneId;
		}

		_PhoneId = PhoneId;
	}

	public int getOriginalPhoneId() {
		return _originalPhoneId;
	}

	@Override
	public int getContactId() {
		return _ContactId;
	}

	@Override
	public void setContactId(int ContactId) {
		_columnBitmask |= CONTACTID_COLUMN_BITMASK;

		if (!_setOriginalContactId) {
			_setOriginalContactId = true;

			_originalContactId = _ContactId;
		}

		_ContactId = ContactId;
	}

	public int getOriginalContactId() {
		return _originalContactId;
	}

	@Override
	public int getPhoneType() {
		return _PhoneType;
	}

	@Override
	public void setPhoneType(int PhoneType) {
		_PhoneType = PhoneType;
	}

	@Override
	public String getPhoneNumber() {
		if (_PhoneNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _PhoneNumber;
		}
	}

	@Override
	public void setPhoneNumber(String PhoneNumber) {
		_PhoneNumber = PhoneNumber;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getIsActive() {
		if (_IsActive == null) {
			return StringPool.BLANK;
		}
		else {
			return _IsActive;
		}
	}

	@Override
	public void setIsActive(String IsActive) {
		_IsActive = IsActive;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CRM_Trn_Phone toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CRM_Trn_Phone)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CRM_Trn_PhoneImpl crm_Trn_PhoneImpl = new CRM_Trn_PhoneImpl();

		crm_Trn_PhoneImpl.setPhoneId(getPhoneId());
		crm_Trn_PhoneImpl.setContactId(getContactId());
		crm_Trn_PhoneImpl.setPhoneType(getPhoneType());
		crm_Trn_PhoneImpl.setPhoneNumber(getPhoneNumber());
		crm_Trn_PhoneImpl.setCreatedBy(getCreatedBy());
		crm_Trn_PhoneImpl.setCreatedDate(getCreatedDate());
		crm_Trn_PhoneImpl.setModifiedBy(getModifiedBy());
		crm_Trn_PhoneImpl.setModifiedDate(getModifiedDate());
		crm_Trn_PhoneImpl.setIsActive(getIsActive());

		crm_Trn_PhoneImpl.resetOriginalValues();

		return crm_Trn_PhoneImpl;
	}

	@Override
	public int compareTo(CRM_Trn_Phone crm_Trn_Phone) {
		int primaryKey = crm_Trn_Phone.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CRM_Trn_Phone)) {
			return false;
		}

		CRM_Trn_Phone crm_Trn_Phone = (CRM_Trn_Phone)obj;

		int primaryKey = crm_Trn_Phone.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CRM_Trn_PhoneModelImpl crm_Trn_PhoneModelImpl = this;

		crm_Trn_PhoneModelImpl._originalPhoneId = crm_Trn_PhoneModelImpl._PhoneId;

		crm_Trn_PhoneModelImpl._setOriginalPhoneId = false;

		crm_Trn_PhoneModelImpl._originalContactId = crm_Trn_PhoneModelImpl._ContactId;

		crm_Trn_PhoneModelImpl._setOriginalContactId = false;

		crm_Trn_PhoneModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CRM_Trn_Phone> toCacheModel() {
		CRM_Trn_PhoneCacheModel crm_Trn_PhoneCacheModel = new CRM_Trn_PhoneCacheModel();

		crm_Trn_PhoneCacheModel.PhoneId = getPhoneId();

		crm_Trn_PhoneCacheModel.ContactId = getContactId();

		crm_Trn_PhoneCacheModel.PhoneType = getPhoneType();

		crm_Trn_PhoneCacheModel.PhoneNumber = getPhoneNumber();

		String PhoneNumber = crm_Trn_PhoneCacheModel.PhoneNumber;

		if ((PhoneNumber != null) && (PhoneNumber.length() == 0)) {
			crm_Trn_PhoneCacheModel.PhoneNumber = null;
		}

		crm_Trn_PhoneCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = crm_Trn_PhoneCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			crm_Trn_PhoneCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			crm_Trn_PhoneCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			crm_Trn_PhoneCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		crm_Trn_PhoneCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = crm_Trn_PhoneCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			crm_Trn_PhoneCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			crm_Trn_PhoneCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			crm_Trn_PhoneCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		crm_Trn_PhoneCacheModel.IsActive = getIsActive();

		String IsActive = crm_Trn_PhoneCacheModel.IsActive;

		if ((IsActive != null) && (IsActive.length() == 0)) {
			crm_Trn_PhoneCacheModel.IsActive = null;
		}

		return crm_Trn_PhoneCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{PhoneId=");
		sb.append(getPhoneId());
		sb.append(", ContactId=");
		sb.append(getContactId());
		sb.append(", PhoneType=");
		sb.append(getPhoneType());
		sb.append(", PhoneNumber=");
		sb.append(getPhoneNumber());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", CreatedDate=");
		sb.append(getCreatedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", IsActive=");
		sb.append(getIsActive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.ifl.rapid.customer.model.CRM_Trn_Phone");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PhoneId</column-name><column-value><![CDATA[");
		sb.append(getPhoneId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ContactId</column-name><column-value><![CDATA[");
		sb.append(getContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PhoneType</column-name><column-value><![CDATA[");
		sb.append(getPhoneType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PhoneNumber</column-name><column-value><![CDATA[");
		sb.append(getPhoneNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IsActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CRM_Trn_Phone.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CRM_Trn_Phone.class
		};
	private int _PhoneId;
	private int _originalPhoneId;
	private boolean _setOriginalPhoneId;
	private int _ContactId;
	private int _originalContactId;
	private boolean _setOriginalContactId;
	private int _PhoneType;
	private String _PhoneNumber;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;
	private String _IsActive;
	private long _columnBitmask;
	private CRM_Trn_Phone _escapedModel;
}