/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model.impl;

import com.ifl.rapid.customer.model.CRMTrnFamilyMember;
import com.ifl.rapid.customer.model.CRMTrnFamilyMemberModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CRMTrnFamilyMember service. Represents a row in the &quot;CRM_Trn_FamilyMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifl.rapid.customer.model.CRMTrnFamilyMemberModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CRMTrnFamilyMemberImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CRMTrnFamilyMemberImpl
 * @see com.ifl.rapid.customer.model.CRMTrnFamilyMember
 * @see com.ifl.rapid.customer.model.CRMTrnFamilyMemberModel
 * @generated
 */
public class CRMTrnFamilyMemberModelImpl extends BaseModelImpl<CRMTrnFamilyMember>
	implements CRMTrnFamilyMemberModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a c r m trn family member model instance should use the {@link com.ifl.rapid.customer.model.CRMTrnFamilyMember} interface instead.
	 */
	public static final String TABLE_NAME = "CRM_Trn_FamilyMember";
	public static final Object[][] TABLE_COLUMNS = {
			{ "FamilyMemberId", Types.INTEGER },
			{ "ContactId", Types.INTEGER },
			{ "MemberId", Types.INTEGER },
			{ "RelationshipId", Types.INTEGER },
			{ "FinanciallyDependent", Types.VARCHAR },
			{ "IsActive", Types.VARCHAR },
			{ "CreatedBy", Types.VARCHAR },
			{ "CreatedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR },
			{ "ModifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table CRM_Trn_FamilyMember (FamilyMemberId INTEGER not null primary key IDENTITY,ContactId INTEGER,MemberId INTEGER,RelationshipId INTEGER,FinanciallyDependent VARCHAR(75) null,IsActive VARCHAR(75) null,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table CRM_Trn_FamilyMember";
	public static final String ORDER_BY_JPQL = " ORDER BY crmTrnFamilyMember.FamilyMemberId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CRM_Trn_FamilyMember.FamilyMemberId ASC";
	public static final String DATA_SOURCE = "servicesDataSourceService";
	public static final String SESSION_FACTORY = "servicesSessionFactoryService";
	public static final String TX_MANAGER = "servicesTransactionManagerService";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifl.rapid.customer.model.CRMTrnFamilyMember"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifl.rapid.customer.model.CRMTrnFamilyMember"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ifl.rapid.customer.model.CRMTrnFamilyMember"),
			true);
	public static long CONTACTID_COLUMN_BITMASK = 1L;
	public static long MEMBERID_COLUMN_BITMASK = 2L;
	public static long FAMILYMEMBERID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifl.rapid.customer.model.CRMTrnFamilyMember"));

	public CRMTrnFamilyMemberModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _FamilyMemberId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setFamilyMemberId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _FamilyMemberId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CRMTrnFamilyMember.class;
	}

	@Override
	public String getModelClassName() {
		return CRMTrnFamilyMember.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("FamilyMemberId", getFamilyMemberId());
		attributes.put("ContactId", getContactId());
		attributes.put("MemberId", getMemberId());
		attributes.put("RelationshipId", getRelationshipId());
		attributes.put("FinanciallyDependent", getFinanciallyDependent());
		attributes.put("IsActive", getIsActive());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("CreatedDate", getCreatedDate());
		attributes.put("ModifiedBy", getModifiedBy());
		attributes.put("ModifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer FamilyMemberId = (Integer)attributes.get("FamilyMemberId");

		if (FamilyMemberId != null) {
			setFamilyMemberId(FamilyMemberId);
		}

		Integer ContactId = (Integer)attributes.get("ContactId");

		if (ContactId != null) {
			setContactId(ContactId);
		}

		Integer MemberId = (Integer)attributes.get("MemberId");

		if (MemberId != null) {
			setMemberId(MemberId);
		}

		Integer RelationshipId = (Integer)attributes.get("RelationshipId");

		if (RelationshipId != null) {
			setRelationshipId(RelationshipId);
		}

		String FinanciallyDependent = (String)attributes.get(
				"FinanciallyDependent");

		if (FinanciallyDependent != null) {
			setFinanciallyDependent(FinanciallyDependent);
		}

		String IsActive = (String)attributes.get("IsActive");

		if (IsActive != null) {
			setIsActive(IsActive);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date CreatedDate = (Date)attributes.get("CreatedDate");

		if (CreatedDate != null) {
			setCreatedDate(CreatedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}
	}

	@Override
	public int getFamilyMemberId() {
		return _FamilyMemberId;
	}

	@Override
	public void setFamilyMemberId(int FamilyMemberId) {
		_FamilyMemberId = FamilyMemberId;
	}

	@Override
	public int getContactId() {
		return _ContactId;
	}

	@Override
	public void setContactId(int ContactId) {
		_columnBitmask |= CONTACTID_COLUMN_BITMASK;

		if (!_setOriginalContactId) {
			_setOriginalContactId = true;

			_originalContactId = _ContactId;
		}

		_ContactId = ContactId;
	}

	public int getOriginalContactId() {
		return _originalContactId;
	}

	@Override
	public int getMemberId() {
		return _MemberId;
	}

	@Override
	public void setMemberId(int MemberId) {
		_columnBitmask |= MEMBERID_COLUMN_BITMASK;

		if (!_setOriginalMemberId) {
			_setOriginalMemberId = true;

			_originalMemberId = _MemberId;
		}

		_MemberId = MemberId;
	}

	public int getOriginalMemberId() {
		return _originalMemberId;
	}

	@Override
	public int getRelationshipId() {
		return _RelationshipId;
	}

	@Override
	public void setRelationshipId(int RelationshipId) {
		_RelationshipId = RelationshipId;
	}

	@Override
	public String getFinanciallyDependent() {
		if (_FinanciallyDependent == null) {
			return StringPool.BLANK;
		}
		else {
			return _FinanciallyDependent;
		}
	}

	@Override
	public void setFinanciallyDependent(String FinanciallyDependent) {
		_FinanciallyDependent = FinanciallyDependent;
	}

	@Override
	public String getIsActive() {
		if (_IsActive == null) {
			return StringPool.BLANK;
		}
		else {
			return _IsActive;
		}
	}

	@Override
	public void setIsActive(String IsActive) {
		_IsActive = IsActive;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CRMTrnFamilyMember toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CRMTrnFamilyMember)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CRMTrnFamilyMemberImpl crmTrnFamilyMemberImpl = new CRMTrnFamilyMemberImpl();

		crmTrnFamilyMemberImpl.setFamilyMemberId(getFamilyMemberId());
		crmTrnFamilyMemberImpl.setContactId(getContactId());
		crmTrnFamilyMemberImpl.setMemberId(getMemberId());
		crmTrnFamilyMemberImpl.setRelationshipId(getRelationshipId());
		crmTrnFamilyMemberImpl.setFinanciallyDependent(getFinanciallyDependent());
		crmTrnFamilyMemberImpl.setIsActive(getIsActive());
		crmTrnFamilyMemberImpl.setCreatedBy(getCreatedBy());
		crmTrnFamilyMemberImpl.setCreatedDate(getCreatedDate());
		crmTrnFamilyMemberImpl.setModifiedBy(getModifiedBy());
		crmTrnFamilyMemberImpl.setModifiedDate(getModifiedDate());

		crmTrnFamilyMemberImpl.resetOriginalValues();

		return crmTrnFamilyMemberImpl;
	}

	@Override
	public int compareTo(CRMTrnFamilyMember crmTrnFamilyMember) {
		int primaryKey = crmTrnFamilyMember.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CRMTrnFamilyMember)) {
			return false;
		}

		CRMTrnFamilyMember crmTrnFamilyMember = (CRMTrnFamilyMember)obj;

		int primaryKey = crmTrnFamilyMember.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CRMTrnFamilyMemberModelImpl crmTrnFamilyMemberModelImpl = this;

		crmTrnFamilyMemberModelImpl._originalContactId = crmTrnFamilyMemberModelImpl._ContactId;

		crmTrnFamilyMemberModelImpl._setOriginalContactId = false;

		crmTrnFamilyMemberModelImpl._originalMemberId = crmTrnFamilyMemberModelImpl._MemberId;

		crmTrnFamilyMemberModelImpl._setOriginalMemberId = false;

		crmTrnFamilyMemberModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CRMTrnFamilyMember> toCacheModel() {
		CRMTrnFamilyMemberCacheModel crmTrnFamilyMemberCacheModel = new CRMTrnFamilyMemberCacheModel();

		crmTrnFamilyMemberCacheModel.FamilyMemberId = getFamilyMemberId();

		crmTrnFamilyMemberCacheModel.ContactId = getContactId();

		crmTrnFamilyMemberCacheModel.MemberId = getMemberId();

		crmTrnFamilyMemberCacheModel.RelationshipId = getRelationshipId();

		crmTrnFamilyMemberCacheModel.FinanciallyDependent = getFinanciallyDependent();

		String FinanciallyDependent = crmTrnFamilyMemberCacheModel.FinanciallyDependent;

		if ((FinanciallyDependent != null) &&
				(FinanciallyDependent.length() == 0)) {
			crmTrnFamilyMemberCacheModel.FinanciallyDependent = null;
		}

		crmTrnFamilyMemberCacheModel.IsActive = getIsActive();

		String IsActive = crmTrnFamilyMemberCacheModel.IsActive;

		if ((IsActive != null) && (IsActive.length() == 0)) {
			crmTrnFamilyMemberCacheModel.IsActive = null;
		}

		crmTrnFamilyMemberCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = crmTrnFamilyMemberCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			crmTrnFamilyMemberCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			crmTrnFamilyMemberCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			crmTrnFamilyMemberCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		crmTrnFamilyMemberCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = crmTrnFamilyMemberCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			crmTrnFamilyMemberCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			crmTrnFamilyMemberCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			crmTrnFamilyMemberCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return crmTrnFamilyMemberCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{FamilyMemberId=");
		sb.append(getFamilyMemberId());
		sb.append(", ContactId=");
		sb.append(getContactId());
		sb.append(", MemberId=");
		sb.append(getMemberId());
		sb.append(", RelationshipId=");
		sb.append(getRelationshipId());
		sb.append(", FinanciallyDependent=");
		sb.append(getFinanciallyDependent());
		sb.append(", IsActive=");
		sb.append(getIsActive());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", CreatedDate=");
		sb.append(getCreatedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.ifl.rapid.customer.model.CRMTrnFamilyMember");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>FamilyMemberId</column-name><column-value><![CDATA[");
		sb.append(getFamilyMemberId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ContactId</column-name><column-value><![CDATA[");
		sb.append(getContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MemberId</column-name><column-value><![CDATA[");
		sb.append(getMemberId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RelationshipId</column-name><column-value><![CDATA[");
		sb.append(getRelationshipId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FinanciallyDependent</column-name><column-value><![CDATA[");
		sb.append(getFinanciallyDependent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IsActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CRMTrnFamilyMember.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CRMTrnFamilyMember.class
		};
	private int _FamilyMemberId;
	private int _ContactId;
	private int _originalContactId;
	private boolean _setOriginalContactId;
	private int _MemberId;
	private int _originalMemberId;
	private boolean _setOriginalMemberId;
	private int _RelationshipId;
	private String _FinanciallyDependent;
	private String _IsActive;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;
	private long _columnBitmask;
	private CRMTrnFamilyMember _escapedModel;
}