/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model.impl;

import com.ifl.rapid.customer.model.QrcTrnServiceRequests;
import com.ifl.rapid.customer.model.QrcTrnServiceRequestsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the QrcTrnServiceRequests service. Represents a row in the &quot;Qrc_Trn_ServiceRequests&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifl.rapid.customer.model.QrcTrnServiceRequestsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QrcTrnServiceRequestsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see QrcTrnServiceRequestsImpl
 * @see com.ifl.rapid.customer.model.QrcTrnServiceRequests
 * @see com.ifl.rapid.customer.model.QrcTrnServiceRequestsModel
 * @generated
 */
public class QrcTrnServiceRequestsModelImpl extends BaseModelImpl<QrcTrnServiceRequests>
	implements QrcTrnServiceRequestsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qrc trn service requests model instance should use the {@link com.ifl.rapid.customer.model.QrcTrnServiceRequests} interface instead.
	 */
	public static final String TABLE_NAME = "Qrc_Trn_ServiceRequests";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ServiceRequestId", Types.INTEGER },
			{ "ContactId", Types.INTEGER },
			{ "SrId", Types.VARCHAR },
			{ "ProcessId", Types.VARCHAR },
			{ "Source", Types.VARCHAR },
			{ "Channel", Types.VARCHAR },
			{ "Priority", Types.VARCHAR },
			{ "PolicyNo", Types.VARCHAR },
			{ "CaseDetails", Types.VARCHAR },
			{ "IsManual", Types.VARCHAR },
			{ "IsLAUpdated", Types.VARCHAR },
			{ "Comments", Types.VARCHAR },
			{ "IsSignVerified", Types.VARCHAR },
			{ "RequestId", Types.INTEGER },
			{ "AssignedTo", Types.INTEGER },
			{ "CreatedContactId", Types.INTEGER },
			{ "HistoryId", Types.INTEGER },
			{ "AddressTypeId", Types.INTEGER },
			{ "IsActive", Types.INTEGER },
			{ "CreatedBy", Types.VARCHAR },
			{ "CreatedDate", Types.TIMESTAMP },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Qrc_Trn_ServiceRequests (ServiceRequestId INTEGER not null primary key IDENTITY,ContactId INTEGER,SrId VARCHAR(75) null,ProcessId VARCHAR(75) null,Source VARCHAR(75) null,Channel VARCHAR(75) null,Priority VARCHAR(75) null,PolicyNo VARCHAR(75) null,CaseDetails VARCHAR(75) null,IsManual VARCHAR(75) null,IsLAUpdated VARCHAR(75) null,Comments VARCHAR(75) null,IsSignVerified VARCHAR(75) null,RequestId INTEGER,AssignedTo INTEGER,CreatedContactId INTEGER,HistoryId INTEGER,AddressTypeId INTEGER,IsActive INTEGER,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Qrc_Trn_ServiceRequests";
	public static final String ORDER_BY_JPQL = " ORDER BY qrcTrnServiceRequests.ServiceRequestId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Qrc_Trn_ServiceRequests.ServiceRequestId ASC";
	public static final String DATA_SOURCE = "servicesDataSourceService";
	public static final String SESSION_FACTORY = "servicesSessionFactoryService";
	public static final String TX_MANAGER = "servicesTransactionManagerService";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifl.rapid.customer.model.QrcTrnServiceRequests"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifl.rapid.customer.model.QrcTrnServiceRequests"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifl.rapid.customer.model.QrcTrnServiceRequests"));

	public QrcTrnServiceRequestsModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _ServiceRequestId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setServiceRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ServiceRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QrcTrnServiceRequests.class;
	}

	@Override
	public String getModelClassName() {
		return QrcTrnServiceRequests.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ServiceRequestId", getServiceRequestId());
		attributes.put("ContactId", getContactId());
		attributes.put("SrId", getSrId());
		attributes.put("ProcessId", getProcessId());
		attributes.put("Source", getSource());
		attributes.put("Channel", getChannel());
		attributes.put("Priority", getPriority());
		attributes.put("PolicyNo", getPolicyNo());
		attributes.put("CaseDetails", getCaseDetails());
		attributes.put("IsManual", getIsManual());
		attributes.put("IsLAUpdated", getIsLAUpdated());
		attributes.put("Comments", getComments());
		attributes.put("IsSignVerified", getIsSignVerified());
		attributes.put("RequestId", getRequestId());
		attributes.put("AssignedTo", getAssignedTo());
		attributes.put("CreatedContactId", getCreatedContactId());
		attributes.put("HistoryId", getHistoryId());
		attributes.put("AddressTypeId", getAddressTypeId());
		attributes.put("IsActive", getIsActive());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("CreatedDate", getCreatedDate());
		attributes.put("ModifiedDate", getModifiedDate());
		attributes.put("ModifiedBy", getModifiedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer ServiceRequestId = (Integer)attributes.get("ServiceRequestId");

		if (ServiceRequestId != null) {
			setServiceRequestId(ServiceRequestId);
		}

		Integer ContactId = (Integer)attributes.get("ContactId");

		if (ContactId != null) {
			setContactId(ContactId);
		}

		String SrId = (String)attributes.get("SrId");

		if (SrId != null) {
			setSrId(SrId);
		}

		String ProcessId = (String)attributes.get("ProcessId");

		if (ProcessId != null) {
			setProcessId(ProcessId);
		}

		String Source = (String)attributes.get("Source");

		if (Source != null) {
			setSource(Source);
		}

		String Channel = (String)attributes.get("Channel");

		if (Channel != null) {
			setChannel(Channel);
		}

		String Priority = (String)attributes.get("Priority");

		if (Priority != null) {
			setPriority(Priority);
		}

		String PolicyNo = (String)attributes.get("PolicyNo");

		if (PolicyNo != null) {
			setPolicyNo(PolicyNo);
		}

		String CaseDetails = (String)attributes.get("CaseDetails");

		if (CaseDetails != null) {
			setCaseDetails(CaseDetails);
		}

		String IsManual = (String)attributes.get("IsManual");

		if (IsManual != null) {
			setIsManual(IsManual);
		}

		String IsLAUpdated = (String)attributes.get("IsLAUpdated");

		if (IsLAUpdated != null) {
			setIsLAUpdated(IsLAUpdated);
		}

		String Comments = (String)attributes.get("Comments");

		if (Comments != null) {
			setComments(Comments);
		}

		String IsSignVerified = (String)attributes.get("IsSignVerified");

		if (IsSignVerified != null) {
			setIsSignVerified(IsSignVerified);
		}

		Integer RequestId = (Integer)attributes.get("RequestId");

		if (RequestId != null) {
			setRequestId(RequestId);
		}

		Integer AssignedTo = (Integer)attributes.get("AssignedTo");

		if (AssignedTo != null) {
			setAssignedTo(AssignedTo);
		}

		Integer CreatedContactId = (Integer)attributes.get("CreatedContactId");

		if (CreatedContactId != null) {
			setCreatedContactId(CreatedContactId);
		}

		Integer HistoryId = (Integer)attributes.get("HistoryId");

		if (HistoryId != null) {
			setHistoryId(HistoryId);
		}

		Integer AddressTypeId = (Integer)attributes.get("AddressTypeId");

		if (AddressTypeId != null) {
			setAddressTypeId(AddressTypeId);
		}

		Integer IsActive = (Integer)attributes.get("IsActive");

		if (IsActive != null) {
			setIsActive(IsActive);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date CreatedDate = (Date)attributes.get("CreatedDate");

		if (CreatedDate != null) {
			setCreatedDate(CreatedDate);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}
	}

	@Override
	public int getServiceRequestId() {
		return _ServiceRequestId;
	}

	@Override
	public void setServiceRequestId(int ServiceRequestId) {
		_ServiceRequestId = ServiceRequestId;
	}

	@Override
	public int getContactId() {
		return _ContactId;
	}

	@Override
	public void setContactId(int ContactId) {
		_ContactId = ContactId;
	}

	@Override
	public String getSrId() {
		if (_SrId == null) {
			return StringPool.BLANK;
		}
		else {
			return _SrId;
		}
	}

	@Override
	public void setSrId(String SrId) {
		_SrId = SrId;
	}

	@Override
	public String getProcessId() {
		if (_ProcessId == null) {
			return StringPool.BLANK;
		}
		else {
			return _ProcessId;
		}
	}

	@Override
	public void setProcessId(String ProcessId) {
		_ProcessId = ProcessId;
	}

	@Override
	public String getSource() {
		if (_Source == null) {
			return StringPool.BLANK;
		}
		else {
			return _Source;
		}
	}

	@Override
	public void setSource(String Source) {
		_Source = Source;
	}

	@Override
	public String getChannel() {
		if (_Channel == null) {
			return StringPool.BLANK;
		}
		else {
			return _Channel;
		}
	}

	@Override
	public void setChannel(String Channel) {
		_Channel = Channel;
	}

	@Override
	public String getPriority() {
		if (_Priority == null) {
			return StringPool.BLANK;
		}
		else {
			return _Priority;
		}
	}

	@Override
	public void setPriority(String Priority) {
		_Priority = Priority;
	}

	@Override
	public String getPolicyNo() {
		if (_PolicyNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _PolicyNo;
		}
	}

	@Override
	public void setPolicyNo(String PolicyNo) {
		_PolicyNo = PolicyNo;
	}

	@Override
	public String getCaseDetails() {
		if (_CaseDetails == null) {
			return StringPool.BLANK;
		}
		else {
			return _CaseDetails;
		}
	}

	@Override
	public void setCaseDetails(String CaseDetails) {
		_CaseDetails = CaseDetails;
	}

	@Override
	public String getIsManual() {
		if (_IsManual == null) {
			return StringPool.BLANK;
		}
		else {
			return _IsManual;
		}
	}

	@Override
	public void setIsManual(String IsManual) {
		_IsManual = IsManual;
	}

	@Override
	public String getIsLAUpdated() {
		if (_IsLAUpdated == null) {
			return StringPool.BLANK;
		}
		else {
			return _IsLAUpdated;
		}
	}

	@Override
	public void setIsLAUpdated(String IsLAUpdated) {
		_IsLAUpdated = IsLAUpdated;
	}

	@Override
	public String getComments() {
		if (_Comments == null) {
			return StringPool.BLANK;
		}
		else {
			return _Comments;
		}
	}

	@Override
	public void setComments(String Comments) {
		_Comments = Comments;
	}

	@Override
	public String getIsSignVerified() {
		if (_IsSignVerified == null) {
			return StringPool.BLANK;
		}
		else {
			return _IsSignVerified;
		}
	}

	@Override
	public void setIsSignVerified(String IsSignVerified) {
		_IsSignVerified = IsSignVerified;
	}

	@Override
	public int getRequestId() {
		return _RequestId;
	}

	@Override
	public void setRequestId(int RequestId) {
		_RequestId = RequestId;
	}

	@Override
	public int getAssignedTo() {
		return _AssignedTo;
	}

	@Override
	public void setAssignedTo(int AssignedTo) {
		_AssignedTo = AssignedTo;
	}

	@Override
	public int getCreatedContactId() {
		return _CreatedContactId;
	}

	@Override
	public void setCreatedContactId(int CreatedContactId) {
		_CreatedContactId = CreatedContactId;
	}

	@Override
	public int getHistoryId() {
		return _HistoryId;
	}

	@Override
	public void setHistoryId(int HistoryId) {
		_HistoryId = HistoryId;
	}

	@Override
	public int getAddressTypeId() {
		return _AddressTypeId;
	}

	@Override
	public void setAddressTypeId(int AddressTypeId) {
		_AddressTypeId = AddressTypeId;
	}

	@Override
	public int getIsActive() {
		return _IsActive;
	}

	@Override
	public void setIsActive(int IsActive) {
		_IsActive = IsActive;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		_CreatedDate = CreatedDate;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public QrcTrnServiceRequests toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QrcTrnServiceRequests)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QrcTrnServiceRequestsImpl qrcTrnServiceRequestsImpl = new QrcTrnServiceRequestsImpl();

		qrcTrnServiceRequestsImpl.setServiceRequestId(getServiceRequestId());
		qrcTrnServiceRequestsImpl.setContactId(getContactId());
		qrcTrnServiceRequestsImpl.setSrId(getSrId());
		qrcTrnServiceRequestsImpl.setProcessId(getProcessId());
		qrcTrnServiceRequestsImpl.setSource(getSource());
		qrcTrnServiceRequestsImpl.setChannel(getChannel());
		qrcTrnServiceRequestsImpl.setPriority(getPriority());
		qrcTrnServiceRequestsImpl.setPolicyNo(getPolicyNo());
		qrcTrnServiceRequestsImpl.setCaseDetails(getCaseDetails());
		qrcTrnServiceRequestsImpl.setIsManual(getIsManual());
		qrcTrnServiceRequestsImpl.setIsLAUpdated(getIsLAUpdated());
		qrcTrnServiceRequestsImpl.setComments(getComments());
		qrcTrnServiceRequestsImpl.setIsSignVerified(getIsSignVerified());
		qrcTrnServiceRequestsImpl.setRequestId(getRequestId());
		qrcTrnServiceRequestsImpl.setAssignedTo(getAssignedTo());
		qrcTrnServiceRequestsImpl.setCreatedContactId(getCreatedContactId());
		qrcTrnServiceRequestsImpl.setHistoryId(getHistoryId());
		qrcTrnServiceRequestsImpl.setAddressTypeId(getAddressTypeId());
		qrcTrnServiceRequestsImpl.setIsActive(getIsActive());
		qrcTrnServiceRequestsImpl.setCreatedBy(getCreatedBy());
		qrcTrnServiceRequestsImpl.setCreatedDate(getCreatedDate());
		qrcTrnServiceRequestsImpl.setModifiedDate(getModifiedDate());
		qrcTrnServiceRequestsImpl.setModifiedBy(getModifiedBy());

		qrcTrnServiceRequestsImpl.resetOriginalValues();

		return qrcTrnServiceRequestsImpl;
	}

	@Override
	public int compareTo(QrcTrnServiceRequests qrcTrnServiceRequests) {
		int primaryKey = qrcTrnServiceRequests.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QrcTrnServiceRequests)) {
			return false;
		}

		QrcTrnServiceRequests qrcTrnServiceRequests = (QrcTrnServiceRequests)obj;

		int primaryKey = qrcTrnServiceRequests.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QrcTrnServiceRequests> toCacheModel() {
		QrcTrnServiceRequestsCacheModel qrcTrnServiceRequestsCacheModel = new QrcTrnServiceRequestsCacheModel();

		qrcTrnServiceRequestsCacheModel.ServiceRequestId = getServiceRequestId();

		qrcTrnServiceRequestsCacheModel.ContactId = getContactId();

		qrcTrnServiceRequestsCacheModel.SrId = getSrId();

		String SrId = qrcTrnServiceRequestsCacheModel.SrId;

		if ((SrId != null) && (SrId.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.SrId = null;
		}

		qrcTrnServiceRequestsCacheModel.ProcessId = getProcessId();

		String ProcessId = qrcTrnServiceRequestsCacheModel.ProcessId;

		if ((ProcessId != null) && (ProcessId.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.ProcessId = null;
		}

		qrcTrnServiceRequestsCacheModel.Source = getSource();

		String Source = qrcTrnServiceRequestsCacheModel.Source;

		if ((Source != null) && (Source.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.Source = null;
		}

		qrcTrnServiceRequestsCacheModel.Channel = getChannel();

		String Channel = qrcTrnServiceRequestsCacheModel.Channel;

		if ((Channel != null) && (Channel.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.Channel = null;
		}

		qrcTrnServiceRequestsCacheModel.Priority = getPriority();

		String Priority = qrcTrnServiceRequestsCacheModel.Priority;

		if ((Priority != null) && (Priority.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.Priority = null;
		}

		qrcTrnServiceRequestsCacheModel.PolicyNo = getPolicyNo();

		String PolicyNo = qrcTrnServiceRequestsCacheModel.PolicyNo;

		if ((PolicyNo != null) && (PolicyNo.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.PolicyNo = null;
		}

		qrcTrnServiceRequestsCacheModel.CaseDetails = getCaseDetails();

		String CaseDetails = qrcTrnServiceRequestsCacheModel.CaseDetails;

		if ((CaseDetails != null) && (CaseDetails.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.CaseDetails = null;
		}

		qrcTrnServiceRequestsCacheModel.IsManual = getIsManual();

		String IsManual = qrcTrnServiceRequestsCacheModel.IsManual;

		if ((IsManual != null) && (IsManual.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.IsManual = null;
		}

		qrcTrnServiceRequestsCacheModel.IsLAUpdated = getIsLAUpdated();

		String IsLAUpdated = qrcTrnServiceRequestsCacheModel.IsLAUpdated;

		if ((IsLAUpdated != null) && (IsLAUpdated.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.IsLAUpdated = null;
		}

		qrcTrnServiceRequestsCacheModel.Comments = getComments();

		String Comments = qrcTrnServiceRequestsCacheModel.Comments;

		if ((Comments != null) && (Comments.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.Comments = null;
		}

		qrcTrnServiceRequestsCacheModel.IsSignVerified = getIsSignVerified();

		String IsSignVerified = qrcTrnServiceRequestsCacheModel.IsSignVerified;

		if ((IsSignVerified != null) && (IsSignVerified.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.IsSignVerified = null;
		}

		qrcTrnServiceRequestsCacheModel.RequestId = getRequestId();

		qrcTrnServiceRequestsCacheModel.AssignedTo = getAssignedTo();

		qrcTrnServiceRequestsCacheModel.CreatedContactId = getCreatedContactId();

		qrcTrnServiceRequestsCacheModel.HistoryId = getHistoryId();

		qrcTrnServiceRequestsCacheModel.AddressTypeId = getAddressTypeId();

		qrcTrnServiceRequestsCacheModel.IsActive = getIsActive();

		qrcTrnServiceRequestsCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = qrcTrnServiceRequestsCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			qrcTrnServiceRequestsCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			qrcTrnServiceRequestsCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			qrcTrnServiceRequestsCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			qrcTrnServiceRequestsCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		qrcTrnServiceRequestsCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = qrcTrnServiceRequestsCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			qrcTrnServiceRequestsCacheModel.ModifiedBy = null;
		}

		return qrcTrnServiceRequestsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(47);

		sb.append("{ServiceRequestId=");
		sb.append(getServiceRequestId());
		sb.append(", ContactId=");
		sb.append(getContactId());
		sb.append(", SrId=");
		sb.append(getSrId());
		sb.append(", ProcessId=");
		sb.append(getProcessId());
		sb.append(", Source=");
		sb.append(getSource());
		sb.append(", Channel=");
		sb.append(getChannel());
		sb.append(", Priority=");
		sb.append(getPriority());
		sb.append(", PolicyNo=");
		sb.append(getPolicyNo());
		sb.append(", CaseDetails=");
		sb.append(getCaseDetails());
		sb.append(", IsManual=");
		sb.append(getIsManual());
		sb.append(", IsLAUpdated=");
		sb.append(getIsLAUpdated());
		sb.append(", Comments=");
		sb.append(getComments());
		sb.append(", IsSignVerified=");
		sb.append(getIsSignVerified());
		sb.append(", RequestId=");
		sb.append(getRequestId());
		sb.append(", AssignedTo=");
		sb.append(getAssignedTo());
		sb.append(", CreatedContactId=");
		sb.append(getCreatedContactId());
		sb.append(", HistoryId=");
		sb.append(getHistoryId());
		sb.append(", AddressTypeId=");
		sb.append(getAddressTypeId());
		sb.append(", IsActive=");
		sb.append(getIsActive());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", CreatedDate=");
		sb.append(getCreatedDate());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(73);

		sb.append("<model><model-name>");
		sb.append("com.ifl.rapid.customer.model.QrcTrnServiceRequests");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ServiceRequestId</column-name><column-value><![CDATA[");
		sb.append(getServiceRequestId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ContactId</column-name><column-value><![CDATA[");
		sb.append(getContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SrId</column-name><column-value><![CDATA[");
		sb.append(getSrId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ProcessId</column-name><column-value><![CDATA[");
		sb.append(getProcessId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Source</column-name><column-value><![CDATA[");
		sb.append(getSource());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Channel</column-name><column-value><![CDATA[");
		sb.append(getChannel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Priority</column-name><column-value><![CDATA[");
		sb.append(getPriority());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PolicyNo</column-name><column-value><![CDATA[");
		sb.append(getPolicyNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CaseDetails</column-name><column-value><![CDATA[");
		sb.append(getCaseDetails());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IsManual</column-name><column-value><![CDATA[");
		sb.append(getIsManual());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IsLAUpdated</column-name><column-value><![CDATA[");
		sb.append(getIsLAUpdated());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Comments</column-name><column-value><![CDATA[");
		sb.append(getComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IsSignVerified</column-name><column-value><![CDATA[");
		sb.append(getIsSignVerified());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RequestId</column-name><column-value><![CDATA[");
		sb.append(getRequestId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AssignedTo</column-name><column-value><![CDATA[");
		sb.append(getAssignedTo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedContactId</column-name><column-value><![CDATA[");
		sb.append(getCreatedContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>HistoryId</column-name><column-value><![CDATA[");
		sb.append(getHistoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AddressTypeId</column-name><column-value><![CDATA[");
		sb.append(getAddressTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IsActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QrcTrnServiceRequests.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QrcTrnServiceRequests.class
		};
	private int _ServiceRequestId;
	private int _ContactId;
	private String _SrId;
	private String _ProcessId;
	private String _Source;
	private String _Channel;
	private String _Priority;
	private String _PolicyNo;
	private String _CaseDetails;
	private String _IsManual;
	private String _IsLAUpdated;
	private String _Comments;
	private String _IsSignVerified;
	private int _RequestId;
	private int _AssignedTo;
	private int _CreatedContactId;
	private int _HistoryId;
	private int _AddressTypeId;
	private int _IsActive;
	private String _CreatedBy;
	private Date _CreatedDate;
	private Date _ModifiedDate;
	private String _ModifiedBy;
	private QrcTrnServiceRequests _escapedModel;
}