/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ApplyTrnApplicationForm service. Represents a row in the &quot;Apply_Trn_ApplicationForm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.ApplyTrnApplicationFormModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.ApplyTrnApplicationFormImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see ApplyTrnApplicationForm
 * @see com.ifl.rapid.customer.model.impl.ApplyTrnApplicationFormImpl
 * @see com.ifl.rapid.customer.model.impl.ApplyTrnApplicationFormModelImpl
 * @generated
 */
public interface ApplyTrnApplicationFormModel extends BaseModel<ApplyTrnApplicationForm> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a apply trn application form model instance should use the {@link ApplyTrnApplicationForm} interface instead.
	 */

	/**
	 * Returns the primary key of this apply trn application form.
	 *
	 * @return the primary key of this apply trn application form
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this apply trn application form.
	 *
	 * @param primaryKey the primary key of this apply trn application form
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the application form ID of this apply trn application form.
	 *
	 * @return the application form ID of this apply trn application form
	 */
	@AutoEscape
	public String getApplicationFormId();

	/**
	 * Sets the application form ID of this apply trn application form.
	 *
	 * @param ApplicationFormId the application form ID of this apply trn application form
	 */
	public void setApplicationFormId(String ApplicationFormId);

	/**
	 * Returns the quote ID of this apply trn application form.
	 *
	 * @return the quote ID of this apply trn application form
	 */
	@AutoEscape
	public String getQuoteId();

	/**
	 * Sets the quote ID of this apply trn application form.
	 *
	 * @param QuoteId the quote ID of this apply trn application form
	 */
	public void setQuoteId(String QuoteId);

	/**
	 * Returns the application ref no of this apply trn application form.
	 *
	 * @return the application ref no of this apply trn application form
	 */
	@AutoEscape
	public String getApplicationRefNo();

	/**
	 * Sets the application ref no of this apply trn application form.
	 *
	 * @param ApplicationRefNo the application ref no of this apply trn application form
	 */
	public void setApplicationRefNo(String ApplicationRefNo);

	/**
	 * Returns the seq generator of this apply trn application form.
	 *
	 * @return the seq generator of this apply trn application form
	 */
	public int getSeqGenerator();

	/**
	 * Sets the seq generator of this apply trn application form.
	 *
	 * @param SeqGenerator the seq generator of this apply trn application form
	 */
	public void setSeqGenerator(int SeqGenerator);

	/**
	 * Returns the l t r f form ref no of this apply trn application form.
	 *
	 * @return the l t r f form ref no of this apply trn application form
	 */
	@AutoEscape
	public String getLTRFFormRefNo();

	/**
	 * Sets the l t r f form ref no of this apply trn application form.
	 *
	 * @param LTRFFormRefNo the l t r f form ref no of this apply trn application form
	 */
	public void setLTRFFormRefNo(String LTRFFormRefNo);

	/**
	 * Returns the premium amount of this apply trn application form.
	 *
	 * @return the premium amount of this apply trn application form
	 */
	public double getPremiumAmount();

	/**
	 * Sets the premium amount of this apply trn application form.
	 *
	 * @param PremiumAmount the premium amount of this apply trn application form
	 */
	public void setPremiumAmount(double PremiumAmount);

	/**
	 * Returns the is medical required of this apply trn application form.
	 *
	 * @return the is medical required of this apply trn application form
	 */
	public int getIsMedicalRequired();

	/**
	 * Sets the is medical required of this apply trn application form.
	 *
	 * @param IsMedicalRequired the is medical required of this apply trn application form
	 */
	public void setIsMedicalRequired(int IsMedicalRequired);

	/**
	 * Returns the short premium of this apply trn application form.
	 *
	 * @return the short premium of this apply trn application form
	 */
	public double getShortPremium();

	/**
	 * Sets the short premium of this apply trn application form.
	 *
	 * @param ShortPremium the short premium of this apply trn application form
	 */
	public void setShortPremium(double ShortPremium);

	/**
	 * Returns the premium due date of this apply trn application form.
	 *
	 * @return the premium due date of this apply trn application form
	 */
	public Date getPremiumDueDate();

	/**
	 * Sets the premium due date of this apply trn application form.
	 *
	 * @param PremiumDueDate the premium due date of this apply trn application form
	 */
	public void setPremiumDueDate(Date PremiumDueDate);

	/**
	 * Returns the policy no of this apply trn application form.
	 *
	 * @return the policy no of this apply trn application form
	 */
	@AutoEscape
	public String getPolicyNo();

	/**
	 * Sets the policy no of this apply trn application form.
	 *
	 * @param PolicyNo the policy no of this apply trn application form
	 */
	public void setPolicyNo(String PolicyNo);

	/**
	 * Returns the policy elapsed date of this apply trn application form.
	 *
	 * @return the policy elapsed date of this apply trn application form
	 */
	public Date getPolicyElapsedDate();

	/**
	 * Sets the policy elapsed date of this apply trn application form.
	 *
	 * @param PolicyElapsedDate the policy elapsed date of this apply trn application form
	 */
	public void setPolicyElapsedDate(Date PolicyElapsedDate);

	/**
	 * Returns the policy issue date of this apply trn application form.
	 *
	 * @return the policy issue date of this apply trn application form
	 */
	public Date getPolicyIssueDate();

	/**
	 * Sets the policy issue date of this apply trn application form.
	 *
	 * @param PolicyIssueDate the policy issue date of this apply trn application form
	 */
	public void setPolicyIssueDate(Date PolicyIssueDate);

	/**
	 * Returns the status of this apply trn application form.
	 *
	 * @return the status of this apply trn application form
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this apply trn application form.
	 *
	 * @param Status the status of this apply trn application form
	 */
	public void setStatus(String Status);

	/**
	 * Returns the completion of this apply trn application form.
	 *
	 * @return the completion of this apply trn application form
	 */
	public int getCompletion();

	/**
	 * Sets the completion of this apply trn application form.
	 *
	 * @param Completion the completion of this apply trn application form
	 */
	public void setCompletion(int Completion);

	/**
	 * Returns the is lapsed of this apply trn application form.
	 *
	 * @return the is lapsed of this apply trn application form
	 */
	public int getIsLapsed();

	/**
	 * Sets the is lapsed of this apply trn application form.
	 *
	 * @param IsLapsed the is lapsed of this apply trn application form
	 */
	public void setIsLapsed(int IsLapsed);

	/**
	 * Returns the next premium due date of this apply trn application form.
	 *
	 * @return the next premium due date of this apply trn application form
	 */
	public Date getNextPremiumDueDate();

	/**
	 * Sets the next premium due date of this apply trn application form.
	 *
	 * @param NextPremiumDueDate the next premium due date of this apply trn application form
	 */
	public void setNextPremiumDueDate(Date NextPremiumDueDate);

	/**
	 * Returns the policy status of this apply trn application form.
	 *
	 * @return the policy status of this apply trn application form
	 */
	@AutoEscape
	public String getPolicyStatus();

	/**
	 * Sets the policy status of this apply trn application form.
	 *
	 * @param PolicyStatus the policy status of this apply trn application form
	 */
	public void setPolicyStatus(String PolicyStatus);

	/**
	 * Returns the is active of this apply trn application form.
	 *
	 * @return the is active of this apply trn application form
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this apply trn application form.
	 *
	 * @param IsActive the is active of this apply trn application form
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created by of this apply trn application form.
	 *
	 * @return the created by of this apply trn application form
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this apply trn application form.
	 *
	 * @param CreatedBy the created by of this apply trn application form
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this apply trn application form.
	 *
	 * @return the created date of this apply trn application form
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this apply trn application form.
	 *
	 * @param CreatedDate the created date of this apply trn application form
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified date of this apply trn application form.
	 *
	 * @return the modified date of this apply trn application form
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this apply trn application form.
	 *
	 * @param ModifiedDate the modified date of this apply trn application form
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this apply trn application form.
	 *
	 * @return the modified by of this apply trn application form
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this apply trn application form.
	 *
	 * @param ModifiedBy the modified by of this apply trn application form
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ApplyTrnApplicationForm applyTrnApplicationForm);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ApplyTrnApplicationForm> toCacheModel();

	@Override
	public ApplyTrnApplicationForm toEscapedModel();

	@Override
	public ApplyTrnApplicationForm toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}