/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ApplyTrnQuoteDetails service. Represents a row in the &quot;Apply_Trn_QuoteDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.ApplyTrnQuoteDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.ApplyTrnQuoteDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see ApplyTrnQuoteDetails
 * @see com.ifl.rapid.customer.model.impl.ApplyTrnQuoteDetailsImpl
 * @see com.ifl.rapid.customer.model.impl.ApplyTrnQuoteDetailsModelImpl
 * @generated
 */
public interface ApplyTrnQuoteDetailsModel extends BaseModel<ApplyTrnQuoteDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a apply trn quote details model instance should use the {@link ApplyTrnQuoteDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this apply trn quote details.
	 *
	 * @return the primary key of this apply trn quote details
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this apply trn quote details.
	 *
	 * @param primaryKey the primary key of this apply trn quote details
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the quote ID of this apply trn quote details.
	 *
	 * @return the quote ID of this apply trn quote details
	 */
	@AutoEscape
	public String getQuoteId();

	/**
	 * Sets the quote ID of this apply trn quote details.
	 *
	 * @param QuoteId the quote ID of this apply trn quote details
	 */
	public void setQuoteId(String QuoteId);

	/**
	 * Returns the contact ID of this apply trn quote details.
	 *
	 * @return the contact ID of this apply trn quote details
	 */
	public int getContactId();

	/**
	 * Sets the contact ID of this apply trn quote details.
	 *
	 * @param ContactId the contact ID of this apply trn quote details
	 */
	public void setContactId(int ContactId);

	/**
	 * Returns the product ID of this apply trn quote details.
	 *
	 * @return the product ID of this apply trn quote details
	 */
	@AutoEscape
	public String getProductId();

	/**
	 * Sets the product ID of this apply trn quote details.
	 *
	 * @param ProductId the product ID of this apply trn quote details
	 */
	public void setProductId(String ProductId);

	/**
	 * Returns the premium type ID of this apply trn quote details.
	 *
	 * @return the premium type ID of this apply trn quote details
	 */
	@AutoEscape
	public String getPremiumTypeId();

	/**
	 * Sets the premium type ID of this apply trn quote details.
	 *
	 * @param PremiumTypeId the premium type ID of this apply trn quote details
	 */
	public void setPremiumTypeId(String PremiumTypeId);

	/**
	 * Returns the premium frequency ID of this apply trn quote details.
	 *
	 * @return the premium frequency ID of this apply trn quote details
	 */
	@AutoEscape
	public String getPremiumFrequencyId();

	/**
	 * Sets the premium frequency ID of this apply trn quote details.
	 *
	 * @param PremiumFrequencyId the premium frequency ID of this apply trn quote details
	 */
	public void setPremiumFrequencyId(String PremiumFrequencyId);

	/**
	 * Returns the assured term of this apply trn quote details.
	 *
	 * @return the assured term of this apply trn quote details
	 */
	public int getAssuredTerm();

	/**
	 * Sets the assured term of this apply trn quote details.
	 *
	 * @param AssuredTerm the assured term of this apply trn quote details
	 */
	public void setAssuredTerm(int AssuredTerm);

	/**
	 * Returns the assured age of this apply trn quote details.
	 *
	 * @return the assured age of this apply trn quote details
	 */
	public int getAssuredAge();

	/**
	 * Sets the assured age of this apply trn quote details.
	 *
	 * @param AssuredAge the assured age of this apply trn quote details
	 */
	public void setAssuredAge(int AssuredAge);

	/**
	 * Returns the data xml of this apply trn quote details.
	 *
	 * @return the data xml of this apply trn quote details
	 */
	@AutoEscape
	public String getDataXml();

	/**
	 * Sets the data xml of this apply trn quote details.
	 *
	 * @param DataXml the data xml of this apply trn quote details
	 */
	public void setDataXml(String DataXml);

	/**
	 * Returns the death benefit option of this apply trn quote details.
	 *
	 * @return the death benefit option of this apply trn quote details
	 */
	public int getDeathBenefitOption();

	/**
	 * Sets the death benefit option of this apply trn quote details.
	 *
	 * @param DeathBenefitOption the death benefit option of this apply trn quote details
	 */
	public void setDeathBenefitOption(int DeathBenefitOption);

	/**
	 * Returns the expiry date of this apply trn quote details.
	 *
	 * @return the expiry date of this apply trn quote details
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this apply trn quote details.
	 *
	 * @param ExpiryDate the expiry date of this apply trn quote details
	 */
	public void setExpiryDate(Date ExpiryDate);

	/**
	 * Returns the is staff of this apply trn quote details.
	 *
	 * @return the is staff of this apply trn quote details
	 */
	@AutoEscape
	public String getIsStaff();

	/**
	 * Sets the is staff of this apply trn quote details.
	 *
	 * @param IsStaff the is staff of this apply trn quote details
	 */
	public void setIsStaff(String IsStaff);

	/**
	 * Returns the is active of this apply trn quote details.
	 *
	 * @return the is active of this apply trn quote details
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this apply trn quote details.
	 *
	 * @param IsActive the is active of this apply trn quote details
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the policy option of this apply trn quote details.
	 *
	 * @return the policy option of this apply trn quote details
	 */
	public int getPolicyOption();

	/**
	 * Sets the policy option of this apply trn quote details.
	 *
	 * @param PolicyOption the policy option of this apply trn quote details
	 */
	public void setPolicyOption(int PolicyOption);

	/**
	 * Returns the paying term of this apply trn quote details.
	 *
	 * @return the paying term of this apply trn quote details
	 */
	public int getPayingTerm();

	/**
	 * Sets the paying term of this apply trn quote details.
	 *
	 * @param PayingTerm the paying term of this apply trn quote details
	 */
	public void setPayingTerm(int PayingTerm);

	/**
	 * Returns the proposal start date of this apply trn quote details.
	 *
	 * @return the proposal start date of this apply trn quote details
	 */
	@AutoEscape
	public String getProposalStartDate();

	/**
	 * Sets the proposal start date of this apply trn quote details.
	 *
	 * @param ProposalStartDate the proposal start date of this apply trn quote details
	 */
	public void setProposalStartDate(String ProposalStartDate);

	/**
	 * Returns the ref no of this apply trn quote details.
	 *
	 * @return the ref no of this apply trn quote details
	 */
	public int getRefNo();

	/**
	 * Sets the ref no of this apply trn quote details.
	 *
	 * @param RefNo the ref no of this apply trn quote details
	 */
	public void setRefNo(int RefNo);

	/**
	 * Returns the plan term of this apply trn quote details.
	 *
	 * @return the plan term of this apply trn quote details
	 */
	public int getPlanTerm();

	/**
	 * Sets the plan term of this apply trn quote details.
	 *
	 * @param PlanTerm the plan term of this apply trn quote details
	 */
	public void setPlanTerm(int PlanTerm);

	/**
	 * Returns the premium term of this apply trn quote details.
	 *
	 * @return the premium term of this apply trn quote details
	 */
	public int getPremiumTerm();

	/**
	 * Sets the premium term of this apply trn quote details.
	 *
	 * @param PremiumTerm the premium term of this apply trn quote details
	 */
	public void setPremiumTerm(int PremiumTerm);

	/**
	 * Returns the premium amount of this apply trn quote details.
	 *
	 * @return the premium amount of this apply trn quote details
	 */
	public double getPremiumAmount();

	/**
	 * Sets the premium amount of this apply trn quote details.
	 *
	 * @param PremiumAmount the premium amount of this apply trn quote details
	 */
	public void setPremiumAmount(double PremiumAmount);

	/**
	 * Returns the sum assured of this apply trn quote details.
	 *
	 * @return the sum assured of this apply trn quote details
	 */
	public double getSumAssured();

	/**
	 * Sets the sum assured of this apply trn quote details.
	 *
	 * @param SumAssured the sum assured of this apply trn quote details
	 */
	public void setSumAssured(double SumAssured);

	/**
	 * Returns the summary xml of this apply trn quote details.
	 *
	 * @return the summary xml of this apply trn quote details
	 */
	@AutoEscape
	public String getSummaryXml();

	/**
	 * Sets the summary xml of this apply trn quote details.
	 *
	 * @param SummaryXml the summary xml of this apply trn quote details
	 */
	public void setSummaryXml(String SummaryXml);

	/**
	 * Returns the pdf location of this apply trn quote details.
	 *
	 * @return the pdf location of this apply trn quote details
	 */
	@AutoEscape
	public String getPdfLocation();

	/**
	 * Sets the pdf location of this apply trn quote details.
	 *
	 * @param PdfLocation the pdf location of this apply trn quote details
	 */
	public void setPdfLocation(String PdfLocation);

	/**
	 * Returns the created by of this apply trn quote details.
	 *
	 * @return the created by of this apply trn quote details
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this apply trn quote details.
	 *
	 * @param CreatedBy the created by of this apply trn quote details
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this apply trn quote details.
	 *
	 * @return the created date of this apply trn quote details
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this apply trn quote details.
	 *
	 * @param CreatedDate the created date of this apply trn quote details
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified date of this apply trn quote details.
	 *
	 * @return the modified date of this apply trn quote details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this apply trn quote details.
	 *
	 * @param ModifiedDate the modified date of this apply trn quote details
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this apply trn quote details.
	 *
	 * @return the modified by of this apply trn quote details
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this apply trn quote details.
	 *
	 * @param ModifiedBy the modified by of this apply trn quote details
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the pdf data xml of this apply trn quote details.
	 *
	 * @return the pdf data xml of this apply trn quote details
	 */
	@AutoEscape
	public String getPdfDataXml();

	/**
	 * Sets the pdf data xml of this apply trn quote details.
	 *
	 * @param pdfDataXml the pdf data xml of this apply trn quote details
	 */
	public void setPdfDataXml(String pdfDataXml);

	/**
	 * Returns the is smoker of this apply trn quote details.
	 *
	 * @return the is smoker of this apply trn quote details
	 */
	public int getIsSmoker();

	/**
	 * Sets the is smoker of this apply trn quote details.
	 *
	 * @param IsSmoker the is smoker of this apply trn quote details
	 */
	public void setIsSmoker(int IsSmoker);

	/**
	 * Returns the signature file path of this apply trn quote details.
	 *
	 * @return the signature file path of this apply trn quote details
	 */
	@AutoEscape
	public String getSignatureFilePath();

	/**
	 * Sets the signature file path of this apply trn quote details.
	 *
	 * @param SignatureFilePath the signature file path of this apply trn quote details
	 */
	public void setSignatureFilePath(String SignatureFilePath);

	/**
	 * Returns the b d m signature file path of this apply trn quote details.
	 *
	 * @return the b d m signature file path of this apply trn quote details
	 */
	@AutoEscape
	public String getBDMSignatureFilePath();

	/**
	 * Sets the b d m signature file path of this apply trn quote details.
	 *
	 * @param BDMSignatureFilePath the b d m signature file path of this apply trn quote details
	 */
	public void setBDMSignatureFilePath(String BDMSignatureFilePath);

	/**
	 * Returns the b d m ID of this apply trn quote details.
	 *
	 * @return the b d m ID of this apply trn quote details
	 */
	public int getBDMId();

	/**
	 * Sets the b d m ID of this apply trn quote details.
	 *
	 * @param BDMId the b d m ID of this apply trn quote details
	 */
	public void setBDMId(int BDMId);

	/**
	 * Returns the is assisted of this apply trn quote details.
	 *
	 * @return the is assisted of this apply trn quote details
	 */
	public int getIsAssisted();

	/**
	 * Sets the is assisted of this apply trn quote details.
	 *
	 * @param IsAssisted the is assisted of this apply trn quote details
	 */
	public void setIsAssisted(int IsAssisted);

	/**
	 * Returns the input x m l of this apply trn quote details.
	 *
	 * @return the input x m l of this apply trn quote details
	 */
	@AutoEscape
	public String getInputXML();

	/**
	 * Sets the input x m l of this apply trn quote details.
	 *
	 * @param InputXML the input x m l of this apply trn quote details
	 */
	public void setInputXML(String InputXML);

	/**
	 * Returns the lead ID of this apply trn quote details.
	 *
	 * @return the lead ID of this apply trn quote details
	 */
	@AutoEscape
	public String getLeadId();

	/**
	 * Sets the lead ID of this apply trn quote details.
	 *
	 * @param LeadId the lead ID of this apply trn quote details
	 */
	public void setLeadId(String LeadId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ApplyTrnQuoteDetails applyTrnQuoteDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ApplyTrnQuoteDetails> toCacheModel();

	@Override
	public ApplyTrnQuoteDetails toEscapedModel();

	@Override
	public ApplyTrnQuoteDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}