/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the City service. Represents a row in the &quot;Loc_Mst_City&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.CityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.CityImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see City
 * @see com.ifl.rapid.customer.model.impl.CityImpl
 * @see com.ifl.rapid.customer.model.impl.CityModelImpl
 * @generated
 */
public interface CityModel extends BaseModel<City> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a city model instance should use the {@link City} interface instead.
	 */

	/**
	 * Returns the primary key of this city.
	 *
	 * @return the primary key of this city
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this city.
	 *
	 * @param primaryKey the primary key of this city
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the city ID of this city.
	 *
	 * @return the city ID of this city
	 */
	public int getCityId();

	/**
	 * Sets the city ID of this city.
	 *
	 * @param CityId the city ID of this city
	 */
	public void setCityId(int CityId);

	/**
	 * Returns the city code of this city.
	 *
	 * @return the city code of this city
	 */
	@AutoEscape
	public String getCityCode();

	/**
	 * Sets the city code of this city.
	 *
	 * @param CityCode the city code of this city
	 */
	public void setCityCode(String CityCode);

	/**
	 * Returns the city name of this city.
	 *
	 * @return the city name of this city
	 */
	@AutoEscape
	public String getCityName();

	/**
	 * Sets the city name of this city.
	 *
	 * @param CityName the city name of this city
	 */
	public void setCityName(String CityName);

	/**
	 * Returns the is active of this city.
	 *
	 * @return the is active of this city
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this city.
	 *
	 * @param IsActive the is active of this city
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created by of this city.
	 *
	 * @return the created by of this city
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this city.
	 *
	 * @param CreatedBy the created by of this city
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this city.
	 *
	 * @return the created date of this city
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this city.
	 *
	 * @param CreatedDate the created date of this city
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified date of this city.
	 *
	 * @return the modified date of this city
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this city.
	 *
	 * @param ModifiedDate the modified date of this city
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this city.
	 *
	 * @return the modified by of this city
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this city.
	 *
	 * @param ModifiedBy the modified by of this city
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the state ID of this city.
	 *
	 * @return the state ID of this city
	 */
	public int getStateId();

	/**
	 * Sets the state ID of this city.
	 *
	 * @param StateId the state ID of this city
	 */
	public void setStateId(int StateId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(City city);

	@Override
	public int hashCode();

	@Override
	public CacheModel<City> toCacheModel();

	@Override
	public City toEscapedModel();

	@Override
	public City toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}