/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Config_Mst_GenericMaster service. Represents a row in the &quot;Config_Mst_GenericMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.Config_Mst_GenericMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.Config_Mst_GenericMasterImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see Config_Mst_GenericMaster
 * @see com.ifl.rapid.customer.model.impl.Config_Mst_GenericMasterImpl
 * @see com.ifl.rapid.customer.model.impl.Config_Mst_GenericMasterModelImpl
 * @generated
 */
public interface Config_Mst_GenericMasterModel extends BaseModel<Config_Mst_GenericMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a config_ mst_ generic master model instance should use the {@link Config_Mst_GenericMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this config_ mst_ generic master.
	 *
	 * @return the primary key of this config_ mst_ generic master
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this config_ mst_ generic master.
	 *
	 * @param primaryKey the primary key of this config_ mst_ generic master
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the generic master ID of this config_ mst_ generic master.
	 *
	 * @return the generic master ID of this config_ mst_ generic master
	 */
	public int getGenericMasterId();

	/**
	 * Sets the generic master ID of this config_ mst_ generic master.
	 *
	 * @param GenericMasterId the generic master ID of this config_ mst_ generic master
	 */
	public void setGenericMasterId(int GenericMasterId);

	/**
	 * Returns the master type of this config_ mst_ generic master.
	 *
	 * @return the master type of this config_ mst_ generic master
	 */
	@AutoEscape
	public String getMasterType();

	/**
	 * Sets the master type of this config_ mst_ generic master.
	 *
	 * @param MasterType the master type of this config_ mst_ generic master
	 */
	public void setMasterType(String MasterType);

	/**
	 * Returns the master ID of this config_ mst_ generic master.
	 *
	 * @return the master ID of this config_ mst_ generic master
	 */
	public int getMasterId();

	/**
	 * Sets the master ID of this config_ mst_ generic master.
	 *
	 * @param MasterId the master ID of this config_ mst_ generic master
	 */
	public void setMasterId(int MasterId);

	/**
	 * Returns the master key of this config_ mst_ generic master.
	 *
	 * @return the master key of this config_ mst_ generic master
	 */
	@AutoEscape
	public String getMasterKey();

	/**
	 * Sets the master key of this config_ mst_ generic master.
	 *
	 * @param MasterKey the master key of this config_ mst_ generic master
	 */
	public void setMasterKey(String MasterKey);

	/**
	 * Returns the is active of this config_ mst_ generic master.
	 *
	 * @return the is active of this config_ mst_ generic master
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this config_ mst_ generic master.
	 *
	 * @param IsActive the is active of this config_ mst_ generic master
	 */
	public void setIsActive(String IsActive);

	/**
	 * Returns the created by of this config_ mst_ generic master.
	 *
	 * @return the created by of this config_ mst_ generic master
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this config_ mst_ generic master.
	 *
	 * @param CreatedBy the created by of this config_ mst_ generic master
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this config_ mst_ generic master.
	 *
	 * @return the created date of this config_ mst_ generic master
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this config_ mst_ generic master.
	 *
	 * @param CreatedDate the created date of this config_ mst_ generic master
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this config_ mst_ generic master.
	 *
	 * @return the modified by of this config_ mst_ generic master
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this config_ mst_ generic master.
	 *
	 * @param ModifiedBy the modified by of this config_ mst_ generic master
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this config_ mst_ generic master.
	 *
	 * @return the modified date of this config_ mst_ generic master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this config_ mst_ generic master.
	 *
	 * @param ModifiedDate the modified date of this config_ mst_ generic master
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the description of this config_ mst_ generic master.
	 *
	 * @return the description of this config_ mst_ generic master
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this config_ mst_ generic master.
	 *
	 * @param Description the description of this config_ mst_ generic master
	 */
	public void setDescription(String Description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Config_Mst_GenericMaster config_Mst_GenericMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Config_Mst_GenericMaster> toCacheModel();

	@Override
	public Config_Mst_GenericMaster toEscapedModel();

	@Override
	public Config_Mst_GenericMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}