/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CRM_Trn_Phone service. Represents a row in the &quot;CRM_Trn_Phone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.CRM_Trn_PhoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.CRM_Trn_PhoneImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CRM_Trn_Phone
 * @see com.ifl.rapid.customer.model.impl.CRM_Trn_PhoneImpl
 * @see com.ifl.rapid.customer.model.impl.CRM_Trn_PhoneModelImpl
 * @generated
 */
public interface CRM_Trn_PhoneModel extends BaseModel<CRM_Trn_Phone> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c r m_ trn_ phone model instance should use the {@link CRM_Trn_Phone} interface instead.
	 */

	/**
	 * Returns the primary key of this c r m_ trn_ phone.
	 *
	 * @return the primary key of this c r m_ trn_ phone
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this c r m_ trn_ phone.
	 *
	 * @param primaryKey the primary key of this c r m_ trn_ phone
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the phone ID of this c r m_ trn_ phone.
	 *
	 * @return the phone ID of this c r m_ trn_ phone
	 */
	public int getPhoneId();

	/**
	 * Sets the phone ID of this c r m_ trn_ phone.
	 *
	 * @param PhoneId the phone ID of this c r m_ trn_ phone
	 */
	public void setPhoneId(int PhoneId);

	/**
	 * Returns the contact ID of this c r m_ trn_ phone.
	 *
	 * @return the contact ID of this c r m_ trn_ phone
	 */
	public int getContactId();

	/**
	 * Sets the contact ID of this c r m_ trn_ phone.
	 *
	 * @param ContactId the contact ID of this c r m_ trn_ phone
	 */
	public void setContactId(int ContactId);

	/**
	 * Returns the phone type of this c r m_ trn_ phone.
	 *
	 * @return the phone type of this c r m_ trn_ phone
	 */
	public int getPhoneType();

	/**
	 * Sets the phone type of this c r m_ trn_ phone.
	 *
	 * @param PhoneType the phone type of this c r m_ trn_ phone
	 */
	public void setPhoneType(int PhoneType);

	/**
	 * Returns the phone number of this c r m_ trn_ phone.
	 *
	 * @return the phone number of this c r m_ trn_ phone
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this c r m_ trn_ phone.
	 *
	 * @param PhoneNumber the phone number of this c r m_ trn_ phone
	 */
	public void setPhoneNumber(String PhoneNumber);

	/**
	 * Returns the created by of this c r m_ trn_ phone.
	 *
	 * @return the created by of this c r m_ trn_ phone
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this c r m_ trn_ phone.
	 *
	 * @param CreatedBy the created by of this c r m_ trn_ phone
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this c r m_ trn_ phone.
	 *
	 * @return the created date of this c r m_ trn_ phone
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this c r m_ trn_ phone.
	 *
	 * @param CreatedDate the created date of this c r m_ trn_ phone
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this c r m_ trn_ phone.
	 *
	 * @return the modified by of this c r m_ trn_ phone
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this c r m_ trn_ phone.
	 *
	 * @param ModifiedBy the modified by of this c r m_ trn_ phone
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this c r m_ trn_ phone.
	 *
	 * @return the modified date of this c r m_ trn_ phone
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c r m_ trn_ phone.
	 *
	 * @param ModifiedDate the modified date of this c r m_ trn_ phone
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the is active of this c r m_ trn_ phone.
	 *
	 * @return the is active of this c r m_ trn_ phone
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this c r m_ trn_ phone.
	 *
	 * @param IsActive the is active of this c r m_ trn_ phone
	 */
	public void setIsActive(String IsActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CRM_Trn_Phone crm_Trn_Phone);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CRM_Trn_Phone> toCacheModel();

	@Override
	public CRM_Trn_Phone toEscapedModel();

	@Override
	public CRM_Trn_Phone toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}