/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CRM_Trn_Address service. Represents a row in the &quot;CRM_Trn_Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.CRM_Trn_AddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.CRM_Trn_AddressImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CRM_Trn_Address
 * @see com.ifl.rapid.customer.model.impl.CRM_Trn_AddressImpl
 * @see com.ifl.rapid.customer.model.impl.CRM_Trn_AddressModelImpl
 * @generated
 */
public interface CRM_Trn_AddressModel extends BaseModel<CRM_Trn_Address> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c r m_ trn_ address model instance should use the {@link CRM_Trn_Address} interface instead.
	 */

	/**
	 * Returns the primary key of this c r m_ trn_ address.
	 *
	 * @return the primary key of this c r m_ trn_ address
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this c r m_ trn_ address.
	 *
	 * @param primaryKey the primary key of this c r m_ trn_ address
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the address ID of this c r m_ trn_ address.
	 *
	 * @return the address ID of this c r m_ trn_ address
	 */
	public int getAddressId();

	/**
	 * Sets the address ID of this c r m_ trn_ address.
	 *
	 * @param AddressId the address ID of this c r m_ trn_ address
	 */
	public void setAddressId(int AddressId);

	/**
	 * Returns the contact ID of this c r m_ trn_ address.
	 *
	 * @return the contact ID of this c r m_ trn_ address
	 */
	public int getContactId();

	/**
	 * Sets the contact ID of this c r m_ trn_ address.
	 *
	 * @param ContactId the contact ID of this c r m_ trn_ address
	 */
	public void setContactId(int ContactId);

	/**
	 * Returns the address type ID of this c r m_ trn_ address.
	 *
	 * @return the address type ID of this c r m_ trn_ address
	 */
	public int getAddressTypeId();

	/**
	 * Sets the address type ID of this c r m_ trn_ address.
	 *
	 * @param AddressTypeId the address type ID of this c r m_ trn_ address
	 */
	public void setAddressTypeId(int AddressTypeId);

	/**
	 * Returns the address line1 of this c r m_ trn_ address.
	 *
	 * @return the address line1 of this c r m_ trn_ address
	 */
	@AutoEscape
	public String getAddressLine1();

	/**
	 * Sets the address line1 of this c r m_ trn_ address.
	 *
	 * @param AddressLine1 the address line1 of this c r m_ trn_ address
	 */
	public void setAddressLine1(String AddressLine1);

	/**
	 * Returns the address line2 of this c r m_ trn_ address.
	 *
	 * @return the address line2 of this c r m_ trn_ address
	 */
	@AutoEscape
	public String getAddressLine2();

	/**
	 * Sets the address line2 of this c r m_ trn_ address.
	 *
	 * @param AddressLine2 the address line2 of this c r m_ trn_ address
	 */
	public void setAddressLine2(String AddressLine2);

	/**
	 * Returns the address line3 of this c r m_ trn_ address.
	 *
	 * @return the address line3 of this c r m_ trn_ address
	 */
	@AutoEscape
	public String getAddressLine3();

	/**
	 * Sets the address line3 of this c r m_ trn_ address.
	 *
	 * @param AddressLine3 the address line3 of this c r m_ trn_ address
	 */
	public void setAddressLine3(String AddressLine3);

	/**
	 * Returns the district of this c r m_ trn_ address.
	 *
	 * @return the district of this c r m_ trn_ address
	 */
	@AutoEscape
	public String getDistrict();

	/**
	 * Sets the district of this c r m_ trn_ address.
	 *
	 * @param District the district of this c r m_ trn_ address
	 */
	public void setDistrict(String District);

	/**
	 * Returns the state ID of this c r m_ trn_ address.
	 *
	 * @return the state ID of this c r m_ trn_ address
	 */
	public int getStateId();

	/**
	 * Sets the state ID of this c r m_ trn_ address.
	 *
	 * @param StateId the state ID of this c r m_ trn_ address
	 */
	public void setStateId(int StateId);

	/**
	 * Returns the city ID of this c r m_ trn_ address.
	 *
	 * @return the city ID of this c r m_ trn_ address
	 */
	public int getCityId();

	/**
	 * Sets the city ID of this c r m_ trn_ address.
	 *
	 * @param CityId the city ID of this c r m_ trn_ address
	 */
	public void setCityId(int CityId);

	/**
	 * Returns the pincode of this c r m_ trn_ address.
	 *
	 * @return the pincode of this c r m_ trn_ address
	 */
	@AutoEscape
	public String getPincode();

	/**
	 * Sets the pincode of this c r m_ trn_ address.
	 *
	 * @param Pincode the pincode of this c r m_ trn_ address
	 */
	public void setPincode(String Pincode);

	/**
	 * Returns the country ID of this c r m_ trn_ address.
	 *
	 * @return the country ID of this c r m_ trn_ address
	 */
	public int getCountryId();

	/**
	 * Sets the country ID of this c r m_ trn_ address.
	 *
	 * @param CountryId the country ID of this c r m_ trn_ address
	 */
	public void setCountryId(int CountryId);

	/**
	 * Returns the is active of this c r m_ trn_ address.
	 *
	 * @return the is active of this c r m_ trn_ address
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this c r m_ trn_ address.
	 *
	 * @param IsActive the is active of this c r m_ trn_ address
	 */
	public void setIsActive(String IsActive);

	/**
	 * Returns the created by of this c r m_ trn_ address.
	 *
	 * @return the created by of this c r m_ trn_ address
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this c r m_ trn_ address.
	 *
	 * @param CreatedBy the created by of this c r m_ trn_ address
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this c r m_ trn_ address.
	 *
	 * @return the created date of this c r m_ trn_ address
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this c r m_ trn_ address.
	 *
	 * @param CreatedDate the created date of this c r m_ trn_ address
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this c r m_ trn_ address.
	 *
	 * @return the modified by of this c r m_ trn_ address
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this c r m_ trn_ address.
	 *
	 * @param ModifiedBy the modified by of this c r m_ trn_ address
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this c r m_ trn_ address.
	 *
	 * @return the modified date of this c r m_ trn_ address
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c r m_ trn_ address.
	 *
	 * @param ModifiedDate the modified date of this c r m_ trn_ address
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CRM_Trn_Address crm_Trn_Address);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CRM_Trn_Address> toCacheModel();

	@Override
	public CRM_Trn_Address toEscapedModel();

	@Override
	public CRM_Trn_Address toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}