/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CRMTrnFamilyMember service. Represents a row in the &quot;CRM_Trn_FamilyMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.CRMTrnFamilyMemberModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.CRMTrnFamilyMemberImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CRMTrnFamilyMember
 * @see com.ifl.rapid.customer.model.impl.CRMTrnFamilyMemberImpl
 * @see com.ifl.rapid.customer.model.impl.CRMTrnFamilyMemberModelImpl
 * @generated
 */
public interface CRMTrnFamilyMemberModel extends BaseModel<CRMTrnFamilyMember> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c r m trn family member model instance should use the {@link CRMTrnFamilyMember} interface instead.
	 */

	/**
	 * Returns the primary key of this c r m trn family member.
	 *
	 * @return the primary key of this c r m trn family member
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this c r m trn family member.
	 *
	 * @param primaryKey the primary key of this c r m trn family member
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the family member ID of this c r m trn family member.
	 *
	 * @return the family member ID of this c r m trn family member
	 */
	public int getFamilyMemberId();

	/**
	 * Sets the family member ID of this c r m trn family member.
	 *
	 * @param FamilyMemberId the family member ID of this c r m trn family member
	 */
	public void setFamilyMemberId(int FamilyMemberId);

	/**
	 * Returns the contact ID of this c r m trn family member.
	 *
	 * @return the contact ID of this c r m trn family member
	 */
	public int getContactId();

	/**
	 * Sets the contact ID of this c r m trn family member.
	 *
	 * @param ContactId the contact ID of this c r m trn family member
	 */
	public void setContactId(int ContactId);

	/**
	 * Returns the member ID of this c r m trn family member.
	 *
	 * @return the member ID of this c r m trn family member
	 */
	public int getMemberId();

	/**
	 * Sets the member ID of this c r m trn family member.
	 *
	 * @param MemberId the member ID of this c r m trn family member
	 */
	public void setMemberId(int MemberId);

	/**
	 * Returns the relationship ID of this c r m trn family member.
	 *
	 * @return the relationship ID of this c r m trn family member
	 */
	public int getRelationshipId();

	/**
	 * Sets the relationship ID of this c r m trn family member.
	 *
	 * @param RelationshipId the relationship ID of this c r m trn family member
	 */
	public void setRelationshipId(int RelationshipId);

	/**
	 * Returns the financially dependent of this c r m trn family member.
	 *
	 * @return the financially dependent of this c r m trn family member
	 */
	@AutoEscape
	public String getFinanciallyDependent();

	/**
	 * Sets the financially dependent of this c r m trn family member.
	 *
	 * @param FinanciallyDependent the financially dependent of this c r m trn family member
	 */
	public void setFinanciallyDependent(String FinanciallyDependent);

	/**
	 * Returns the is active of this c r m trn family member.
	 *
	 * @return the is active of this c r m trn family member
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this c r m trn family member.
	 *
	 * @param IsActive the is active of this c r m trn family member
	 */
	public void setIsActive(String IsActive);

	/**
	 * Returns the created by of this c r m trn family member.
	 *
	 * @return the created by of this c r m trn family member
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this c r m trn family member.
	 *
	 * @param CreatedBy the created by of this c r m trn family member
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this c r m trn family member.
	 *
	 * @return the created date of this c r m trn family member
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this c r m trn family member.
	 *
	 * @param CreatedDate the created date of this c r m trn family member
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this c r m trn family member.
	 *
	 * @return the modified by of this c r m trn family member
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this c r m trn family member.
	 *
	 * @param ModifiedBy the modified by of this c r m trn family member
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this c r m trn family member.
	 *
	 * @return the modified date of this c r m trn family member
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c r m trn family member.
	 *
	 * @param ModifiedDate the modified date of this c r m trn family member
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CRMTrnFamilyMember crmTrnFamilyMember);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CRMTrnFamilyMember> toCacheModel();

	@Override
	public CRMTrnFamilyMember toEscapedModel();

	@Override
	public CRMTrnFamilyMember toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}