/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CRMTrnContactCommunication service. Represents a row in the &quot;CRM_Trn_ContactCommunication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.CRMTrnContactCommunicationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.CRMTrnContactCommunicationImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CRMTrnContactCommunication
 * @see com.ifl.rapid.customer.model.impl.CRMTrnContactCommunicationImpl
 * @see com.ifl.rapid.customer.model.impl.CRMTrnContactCommunicationModelImpl
 * @generated
 */
public interface CRMTrnContactCommunicationModel extends BaseModel<CRMTrnContactCommunication> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c r m trn contact communication model instance should use the {@link CRMTrnContactCommunication} interface instead.
	 */

	/**
	 * Returns the primary key of this c r m trn contact communication.
	 *
	 * @return the primary key of this c r m trn contact communication
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this c r m trn contact communication.
	 *
	 * @param primaryKey the primary key of this c r m trn contact communication
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the contact communication ID of this c r m trn contact communication.
	 *
	 * @return the contact communication ID of this c r m trn contact communication
	 */
	public int getContactCommunicationId();

	/**
	 * Sets the contact communication ID of this c r m trn contact communication.
	 *
	 * @param ContactCommunicationId the contact communication ID of this c r m trn contact communication
	 */
	public void setContactCommunicationId(int ContactCommunicationId);

	/**
	 * Returns the contact ID of this c r m trn contact communication.
	 *
	 * @return the contact ID of this c r m trn contact communication
	 */
	public int getContactId();

	/**
	 * Sets the contact ID of this c r m trn contact communication.
	 *
	 * @param ContactId the contact ID of this c r m trn contact communication
	 */
	public void setContactId(int ContactId);

	/**
	 * Returns the communication medium of this c r m trn contact communication.
	 *
	 * @return the communication medium of this c r m trn contact communication
	 */
	public int getCommunicationMedium();

	/**
	 * Sets the communication medium of this c r m trn contact communication.
	 *
	 * @param CommunicationMedium the communication medium of this c r m trn contact communication
	 */
	public void setCommunicationMedium(int CommunicationMedium);

	/**
	 * Returns the communication medium ID of this c r m trn contact communication.
	 *
	 * @return the communication medium ID of this c r m trn contact communication
	 */
	@AutoEscape
	public String getCommunicationMediumId();

	/**
	 * Sets the communication medium ID of this c r m trn contact communication.
	 *
	 * @param CommunicationMediumId the communication medium ID of this c r m trn contact communication
	 */
	public void setCommunicationMediumId(String CommunicationMediumId);

	/**
	 * Returns the created by of this c r m trn contact communication.
	 *
	 * @return the created by of this c r m trn contact communication
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this c r m trn contact communication.
	 *
	 * @param CreatedBy the created by of this c r m trn contact communication
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this c r m trn contact communication.
	 *
	 * @return the created date of this c r m trn contact communication
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this c r m trn contact communication.
	 *
	 * @param CreatedDate the created date of this c r m trn contact communication
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this c r m trn contact communication.
	 *
	 * @return the modified by of this c r m trn contact communication
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this c r m trn contact communication.
	 *
	 * @param ModifiedBy the modified by of this c r m trn contact communication
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this c r m trn contact communication.
	 *
	 * @return the modified date of this c r m trn contact communication
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c r m trn contact communication.
	 *
	 * @param ModifiedDate the modified date of this c r m trn contact communication
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the is active of this c r m trn contact communication.
	 *
	 * @return the is active of this c r m trn contact communication
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this c r m trn contact communication.
	 *
	 * @param IsActive the is active of this c r m trn contact communication
	 */
	public void setIsActive(String IsActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CRMTrnContactCommunication crmTrnContactCommunication);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CRMTrnContactCommunication> toCacheModel();

	@Override
	public CRMTrnContactCommunication toEscapedModel();

	@Override
	public CRMTrnContactCommunication toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}