/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LocMstBranchLocation service. Represents a row in the &quot;Loc_Mst_BranchLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.LocMstBranchLocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.LocMstBranchLocationImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see LocMstBranchLocation
 * @see com.ifl.rapid.customer.model.impl.LocMstBranchLocationImpl
 * @see com.ifl.rapid.customer.model.impl.LocMstBranchLocationModelImpl
 * @generated
 */
public interface LocMstBranchLocationModel extends BaseModel<LocMstBranchLocation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loc mst branch location model instance should use the {@link LocMstBranchLocation} interface instead.
	 */

	/**
	 * Returns the primary key of this loc mst branch location.
	 *
	 * @return the primary key of this loc mst branch location
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this loc mst branch location.
	 *
	 * @param primaryKey the primary key of this loc mst branch location
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the branch ID of this loc mst branch location.
	 *
	 * @return the branch ID of this loc mst branch location
	 */
	public int getBranchId();

	/**
	 * Sets the branch ID of this loc mst branch location.
	 *
	 * @param BranchId the branch ID of this loc mst branch location
	 */
	public void setBranchId(int BranchId);

	/**
	 * Returns the branch name of this loc mst branch location.
	 *
	 * @return the branch name of this loc mst branch location
	 */
	@AutoEscape
	public String getBranchName();

	/**
	 * Sets the branch name of this loc mst branch location.
	 *
	 * @param BranchName the branch name of this loc mst branch location
	 */
	public void setBranchName(String BranchName);

	/**
	 * Returns the branch opening time of this loc mst branch location.
	 *
	 * @return the branch opening time of this loc mst branch location
	 */
	@AutoEscape
	public String getBranchOpeningTime();

	/**
	 * Sets the branch opening time of this loc mst branch location.
	 *
	 * @param BranchOpeningTime the branch opening time of this loc mst branch location
	 */
	public void setBranchOpeningTime(String BranchOpeningTime);

	/**
	 * Returns the branch closing time of this loc mst branch location.
	 *
	 * @return the branch closing time of this loc mst branch location
	 */
	@AutoEscape
	public String getBranchClosingTime();

	/**
	 * Sets the branch closing time of this loc mst branch location.
	 *
	 * @param BranchClosingTime the branch closing time of this loc mst branch location
	 */
	public void setBranchClosingTime(String BranchClosingTime);

	/**
	 * Returns the address first line of this loc mst branch location.
	 *
	 * @return the address first line of this loc mst branch location
	 */
	@AutoEscape
	public String getAddressFirstLine();

	/**
	 * Sets the address first line of this loc mst branch location.
	 *
	 * @param AddressFirstLine the address first line of this loc mst branch location
	 */
	public void setAddressFirstLine(String AddressFirstLine);

	/**
	 * Returns the address second line of this loc mst branch location.
	 *
	 * @return the address second line of this loc mst branch location
	 */
	@AutoEscape
	public String getAddressSecondLine();

	/**
	 * Sets the address second line of this loc mst branch location.
	 *
	 * @param AddressSecondLine the address second line of this loc mst branch location
	 */
	public void setAddressSecondLine(String AddressSecondLine);

	/**
	 * Returns the primary contact no of this loc mst branch location.
	 *
	 * @return the primary contact no of this loc mst branch location
	 */
	@AutoEscape
	public String getPrimaryContactNo();

	/**
	 * Sets the primary contact no of this loc mst branch location.
	 *
	 * @param PrimaryContactNo the primary contact no of this loc mst branch location
	 */
	public void setPrimaryContactNo(String PrimaryContactNo);

	/**
	 * Returns the other contact no of this loc mst branch location.
	 *
	 * @return the other contact no of this loc mst branch location
	 */
	@AutoEscape
	public String getOtherContactNo();

	/**
	 * Sets the other contact no of this loc mst branch location.
	 *
	 * @param OtherContactNo the other contact no of this loc mst branch location
	 */
	public void setOtherContactNo(String OtherContactNo);

	/**
	 * Returns the fax number of this loc mst branch location.
	 *
	 * @return the fax number of this loc mst branch location
	 */
	@AutoEscape
	public String getFaxNumber();

	/**
	 * Sets the fax number of this loc mst branch location.
	 *
	 * @param FaxNumber the fax number of this loc mst branch location
	 */
	public void setFaxNumber(String FaxNumber);

	/**
	 * Returns the location ID of this loc mst branch location.
	 *
	 * @return the location ID of this loc mst branch location
	 */
	public int getLocationId();

	/**
	 * Sets the location ID of this loc mst branch location.
	 *
	 * @param LocationId the location ID of this loc mst branch location
	 */
	public void setLocationId(int LocationId);

	/**
	 * Returns the location id_old of this loc mst branch location.
	 *
	 * @return the location id_old of this loc mst branch location
	 */
	@AutoEscape
	public String getLocationId_old();

	/**
	 * Sets the location id_old of this loc mst branch location.
	 *
	 * @param LocationId_old the location id_old of this loc mst branch location
	 */
	public void setLocationId_old(String LocationId_old);

	/**
	 * Returns the longitude of this loc mst branch location.
	 *
	 * @return the longitude of this loc mst branch location
	 */
	public double getLongitude();

	/**
	 * Sets the longitude of this loc mst branch location.
	 *
	 * @param Longitude the longitude of this loc mst branch location
	 */
	public void setLongitude(double Longitude);

	/**
	 * Returns the latitude of this loc mst branch location.
	 *
	 * @return the latitude of this loc mst branch location
	 */
	public double getLatitude();

	/**
	 * Sets the latitude of this loc mst branch location.
	 *
	 * @param Latitude the latitude of this loc mst branch location
	 */
	public void setLatitude(double Latitude);

	/**
	 * Returns the branch code of this loc mst branch location.
	 *
	 * @return the branch code of this loc mst branch location
	 */
	@AutoEscape
	public String getBranchCode();

	/**
	 * Sets the branch code of this loc mst branch location.
	 *
	 * @param BranchCode the branch code of this loc mst branch location
	 */
	public void setBranchCode(String BranchCode);

	/**
	 * Returns the created by of this loc mst branch location.
	 *
	 * @return the created by of this loc mst branch location
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this loc mst branch location.
	 *
	 * @param CreatedBy the created by of this loc mst branch location
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this loc mst branch location.
	 *
	 * @return the created date of this loc mst branch location
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this loc mst branch location.
	 *
	 * @param CreatedDate the created date of this loc mst branch location
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this loc mst branch location.
	 *
	 * @return the modified by of this loc mst branch location
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this loc mst branch location.
	 *
	 * @param ModifiedBy the modified by of this loc mst branch location
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this loc mst branch location.
	 *
	 * @return the modified date of this loc mst branch location
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loc mst branch location.
	 *
	 * @param ModifiedDate the modified date of this loc mst branch location
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the is active of this loc mst branch location.
	 *
	 * @return the is active of this loc mst branch location
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this loc mst branch location.
	 *
	 * @param IsActive the is active of this loc mst branch location
	 */
	public void setIsActive(String IsActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LocMstBranchLocation locMstBranchLocation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LocMstBranchLocation> toCacheModel();

	@Override
	public LocMstBranchLocation toEscapedModel();

	@Override
	public LocMstBranchLocation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}