/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PrdMstProduct service. Represents a row in the &quot;Prd_Mst_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.PrdMstProductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.PrdMstProductImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PrdMstProduct
 * @see com.ifl.rapid.customer.model.impl.PrdMstProductImpl
 * @see com.ifl.rapid.customer.model.impl.PrdMstProductModelImpl
 * @generated
 */
public interface PrdMstProductModel extends BaseModel<PrdMstProduct> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a prd mst product model instance should use the {@link PrdMstProduct} interface instead.
	 */

	/**
	 * Returns the primary key of this prd mst product.
	 *
	 * @return the primary key of this prd mst product
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this prd mst product.
	 *
	 * @param primaryKey the primary key of this prd mst product
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the product ID of this prd mst product.
	 *
	 * @return the product ID of this prd mst product
	 */
	@AutoEscape
	public String getProductId();

	/**
	 * Sets the product ID of this prd mst product.
	 *
	 * @param ProductId the product ID of this prd mst product
	 */
	public void setProductId(String ProductId);

	/**
	 * Returns the product key of this prd mst product.
	 *
	 * @return the product key of this prd mst product
	 */
	@AutoEscape
	public String getProductKey();

	/**
	 * Sets the product key of this prd mst product.
	 *
	 * @param ProductKey the product key of this prd mst product
	 */
	public void setProductKey(String ProductKey);

	/**
	 * Returns the display order of this prd mst product.
	 *
	 * @return the display order of this prd mst product
	 */
	public int getDisplayOrder();

	/**
	 * Sets the display order of this prd mst product.
	 *
	 * @param DisplayOrder the display order of this prd mst product
	 */
	public void setDisplayOrder(int DisplayOrder);

	/**
	 * Returns the renewal duration of this prd mst product.
	 *
	 * @return the renewal duration of this prd mst product
	 */
	public int getRenewalDuration();

	/**
	 * Sets the renewal duration of this prd mst product.
	 *
	 * @param RenewalDuration the renewal duration of this prd mst product
	 */
	public void setRenewalDuration(int RenewalDuration);

	/**
	 * Returns the short term duration of this prd mst product.
	 *
	 * @return the short term duration of this prd mst product
	 */
	public int getShortTermDuration();

	/**
	 * Sets the short term duration of this prd mst product.
	 *
	 * @param ShortTermDuration the short term duration of this prd mst product
	 */
	public void setShortTermDuration(int ShortTermDuration);

	/**
	 * Returns the min plan term of this prd mst product.
	 *
	 * @return the min plan term of this prd mst product
	 */
	public int getMinPlanTerm();

	/**
	 * Sets the min plan term of this prd mst product.
	 *
	 * @param MinPlanTerm the min plan term of this prd mst product
	 */
	public void setMinPlanTerm(int MinPlanTerm);

	/**
	 * Returns the max plan term of this prd mst product.
	 *
	 * @return the max plan term of this prd mst product
	 */
	public int getMaxPlanTerm();

	/**
	 * Sets the max plan term of this prd mst product.
	 *
	 * @param MaxPlanTerm the max plan term of this prd mst product
	 */
	public void setMaxPlanTerm(int MaxPlanTerm);

	/**
	 * Returns the min sum assured of this prd mst product.
	 *
	 * @return the min sum assured of this prd mst product
	 */
	public int getMinSumAssured();

	/**
	 * Sets the min sum assured of this prd mst product.
	 *
	 * @param MinSumAssured the min sum assured of this prd mst product
	 */
	public void setMinSumAssured(int MinSumAssured);

	/**
	 * Returns the max sum assured of this prd mst product.
	 *
	 * @return the max sum assured of this prd mst product
	 */
	public int getMaxSumAssured();

	/**
	 * Sets the max sum assured of this prd mst product.
	 *
	 * @param MaxSumAssured the max sum assured of this prd mst product
	 */
	public void setMaxSumAssured(int MaxSumAssured);

	/**
	 * Returns the is regular premium of this prd mst product.
	 *
	 * @return the is regular premium of this prd mst product
	 */
	public int getIsRegularPremium();

	/**
	 * Sets the is regular premium of this prd mst product.
	 *
	 * @param IsRegularPremium the is regular premium of this prd mst product
	 */
	public void setIsRegularPremium(int IsRegularPremium);

	/**
	 * Returns the is limited premium of this prd mst product.
	 *
	 * @return the is limited premium of this prd mst product
	 */
	public int getIsLimitedPremium();

	/**
	 * Sets the is limited premium of this prd mst product.
	 *
	 * @param IsLimitedPremium the is limited premium of this prd mst product
	 */
	public void setIsLimitedPremium(int IsLimitedPremium);

	/**
	 * Returns the is single premium of this prd mst product.
	 *
	 * @return the is single premium of this prd mst product
	 */
	public int getIsSinglePremium();

	/**
	 * Sets the is single premium of this prd mst product.
	 *
	 * @param IsSinglePremium the is single premium of this prd mst product
	 */
	public void setIsSinglePremium(int IsSinglePremium);

	/**
	 * Returns the is active of this prd mst product.
	 *
	 * @return the is active of this prd mst product
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this prd mst product.
	 *
	 * @param IsActive the is active of this prd mst product
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created by of this prd mst product.
	 *
	 * @return the created by of this prd mst product
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this prd mst product.
	 *
	 * @param CreatedBy the created by of this prd mst product
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this prd mst product.
	 *
	 * @return the created date of this prd mst product
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this prd mst product.
	 *
	 * @param CreatedDate the created date of this prd mst product
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified date of this prd mst product.
	 *
	 * @return the modified date of this prd mst product
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this prd mst product.
	 *
	 * @param ModifiedDate the modified date of this prd mst product
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this prd mst product.
	 *
	 * @return the modified by of this prd mst product
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this prd mst product.
	 *
	 * @param ModifiedBy the modified by of this prd mst product
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PrdMstProduct prdMstProduct);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PrdMstProduct> toCacheModel();

	@Override
	public PrdMstProduct toEscapedModel();

	@Override
	public PrdMstProduct toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}