/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QrcMstRequests service. Represents a row in the &quot;Qrc_Mst_Requests&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.QrcMstRequestsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.QrcMstRequestsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see QrcMstRequests
 * @see com.ifl.rapid.customer.model.impl.QrcMstRequestsImpl
 * @see com.ifl.rapid.customer.model.impl.QrcMstRequestsModelImpl
 * @generated
 */
public interface QrcMstRequestsModel extends BaseModel<QrcMstRequests> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qrc mst requests model instance should use the {@link QrcMstRequests} interface instead.
	 */

	/**
	 * Returns the primary key of this qrc mst requests.
	 *
	 * @return the primary key of this qrc mst requests
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this qrc mst requests.
	 *
	 * @param primaryKey the primary key of this qrc mst requests
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the request ID of this qrc mst requests.
	 *
	 * @return the request ID of this qrc mst requests
	 */
	public int getRequestId();

	/**
	 * Sets the request ID of this qrc mst requests.
	 *
	 * @param RequestId the request ID of this qrc mst requests
	 */
	public void setRequestId(int RequestId);

	/**
	 * Returns the category of this qrc mst requests.
	 *
	 * @return the category of this qrc mst requests
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this qrc mst requests.
	 *
	 * @param Category the category of this qrc mst requests
	 */
	public void setCategory(String Category);

	/**
	 * Returns the call type of this qrc mst requests.
	 *
	 * @return the call type of this qrc mst requests
	 */
	@AutoEscape
	public String getCallType();

	/**
	 * Sets the call type of this qrc mst requests.
	 *
	 * @param CallType the call type of this qrc mst requests
	 */
	public void setCallType(String CallType);

	/**
	 * Returns the call sub type of this qrc mst requests.
	 *
	 * @return the call sub type of this qrc mst requests
	 */
	@AutoEscape
	public String getCallSubType();

	/**
	 * Sets the call sub type of this qrc mst requests.
	 *
	 * @param CallSubType the call sub type of this qrc mst requests
	 */
	public void setCallSubType(String CallSubType);

	/**
	 * Returns the keyword of this qrc mst requests.
	 *
	 * @return the keyword of this qrc mst requests
	 */
	@AutoEscape
	public String getKeyword();

	/**
	 * Sets the keyword of this qrc mst requests.
	 *
	 * @param Keyword the keyword of this qrc mst requests
	 */
	public void setKeyword(String Keyword);

	/**
	 * Returns the is active of this qrc mst requests.
	 *
	 * @return the is active of this qrc mst requests
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this qrc mst requests.
	 *
	 * @param IsActive the is active of this qrc mst requests
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created by of this qrc mst requests.
	 *
	 * @return the created by of this qrc mst requests
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this qrc mst requests.
	 *
	 * @param CreatedBy the created by of this qrc mst requests
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this qrc mst requests.
	 *
	 * @return the created date of this qrc mst requests
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this qrc mst requests.
	 *
	 * @param CreatedDate the created date of this qrc mst requests
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified date of this qrc mst requests.
	 *
	 * @return the modified date of this qrc mst requests
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this qrc mst requests.
	 *
	 * @param ModifiedDate the modified date of this qrc mst requests
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this qrc mst requests.
	 *
	 * @return the modified by of this qrc mst requests
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this qrc mst requests.
	 *
	 * @param ModifiedBy the modified by of this qrc mst requests
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QrcMstRequests qrcMstRequests);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QrcMstRequests> toCacheModel();

	@Override
	public QrcMstRequests toEscapedModel();

	@Override
	public QrcMstRequests toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}