/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QrcMstSubServices service. Represents a row in the &quot;Qrc_Mst_Sub_Services&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.QrcMstSubServicesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.QrcMstSubServicesImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see QrcMstSubServices
 * @see com.ifl.rapid.customer.model.impl.QrcMstSubServicesImpl
 * @see com.ifl.rapid.customer.model.impl.QrcMstSubServicesModelImpl
 * @generated
 */
public interface QrcMstSubServicesModel extends BaseModel<QrcMstSubServices> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qrc mst sub services model instance should use the {@link QrcMstSubServices} interface instead.
	 */

	/**
	 * Returns the primary key of this qrc mst sub services.
	 *
	 * @return the primary key of this qrc mst sub services
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this qrc mst sub services.
	 *
	 * @param primaryKey the primary key of this qrc mst sub services
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the sub service ID of this qrc mst sub services.
	 *
	 * @return the sub service ID of this qrc mst sub services
	 */
	public int getSubServiceId();

	/**
	 * Sets the sub service ID of this qrc mst sub services.
	 *
	 * @param SubServiceId the sub service ID of this qrc mst sub services
	 */
	public void setSubServiceId(int SubServiceId);

	/**
	 * Returns the sub service name of this qrc mst sub services.
	 *
	 * @return the sub service name of this qrc mst sub services
	 */
	@AutoEscape
	public String getSubServiceName();

	/**
	 * Sets the sub service name of this qrc mst sub services.
	 *
	 * @param SubServiceName the sub service name of this qrc mst sub services
	 */
	public void setSubServiceName(String SubServiceName);

	/**
	 * Returns the sub service url of this qrc mst sub services.
	 *
	 * @return the sub service url of this qrc mst sub services
	 */
	@AutoEscape
	public String getSubServiceUrl();

	/**
	 * Sets the sub service url of this qrc mst sub services.
	 *
	 * @param SubServiceUrl the sub service url of this qrc mst sub services
	 */
	public void setSubServiceUrl(String SubServiceUrl);

	/**
	 * Returns the service ID of this qrc mst sub services.
	 *
	 * @return the service ID of this qrc mst sub services
	 */
	public int getServiceId();

	/**
	 * Sets the service ID of this qrc mst sub services.
	 *
	 * @param ServiceId the service ID of this qrc mst sub services
	 */
	public void setServiceId(int ServiceId);

	/**
	 * Returns the is active of this qrc mst sub services.
	 *
	 * @return the is active of this qrc mst sub services
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this qrc mst sub services.
	 *
	 * @param IsActive the is active of this qrc mst sub services
	 */
	public void setIsActive(String IsActive);

	/**
	 * Returns the created by of this qrc mst sub services.
	 *
	 * @return the created by of this qrc mst sub services
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this qrc mst sub services.
	 *
	 * @param CreatedBy the created by of this qrc mst sub services
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this qrc mst sub services.
	 *
	 * @return the created date of this qrc mst sub services
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this qrc mst sub services.
	 *
	 * @param CreatedDate the created date of this qrc mst sub services
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this qrc mst sub services.
	 *
	 * @return the modified by of this qrc mst sub services
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this qrc mst sub services.
	 *
	 * @param ModifiedBy the modified by of this qrc mst sub services
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this qrc mst sub services.
	 *
	 * @return the modified date of this qrc mst sub services
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this qrc mst sub services.
	 *
	 * @param ModifiedDate the modified date of this qrc mst sub services
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QrcMstSubServices qrcMstSubServices);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QrcMstSubServices> toCacheModel();

	@Override
	public QrcMstSubServices toEscapedModel();

	@Override
	public QrcMstSubServices toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}