/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QrcTrnOtp service. Represents a row in the &quot;Qrc_Trn_Otp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.QrcTrnOtpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.QrcTrnOtpImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see QrcTrnOtp
 * @see com.ifl.rapid.customer.model.impl.QrcTrnOtpImpl
 * @see com.ifl.rapid.customer.model.impl.QrcTrnOtpModelImpl
 * @generated
 */
public interface QrcTrnOtpModel extends BaseModel<QrcTrnOtp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qrc trn otp model instance should use the {@link QrcTrnOtp} interface instead.
	 */

	/**
	 * Returns the primary key of this qrc trn otp.
	 *
	 * @return the primary key of this qrc trn otp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this qrc trn otp.
	 *
	 * @param primaryKey the primary key of this qrc trn otp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the otp_ ID of this qrc trn otp.
	 *
	 * @return the otp_ ID of this qrc trn otp
	 */
	public int getOtp_Id();

	/**
	 * Sets the otp_ ID of this qrc trn otp.
	 *
	 * @param Otp_Id the otp_ ID of this qrc trn otp
	 */
	public void setOtp_Id(int Otp_Id);

	/**
	 * Returns the otp of this qrc trn otp.
	 *
	 * @return the otp of this qrc trn otp
	 */
	@AutoEscape
	public String getOtp();

	/**
	 * Sets the otp of this qrc trn otp.
	 *
	 * @param Otp the otp of this qrc trn otp
	 */
	public void setOtp(String Otp);

	/**
	 * Returns the contact ID of this qrc trn otp.
	 *
	 * @return the contact ID of this qrc trn otp
	 */
	public int getContactId();

	/**
	 * Sets the contact ID of this qrc trn otp.
	 *
	 * @param ContactId the contact ID of this qrc trn otp
	 */
	public void setContactId(int ContactId);

	/**
	 * Returns the created by of this qrc trn otp.
	 *
	 * @return the created by of this qrc trn otp
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this qrc trn otp.
	 *
	 * @param CreatedBy the created by of this qrc trn otp
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this qrc trn otp.
	 *
	 * @return the created date of this qrc trn otp
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this qrc trn otp.
	 *
	 * @param CreatedDate the created date of this qrc trn otp
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this qrc trn otp.
	 *
	 * @return the modified by of this qrc trn otp
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this qrc trn otp.
	 *
	 * @param ModifiedBy the modified by of this qrc trn otp
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this qrc trn otp.
	 *
	 * @return the modified date of this qrc trn otp
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this qrc trn otp.
	 *
	 * @param ModifiedDate the modified date of this qrc trn otp
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the is active of this qrc trn otp.
	 *
	 * @return the is active of this qrc trn otp
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this qrc trn otp.
	 *
	 * @param IsActive the is active of this qrc trn otp
	 */
	public void setIsActive(String IsActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QrcTrnOtp qrcTrnOtp);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QrcTrnOtp> toCacheModel();

	@Override
	public QrcTrnOtp toEscapedModel();

	@Override
	public QrcTrnOtp toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}