/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QrcTrnHistory service. Represents a row in the &quot;Qrc_Trn_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.QrcTrnHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.QrcTrnHistoryImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see QrcTrnHistory
 * @see com.ifl.rapid.customer.model.impl.QrcTrnHistoryImpl
 * @see com.ifl.rapid.customer.model.impl.QrcTrnHistoryModelImpl
 * @generated
 */
public interface QrcTrnHistoryModel extends BaseModel<QrcTrnHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qrc trn history model instance should use the {@link QrcTrnHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this qrc trn history.
	 *
	 * @return the primary key of this qrc trn history
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this qrc trn history.
	 *
	 * @param primaryKey the primary key of this qrc trn history
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the history ID of this qrc trn history.
	 *
	 * @return the history ID of this qrc trn history
	 */
	public int getHistoryId();

	/**
	 * Sets the history ID of this qrc trn history.
	 *
	 * @param HistoryId the history ID of this qrc trn history
	 */
	public void setHistoryId(int HistoryId);

	/**
	 * Returns the contact ID of this qrc trn history.
	 *
	 * @return the contact ID of this qrc trn history
	 */
	public int getContactId();

	/**
	 * Sets the contact ID of this qrc trn history.
	 *
	 * @param ContactId the contact ID of this qrc trn history
	 */
	public void setContactId(int ContactId);

	/**
	 * Returns the created contact ID of this qrc trn history.
	 *
	 * @return the created contact ID of this qrc trn history
	 */
	public int getCreatedContactId();

	/**
	 * Sets the created contact ID of this qrc trn history.
	 *
	 * @param CreatedContactId the created contact ID of this qrc trn history
	 */
	public void setCreatedContactId(int CreatedContactId);

	/**
	 * Returns the request type of this qrc trn history.
	 *
	 * @return the request type of this qrc trn history
	 */
	@AutoEscape
	public String getRequestType();

	/**
	 * Sets the request type of this qrc trn history.
	 *
	 * @param RequestType the request type of this qrc trn history
	 */
	public void setRequestType(String RequestType);

	/**
	 * Returns the change request type of this qrc trn history.
	 *
	 * @return the change request type of this qrc trn history
	 */
	@AutoEscape
	public String getChangeRequestType();

	/**
	 * Sets the change request type of this qrc trn history.
	 *
	 * @param ChangeRequestType the change request type of this qrc trn history
	 */
	public void setChangeRequestType(String ChangeRequestType);

	/**
	 * Returns the pickup date of this qrc trn history.
	 *
	 * @return the pickup date of this qrc trn history
	 */
	public Date getPickupDate();

	/**
	 * Sets the pickup date of this qrc trn history.
	 *
	 * @param PickupDate the pickup date of this qrc trn history
	 */
	public void setPickupDate(Date PickupDate);

	/**
	 * Returns the pickup time of this qrc trn history.
	 *
	 * @return the pickup time of this qrc trn history
	 */
	@AutoEscape
	public String getPickupTime();

	/**
	 * Sets the pickup time of this qrc trn history.
	 *
	 * @param PickupTime the pickup time of this qrc trn history
	 */
	public void setPickupTime(String PickupTime);

	/**
	 * Returns the x m l data of this qrc trn history.
	 *
	 * @return the x m l data of this qrc trn history
	 */
	@AutoEscape
	public String getXMLData();

	/**
	 * Sets the x m l data of this qrc trn history.
	 *
	 * @param XMLData the x m l data of this qrc trn history
	 */
	public void setXMLData(String XMLData);

	/**
	 * Returns the address type ID of this qrc trn history.
	 *
	 * @return the address type ID of this qrc trn history
	 */
	public int getAddressTypeId();

	/**
	 * Sets the address type ID of this qrc trn history.
	 *
	 * @param AddressTypeId the address type ID of this qrc trn history
	 */
	public void setAddressTypeId(int AddressTypeId);

	/**
	 * Returns the branch ID of this qrc trn history.
	 *
	 * @return the branch ID of this qrc trn history
	 */
	public int getBranchId();

	/**
	 * Sets the branch ID of this qrc trn history.
	 *
	 * @param BranchId the branch ID of this qrc trn history
	 */
	public void setBranchId(int BranchId);

	/**
	 * Returns the is active of this qrc trn history.
	 *
	 * @return the is active of this qrc trn history
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this qrc trn history.
	 *
	 * @param IsActive the is active of this qrc trn history
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created by of this qrc trn history.
	 *
	 * @return the created by of this qrc trn history
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this qrc trn history.
	 *
	 * @param CreatedBy the created by of this qrc trn history
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this qrc trn history.
	 *
	 * @return the created date of this qrc trn history
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this qrc trn history.
	 *
	 * @param CreatedDate the created date of this qrc trn history
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified date of this qrc trn history.
	 *
	 * @return the modified date of this qrc trn history
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this qrc trn history.
	 *
	 * @param ModifiedDate the modified date of this qrc trn history
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this qrc trn history.
	 *
	 * @return the modified by of this qrc trn history
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this qrc trn history.
	 *
	 * @param ModifiedBy the modified by of this qrc trn history
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QrcTrnHistory qrcTrnHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QrcTrnHistory> toCacheModel();

	@Override
	public QrcTrnHistory toEscapedModel();

	@Override
	public QrcTrnHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}