/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QrcTrnServiceRequests service. Represents a row in the &quot;Qrc_Trn_ServiceRequests&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.QrcTrnServiceRequestsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.QrcTrnServiceRequestsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see QrcTrnServiceRequests
 * @see com.ifl.rapid.customer.model.impl.QrcTrnServiceRequestsImpl
 * @see com.ifl.rapid.customer.model.impl.QrcTrnServiceRequestsModelImpl
 * @generated
 */
public interface QrcTrnServiceRequestsModel extends BaseModel<QrcTrnServiceRequests> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qrc trn service requests model instance should use the {@link QrcTrnServiceRequests} interface instead.
	 */

	/**
	 * Returns the primary key of this qrc trn service requests.
	 *
	 * @return the primary key of this qrc trn service requests
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this qrc trn service requests.
	 *
	 * @param primaryKey the primary key of this qrc trn service requests
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the service request ID of this qrc trn service requests.
	 *
	 * @return the service request ID of this qrc trn service requests
	 */
	public int getServiceRequestId();

	/**
	 * Sets the service request ID of this qrc trn service requests.
	 *
	 * @param ServiceRequestId the service request ID of this qrc trn service requests
	 */
	public void setServiceRequestId(int ServiceRequestId);

	/**
	 * Returns the contact ID of this qrc trn service requests.
	 *
	 * @return the contact ID of this qrc trn service requests
	 */
	public int getContactId();

	/**
	 * Sets the contact ID of this qrc trn service requests.
	 *
	 * @param ContactId the contact ID of this qrc trn service requests
	 */
	public void setContactId(int ContactId);

	/**
	 * Returns the sr ID of this qrc trn service requests.
	 *
	 * @return the sr ID of this qrc trn service requests
	 */
	@AutoEscape
	public String getSrId();

	/**
	 * Sets the sr ID of this qrc trn service requests.
	 *
	 * @param SrId the sr ID of this qrc trn service requests
	 */
	public void setSrId(String SrId);

	/**
	 * Returns the process ID of this qrc trn service requests.
	 *
	 * @return the process ID of this qrc trn service requests
	 */
	@AutoEscape
	public String getProcessId();

	/**
	 * Sets the process ID of this qrc trn service requests.
	 *
	 * @param ProcessId the process ID of this qrc trn service requests
	 */
	public void setProcessId(String ProcessId);

	/**
	 * Returns the source of this qrc trn service requests.
	 *
	 * @return the source of this qrc trn service requests
	 */
	@AutoEscape
	public String getSource();

	/**
	 * Sets the source of this qrc trn service requests.
	 *
	 * @param Source the source of this qrc trn service requests
	 */
	public void setSource(String Source);

	/**
	 * Returns the channel of this qrc trn service requests.
	 *
	 * @return the channel of this qrc trn service requests
	 */
	@AutoEscape
	public String getChannel();

	/**
	 * Sets the channel of this qrc trn service requests.
	 *
	 * @param Channel the channel of this qrc trn service requests
	 */
	public void setChannel(String Channel);

	/**
	 * Returns the priority of this qrc trn service requests.
	 *
	 * @return the priority of this qrc trn service requests
	 */
	@AutoEscape
	public String getPriority();

	/**
	 * Sets the priority of this qrc trn service requests.
	 *
	 * @param Priority the priority of this qrc trn service requests
	 */
	public void setPriority(String Priority);

	/**
	 * Returns the policy no of this qrc trn service requests.
	 *
	 * @return the policy no of this qrc trn service requests
	 */
	@AutoEscape
	public String getPolicyNo();

	/**
	 * Sets the policy no of this qrc trn service requests.
	 *
	 * @param PolicyNo the policy no of this qrc trn service requests
	 */
	public void setPolicyNo(String PolicyNo);

	/**
	 * Returns the case details of this qrc trn service requests.
	 *
	 * @return the case details of this qrc trn service requests
	 */
	@AutoEscape
	public String getCaseDetails();

	/**
	 * Sets the case details of this qrc trn service requests.
	 *
	 * @param CaseDetails the case details of this qrc trn service requests
	 */
	public void setCaseDetails(String CaseDetails);

	/**
	 * Returns the is manual of this qrc trn service requests.
	 *
	 * @return the is manual of this qrc trn service requests
	 */
	@AutoEscape
	public String getIsManual();

	/**
	 * Sets the is manual of this qrc trn service requests.
	 *
	 * @param IsManual the is manual of this qrc trn service requests
	 */
	public void setIsManual(String IsManual);

	/**
	 * Returns the is l a updated of this qrc trn service requests.
	 *
	 * @return the is l a updated of this qrc trn service requests
	 */
	@AutoEscape
	public String getIsLAUpdated();

	/**
	 * Sets the is l a updated of this qrc trn service requests.
	 *
	 * @param IsLAUpdated the is l a updated of this qrc trn service requests
	 */
	public void setIsLAUpdated(String IsLAUpdated);

	/**
	 * Returns the comments of this qrc trn service requests.
	 *
	 * @return the comments of this qrc trn service requests
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this qrc trn service requests.
	 *
	 * @param Comments the comments of this qrc trn service requests
	 */
	public void setComments(String Comments);

	/**
	 * Returns the is sign verified of this qrc trn service requests.
	 *
	 * @return the is sign verified of this qrc trn service requests
	 */
	@AutoEscape
	public String getIsSignVerified();

	/**
	 * Sets the is sign verified of this qrc trn service requests.
	 *
	 * @param IsSignVerified the is sign verified of this qrc trn service requests
	 */
	public void setIsSignVerified(String IsSignVerified);

	/**
	 * Returns the request ID of this qrc trn service requests.
	 *
	 * @return the request ID of this qrc trn service requests
	 */
	public int getRequestId();

	/**
	 * Sets the request ID of this qrc trn service requests.
	 *
	 * @param RequestId the request ID of this qrc trn service requests
	 */
	public void setRequestId(int RequestId);

	/**
	 * Returns the assigned to of this qrc trn service requests.
	 *
	 * @return the assigned to of this qrc trn service requests
	 */
	public int getAssignedTo();

	/**
	 * Sets the assigned to of this qrc trn service requests.
	 *
	 * @param AssignedTo the assigned to of this qrc trn service requests
	 */
	public void setAssignedTo(int AssignedTo);

	/**
	 * Returns the created contact ID of this qrc trn service requests.
	 *
	 * @return the created contact ID of this qrc trn service requests
	 */
	public int getCreatedContactId();

	/**
	 * Sets the created contact ID of this qrc trn service requests.
	 *
	 * @param CreatedContactId the created contact ID of this qrc trn service requests
	 */
	public void setCreatedContactId(int CreatedContactId);

	/**
	 * Returns the history ID of this qrc trn service requests.
	 *
	 * @return the history ID of this qrc trn service requests
	 */
	public int getHistoryId();

	/**
	 * Sets the history ID of this qrc trn service requests.
	 *
	 * @param HistoryId the history ID of this qrc trn service requests
	 */
	public void setHistoryId(int HistoryId);

	/**
	 * Returns the address type ID of this qrc trn service requests.
	 *
	 * @return the address type ID of this qrc trn service requests
	 */
	public int getAddressTypeId();

	/**
	 * Sets the address type ID of this qrc trn service requests.
	 *
	 * @param AddressTypeId the address type ID of this qrc trn service requests
	 */
	public void setAddressTypeId(int AddressTypeId);

	/**
	 * Returns the is active of this qrc trn service requests.
	 *
	 * @return the is active of this qrc trn service requests
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this qrc trn service requests.
	 *
	 * @param IsActive the is active of this qrc trn service requests
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created by of this qrc trn service requests.
	 *
	 * @return the created by of this qrc trn service requests
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this qrc trn service requests.
	 *
	 * @param CreatedBy the created by of this qrc trn service requests
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this qrc trn service requests.
	 *
	 * @return the created date of this qrc trn service requests
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this qrc trn service requests.
	 *
	 * @param CreatedDate the created date of this qrc trn service requests
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified date of this qrc trn service requests.
	 *
	 * @return the modified date of this qrc trn service requests
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this qrc trn service requests.
	 *
	 * @param ModifiedDate the modified date of this qrc trn service requests
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this qrc trn service requests.
	 *
	 * @return the modified by of this qrc trn service requests
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this qrc trn service requests.
	 *
	 * @param ModifiedBy the modified by of this qrc trn service requests
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QrcTrnServiceRequests qrcTrnServiceRequests);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QrcTrnServiceRequests> toCacheModel();

	@Override
	public QrcTrnServiceRequests toEscapedModel();

	@Override
	public QrcTrnServiceRequests toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}