/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the State service. Represents a row in the &quot;Loc_Mst_State&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifl.rapid.customer.model.impl.StateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifl.rapid.customer.model.impl.StateImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see State
 * @see com.ifl.rapid.customer.model.impl.StateImpl
 * @see com.ifl.rapid.customer.model.impl.StateModelImpl
 * @generated
 */
public interface StateModel extends BaseModel<State> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a state model instance should use the {@link State} interface instead.
	 */

	/**
	 * Returns the primary key of this state.
	 *
	 * @return the primary key of this state
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this state.
	 *
	 * @param primaryKey the primary key of this state
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the state ID of this state.
	 *
	 * @return the state ID of this state
	 */
	public int getStateId();

	/**
	 * Sets the state ID of this state.
	 *
	 * @param StateId the state ID of this state
	 */
	public void setStateId(int StateId);

	/**
	 * Returns the state code of this state.
	 *
	 * @return the state code of this state
	 */
	@AutoEscape
	public String getStateCode();

	/**
	 * Sets the state code of this state.
	 *
	 * @param StateCode the state code of this state
	 */
	public void setStateCode(String StateCode);

	/**
	 * Returns the state name of this state.
	 *
	 * @return the state name of this state
	 */
	@AutoEscape
	public String getStateName();

	/**
	 * Sets the state name of this state.
	 *
	 * @param StateName the state name of this state
	 */
	public void setStateName(String StateName);

	/**
	 * Returns the is active of this state.
	 *
	 * @return the is active of this state
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this state.
	 *
	 * @param IsActive the is active of this state
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created by of this state.
	 *
	 * @return the created by of this state
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this state.
	 *
	 * @param CreatedBy the created by of this state
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this state.
	 *
	 * @return the created date of this state
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this state.
	 *
	 * @param CreatedDate the created date of this state
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified date of this state.
	 *
	 * @return the modified date of this state
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this state.
	 *
	 * @param ModifiedDate the modified date of this state
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this state.
	 *
	 * @return the modified by of this state
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this state.
	 *
	 * @param ModifiedBy the modified by of this state
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(State state);

	@Override
	public int hashCode();

	@Override
	public CacheModel<State> toCacheModel();

	@Override
	public State toEscapedModel();

	@Override
	public State toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}