/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifl.rapid.customer.service.base;

import com.ifl.rapid.customer.model.CRM_Trn_PolicyAddress;
import com.ifl.rapid.customer.service.CRM_Trn_PolicyAddressLocalService;
import com.ifl.rapid.customer.service.persistence.ApplyTrnApplicationFormPersistence;
import com.ifl.rapid.customer.service.persistence.ApplyTrnQuoteDetailsPersistence;
import com.ifl.rapid.customer.service.persistence.CRMTrnContactCommunicationPersistence;
import com.ifl.rapid.customer.service.persistence.CRMTrnFamilyMemberPersistence;
import com.ifl.rapid.customer.service.persistence.CRM_Trn_AddressPersistence;
import com.ifl.rapid.customer.service.persistence.CRM_Trn_ContactPersistence;
import com.ifl.rapid.customer.service.persistence.CRM_Trn_PhonePersistence;
import com.ifl.rapid.customer.service.persistence.CRM_Trn_PolicyAddressPersistence;
import com.ifl.rapid.customer.service.persistence.CityPersistence;
import com.ifl.rapid.customer.service.persistence.Config_Mst_GenericMasterPersistence;
import com.ifl.rapid.customer.service.persistence.LocMstBranchLocationPersistence;
import com.ifl.rapid.customer.service.persistence.LocMstLocationPersistence;
import com.ifl.rapid.customer.service.persistence.PrdMstProductPersistence;
import com.ifl.rapid.customer.service.persistence.QrcMstRequestsPersistence;
import com.ifl.rapid.customer.service.persistence.QrcMstServicesPersistence;
import com.ifl.rapid.customer.service.persistence.QrcMstSubServicesPersistence;
import com.ifl.rapid.customer.service.persistence.QrcTrnHistoryPersistence;
import com.ifl.rapid.customer.service.persistence.QrcTrnOtpPersistence;
import com.ifl.rapid.customer.service.persistence.QrcTrnServiceRequestsPersistence;
import com.ifl.rapid.customer.service.persistence.StatePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the c r m_ trn_ policy address local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ifl.rapid.customer.service.impl.CRM_Trn_PolicyAddressLocalServiceImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see com.ifl.rapid.customer.service.impl.CRM_Trn_PolicyAddressLocalServiceImpl
 * @see com.ifl.rapid.customer.service.CRM_Trn_PolicyAddressLocalServiceUtil
 * @generated
 */
public abstract class CRM_Trn_PolicyAddressLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements CRM_Trn_PolicyAddressLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.ifl.rapid.customer.service.CRM_Trn_PolicyAddressLocalServiceUtil} to access the c r m_ trn_ policy address local service.
	 */

	/**
	 * Adds the c r m_ trn_ policy address to the database. Also notifies the appropriate model listeners.
	 *
	 * @param crm_Trn_PolicyAddress the c r m_ trn_ policy address
	 * @return the c r m_ trn_ policy address that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CRM_Trn_PolicyAddress addCRM_Trn_PolicyAddress(
		CRM_Trn_PolicyAddress crm_Trn_PolicyAddress) throws SystemException {
		crm_Trn_PolicyAddress.setNew(true);

		return crm_Trn_PolicyAddressPersistence.update(crm_Trn_PolicyAddress);
	}

	/**
	 * Creates a new c r m_ trn_ policy address with the primary key. Does not add the c r m_ trn_ policy address to the database.
	 *
	 * @param PolicyAddressId the primary key for the new c r m_ trn_ policy address
	 * @return the new c r m_ trn_ policy address
	 */
	@Override
	public CRM_Trn_PolicyAddress createCRM_Trn_PolicyAddress(
		int PolicyAddressId) {
		return crm_Trn_PolicyAddressPersistence.create(PolicyAddressId);
	}

	/**
	 * Deletes the c r m_ trn_ policy address with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param PolicyAddressId the primary key of the c r m_ trn_ policy address
	 * @return the c r m_ trn_ policy address that was removed
	 * @throws PortalException if a c r m_ trn_ policy address with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CRM_Trn_PolicyAddress deleteCRM_Trn_PolicyAddress(
		int PolicyAddressId) throws PortalException, SystemException {
		return crm_Trn_PolicyAddressPersistence.remove(PolicyAddressId);
	}

	/**
	 * Deletes the c r m_ trn_ policy address from the database. Also notifies the appropriate model listeners.
	 *
	 * @param crm_Trn_PolicyAddress the c r m_ trn_ policy address
	 * @return the c r m_ trn_ policy address that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CRM_Trn_PolicyAddress deleteCRM_Trn_PolicyAddress(
		CRM_Trn_PolicyAddress crm_Trn_PolicyAddress) throws SystemException {
		return crm_Trn_PolicyAddressPersistence.remove(crm_Trn_PolicyAddress);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(CRM_Trn_PolicyAddress.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return crm_Trn_PolicyAddressPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.ifl.rapid.customer.model.impl.CRM_Trn_PolicyAddressModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return crm_Trn_PolicyAddressPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.ifl.rapid.customer.model.impl.CRM_Trn_PolicyAddressModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return crm_Trn_PolicyAddressPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return crm_Trn_PolicyAddressPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return crm_Trn_PolicyAddressPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public CRM_Trn_PolicyAddress fetchCRM_Trn_PolicyAddress(int PolicyAddressId)
		throws SystemException {
		return crm_Trn_PolicyAddressPersistence.fetchByPrimaryKey(PolicyAddressId);
	}

	/**
	 * Returns the c r m_ trn_ policy address with the primary key.
	 *
	 * @param PolicyAddressId the primary key of the c r m_ trn_ policy address
	 * @return the c r m_ trn_ policy address
	 * @throws PortalException if a c r m_ trn_ policy address with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public CRM_Trn_PolicyAddress getCRM_Trn_PolicyAddress(int PolicyAddressId)
		throws PortalException, SystemException {
		return crm_Trn_PolicyAddressPersistence.findByPrimaryKey(PolicyAddressId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return crm_Trn_PolicyAddressPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the c r m_ trn_ policy addresses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.ifl.rapid.customer.model.impl.CRM_Trn_PolicyAddressModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of c r m_ trn_ policy addresses
	 * @param end the upper bound of the range of c r m_ trn_ policy addresses (not inclusive)
	 * @return the range of c r m_ trn_ policy addresses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<CRM_Trn_PolicyAddress> getCRM_Trn_PolicyAddresses(int start,
		int end) throws SystemException {
		return crm_Trn_PolicyAddressPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of c r m_ trn_ policy addresses.
	 *
	 * @return the number of c r m_ trn_ policy addresses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getCRM_Trn_PolicyAddressesCount() throws SystemException {
		return crm_Trn_PolicyAddressPersistence.countAll();
	}

	/**
	 * Updates the c r m_ trn_ policy address in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param crm_Trn_PolicyAddress the c r m_ trn_ policy address
	 * @return the c r m_ trn_ policy address that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CRM_Trn_PolicyAddress updateCRM_Trn_PolicyAddress(
		CRM_Trn_PolicyAddress crm_Trn_PolicyAddress) throws SystemException {
		return crm_Trn_PolicyAddressPersistence.update(crm_Trn_PolicyAddress);
	}

	/**
	 * Returns the apply trn application form local service.
	 *
	 * @return the apply trn application form local service
	 */
	public com.ifl.rapid.customer.service.ApplyTrnApplicationFormLocalService getApplyTrnApplicationFormLocalService() {
		return applyTrnApplicationFormLocalService;
	}

	/**
	 * Sets the apply trn application form local service.
	 *
	 * @param applyTrnApplicationFormLocalService the apply trn application form local service
	 */
	public void setApplyTrnApplicationFormLocalService(
		com.ifl.rapid.customer.service.ApplyTrnApplicationFormLocalService applyTrnApplicationFormLocalService) {
		this.applyTrnApplicationFormLocalService = applyTrnApplicationFormLocalService;
	}

	/**
	 * Returns the apply trn application form persistence.
	 *
	 * @return the apply trn application form persistence
	 */
	public ApplyTrnApplicationFormPersistence getApplyTrnApplicationFormPersistence() {
		return applyTrnApplicationFormPersistence;
	}

	/**
	 * Sets the apply trn application form persistence.
	 *
	 * @param applyTrnApplicationFormPersistence the apply trn application form persistence
	 */
	public void setApplyTrnApplicationFormPersistence(
		ApplyTrnApplicationFormPersistence applyTrnApplicationFormPersistence) {
		this.applyTrnApplicationFormPersistence = applyTrnApplicationFormPersistence;
	}

	/**
	 * Returns the apply trn quote details local service.
	 *
	 * @return the apply trn quote details local service
	 */
	public com.ifl.rapid.customer.service.ApplyTrnQuoteDetailsLocalService getApplyTrnQuoteDetailsLocalService() {
		return applyTrnQuoteDetailsLocalService;
	}

	/**
	 * Sets the apply trn quote details local service.
	 *
	 * @param applyTrnQuoteDetailsLocalService the apply trn quote details local service
	 */
	public void setApplyTrnQuoteDetailsLocalService(
		com.ifl.rapid.customer.service.ApplyTrnQuoteDetailsLocalService applyTrnQuoteDetailsLocalService) {
		this.applyTrnQuoteDetailsLocalService = applyTrnQuoteDetailsLocalService;
	}

	/**
	 * Returns the apply trn quote details persistence.
	 *
	 * @return the apply trn quote details persistence
	 */
	public ApplyTrnQuoteDetailsPersistence getApplyTrnQuoteDetailsPersistence() {
		return applyTrnQuoteDetailsPersistence;
	}

	/**
	 * Sets the apply trn quote details persistence.
	 *
	 * @param applyTrnQuoteDetailsPersistence the apply trn quote details persistence
	 */
	public void setApplyTrnQuoteDetailsPersistence(
		ApplyTrnQuoteDetailsPersistence applyTrnQuoteDetailsPersistence) {
		this.applyTrnQuoteDetailsPersistence = applyTrnQuoteDetailsPersistence;
	}

	/**
	 * Returns the city local service.
	 *
	 * @return the city local service
	 */
	public com.ifl.rapid.customer.service.CityLocalService getCityLocalService() {
		return cityLocalService;
	}

	/**
	 * Sets the city local service.
	 *
	 * @param cityLocalService the city local service
	 */
	public void setCityLocalService(
		com.ifl.rapid.customer.service.CityLocalService cityLocalService) {
		this.cityLocalService = cityLocalService;
	}

	/**
	 * Returns the city persistence.
	 *
	 * @return the city persistence
	 */
	public CityPersistence getCityPersistence() {
		return cityPersistence;
	}

	/**
	 * Sets the city persistence.
	 *
	 * @param cityPersistence the city persistence
	 */
	public void setCityPersistence(CityPersistence cityPersistence) {
		this.cityPersistence = cityPersistence;
	}

	/**
	 * Returns the config_ mst_ generic master local service.
	 *
	 * @return the config_ mst_ generic master local service
	 */
	public com.ifl.rapid.customer.service.Config_Mst_GenericMasterLocalService getConfig_Mst_GenericMasterLocalService() {
		return config_Mst_GenericMasterLocalService;
	}

	/**
	 * Sets the config_ mst_ generic master local service.
	 *
	 * @param config_Mst_GenericMasterLocalService the config_ mst_ generic master local service
	 */
	public void setConfig_Mst_GenericMasterLocalService(
		com.ifl.rapid.customer.service.Config_Mst_GenericMasterLocalService config_Mst_GenericMasterLocalService) {
		this.config_Mst_GenericMasterLocalService = config_Mst_GenericMasterLocalService;
	}

	/**
	 * Returns the config_ mst_ generic master persistence.
	 *
	 * @return the config_ mst_ generic master persistence
	 */
	public Config_Mst_GenericMasterPersistence getConfig_Mst_GenericMasterPersistence() {
		return config_Mst_GenericMasterPersistence;
	}

	/**
	 * Sets the config_ mst_ generic master persistence.
	 *
	 * @param config_Mst_GenericMasterPersistence the config_ mst_ generic master persistence
	 */
	public void setConfig_Mst_GenericMasterPersistence(
		Config_Mst_GenericMasterPersistence config_Mst_GenericMasterPersistence) {
		this.config_Mst_GenericMasterPersistence = config_Mst_GenericMasterPersistence;
	}

	/**
	 * Returns the c r m_ trn_ address local service.
	 *
	 * @return the c r m_ trn_ address local service
	 */
	public com.ifl.rapid.customer.service.CRM_Trn_AddressLocalService getCRM_Trn_AddressLocalService() {
		return crm_Trn_AddressLocalService;
	}

	/**
	 * Sets the c r m_ trn_ address local service.
	 *
	 * @param crm_Trn_AddressLocalService the c r m_ trn_ address local service
	 */
	public void setCRM_Trn_AddressLocalService(
		com.ifl.rapid.customer.service.CRM_Trn_AddressLocalService crm_Trn_AddressLocalService) {
		this.crm_Trn_AddressLocalService = crm_Trn_AddressLocalService;
	}

	/**
	 * Returns the c r m_ trn_ address persistence.
	 *
	 * @return the c r m_ trn_ address persistence
	 */
	public CRM_Trn_AddressPersistence getCRM_Trn_AddressPersistence() {
		return crm_Trn_AddressPersistence;
	}

	/**
	 * Sets the c r m_ trn_ address persistence.
	 *
	 * @param crm_Trn_AddressPersistence the c r m_ trn_ address persistence
	 */
	public void setCRM_Trn_AddressPersistence(
		CRM_Trn_AddressPersistence crm_Trn_AddressPersistence) {
		this.crm_Trn_AddressPersistence = crm_Trn_AddressPersistence;
	}

	/**
	 * Returns the c r m_ trn_ contact local service.
	 *
	 * @return the c r m_ trn_ contact local service
	 */
	public com.ifl.rapid.customer.service.CRM_Trn_ContactLocalService getCRM_Trn_ContactLocalService() {
		return crm_Trn_ContactLocalService;
	}

	/**
	 * Sets the c r m_ trn_ contact local service.
	 *
	 * @param crm_Trn_ContactLocalService the c r m_ trn_ contact local service
	 */
	public void setCRM_Trn_ContactLocalService(
		com.ifl.rapid.customer.service.CRM_Trn_ContactLocalService crm_Trn_ContactLocalService) {
		this.crm_Trn_ContactLocalService = crm_Trn_ContactLocalService;
	}

	/**
	 * Returns the c r m_ trn_ contact remote service.
	 *
	 * @return the c r m_ trn_ contact remote service
	 */
	public com.ifl.rapid.customer.service.CRM_Trn_ContactService getCRM_Trn_ContactService() {
		return crm_Trn_ContactService;
	}

	/**
	 * Sets the c r m_ trn_ contact remote service.
	 *
	 * @param crm_Trn_ContactService the c r m_ trn_ contact remote service
	 */
	public void setCRM_Trn_ContactService(
		com.ifl.rapid.customer.service.CRM_Trn_ContactService crm_Trn_ContactService) {
		this.crm_Trn_ContactService = crm_Trn_ContactService;
	}

	/**
	 * Returns the c r m_ trn_ contact persistence.
	 *
	 * @return the c r m_ trn_ contact persistence
	 */
	public CRM_Trn_ContactPersistence getCRM_Trn_ContactPersistence() {
		return crm_Trn_ContactPersistence;
	}

	/**
	 * Sets the c r m_ trn_ contact persistence.
	 *
	 * @param crm_Trn_ContactPersistence the c r m_ trn_ contact persistence
	 */
	public void setCRM_Trn_ContactPersistence(
		CRM_Trn_ContactPersistence crm_Trn_ContactPersistence) {
		this.crm_Trn_ContactPersistence = crm_Trn_ContactPersistence;
	}

	/**
	 * Returns the c r m_ trn_ phone local service.
	 *
	 * @return the c r m_ trn_ phone local service
	 */
	public com.ifl.rapid.customer.service.CRM_Trn_PhoneLocalService getCRM_Trn_PhoneLocalService() {
		return crm_Trn_PhoneLocalService;
	}

	/**
	 * Sets the c r m_ trn_ phone local service.
	 *
	 * @param crm_Trn_PhoneLocalService the c r m_ trn_ phone local service
	 */
	public void setCRM_Trn_PhoneLocalService(
		com.ifl.rapid.customer.service.CRM_Trn_PhoneLocalService crm_Trn_PhoneLocalService) {
		this.crm_Trn_PhoneLocalService = crm_Trn_PhoneLocalService;
	}

	/**
	 * Returns the c r m_ trn_ phone persistence.
	 *
	 * @return the c r m_ trn_ phone persistence
	 */
	public CRM_Trn_PhonePersistence getCRM_Trn_PhonePersistence() {
		return crm_Trn_PhonePersistence;
	}

	/**
	 * Sets the c r m_ trn_ phone persistence.
	 *
	 * @param crm_Trn_PhonePersistence the c r m_ trn_ phone persistence
	 */
	public void setCRM_Trn_PhonePersistence(
		CRM_Trn_PhonePersistence crm_Trn_PhonePersistence) {
		this.crm_Trn_PhonePersistence = crm_Trn_PhonePersistence;
	}

	/**
	 * Returns the c r m_ trn_ policy address local service.
	 *
	 * @return the c r m_ trn_ policy address local service
	 */
	public com.ifl.rapid.customer.service.CRM_Trn_PolicyAddressLocalService getCRM_Trn_PolicyAddressLocalService() {
		return crm_Trn_PolicyAddressLocalService;
	}

	/**
	 * Sets the c r m_ trn_ policy address local service.
	 *
	 * @param crm_Trn_PolicyAddressLocalService the c r m_ trn_ policy address local service
	 */
	public void setCRM_Trn_PolicyAddressLocalService(
		com.ifl.rapid.customer.service.CRM_Trn_PolicyAddressLocalService crm_Trn_PolicyAddressLocalService) {
		this.crm_Trn_PolicyAddressLocalService = crm_Trn_PolicyAddressLocalService;
	}

	/**
	 * Returns the c r m_ trn_ policy address persistence.
	 *
	 * @return the c r m_ trn_ policy address persistence
	 */
	public CRM_Trn_PolicyAddressPersistence getCRM_Trn_PolicyAddressPersistence() {
		return crm_Trn_PolicyAddressPersistence;
	}

	/**
	 * Sets the c r m_ trn_ policy address persistence.
	 *
	 * @param crm_Trn_PolicyAddressPersistence the c r m_ trn_ policy address persistence
	 */
	public void setCRM_Trn_PolicyAddressPersistence(
		CRM_Trn_PolicyAddressPersistence crm_Trn_PolicyAddressPersistence) {
		this.crm_Trn_PolicyAddressPersistence = crm_Trn_PolicyAddressPersistence;
	}

	/**
	 * Returns the c r m trn contact communication local service.
	 *
	 * @return the c r m trn contact communication local service
	 */
	public com.ifl.rapid.customer.service.CRMTrnContactCommunicationLocalService getCRMTrnContactCommunicationLocalService() {
		return crmTrnContactCommunicationLocalService;
	}

	/**
	 * Sets the c r m trn contact communication local service.
	 *
	 * @param crmTrnContactCommunicationLocalService the c r m trn contact communication local service
	 */
	public void setCRMTrnContactCommunicationLocalService(
		com.ifl.rapid.customer.service.CRMTrnContactCommunicationLocalService crmTrnContactCommunicationLocalService) {
		this.crmTrnContactCommunicationLocalService = crmTrnContactCommunicationLocalService;
	}

	/**
	 * Returns the c r m trn contact communication persistence.
	 *
	 * @return the c r m trn contact communication persistence
	 */
	public CRMTrnContactCommunicationPersistence getCRMTrnContactCommunicationPersistence() {
		return crmTrnContactCommunicationPersistence;
	}

	/**
	 * Sets the c r m trn contact communication persistence.
	 *
	 * @param crmTrnContactCommunicationPersistence the c r m trn contact communication persistence
	 */
	public void setCRMTrnContactCommunicationPersistence(
		CRMTrnContactCommunicationPersistence crmTrnContactCommunicationPersistence) {
		this.crmTrnContactCommunicationPersistence = crmTrnContactCommunicationPersistence;
	}

	/**
	 * Returns the c r m trn family member local service.
	 *
	 * @return the c r m trn family member local service
	 */
	public com.ifl.rapid.customer.service.CRMTrnFamilyMemberLocalService getCRMTrnFamilyMemberLocalService() {
		return crmTrnFamilyMemberLocalService;
	}

	/**
	 * Sets the c r m trn family member local service.
	 *
	 * @param crmTrnFamilyMemberLocalService the c r m trn family member local service
	 */
	public void setCRMTrnFamilyMemberLocalService(
		com.ifl.rapid.customer.service.CRMTrnFamilyMemberLocalService crmTrnFamilyMemberLocalService) {
		this.crmTrnFamilyMemberLocalService = crmTrnFamilyMemberLocalService;
	}

	/**
	 * Returns the c r m trn family member persistence.
	 *
	 * @return the c r m trn family member persistence
	 */
	public CRMTrnFamilyMemberPersistence getCRMTrnFamilyMemberPersistence() {
		return crmTrnFamilyMemberPersistence;
	}

	/**
	 * Sets the c r m trn family member persistence.
	 *
	 * @param crmTrnFamilyMemberPersistence the c r m trn family member persistence
	 */
	public void setCRMTrnFamilyMemberPersistence(
		CRMTrnFamilyMemberPersistence crmTrnFamilyMemberPersistence) {
		this.crmTrnFamilyMemberPersistence = crmTrnFamilyMemberPersistence;
	}

	/**
	 * Returns the loc mst branch location local service.
	 *
	 * @return the loc mst branch location local service
	 */
	public com.ifl.rapid.customer.service.LocMstBranchLocationLocalService getLocMstBranchLocationLocalService() {
		return locMstBranchLocationLocalService;
	}

	/**
	 * Sets the loc mst branch location local service.
	 *
	 * @param locMstBranchLocationLocalService the loc mst branch location local service
	 */
	public void setLocMstBranchLocationLocalService(
		com.ifl.rapid.customer.service.LocMstBranchLocationLocalService locMstBranchLocationLocalService) {
		this.locMstBranchLocationLocalService = locMstBranchLocationLocalService;
	}

	/**
	 * Returns the loc mst branch location persistence.
	 *
	 * @return the loc mst branch location persistence
	 */
	public LocMstBranchLocationPersistence getLocMstBranchLocationPersistence() {
		return locMstBranchLocationPersistence;
	}

	/**
	 * Sets the loc mst branch location persistence.
	 *
	 * @param locMstBranchLocationPersistence the loc mst branch location persistence
	 */
	public void setLocMstBranchLocationPersistence(
		LocMstBranchLocationPersistence locMstBranchLocationPersistence) {
		this.locMstBranchLocationPersistence = locMstBranchLocationPersistence;
	}

	/**
	 * Returns the loc mst location local service.
	 *
	 * @return the loc mst location local service
	 */
	public com.ifl.rapid.customer.service.LocMstLocationLocalService getLocMstLocationLocalService() {
		return locMstLocationLocalService;
	}

	/**
	 * Sets the loc mst location local service.
	 *
	 * @param locMstLocationLocalService the loc mst location local service
	 */
	public void setLocMstLocationLocalService(
		com.ifl.rapid.customer.service.LocMstLocationLocalService locMstLocationLocalService) {
		this.locMstLocationLocalService = locMstLocationLocalService;
	}

	/**
	 * Returns the loc mst location persistence.
	 *
	 * @return the loc mst location persistence
	 */
	public LocMstLocationPersistence getLocMstLocationPersistence() {
		return locMstLocationPersistence;
	}

	/**
	 * Sets the loc mst location persistence.
	 *
	 * @param locMstLocationPersistence the loc mst location persistence
	 */
	public void setLocMstLocationPersistence(
		LocMstLocationPersistence locMstLocationPersistence) {
		this.locMstLocationPersistence = locMstLocationPersistence;
	}

	/**
	 * Returns the prd mst product local service.
	 *
	 * @return the prd mst product local service
	 */
	public com.ifl.rapid.customer.service.PrdMstProductLocalService getPrdMstProductLocalService() {
		return prdMstProductLocalService;
	}

	/**
	 * Sets the prd mst product local service.
	 *
	 * @param prdMstProductLocalService the prd mst product local service
	 */
	public void setPrdMstProductLocalService(
		com.ifl.rapid.customer.service.PrdMstProductLocalService prdMstProductLocalService) {
		this.prdMstProductLocalService = prdMstProductLocalService;
	}

	/**
	 * Returns the prd mst product persistence.
	 *
	 * @return the prd mst product persistence
	 */
	public PrdMstProductPersistence getPrdMstProductPersistence() {
		return prdMstProductPersistence;
	}

	/**
	 * Sets the prd mst product persistence.
	 *
	 * @param prdMstProductPersistence the prd mst product persistence
	 */
	public void setPrdMstProductPersistence(
		PrdMstProductPersistence prdMstProductPersistence) {
		this.prdMstProductPersistence = prdMstProductPersistence;
	}

	/**
	 * Returns the qrc mst requests local service.
	 *
	 * @return the qrc mst requests local service
	 */
	public com.ifl.rapid.customer.service.QrcMstRequestsLocalService getQrcMstRequestsLocalService() {
		return qrcMstRequestsLocalService;
	}

	/**
	 * Sets the qrc mst requests local service.
	 *
	 * @param qrcMstRequestsLocalService the qrc mst requests local service
	 */
	public void setQrcMstRequestsLocalService(
		com.ifl.rapid.customer.service.QrcMstRequestsLocalService qrcMstRequestsLocalService) {
		this.qrcMstRequestsLocalService = qrcMstRequestsLocalService;
	}

	/**
	 * Returns the qrc mst requests persistence.
	 *
	 * @return the qrc mst requests persistence
	 */
	public QrcMstRequestsPersistence getQrcMstRequestsPersistence() {
		return qrcMstRequestsPersistence;
	}

	/**
	 * Sets the qrc mst requests persistence.
	 *
	 * @param qrcMstRequestsPersistence the qrc mst requests persistence
	 */
	public void setQrcMstRequestsPersistence(
		QrcMstRequestsPersistence qrcMstRequestsPersistence) {
		this.qrcMstRequestsPersistence = qrcMstRequestsPersistence;
	}

	/**
	 * Returns the qrc mst services local service.
	 *
	 * @return the qrc mst services local service
	 */
	public com.ifl.rapid.customer.service.QrcMstServicesLocalService getQrcMstServicesLocalService() {
		return qrcMstServicesLocalService;
	}

	/**
	 * Sets the qrc mst services local service.
	 *
	 * @param qrcMstServicesLocalService the qrc mst services local service
	 */
	public void setQrcMstServicesLocalService(
		com.ifl.rapid.customer.service.QrcMstServicesLocalService qrcMstServicesLocalService) {
		this.qrcMstServicesLocalService = qrcMstServicesLocalService;
	}

	/**
	 * Returns the qrc mst services persistence.
	 *
	 * @return the qrc mst services persistence
	 */
	public QrcMstServicesPersistence getQrcMstServicesPersistence() {
		return qrcMstServicesPersistence;
	}

	/**
	 * Sets the qrc mst services persistence.
	 *
	 * @param qrcMstServicesPersistence the qrc mst services persistence
	 */
	public void setQrcMstServicesPersistence(
		QrcMstServicesPersistence qrcMstServicesPersistence) {
		this.qrcMstServicesPersistence = qrcMstServicesPersistence;
	}

	/**
	 * Returns the qrc mst sub services local service.
	 *
	 * @return the qrc mst sub services local service
	 */
	public com.ifl.rapid.customer.service.QrcMstSubServicesLocalService getQrcMstSubServicesLocalService() {
		return qrcMstSubServicesLocalService;
	}

	/**
	 * Sets the qrc mst sub services local service.
	 *
	 * @param qrcMstSubServicesLocalService the qrc mst sub services local service
	 */
	public void setQrcMstSubServicesLocalService(
		com.ifl.rapid.customer.service.QrcMstSubServicesLocalService qrcMstSubServicesLocalService) {
		this.qrcMstSubServicesLocalService = qrcMstSubServicesLocalService;
	}

	/**
	 * Returns the qrc mst sub services persistence.
	 *
	 * @return the qrc mst sub services persistence
	 */
	public QrcMstSubServicesPersistence getQrcMstSubServicesPersistence() {
		return qrcMstSubServicesPersistence;
	}

	/**
	 * Sets the qrc mst sub services persistence.
	 *
	 * @param qrcMstSubServicesPersistence the qrc mst sub services persistence
	 */
	public void setQrcMstSubServicesPersistence(
		QrcMstSubServicesPersistence qrcMstSubServicesPersistence) {
		this.qrcMstSubServicesPersistence = qrcMstSubServicesPersistence;
	}

	/**
	 * Returns the qrc trn history local service.
	 *
	 * @return the qrc trn history local service
	 */
	public com.ifl.rapid.customer.service.QrcTrnHistoryLocalService getQrcTrnHistoryLocalService() {
		return qrcTrnHistoryLocalService;
	}

	/**
	 * Sets the qrc trn history local service.
	 *
	 * @param qrcTrnHistoryLocalService the qrc trn history local service
	 */
	public void setQrcTrnHistoryLocalService(
		com.ifl.rapid.customer.service.QrcTrnHistoryLocalService qrcTrnHistoryLocalService) {
		this.qrcTrnHistoryLocalService = qrcTrnHistoryLocalService;
	}

	/**
	 * Returns the qrc trn history persistence.
	 *
	 * @return the qrc trn history persistence
	 */
	public QrcTrnHistoryPersistence getQrcTrnHistoryPersistence() {
		return qrcTrnHistoryPersistence;
	}

	/**
	 * Sets the qrc trn history persistence.
	 *
	 * @param qrcTrnHistoryPersistence the qrc trn history persistence
	 */
	public void setQrcTrnHistoryPersistence(
		QrcTrnHistoryPersistence qrcTrnHistoryPersistence) {
		this.qrcTrnHistoryPersistence = qrcTrnHistoryPersistence;
	}

	/**
	 * Returns the qrc trn otp local service.
	 *
	 * @return the qrc trn otp local service
	 */
	public com.ifl.rapid.customer.service.QrcTrnOtpLocalService getQrcTrnOtpLocalService() {
		return qrcTrnOtpLocalService;
	}

	/**
	 * Sets the qrc trn otp local service.
	 *
	 * @param qrcTrnOtpLocalService the qrc trn otp local service
	 */
	public void setQrcTrnOtpLocalService(
		com.ifl.rapid.customer.service.QrcTrnOtpLocalService qrcTrnOtpLocalService) {
		this.qrcTrnOtpLocalService = qrcTrnOtpLocalService;
	}

	/**
	 * Returns the qrc trn otp persistence.
	 *
	 * @return the qrc trn otp persistence
	 */
	public QrcTrnOtpPersistence getQrcTrnOtpPersistence() {
		return qrcTrnOtpPersistence;
	}

	/**
	 * Sets the qrc trn otp persistence.
	 *
	 * @param qrcTrnOtpPersistence the qrc trn otp persistence
	 */
	public void setQrcTrnOtpPersistence(
		QrcTrnOtpPersistence qrcTrnOtpPersistence) {
		this.qrcTrnOtpPersistence = qrcTrnOtpPersistence;
	}

	/**
	 * Returns the qrc trn service requests local service.
	 *
	 * @return the qrc trn service requests local service
	 */
	public com.ifl.rapid.customer.service.QrcTrnServiceRequestsLocalService getQrcTrnServiceRequestsLocalService() {
		return qrcTrnServiceRequestsLocalService;
	}

	/**
	 * Sets the qrc trn service requests local service.
	 *
	 * @param qrcTrnServiceRequestsLocalService the qrc trn service requests local service
	 */
	public void setQrcTrnServiceRequestsLocalService(
		com.ifl.rapid.customer.service.QrcTrnServiceRequestsLocalService qrcTrnServiceRequestsLocalService) {
		this.qrcTrnServiceRequestsLocalService = qrcTrnServiceRequestsLocalService;
	}

	/**
	 * Returns the qrc trn service requests persistence.
	 *
	 * @return the qrc trn service requests persistence
	 */
	public QrcTrnServiceRequestsPersistence getQrcTrnServiceRequestsPersistence() {
		return qrcTrnServiceRequestsPersistence;
	}

	/**
	 * Sets the qrc trn service requests persistence.
	 *
	 * @param qrcTrnServiceRequestsPersistence the qrc trn service requests persistence
	 */
	public void setQrcTrnServiceRequestsPersistence(
		QrcTrnServiceRequestsPersistence qrcTrnServiceRequestsPersistence) {
		this.qrcTrnServiceRequestsPersistence = qrcTrnServiceRequestsPersistence;
	}

	/**
	 * Returns the state local service.
	 *
	 * @return the state local service
	 */
	public com.ifl.rapid.customer.service.StateLocalService getStateLocalService() {
		return stateLocalService;
	}

	/**
	 * Sets the state local service.
	 *
	 * @param stateLocalService the state local service
	 */
	public void setStateLocalService(
		com.ifl.rapid.customer.service.StateLocalService stateLocalService) {
		this.stateLocalService = stateLocalService;
	}

	/**
	 * Returns the state persistence.
	 *
	 * @return the state persistence
	 */
	public StatePersistence getStatePersistence() {
		return statePersistence;
	}

	/**
	 * Sets the state persistence.
	 *
	 * @param statePersistence the state persistence
	 */
	public void setStatePersistence(StatePersistence statePersistence) {
		this.statePersistence = statePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.ifl.rapid.customer.model.CRM_Trn_PolicyAddress",
			crm_Trn_PolicyAddressLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.ifl.rapid.customer.model.CRM_Trn_PolicyAddress");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return CRM_Trn_PolicyAddress.class;
	}

	protected String getModelClassName() {
		return CRM_Trn_PolicyAddress.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = crm_Trn_PolicyAddressPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.ifl.rapid.customer.service.ApplyTrnApplicationFormLocalService.class)
	protected com.ifl.rapid.customer.service.ApplyTrnApplicationFormLocalService applyTrnApplicationFormLocalService;
	@BeanReference(type = ApplyTrnApplicationFormPersistence.class)
	protected ApplyTrnApplicationFormPersistence applyTrnApplicationFormPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.ApplyTrnQuoteDetailsLocalService.class)
	protected com.ifl.rapid.customer.service.ApplyTrnQuoteDetailsLocalService applyTrnQuoteDetailsLocalService;
	@BeanReference(type = ApplyTrnQuoteDetailsPersistence.class)
	protected ApplyTrnQuoteDetailsPersistence applyTrnQuoteDetailsPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.CityLocalService.class)
	protected com.ifl.rapid.customer.service.CityLocalService cityLocalService;
	@BeanReference(type = CityPersistence.class)
	protected CityPersistence cityPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.Config_Mst_GenericMasterLocalService.class)
	protected com.ifl.rapid.customer.service.Config_Mst_GenericMasterLocalService config_Mst_GenericMasterLocalService;
	@BeanReference(type = Config_Mst_GenericMasterPersistence.class)
	protected Config_Mst_GenericMasterPersistence config_Mst_GenericMasterPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.CRM_Trn_AddressLocalService.class)
	protected com.ifl.rapid.customer.service.CRM_Trn_AddressLocalService crm_Trn_AddressLocalService;
	@BeanReference(type = CRM_Trn_AddressPersistence.class)
	protected CRM_Trn_AddressPersistence crm_Trn_AddressPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.CRM_Trn_ContactLocalService.class)
	protected com.ifl.rapid.customer.service.CRM_Trn_ContactLocalService crm_Trn_ContactLocalService;
	@BeanReference(type = com.ifl.rapid.customer.service.CRM_Trn_ContactService.class)
	protected com.ifl.rapid.customer.service.CRM_Trn_ContactService crm_Trn_ContactService;
	@BeanReference(type = CRM_Trn_ContactPersistence.class)
	protected CRM_Trn_ContactPersistence crm_Trn_ContactPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.CRM_Trn_PhoneLocalService.class)
	protected com.ifl.rapid.customer.service.CRM_Trn_PhoneLocalService crm_Trn_PhoneLocalService;
	@BeanReference(type = CRM_Trn_PhonePersistence.class)
	protected CRM_Trn_PhonePersistence crm_Trn_PhonePersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.CRM_Trn_PolicyAddressLocalService.class)
	protected com.ifl.rapid.customer.service.CRM_Trn_PolicyAddressLocalService crm_Trn_PolicyAddressLocalService;
	@BeanReference(type = CRM_Trn_PolicyAddressPersistence.class)
	protected CRM_Trn_PolicyAddressPersistence crm_Trn_PolicyAddressPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.CRMTrnContactCommunicationLocalService.class)
	protected com.ifl.rapid.customer.service.CRMTrnContactCommunicationLocalService crmTrnContactCommunicationLocalService;
	@BeanReference(type = CRMTrnContactCommunicationPersistence.class)
	protected CRMTrnContactCommunicationPersistence crmTrnContactCommunicationPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.CRMTrnFamilyMemberLocalService.class)
	protected com.ifl.rapid.customer.service.CRMTrnFamilyMemberLocalService crmTrnFamilyMemberLocalService;
	@BeanReference(type = CRMTrnFamilyMemberPersistence.class)
	protected CRMTrnFamilyMemberPersistence crmTrnFamilyMemberPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.LocMstBranchLocationLocalService.class)
	protected com.ifl.rapid.customer.service.LocMstBranchLocationLocalService locMstBranchLocationLocalService;
	@BeanReference(type = LocMstBranchLocationPersistence.class)
	protected LocMstBranchLocationPersistence locMstBranchLocationPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.LocMstLocationLocalService.class)
	protected com.ifl.rapid.customer.service.LocMstLocationLocalService locMstLocationLocalService;
	@BeanReference(type = LocMstLocationPersistence.class)
	protected LocMstLocationPersistence locMstLocationPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.PrdMstProductLocalService.class)
	protected com.ifl.rapid.customer.service.PrdMstProductLocalService prdMstProductLocalService;
	@BeanReference(type = PrdMstProductPersistence.class)
	protected PrdMstProductPersistence prdMstProductPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.QrcMstRequestsLocalService.class)
	protected com.ifl.rapid.customer.service.QrcMstRequestsLocalService qrcMstRequestsLocalService;
	@BeanReference(type = QrcMstRequestsPersistence.class)
	protected QrcMstRequestsPersistence qrcMstRequestsPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.QrcMstServicesLocalService.class)
	protected com.ifl.rapid.customer.service.QrcMstServicesLocalService qrcMstServicesLocalService;
	@BeanReference(type = QrcMstServicesPersistence.class)
	protected QrcMstServicesPersistence qrcMstServicesPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.QrcMstSubServicesLocalService.class)
	protected com.ifl.rapid.customer.service.QrcMstSubServicesLocalService qrcMstSubServicesLocalService;
	@BeanReference(type = QrcMstSubServicesPersistence.class)
	protected QrcMstSubServicesPersistence qrcMstSubServicesPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.QrcTrnHistoryLocalService.class)
	protected com.ifl.rapid.customer.service.QrcTrnHistoryLocalService qrcTrnHistoryLocalService;
	@BeanReference(type = QrcTrnHistoryPersistence.class)
	protected QrcTrnHistoryPersistence qrcTrnHistoryPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.QrcTrnOtpLocalService.class)
	protected com.ifl.rapid.customer.service.QrcTrnOtpLocalService qrcTrnOtpLocalService;
	@BeanReference(type = QrcTrnOtpPersistence.class)
	protected QrcTrnOtpPersistence qrcTrnOtpPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.QrcTrnServiceRequestsLocalService.class)
	protected com.ifl.rapid.customer.service.QrcTrnServiceRequestsLocalService qrcTrnServiceRequestsLocalService;
	@BeanReference(type = QrcTrnServiceRequestsPersistence.class)
	protected QrcTrnServiceRequestsPersistence qrcTrnServiceRequestsPersistence;
	@BeanReference(type = com.ifl.rapid.customer.service.StateLocalService.class)
	protected com.ifl.rapid.customer.service.StateLocalService stateLocalService;
	@BeanReference(type = StatePersistence.class)
	protected StatePersistence statePersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private CRM_Trn_PolicyAddressLocalServiceClpInvoker _clpInvoker = new CRM_Trn_PolicyAddressLocalServiceClpInvoker();
}