/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AddressType service. Represents a row in the &quot;address_type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.AddressTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.AddressTypeImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see AddressType
 * @see com.ifli.rapid.model.impl.AddressTypeImpl
 * @see com.ifli.rapid.model.impl.AddressTypeModelImpl
 * @generated
 */
public interface AddressTypeModel extends BaseModel<AddressType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a address type model instance should use the {@link AddressType} interface instead.
	 */

	/**
	 * Returns the primary key of this address type.
	 *
	 * @return the primary key of this address type
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this address type.
	 *
	 * @param primaryKey the primary key of this address type
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the a d d r e s s_ t y p e_ i d of this address type.
	 *
	 * @return the a d d r e s s_ t y p e_ i d of this address type
	 */
	public int getADDRESS_TYPE_ID();

	/**
	 * Sets the a d d r e s s_ t y p e_ i d of this address type.
	 *
	 * @param ADDRESS_TYPE_ID the a d d r e s s_ t y p e_ i d of this address type
	 */
	public void setADDRESS_TYPE_ID(int ADDRESS_TYPE_ID);

	/**
	 * Returns the i n s e r t e d_ b y of this address type.
	 *
	 * @return the i n s e r t e d_ b y of this address type
	 */
	@AutoEscape
	public String getINSERTED_BY();

	/**
	 * Sets the i n s e r t e d_ b y of this address type.
	 *
	 * @param INSERTED_BY the i n s e r t e d_ b y of this address type
	 */
	public void setINSERTED_BY(String INSERTED_BY);

	/**
	 * Returns the i n s e r t e d_ d a t e of this address type.
	 *
	 * @return the i n s e r t e d_ d a t e of this address type
	 */
	public Date getINSERTED_DATE();

	/**
	 * Sets the i n s e r t e d_ d a t e of this address type.
	 *
	 * @param INSERTED_DATE the i n s e r t e d_ d a t e of this address type
	 */
	public void setINSERTED_DATE(Date INSERTED_DATE);

	/**
	 * Returns the u p d a t e d_ b y of this address type.
	 *
	 * @return the u p d a t e d_ b y of this address type
	 */
	@AutoEscape
	public String getUPDATED_BY();

	/**
	 * Sets the u p d a t e d_ b y of this address type.
	 *
	 * @param UPDATED_BY the u p d a t e d_ b y of this address type
	 */
	public void setUPDATED_BY(String UPDATED_BY);

	/**
	 * Returns the u p d a t e d_ d a t e of this address type.
	 *
	 * @return the u p d a t e d_ d a t e of this address type
	 */
	public Date getUPDATED_DATE();

	/**
	 * Sets the u p d a t e d_ d a t e of this address type.
	 *
	 * @param UPDATED_DATE the u p d a t e d_ d a t e of this address type
	 */
	public void setUPDATED_DATE(Date UPDATED_DATE);

	/**
	 * Returns the a c t i v e_ f l a g of this address type.
	 *
	 * @return the a c t i v e_ f l a g of this address type
	 */
	@AutoEscape
	public String getACTIVE_FLAG();

	/**
	 * Sets the a c t i v e_ f l a g of this address type.
	 *
	 * @param ACTIVE_FLAG the a c t i v e_ f l a g of this address type
	 */
	public void setACTIVE_FLAG(String ACTIVE_FLAG);

	/**
	 * Returns the a d d r e s s_ t y p e_ d e s c of this address type.
	 *
	 * @return the a d d r e s s_ t y p e_ d e s c of this address type
	 */
	@AutoEscape
	public String getADDRESS_TYPE_DESC();

	/**
	 * Sets the a d d r e s s_ t y p e_ d e s c of this address type.
	 *
	 * @param ADDRESS_TYPE_DESC the a d d r e s s_ t y p e_ d e s c of this address type
	 */
	public void setADDRESS_TYPE_DESC(String ADDRESS_TYPE_DESC);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AddressType addressType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AddressType> toCacheModel();

	@Override
	public AddressType toEscapedModel();

	@Override
	public AddressType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}