/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ConfirmDetails service. Represents a row in the &quot;confirm_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.ConfirmDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.ConfirmDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see ConfirmDetails
 * @see com.ifli.rapid.model.impl.ConfirmDetailsImpl
 * @see com.ifli.rapid.model.impl.ConfirmDetailsModelImpl
 * @generated
 */
public interface ConfirmDetailsModel extends BaseModel<ConfirmDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a confirm details model instance should use the {@link ConfirmDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this confirm details.
	 *
	 * @return the primary key of this confirm details
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this confirm details.
	 *
	 * @param primaryKey the primary key of this confirm details
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this confirm details.
	 *
	 * @return the i d of this confirm details
	 */
	public int getID();

	/**
	 * Sets the i d of this confirm details.
	 *
	 * @param ID the i d of this confirm details
	 */
	public void setID(int ID);

	/**
	 * Returns the q r c_ a s r_ i d of this confirm details.
	 *
	 * @return the q r c_ a s r_ i d of this confirm details
	 */
	public int getQRC_ASR_ID();

	/**
	 * Sets the q r c_ a s r_ i d of this confirm details.
	 *
	 * @param QRC_ASR_ID the q r c_ a s r_ i d of this confirm details
	 */
	public void setQRC_ASR_ID(int QRC_ASR_ID);

	/**
	 * Returns the approval_ status of this confirm details.
	 *
	 * @return the approval_ status of this confirm details
	 */
	@AutoEscape
	public String getApproval_Status();

	/**
	 * Sets the approval_ status of this confirm details.
	 *
	 * @param Approval_Status the approval_ status of this confirm details
	 */
	public void setApproval_Status(String Approval_Status);

	/**
	 * Returns the comments of this confirm details.
	 *
	 * @return the comments of this confirm details
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this confirm details.
	 *
	 * @param Comments the comments of this confirm details
	 */
	public void setComments(String Comments);

	/**
	 * Returns the sign_ flag of this confirm details.
	 *
	 * @return the sign_ flag of this confirm details
	 */
	@AutoEscape
	public String getSign_Flag();

	/**
	 * Sets the sign_ flag of this confirm details.
	 *
	 * @param Sign_Flag the sign_ flag of this confirm details
	 */
	public void setSign_Flag(String Sign_Flag);

	/**
	 * Returns the created by of this confirm details.
	 *
	 * @return the created by of this confirm details
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this confirm details.
	 *
	 * @param CreatedBy the created by of this confirm details
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this confirm details.
	 *
	 * @return the created date of this confirm details
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this confirm details.
	 *
	 * @param CreatedDate the created date of this confirm details
	 */
	public void setCreatedDate(Date CreatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ConfirmDetails confirmDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ConfirmDetails> toCacheModel();

	@Override
	public ConfirmDetails toEscapedModel();

	@Override
	public ConfirmDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}