/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CustomerOtp service. Represents a row in the &quot;customer_otp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.CustomerOtpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.CustomerOtpImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CustomerOtp
 * @see com.ifli.rapid.model.impl.CustomerOtpImpl
 * @see com.ifli.rapid.model.impl.CustomerOtpModelImpl
 * @generated
 */
public interface CustomerOtpModel extends BaseModel<CustomerOtp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer otp model instance should use the {@link CustomerOtp} interface instead.
	 */

	/**
	 * Returns the primary key of this customer otp.
	 *
	 * @return the primary key of this customer otp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this customer otp.
	 *
	 * @param primaryKey the primary key of this customer otp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the c u s t o m e r_ i d of this customer otp.
	 *
	 * @return the c u s t o m e r_ i d of this customer otp
	 */
	public int getCUSTOMER_ID();

	/**
	 * Sets the c u s t o m e r_ i d of this customer otp.
	 *
	 * @param CUSTOMER_ID the c u s t o m e r_ i d of this customer otp
	 */
	public void setCUSTOMER_ID(int CUSTOMER_ID);

	/**
	 * Returns the e m a i l_ o t p of this customer otp.
	 *
	 * @return the e m a i l_ o t p of this customer otp
	 */
	@AutoEscape
	public String getEMAIL_OTP();

	/**
	 * Sets the e m a i l_ o t p of this customer otp.
	 *
	 * @param EMAIL_OTP the e m a i l_ o t p of this customer otp
	 */
	public void setEMAIL_OTP(String EMAIL_OTP);

	/**
	 * Returns the p h o n e_ o t p of this customer otp.
	 *
	 * @return the p h o n e_ o t p of this customer otp
	 */
	@AutoEscape
	public String getPHONE_OTP();

	/**
	 * Sets the p h o n e_ o t p of this customer otp.
	 *
	 * @param PHONE_OTP the p h o n e_ o t p of this customer otp
	 */
	public void setPHONE_OTP(String PHONE_OTP);

	/**
	 * Returns the s t a t u s of this customer otp.
	 *
	 * @return the s t a t u s of this customer otp
	 */
	@AutoEscape
	public String getSTATUS();

	/**
	 * Sets the s t a t u s of this customer otp.
	 *
	 * @param STATUS the s t a t u s of this customer otp
	 */
	public void setSTATUS(String STATUS);

	/**
	 * Returns the a d d e d_ d a t e of this customer otp.
	 *
	 * @return the a d d e d_ d a t e of this customer otp
	 */
	public Date getADDED_DATE();

	/**
	 * Sets the a d d e d_ d a t e of this customer otp.
	 *
	 * @param ADDED_DATE the a d d e d_ d a t e of this customer otp
	 */
	public void setADDED_DATE(Date ADDED_DATE);

	/**
	 * Returns the u p d a t e d_ d a t e of this customer otp.
	 *
	 * @return the u p d a t e d_ d a t e of this customer otp
	 */
	public Date getUPDATED_DATE();

	/**
	 * Sets the u p d a t e d_ d a t e of this customer otp.
	 *
	 * @param UPDATED_DATE the u p d a t e d_ d a t e of this customer otp
	 */
	public void setUPDATED_DATE(Date UPDATED_DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CustomerOtp customerOtp);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CustomerOtp> toCacheModel();

	@Override
	public CustomerOtp toEscapedModel();

	@Override
	public CustomerOtp toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}