/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CustomerFamilyDetails service. Represents a row in the &quot;customer_family&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.CustomerFamilyDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.CustomerFamilyDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CustomerFamilyDetails
 * @see com.ifli.rapid.model.impl.CustomerFamilyDetailsImpl
 * @see com.ifli.rapid.model.impl.CustomerFamilyDetailsModelImpl
 * @generated
 */
public interface CustomerFamilyDetailsModel extends BaseModel<CustomerFamilyDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer family details model instance should use the {@link CustomerFamilyDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this customer family details.
	 *
	 * @return the primary key of this customer family details
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this customer family details.
	 *
	 * @param primaryKey the primary key of this customer family details
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the c u s t o m e r_ f a m i l y_ i d of this customer family details.
	 *
	 * @return the c u s t o m e r_ f a m i l y_ i d of this customer family details
	 */
	public int getCUSTOMER_FAMILY_ID();

	/**
	 * Sets the c u s t o m e r_ f a m i l y_ i d of this customer family details.
	 *
	 * @param CUSTOMER_FAMILY_ID the c u s t o m e r_ f a m i l y_ i d of this customer family details
	 */
	public void setCUSTOMER_FAMILY_ID(int CUSTOMER_FAMILY_ID);

	/**
	 * Returns the p e r s o n_ n a m e of this customer family details.
	 *
	 * @return the p e r s o n_ n a m e of this customer family details
	 */
	@AutoEscape
	public String getPERSON_NAME();

	/**
	 * Sets the p e r s o n_ n a m e of this customer family details.
	 *
	 * @param PERSON_NAME the p e r s o n_ n a m e of this customer family details
	 */
	public void setPERSON_NAME(String PERSON_NAME);

	/**
	 * Returns the r e l a t i o n of this customer family details.
	 *
	 * @return the r e l a t i o n of this customer family details
	 */
	@AutoEscape
	public String getRELATION();

	/**
	 * Sets the r e l a t i o n of this customer family details.
	 *
	 * @param RELATION the r e l a t i o n of this customer family details
	 */
	public void setRELATION(String RELATION);

	/**
	 * Returns the d e p e n d e n t of this customer family details.
	 *
	 * @return the d e p e n d e n t of this customer family details
	 */
	@AutoEscape
	public String getDEPENDENT();

	/**
	 * Sets the d e p e n d e n t of this customer family details.
	 *
	 * @param DEPENDENT the d e p e n d e n t of this customer family details
	 */
	public void setDEPENDENT(String DEPENDENT);

	/**
	 * Returns the a g e of this customer family details.
	 *
	 * @return the a g e of this customer family details
	 */
	public int getAGE();

	/**
	 * Sets the a g e of this customer family details.
	 *
	 * @param AGE the a g e of this customer family details
	 */
	public void setAGE(int AGE);

	/**
	 * Returns the c u s t o m e r_ i d of this customer family details.
	 *
	 * @return the c u s t o m e r_ i d of this customer family details
	 */
	public int getCUSTOMER_ID();

	/**
	 * Sets the c u s t o m e r_ i d of this customer family details.
	 *
	 * @param CUSTOMER_ID the c u s t o m e r_ i d of this customer family details
	 */
	public void setCUSTOMER_ID(int CUSTOMER_ID);

	/**
	 * Returns the a d d e d_ b y of this customer family details.
	 *
	 * @return the a d d e d_ b y of this customer family details
	 */
	@AutoEscape
	public String getADDED_BY();

	/**
	 * Sets the a d d e d_ b y of this customer family details.
	 *
	 * @param ADDED_BY the a d d e d_ b y of this customer family details
	 */
	public void setADDED_BY(String ADDED_BY);

	/**
	 * Returns the a d d e d_ d a t e of this customer family details.
	 *
	 * @return the a d d e d_ d a t e of this customer family details
	 */
	public Date getADDED_DATE();

	/**
	 * Sets the a d d e d_ d a t e of this customer family details.
	 *
	 * @param ADDED_DATE the a d d e d_ d a t e of this customer family details
	 */
	public void setADDED_DATE(Date ADDED_DATE);

	/**
	 * Returns the u p d a t e d_ b y of this customer family details.
	 *
	 * @return the u p d a t e d_ b y of this customer family details
	 */
	@AutoEscape
	public String getUPDATED_BY();

	/**
	 * Sets the u p d a t e d_ b y of this customer family details.
	 *
	 * @param UPDATED_BY the u p d a t e d_ b y of this customer family details
	 */
	public void setUPDATED_BY(String UPDATED_BY);

	/**
	 * Returns the u p d a t e d_ d a t e of this customer family details.
	 *
	 * @return the u p d a t e d_ d a t e of this customer family details
	 */
	public Date getUPDATED_DATE();

	/**
	 * Sets the u p d a t e d_ d a t e of this customer family details.
	 *
	 * @param UPDATED_DATE the u p d a t e d_ d a t e of this customer family details
	 */
	public void setUPDATED_DATE(Date UPDATED_DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CustomerFamilyDetails customerFamilyDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CustomerFamilyDetails> toCacheModel();

	@Override
	public CustomerFamilyDetails toEscapedModel();

	@Override
	public CustomerFamilyDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}