/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FamilyRelations service. Represents a row in the &quot;family_relations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.FamilyRelationsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.FamilyRelationsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see FamilyRelations
 * @see com.ifli.rapid.model.impl.FamilyRelationsImpl
 * @see com.ifli.rapid.model.impl.FamilyRelationsModelImpl
 * @generated
 */
public interface FamilyRelationsModel extends BaseModel<FamilyRelations> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a family relations model instance should use the {@link FamilyRelations} interface instead.
	 */

	/**
	 * Returns the primary key of this family relations.
	 *
	 * @return the primary key of this family relations
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this family relations.
	 *
	 * @param primaryKey the primary key of this family relations
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the r e l a t i o n_ i d of this family relations.
	 *
	 * @return the r e l a t i o n_ i d of this family relations
	 */
	public int getRELATION_ID();

	/**
	 * Sets the r e l a t i o n_ i d of this family relations.
	 *
	 * @param RELATION_ID the r e l a t i o n_ i d of this family relations
	 */
	public void setRELATION_ID(int RELATION_ID);

	/**
	 * Returns the r e l a t i o n_ n a m e of this family relations.
	 *
	 * @return the r e l a t i o n_ n a m e of this family relations
	 */
	@AutoEscape
	public String getRELATION_NAME();

	/**
	 * Sets the r e l a t i o n_ n a m e of this family relations.
	 *
	 * @param RELATION_NAME the r e l a t i o n_ n a m e of this family relations
	 */
	public void setRELATION_NAME(String RELATION_NAME);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FamilyRelations familyRelations);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FamilyRelations> toCacheModel();

	@Override
	public FamilyRelations toEscapedModel();

	@Override
	public FamilyRelations toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}