/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LocationDetails service. Represents a row in the &quot;location_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.LocationDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.LocationDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see LocationDetails
 * @see com.ifli.rapid.model.impl.LocationDetailsImpl
 * @see com.ifli.rapid.model.impl.LocationDetailsModelImpl
 * @generated
 */
public interface LocationDetailsModel extends BaseModel<LocationDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a location details model instance should use the {@link LocationDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this location details.
	 *
	 * @return the primary key of this location details
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this location details.
	 *
	 * @param primaryKey the primary key of this location details
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the l o c a t i o n_ i d of this location details.
	 *
	 * @return the l o c a t i o n_ i d of this location details
	 */
	public int getLOCATION_ID();

	/**
	 * Sets the l o c a t i o n_ i d of this location details.
	 *
	 * @param LOCATION_ID the l o c a t i o n_ i d of this location details
	 */
	public void setLOCATION_ID(int LOCATION_ID);

	/**
	 * Returns the l o c a t i o n_ n a m e of this location details.
	 *
	 * @return the l o c a t i o n_ n a m e of this location details
	 */
	@AutoEscape
	public String getLOCATION_NAME();

	/**
	 * Sets the l o c a t i o n_ n a m e of this location details.
	 *
	 * @param LOCATION_NAME the l o c a t i o n_ n a m e of this location details
	 */
	public void setLOCATION_NAME(String LOCATION_NAME);

	/**
	 * Returns the c i t y_ i d of this location details.
	 *
	 * @return the c i t y_ i d of this location details
	 */
	public int getCITY_ID();

	/**
	 * Sets the c i t y_ i d of this location details.
	 *
	 * @param CITY_ID the c i t y_ i d of this location details
	 */
	public void setCITY_ID(int CITY_ID);

	/**
	 * Returns the s t a t e_ i d of this location details.
	 *
	 * @return the s t a t e_ i d of this location details
	 */
	public int getSTATE_ID();

	/**
	 * Sets the s t a t e_ i d of this location details.
	 *
	 * @param STATE_ID the s t a t e_ i d of this location details
	 */
	public void setSTATE_ID(int STATE_ID);

	/**
	 * Returns the l a t i t u d e of this location details.
	 *
	 * @return the l a t i t u d e of this location details
	 */
	@AutoEscape
	public String getLATITUDE();

	/**
	 * Sets the l a t i t u d e of this location details.
	 *
	 * @param LATITUDE the l a t i t u d e of this location details
	 */
	public void setLATITUDE(String LATITUDE);

	/**
	 * Returns the l o n g i t u d e of this location details.
	 *
	 * @return the l o n g i t u d e of this location details
	 */
	@AutoEscape
	public String getLONGITUDE();

	/**
	 * Sets the l o n g i t u d e of this location details.
	 *
	 * @param LONGITUDE the l o n g i t u d e of this location details
	 */
	public void setLONGITUDE(String LONGITUDE);

	/**
	 * Returns the b r a n c h_ f l a g of this location details.
	 *
	 * @return the b r a n c h_ f l a g of this location details
	 */
	@AutoEscape
	public String getBRANCH_FLAG();

	/**
	 * Sets the b r a n c h_ f l a g of this location details.
	 *
	 * @param BRANCH_FLAG the b r a n c h_ f l a g of this location details
	 */
	public void setBRANCH_FLAG(String BRANCH_FLAG);

	/**
	 * Returns the m e d i c a l_ c e n t e r_ f l a g of this location details.
	 *
	 * @return the m e d i c a l_ c e n t e r_ f l a g of this location details
	 */
	@AutoEscape
	public String getMEDICAL_CENTER_FLAG();

	/**
	 * Sets the m e d i c a l_ c e n t e r_ f l a g of this location details.
	 *
	 * @param MEDICAL_CENTER_FLAG the m e d i c a l_ c e n t e r_ f l a g of this location details
	 */
	public void setMEDICAL_CENTER_FLAG(String MEDICAL_CENTER_FLAG);

	/**
	 * Returns the d r o p_ b o x_ f l a g of this location details.
	 *
	 * @return the d r o p_ b o x_ f l a g of this location details
	 */
	@AutoEscape
	public String getDROP_BOX_FLAG();

	/**
	 * Sets the d r o p_ b o x_ f l a g of this location details.
	 *
	 * @param DROP_BOX_FLAG the d r o p_ b o x_ f l a g of this location details
	 */
	public void setDROP_BOX_FLAG(String DROP_BOX_FLAG);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LocationDetails locationDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LocationDetails> toCacheModel();

	@Override
	public LocationDetails toEscapedModel();

	@Override
	public LocationDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}