/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentMethodType service. Represents a row in the &quot;PaymentMethodType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PaymentMethodTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PaymentMethodTypeImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PaymentMethodType
 * @see com.ifli.rapid.model.impl.PaymentMethodTypeImpl
 * @see com.ifli.rapid.model.impl.PaymentMethodTypeModelImpl
 * @generated
 */
public interface PaymentMethodTypeModel extends BaseModel<PaymentMethodType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment method type model instance should use the {@link PaymentMethodType} interface instead.
	 */

	/**
	 * Returns the primary key of this payment method type.
	 *
	 * @return the primary key of this payment method type
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this payment method type.
	 *
	 * @param primaryKey the primary key of this payment method type
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this payment method type.
	 *
	 * @return the ID of this payment method type
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this payment method type.
	 *
	 * @param Id the ID of this payment method type
	 */
	public void setId(String Id);

	/**
	 * Returns the payment method i d of this payment method type.
	 *
	 * @return the payment method i d of this payment method type
	 */
	@AutoEscape
	public String getPaymentMethodID();

	/**
	 * Sets the payment method i d of this payment method type.
	 *
	 * @param PaymentMethodID the payment method i d of this payment method type
	 */
	public void setPaymentMethodID(String PaymentMethodID);

	/**
	 * Returns the gateway i d of this payment method type.
	 *
	 * @return the gateway i d of this payment method type
	 */
	@AutoEscape
	public String getGatewayID();

	/**
	 * Sets the gateway i d of this payment method type.
	 *
	 * @param GatewayID the gateway i d of this payment method type
	 */
	public void setGatewayID(String GatewayID);

	/**
	 * Returns the type key of this payment method type.
	 *
	 * @return the type key of this payment method type
	 */
	@AutoEscape
	public String getTypeKey();

	/**
	 * Sets the type key of this payment method type.
	 *
	 * @param TypeKey the type key of this payment method type
	 */
	public void setTypeKey(String TypeKey);

	/**
	 * Returns the description of this payment method type.
	 *
	 * @return the description of this payment method type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this payment method type.
	 *
	 * @param Description the description of this payment method type
	 */
	public void setDescription(String Description);

	/**
	 * Returns the bank ID of this payment method type.
	 *
	 * @return the bank ID of this payment method type
	 */
	@AutoEscape
	public String getBankId();

	/**
	 * Sets the bank ID of this payment method type.
	 *
	 * @param BankId the bank ID of this payment method type
	 */
	public void setBankId(String BankId);

	/**
	 * Returns the active of this payment method type.
	 *
	 * @return the active of this payment method type
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this payment method type is active.
	 *
	 * @return <code>true</code> if this payment method type is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this payment method type is active.
	 *
	 * @param Active the active of this payment method type
	 */
	public void setActive(boolean Active);

	/**
	 * Returns the created by of this payment method type.
	 *
	 * @return the created by of this payment method type
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this payment method type.
	 *
	 * @param CreatedBy the created by of this payment method type
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this payment method type.
	 *
	 * @return the created date of this payment method type
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this payment method type.
	 *
	 * @param CreatedDate the created date of this payment method type
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this payment method type.
	 *
	 * @return the modified by of this payment method type
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this payment method type.
	 *
	 * @param ModifiedBy the modified by of this payment method type
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this payment method type.
	 *
	 * @return the modified date of this payment method type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment method type.
	 *
	 * @param ModifiedDate the modified date of this payment method type
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the type of this payment method type.
	 *
	 * @return the type of this payment method type
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this payment method type.
	 *
	 * @param Type the type of this payment method type
	 */
	public void setType(String Type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PaymentMethodType paymentMethodType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PaymentMethodType> toCacheModel();

	@Override
	public PaymentMethodType toEscapedModel();

	@Override
	public PaymentMethodType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}