/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentDetails service. Represents a row in the &quot;PaymentDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PaymentDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PaymentDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PaymentDetails
 * @see com.ifli.rapid.model.impl.PaymentDetailsImpl
 * @see com.ifli.rapid.model.impl.PaymentDetailsModelImpl
 * @generated
 */
public interface PaymentDetailsModel extends BaseModel<PaymentDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment details model instance should use the {@link PaymentDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this payment details.
	 *
	 * @return the primary key of this payment details
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this payment details.
	 *
	 * @param primaryKey the primary key of this payment details
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the payment ID of this payment details.
	 *
	 * @return the payment ID of this payment details
	 */
	public int getPaymentId();

	/**
	 * Sets the payment ID of this payment details.
	 *
	 * @param PaymentId the payment ID of this payment details
	 */
	public void setPaymentId(int PaymentId);

	/**
	 * Returns the premium frequency i d of this payment details.
	 *
	 * @return the premium frequency i d of this payment details
	 */
	@AutoEscape
	public String getPremiumFrequencyID();

	/**
	 * Sets the premium frequency i d of this payment details.
	 *
	 * @param PremiumFrequencyID the premium frequency i d of this payment details
	 */
	public void setPremiumFrequencyID(String PremiumFrequencyID);

	/**
	 * Returns the transaction status i d of this payment details.
	 *
	 * @return the transaction status i d of this payment details
	 */
	public int getTransactionStatusID();

	/**
	 * Sets the transaction status i d of this payment details.
	 *
	 * @param TransactionStatusID the transaction status i d of this payment details
	 */
	public void setTransactionStatusID(int TransactionStatusID);

	/**
	 * Returns the request type i d of this payment details.
	 *
	 * @return the request type i d of this payment details
	 */
	@AutoEscape
	public String getRequestTypeID();

	/**
	 * Sets the request type i d of this payment details.
	 *
	 * @param RequestTypeID the request type i d of this payment details
	 */
	public void setRequestTypeID(String RequestTypeID);

	/**
	 * Returns the payment option ID of this payment details.
	 *
	 * @return the payment option ID of this payment details
	 */
	@AutoEscape
	public String getPaymentOptionId();

	/**
	 * Sets the payment option ID of this payment details.
	 *
	 * @param PaymentOptionId the payment option ID of this payment details
	 */
	public void setPaymentOptionId(String PaymentOptionId);

	/**
	 * Returns the payment method i d of this payment details.
	 *
	 * @return the payment method i d of this payment details
	 */
	@AutoEscape
	public String getPaymentMethodID();

	/**
	 * Sets the payment method i d of this payment details.
	 *
	 * @param PaymentMethodID the payment method i d of this payment details
	 */
	public void setPaymentMethodID(String PaymentMethodID);

	/**
	 * Returns the product i d of this payment details.
	 *
	 * @return the product i d of this payment details
	 */
	@AutoEscape
	public String getProductID();

	/**
	 * Sets the product i d of this payment details.
	 *
	 * @param ProductID the product i d of this payment details
	 */
	public void setProductID(String ProductID);

	/**
	 * Returns the proposal ID of this payment details.
	 *
	 * @return the proposal ID of this payment details
	 */
	@AutoEscape
	public String getProposalId();

	/**
	 * Sets the proposal ID of this payment details.
	 *
	 * @param ProposalId the proposal ID of this payment details
	 */
	public void setProposalId(String ProposalId);

	/**
	 * Returns the premium amount of this payment details.
	 *
	 * @return the premium amount of this payment details
	 */
	public double getPremiumAmount();

	/**
	 * Sets the premium amount of this payment details.
	 *
	 * @param PremiumAmount the premium amount of this payment details
	 */
	public void setPremiumAmount(double PremiumAmount);

	/**
	 * Returns the bank name of this payment details.
	 *
	 * @return the bank name of this payment details
	 */
	@AutoEscape
	public String getBankName();

	/**
	 * Sets the bank name of this payment details.
	 *
	 * @param BankName the bank name of this payment details
	 */
	public void setBankName(String BankName);

	/**
	 * Returns the credit card no of this payment details.
	 *
	 * @return the credit card no of this payment details
	 */
	public long getCreditCardNo();

	/**
	 * Sets the credit card no of this payment details.
	 *
	 * @param CreditCardNo the credit card no of this payment details
	 */
	public void setCreditCardNo(long CreditCardNo);

	/**
	 * Returns the card type of this payment details.
	 *
	 * @return the card type of this payment details
	 */
	@AutoEscape
	public String getCardType();

	/**
	 * Sets the card type of this payment details.
	 *
	 * @param CardType the card type of this payment details
	 */
	public void setCardType(String CardType);

	/**
	 * Returns the name as card of this payment details.
	 *
	 * @return the name as card of this payment details
	 */
	@AutoEscape
	public String getNameAsCard();

	/**
	 * Sets the name as card of this payment details.
	 *
	 * @param NameAsCard the name as card of this payment details
	 */
	public void setNameAsCard(String NameAsCard);

	/**
	 * Returns the c v v no of this payment details.
	 *
	 * @return the c v v no of this payment details
	 */
	public int getCVVNo();

	/**
	 * Sets the c v v no of this payment details.
	 *
	 * @param CVVNo the c v v no of this payment details
	 */
	public void setCVVNo(int CVVNo);

	/**
	 * Returns the card expiry date of this payment details.
	 *
	 * @return the card expiry date of this payment details
	 */
	public Date getCardExpiryDate();

	/**
	 * Sets the card expiry date of this payment details.
	 *
	 * @param CardExpiryDate the card expiry date of this payment details
	 */
	public void setCardExpiryDate(Date CardExpiryDate);

	/**
	 * Returns the created by of this payment details.
	 *
	 * @return the created by of this payment details
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this payment details.
	 *
	 * @param CreatedBy the created by of this payment details
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this payment details.
	 *
	 * @return the created date of this payment details
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this payment details.
	 *
	 * @param CreatedDate the created date of this payment details
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this payment details.
	 *
	 * @return the modified by of this payment details
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this payment details.
	 *
	 * @param ModifiedBy the modified by of this payment details
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this payment details.
	 *
	 * @return the modified date of this payment details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment details.
	 *
	 * @param ModifiedDate the modified date of this payment details
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the cheque pickup request ID of this payment details.
	 *
	 * @return the cheque pickup request ID of this payment details
	 */
	@AutoEscape
	public String getChequePickupRequestId();

	/**
	 * Sets the cheque pickup request ID of this payment details.
	 *
	 * @param ChequePickupRequestId the cheque pickup request ID of this payment details
	 */
	public void setChequePickupRequestId(String ChequePickupRequestId);

	/**
	 * Returns the transaction reference no of this payment details.
	 *
	 * @return the transaction reference no of this payment details
	 */
	@AutoEscape
	public String getTransactionReferenceNo();

	/**
	 * Sets the transaction reference no of this payment details.
	 *
	 * @param TransactionReferenceNo the transaction reference no of this payment details
	 */
	public void setTransactionReferenceNo(String TransactionReferenceNo);

	/**
	 * Returns the bill desk merchant ID of this payment details.
	 *
	 * @return the bill desk merchant ID of this payment details
	 */
	@AutoEscape
	public String getBillDeskMerchantId();

	/**
	 * Sets the bill desk merchant ID of this payment details.
	 *
	 * @param BillDeskMerchantId the bill desk merchant ID of this payment details
	 */
	public void setBillDeskMerchantId(String BillDeskMerchantId);

	/**
	 * Returns the bob merchant txn ID of this payment details.
	 *
	 * @return the bob merchant txn ID of this payment details
	 */
	@AutoEscape
	public String getBobMerchantTxnId();

	/**
	 * Sets the bob merchant txn ID of this payment details.
	 *
	 * @param BobMerchantTxnId the bob merchant txn ID of this payment details
	 */
	public void setBobMerchantTxnId(String BobMerchantTxnId);

	/**
	 * Returns the payment receipt no of this payment details.
	 *
	 * @return the payment receipt no of this payment details
	 */
	public long getPaymentReceiptNo();

	/**
	 * Sets the payment receipt no of this payment details.
	 *
	 * @param PaymentReceiptNo the payment receipt no of this payment details
	 */
	public void setPaymentReceiptNo(long PaymentReceiptNo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PaymentDetails paymentDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PaymentDetails> toCacheModel();

	@Override
	public PaymentDetails toEscapedModel();

	@Override
	public PaymentDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}