/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentMethodMaster service. Represents a row in the &quot;PaymentMethodMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PaymentMethodMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PaymentMethodMasterImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PaymentMethodMaster
 * @see com.ifli.rapid.model.impl.PaymentMethodMasterImpl
 * @see com.ifli.rapid.model.impl.PaymentMethodMasterModelImpl
 * @generated
 */
public interface PaymentMethodMasterModel extends BaseModel<PaymentMethodMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment method master model instance should use the {@link PaymentMethodMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this payment method master.
	 *
	 * @return the primary key of this payment method master
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this payment method master.
	 *
	 * @param primaryKey the primary key of this payment method master
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the payment method i d of this payment method master.
	 *
	 * @return the payment method i d of this payment method master
	 */
	@AutoEscape
	public String getPaymentMethodID();

	/**
	 * Sets the payment method i d of this payment method master.
	 *
	 * @param PaymentMethodID the payment method i d of this payment method master
	 */
	public void setPaymentMethodID(String PaymentMethodID);

	/**
	 * Returns the payment method key of this payment method master.
	 *
	 * @return the payment method key of this payment method master
	 */
	@AutoEscape
	public String getPaymentMethodKey();

	/**
	 * Sets the payment method key of this payment method master.
	 *
	 * @param PaymentMethodKey the payment method key of this payment method master
	 */
	public void setPaymentMethodKey(String PaymentMethodKey);

	/**
	 * Returns the is active of this payment method master.
	 *
	 * @return the is active of this payment method master
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this payment method master is is active.
	 *
	 * @return <code>true</code> if this payment method master is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this payment method master is is active.
	 *
	 * @param IsActive the is active of this payment method master
	 */
	public void setIsActive(boolean IsActive);

	/**
	 * Returns the created by of this payment method master.
	 *
	 * @return the created by of this payment method master
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this payment method master.
	 *
	 * @param CreatedBy the created by of this payment method master
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this payment method master.
	 *
	 * @return the created date of this payment method master
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this payment method master.
	 *
	 * @param CreatedDate the created date of this payment method master
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this payment method master.
	 *
	 * @return the modified by of this payment method master
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this payment method master.
	 *
	 * @param ModifiedBy the modified by of this payment method master
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this payment method master.
	 *
	 * @return the modified date of this payment method master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment method master.
	 *
	 * @param ModifiedDate the modified date of this payment method master
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the priority of this payment method master.
	 *
	 * @return the priority of this payment method master
	 */
	public int getPriority();

	/**
	 * Sets the priority of this payment method master.
	 *
	 * @param Priority the priority of this payment method master
	 */
	public void setPriority(int Priority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PaymentMethodMaster paymentMethodMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PaymentMethodMaster> toCacheModel();

	@Override
	public PaymentMethodMaster toEscapedModel();

	@Override
	public PaymentMethodMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}