/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentTransactionStatusMaster service. Represents a row in the &quot;PaymentTransactionStatusMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PaymentTransactionStatusMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PaymentTransactionStatusMasterImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PaymentTransactionStatusMaster
 * @see com.ifli.rapid.model.impl.PaymentTransactionStatusMasterImpl
 * @see com.ifli.rapid.model.impl.PaymentTransactionStatusMasterModelImpl
 * @generated
 */
public interface PaymentTransactionStatusMasterModel extends BaseModel<PaymentTransactionStatusMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment transaction status master model instance should use the {@link PaymentTransactionStatusMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this payment transaction status master.
	 *
	 * @return the primary key of this payment transaction status master
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this payment transaction status master.
	 *
	 * @param primaryKey the primary key of this payment transaction status master
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the transaction status i d of this payment transaction status master.
	 *
	 * @return the transaction status i d of this payment transaction status master
	 */
	public int getTransactionStatusID();

	/**
	 * Sets the transaction status i d of this payment transaction status master.
	 *
	 * @param TransactionStatusID the transaction status i d of this payment transaction status master
	 */
	public void setTransactionStatusID(int TransactionStatusID);

	/**
	 * Returns the status code of this payment transaction status master.
	 *
	 * @return the status code of this payment transaction status master
	 */
	public int getStatusCode();

	/**
	 * Sets the status code of this payment transaction status master.
	 *
	 * @param StatusCode the status code of this payment transaction status master
	 */
	public void setStatusCode(int StatusCode);

	/**
	 * Returns the status name of this payment transaction status master.
	 *
	 * @return the status name of this payment transaction status master
	 */
	@AutoEscape
	public String getStatusName();

	/**
	 * Sets the status name of this payment transaction status master.
	 *
	 * @param StatusName the status name of this payment transaction status master
	 */
	public void setStatusName(String StatusName);

	/**
	 * Returns the status desc of this payment transaction status master.
	 *
	 * @return the status desc of this payment transaction status master
	 */
	@AutoEscape
	public String getStatusDesc();

	/**
	 * Sets the status desc of this payment transaction status master.
	 *
	 * @param StatusDesc the status desc of this payment transaction status master
	 */
	public void setStatusDesc(String StatusDesc);

	/**
	 * Returns the is active of this payment transaction status master.
	 *
	 * @return the is active of this payment transaction status master
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this payment transaction status master is is active.
	 *
	 * @return <code>true</code> if this payment transaction status master is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this payment transaction status master is is active.
	 *
	 * @param IsActive the is active of this payment transaction status master
	 */
	public void setIsActive(boolean IsActive);

	/**
	 * Returns the created by of this payment transaction status master.
	 *
	 * @return the created by of this payment transaction status master
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this payment transaction status master.
	 *
	 * @param CreatedBy the created by of this payment transaction status master
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this payment transaction status master.
	 *
	 * @return the created date of this payment transaction status master
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this payment transaction status master.
	 *
	 * @param CreatedDate the created date of this payment transaction status master
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this payment transaction status master.
	 *
	 * @return the modified by of this payment transaction status master
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this payment transaction status master.
	 *
	 * @param ModifiedBy the modified by of this payment transaction status master
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this payment transaction status master.
	 *
	 * @return the modified date of this payment transaction status master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment transaction status master.
	 *
	 * @param ModifiedDate the modified date of this payment transaction status master
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		PaymentTransactionStatusMaster paymentTransactionStatusMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PaymentTransactionStatusMaster> toCacheModel();

	@Override
	public PaymentTransactionStatusMaster toEscapedModel();

	@Override
	public PaymentTransactionStatusMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}