/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentGatewayMaster service. Represents a row in the &quot;PaymentGatewayMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PaymentGatewayMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PaymentGatewayMasterImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PaymentGatewayMaster
 * @see com.ifli.rapid.model.impl.PaymentGatewayMasterImpl
 * @see com.ifli.rapid.model.impl.PaymentGatewayMasterModelImpl
 * @generated
 */
public interface PaymentGatewayMasterModel extends BaseModel<PaymentGatewayMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment gateway master model instance should use the {@link PaymentGatewayMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this payment gateway master.
	 *
	 * @return the primary key of this payment gateway master
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this payment gateway master.
	 *
	 * @param primaryKey the primary key of this payment gateway master
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the gateway i d of this payment gateway master.
	 *
	 * @return the gateway i d of this payment gateway master
	 */
	@AutoEscape
	public String getGatewayID();

	/**
	 * Sets the gateway i d of this payment gateway master.
	 *
	 * @param GatewayID the gateway i d of this payment gateway master
	 */
	public void setGatewayID(String GatewayID);

	/**
	 * Returns the gateway description of this payment gateway master.
	 *
	 * @return the gateway description of this payment gateway master
	 */
	@AutoEscape
	public String getGatewayDescription();

	/**
	 * Sets the gateway description of this payment gateway master.
	 *
	 * @param GatewayDescription the gateway description of this payment gateway master
	 */
	public void setGatewayDescription(String GatewayDescription);

	/**
	 * Returns the gateway key of this payment gateway master.
	 *
	 * @return the gateway key of this payment gateway master
	 */
	@AutoEscape
	public String getGatewayKey();

	/**
	 * Sets the gateway key of this payment gateway master.
	 *
	 * @param GatewayKey the gateway key of this payment gateway master
	 */
	public void setGatewayKey(String GatewayKey);

	/**
	 * Returns the is active of this payment gateway master.
	 *
	 * @return the is active of this payment gateway master
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this payment gateway master is is active.
	 *
	 * @return <code>true</code> if this payment gateway master is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this payment gateway master is is active.
	 *
	 * @param IsActive the is active of this payment gateway master
	 */
	public void setIsActive(boolean IsActive);

	/**
	 * Returns the created by of this payment gateway master.
	 *
	 * @return the created by of this payment gateway master
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this payment gateway master.
	 *
	 * @param CreatedBy the created by of this payment gateway master
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this payment gateway master.
	 *
	 * @return the created date of this payment gateway master
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this payment gateway master.
	 *
	 * @param CreatedDate the created date of this payment gateway master
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this payment gateway master.
	 *
	 * @return the modified by of this payment gateway master
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this payment gateway master.
	 *
	 * @param ModifiedBy the modified by of this payment gateway master
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this payment gateway master.
	 *
	 * @return the modified date of this payment gateway master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment gateway master.
	 *
	 * @param ModifiedDate the modified date of this payment gateway master
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the priority of this payment gateway master.
	 *
	 * @return the priority of this payment gateway master
	 */
	public int getPriority();

	/**
	 * Sets the priority of this payment gateway master.
	 *
	 * @param Priority the priority of this payment gateway master
	 */
	public void setPriority(int Priority);

	/**
	 * Returns the item code of this payment gateway master.
	 *
	 * @return the item code of this payment gateway master
	 */
	@AutoEscape
	public String getItemCode();

	/**
	 * Sets the item code of this payment gateway master.
	 *
	 * @param ItemCode the item code of this payment gateway master
	 */
	public void setItemCode(String ItemCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PaymentGatewayMaster paymentGatewayMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PaymentGatewayMaster> toCacheModel();

	@Override
	public PaymentGatewayMaster toEscapedModel();

	@Override
	public PaymentGatewayMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}