/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PincodeDetails service. Represents a row in the &quot;pincode_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PincodeDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PincodeDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PincodeDetails
 * @see com.ifli.rapid.model.impl.PincodeDetailsImpl
 * @see com.ifli.rapid.model.impl.PincodeDetailsModelImpl
 * @generated
 */
public interface PincodeDetailsModel extends BaseModel<PincodeDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pincode details model instance should use the {@link PincodeDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this pincode details.
	 *
	 * @return the primary key of this pincode details
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this pincode details.
	 *
	 * @param primaryKey the primary key of this pincode details
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the p i n_ i d of this pincode details.
	 *
	 * @return the p i n_ i d of this pincode details
	 */
	public int getPIN_ID();

	/**
	 * Sets the p i n_ i d of this pincode details.
	 *
	 * @param PIN_ID the p i n_ i d of this pincode details
	 */
	public void setPIN_ID(int PIN_ID);

	/**
	 * Returns the c i t y_ i d of this pincode details.
	 *
	 * @return the c i t y_ i d of this pincode details
	 */
	public int getCITY_ID();

	/**
	 * Sets the c i t y_ i d of this pincode details.
	 *
	 * @param CITY_ID the c i t y_ i d of this pincode details
	 */
	public void setCITY_ID(int CITY_ID);

	/**
	 * Returns the s t a t e_ i d of this pincode details.
	 *
	 * @return the s t a t e_ i d of this pincode details
	 */
	public int getSTATE_ID();

	/**
	 * Sets the s t a t e_ i d of this pincode details.
	 *
	 * @param STATE_ID the s t a t e_ i d of this pincode details
	 */
	public void setSTATE_ID(int STATE_ID);

	/**
	 * Returns the p i n_ c o d e of this pincode details.
	 *
	 * @return the p i n_ c o d e of this pincode details
	 */
	@AutoEscape
	public String getPIN_CODE();

	/**
	 * Sets the p i n_ c o d e of this pincode details.
	 *
	 * @param PIN_CODE the p i n_ c o d e of this pincode details
	 */
	public void setPIN_CODE(String PIN_CODE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PincodeDetails pincodeDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PincodeDetails> toCacheModel();

	@Override
	public PincodeDetails toEscapedModel();

	@Override
	public PincodeDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}