/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the POLICY_DOC_TYPES service. Represents a row in the &quot;POLICY_DOC_TYPES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.POLICY_DOC_TYPESModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.POLICY_DOC_TYPESImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see POLICY_DOC_TYPES
 * @see com.ifli.rapid.model.impl.POLICY_DOC_TYPESImpl
 * @see com.ifli.rapid.model.impl.POLICY_DOC_TYPESModelImpl
 * @generated
 */
public interface POLICY_DOC_TYPESModel extends BaseModel<POLICY_DOC_TYPES> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a p o l i c y_ d o c_ t y p e s model instance should use the {@link POLICY_DOC_TYPES} interface instead.
	 */

	/**
	 * Returns the primary key of this p o l i c y_ d o c_ t y p e s.
	 *
	 * @return the primary key of this p o l i c y_ d o c_ t y p e s
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this p o l i c y_ d o c_ t y p e s.
	 *
	 * @param primaryKey the primary key of this p o l i c y_ d o c_ t y p e s
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this p o l i c y_ d o c_ t y p e s.
	 *
	 * @return the i d of this p o l i c y_ d o c_ t y p e s
	 */
	public int getID();

	/**
	 * Sets the i d of this p o l i c y_ d o c_ t y p e s.
	 *
	 * @param ID the i d of this p o l i c y_ d o c_ t y p e s
	 */
	public void setID(int ID);

	/**
	 * Returns the d o c_ n a m e of this p o l i c y_ d o c_ t y p e s.
	 *
	 * @return the d o c_ n a m e of this p o l i c y_ d o c_ t y p e s
	 */
	@AutoEscape
	public String getDOC_NAME();

	/**
	 * Sets the d o c_ n a m e of this p o l i c y_ d o c_ t y p e s.
	 *
	 * @param DOC_NAME the d o c_ n a m e of this p o l i c y_ d o c_ t y p e s
	 */
	public void setDOC_NAME(String DOC_NAME);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(POLICY_DOC_TYPES policy_doc_types);

	@Override
	public int hashCode();

	@Override
	public CacheModel<POLICY_DOC_TYPES> toCacheModel();

	@Override
	public POLICY_DOC_TYPES toEscapedModel();

	@Override
	public POLICY_DOC_TYPES toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}