/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PolicyFundSwitchCounter service. Represents a row in the &quot;policy_fund_switch_counter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PolicyFundSwitchCounterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PolicyFundSwitchCounterImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PolicyFundSwitchCounter
 * @see com.ifli.rapid.model.impl.PolicyFundSwitchCounterImpl
 * @see com.ifli.rapid.model.impl.PolicyFundSwitchCounterModelImpl
 * @generated
 */
public interface PolicyFundSwitchCounterModel extends BaseModel<PolicyFundSwitchCounter> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a policy fund switch counter model instance should use the {@link PolicyFundSwitchCounter} interface instead.
	 */

	/**
	 * Returns the primary key of this policy fund switch counter.
	 *
	 * @return the primary key of this policy fund switch counter
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this policy fund switch counter.
	 *
	 * @param primaryKey the primary key of this policy fund switch counter
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the p o l i c y_ i d of this policy fund switch counter.
	 *
	 * @return the p o l i c y_ i d of this policy fund switch counter
	 */
	@AutoEscape
	public String getPOLICY_ID();

	/**
	 * Sets the p o l i c y_ i d of this policy fund switch counter.
	 *
	 * @param POLICY_ID the p o l i c y_ i d of this policy fund switch counter
	 */
	public void setPOLICY_ID(String POLICY_ID);

	/**
	 * Returns the f u n d_ s w i t c h_ c o u n t e r of this policy fund switch counter.
	 *
	 * @return the f u n d_ s w i t c h_ c o u n t e r of this policy fund switch counter
	 */
	public int getFUND_SWITCH_COUNTER();

	/**
	 * Sets the f u n d_ s w i t c h_ c o u n t e r of this policy fund switch counter.
	 *
	 * @param FUND_SWITCH_COUNTER the f u n d_ s w i t c h_ c o u n t e r of this policy fund switch counter
	 */
	public void setFUND_SWITCH_COUNTER(int FUND_SWITCH_COUNTER);

	/**
	 * Returns the f u n d_ s w i t c h_ y e a r of this policy fund switch counter.
	 *
	 * @return the f u n d_ s w i t c h_ y e a r of this policy fund switch counter
	 */
	public Date getFUND_SWITCH_YEAR();

	/**
	 * Sets the f u n d_ s w i t c h_ y e a r of this policy fund switch counter.
	 *
	 * @param FUND_SWITCH_YEAR the f u n d_ s w i t c h_ y e a r of this policy fund switch counter
	 */
	public void setFUND_SWITCH_YEAR(Date FUND_SWITCH_YEAR);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PolicyFundSwitchCounter policyFundSwitchCounter);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PolicyFundSwitchCounter> toCacheModel();

	@Override
	public PolicyFundSwitchCounter toEscapedModel();

	@Override
	public PolicyFundSwitchCounter toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}