/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PolicyPremPercentage service. Represents a row in the &quot;policy_prem_percentage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PolicyPremPercentageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PolicyPremPercentageImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PolicyPremPercentage
 * @see com.ifli.rapid.model.impl.PolicyPremPercentageImpl
 * @see com.ifli.rapid.model.impl.PolicyPremPercentageModelImpl
 * @generated
 */
public interface PolicyPremPercentageModel extends BaseModel<PolicyPremPercentage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a policy prem percentage model instance should use the {@link PolicyPremPercentage} interface instead.
	 */

	/**
	 * Returns the primary key of this policy prem percentage.
	 *
	 * @return the primary key of this policy prem percentage
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this policy prem percentage.
	 *
	 * @param primaryKey the primary key of this policy prem percentage
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the p r e m_ p e r c e n t a g e_ i d of this policy prem percentage.
	 *
	 * @return the p r e m_ p e r c e n t a g e_ i d of this policy prem percentage
	 */
	public int getPREM_PERCENTAGE_ID();

	/**
	 * Sets the p r e m_ p e r c e n t a g e_ i d of this policy prem percentage.
	 *
	 * @param PREM_PERCENTAGE_ID the p r e m_ p e r c e n t a g e_ i d of this policy prem percentage
	 */
	public void setPREM_PERCENTAGE_ID(int PREM_PERCENTAGE_ID);

	/**
	 * Returns the p o l i c y_ i d of this policy prem percentage.
	 *
	 * @return the p o l i c y_ i d of this policy prem percentage
	 */
	@AutoEscape
	public String getPOLICY_ID();

	/**
	 * Sets the p o l i c y_ i d of this policy prem percentage.
	 *
	 * @param POLICY_ID the p o l i c y_ i d of this policy prem percentage
	 */
	public void setPOLICY_ID(String POLICY_ID);

	/**
	 * Returns the f u n d_ i d of this policy prem percentage.
	 *
	 * @return the f u n d_ i d of this policy prem percentage
	 */
	public int getFUND_ID();

	/**
	 * Sets the f u n d_ i d of this policy prem percentage.
	 *
	 * @param FUND_ID the f u n d_ i d of this policy prem percentage
	 */
	public void setFUND_ID(int FUND_ID);

	/**
	 * Returns the f u n d_ p e r c e n t a g e of this policy prem percentage.
	 *
	 * @return the f u n d_ p e r c e n t a g e of this policy prem percentage
	 */
	public int getFUND_PERCENTAGE();

	/**
	 * Sets the f u n d_ p e r c e n t a g e of this policy prem percentage.
	 *
	 * @param FUND_PERCENTAGE the f u n d_ p e r c e n t a g e of this policy prem percentage
	 */
	public void setFUND_PERCENTAGE(int FUND_PERCENTAGE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PolicyPremPercentage policyPremPercentage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PolicyPremPercentage> toCacheModel();

	@Override
	public PolicyPremPercentage toEscapedModel();

	@Override
	public PolicyPremPercentage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}