/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PolicyTopupDetails service. Represents a row in the &quot;policy_topup_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PolicyTopupDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PolicyTopupDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PolicyTopupDetails
 * @see com.ifli.rapid.model.impl.PolicyTopupDetailsImpl
 * @see com.ifli.rapid.model.impl.PolicyTopupDetailsModelImpl
 * @generated
 */
public interface PolicyTopupDetailsModel extends BaseModel<PolicyTopupDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a policy topup details model instance should use the {@link PolicyTopupDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this policy topup details.
	 *
	 * @return the primary key of this policy topup details
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this policy topup details.
	 *
	 * @param primaryKey the primary key of this policy topup details
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the t o p u p_ i d of this policy topup details.
	 *
	 * @return the t o p u p_ i d of this policy topup details
	 */
	public int getTOPUP_ID();

	/**
	 * Sets the t o p u p_ i d of this policy topup details.
	 *
	 * @param TOPUP_ID the t o p u p_ i d of this policy topup details
	 */
	public void setTOPUP_ID(int TOPUP_ID);

	/**
	 * Returns the p o l i c y_ i d of this policy topup details.
	 *
	 * @return the p o l i c y_ i d of this policy topup details
	 */
	@AutoEscape
	public String getPOLICY_ID();

	/**
	 * Sets the p o l i c y_ i d of this policy topup details.
	 *
	 * @param POLICY_ID the p o l i c y_ i d of this policy topup details
	 */
	public void setPOLICY_ID(String POLICY_ID);

	/**
	 * Returns the q r c_ a s r_ i d of this policy topup details.
	 *
	 * @return the q r c_ a s r_ i d of this policy topup details
	 */
	public int getQRC_ASR_ID();

	/**
	 * Sets the q r c_ a s r_ i d of this policy topup details.
	 *
	 * @param QRC_ASR_ID the q r c_ a s r_ i d of this policy topup details
	 */
	public void setQRC_ASR_ID(int QRC_ASR_ID);

	/**
	 * Returns the f u n d_ i d of this policy topup details.
	 *
	 * @return the f u n d_ i d of this policy topup details
	 */
	public int getFUND_ID();

	/**
	 * Sets the f u n d_ i d of this policy topup details.
	 *
	 * @param FUND_ID the f u n d_ i d of this policy topup details
	 */
	public void setFUND_ID(int FUND_ID);

	/**
	 * Returns the f u n d_ v a l u e of this policy topup details.
	 *
	 * @return the f u n d_ v a l u e of this policy topup details
	 */
	public double getFUND_VALUE();

	/**
	 * Sets the f u n d_ v a l u e of this policy topup details.
	 *
	 * @param FUND_VALUE the f u n d_ v a l u e of this policy topup details
	 */
	public void setFUND_VALUE(double FUND_VALUE);

	/**
	 * Returns the t o p u p_ v a l u e of this policy topup details.
	 *
	 * @return the t o p u p_ v a l u e of this policy topup details
	 */
	public double getTOPUP_VALUE();

	/**
	 * Sets the t o p u p_ v a l u e of this policy topup details.
	 *
	 * @param TOPUP_VALUE the t o p u p_ v a l u e of this policy topup details
	 */
	public void setTOPUP_VALUE(double TOPUP_VALUE);

	/**
	 * Returns the t o t_ v a l u e of this policy topup details.
	 *
	 * @return the t o t_ v a l u e of this policy topup details
	 */
	public double getTOT_VALUE();

	/**
	 * Sets the t o t_ v a l u e of this policy topup details.
	 *
	 * @param TOT_VALUE the t o t_ v a l u e of this policy topup details
	 */
	public void setTOT_VALUE(double TOT_VALUE);

	/**
	 * Returns the t o p u p_ p e r c e n t a g e of this policy topup details.
	 *
	 * @return the t o p u p_ p e r c e n t a g e of this policy topup details
	 */
	public double getTOPUP_PERCENTAGE();

	/**
	 * Sets the t o p u p_ p e r c e n t a g e of this policy topup details.
	 *
	 * @param TOPUP_PERCENTAGE the t o p u p_ p e r c e n t a g e of this policy topup details
	 */
	public void setTOPUP_PERCENTAGE(double TOPUP_PERCENTAGE);

	/**
	 * Returns the created by of this policy topup details.
	 *
	 * @return the created by of this policy topup details
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this policy topup details.
	 *
	 * @param CreatedBy the created by of this policy topup details
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this policy topup details.
	 *
	 * @return the created date of this policy topup details
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this policy topup details.
	 *
	 * @param CreatedDate the created date of this policy topup details
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this policy topup details.
	 *
	 * @return the modified by of this policy topup details
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this policy topup details.
	 *
	 * @param ModifiedBy the modified by of this policy topup details
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this policy topup details.
	 *
	 * @return the modified date of this policy topup details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this policy topup details.
	 *
	 * @param ModifiedDate the modified date of this policy topup details
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PolicyTopupDetails policyTopupDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PolicyTopupDetails> toCacheModel();

	@Override
	public PolicyTopupDetails toEscapedModel();

	@Override
	public PolicyTopupDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}