/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PremiumFrequencyMaster service. Represents a row in the &quot;PremiumFrequencyMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PremiumFrequencyMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PremiumFrequencyMasterImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PremiumFrequencyMaster
 * @see com.ifli.rapid.model.impl.PremiumFrequencyMasterImpl
 * @see com.ifli.rapid.model.impl.PremiumFrequencyMasterModelImpl
 * @generated
 */
public interface PremiumFrequencyMasterModel extends BaseModel<PremiumFrequencyMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a premium frequency master model instance should use the {@link PremiumFrequencyMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this premium frequency master.
	 *
	 * @return the primary key of this premium frequency master
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this premium frequency master.
	 *
	 * @param primaryKey the primary key of this premium frequency master
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the premium frequency ID of this premium frequency master.
	 *
	 * @return the premium frequency ID of this premium frequency master
	 */
	@AutoEscape
	public String getPremiumFrequencyId();

	/**
	 * Sets the premium frequency ID of this premium frequency master.
	 *
	 * @param PremiumFrequencyId the premium frequency ID of this premium frequency master
	 */
	public void setPremiumFrequencyId(String PremiumFrequencyId);

	/**
	 * Returns the premium frequency description of this premium frequency master.
	 *
	 * @return the premium frequency description of this premium frequency master
	 */
	@AutoEscape
	public String getPremiumFrequencyDescription();

	/**
	 * Sets the premium frequency description of this premium frequency master.
	 *
	 * @param PremiumFrequencyDescription the premium frequency description of this premium frequency master
	 */
	public void setPremiumFrequencyDescription(
		String PremiumFrequencyDescription);

	/**
	 * Returns the is active of this premium frequency master.
	 *
	 * @return the is active of this premium frequency master
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this premium frequency master is is active.
	 *
	 * @return <code>true</code> if this premium frequency master is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this premium frequency master is is active.
	 *
	 * @param IsActive the is active of this premium frequency master
	 */
	public void setIsActive(boolean IsActive);

	/**
	 * Returns the created by of this premium frequency master.
	 *
	 * @return the created by of this premium frequency master
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this premium frequency master.
	 *
	 * @param CreatedBy the created by of this premium frequency master
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this premium frequency master.
	 *
	 * @return the created date of this premium frequency master
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this premium frequency master.
	 *
	 * @param CreatedDate the created date of this premium frequency master
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this premium frequency master.
	 *
	 * @return the modified by of this premium frequency master
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this premium frequency master.
	 *
	 * @param ModifiedBy the modified by of this premium frequency master
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this premium frequency master.
	 *
	 * @return the modified date of this premium frequency master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this premium frequency master.
	 *
	 * @param ModifiedDate the modified date of this premium frequency master
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the priority of this premium frequency master.
	 *
	 * @return the priority of this premium frequency master
	 */
	public int getPriority();

	/**
	 * Sets the priority of this premium frequency master.
	 *
	 * @param Priority the priority of this premium frequency master
	 */
	public void setPriority(int Priority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PremiumFrequencyMaster premiumFrequencyMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PremiumFrequencyMaster> toCacheModel();

	@Override
	public PremiumFrequencyMaster toEscapedModel();

	@Override
	public PremiumFrequencyMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}