/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PremiumType service. Represents a row in the &quot;PremiumType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.PremiumTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.PremiumTypeImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PremiumType
 * @see com.ifli.rapid.model.impl.PremiumTypeImpl
 * @see com.ifli.rapid.model.impl.PremiumTypeModelImpl
 * @generated
 */
public interface PremiumTypeModel extends BaseModel<PremiumType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a premium type model instance should use the {@link PremiumType} interface instead.
	 */

	/**
	 * Returns the primary key of this premium type.
	 *
	 * @return the primary key of this premium type
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this premium type.
	 *
	 * @param primaryKey the primary key of this premium type
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this premium type.
	 *
	 * @return the ID of this premium type
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this premium type.
	 *
	 * @param Id the ID of this premium type
	 */
	public void setId(String Id);

	/**
	 * Returns the name of this premium type.
	 *
	 * @return the name of this premium type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this premium type.
	 *
	 * @param Name the name of this premium type
	 */
	public void setName(String Name);

	/**
	 * Returns the active of this premium type.
	 *
	 * @return the active of this premium type
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this premium type is active.
	 *
	 * @return <code>true</code> if this premium type is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this premium type is active.
	 *
	 * @param Active the active of this premium type
	 */
	public void setActive(boolean Active);

	/**
	 * Returns the created by of this premium type.
	 *
	 * @return the created by of this premium type
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this premium type.
	 *
	 * @param CreatedBy the created by of this premium type
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this premium type.
	 *
	 * @return the created date of this premium type
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this premium type.
	 *
	 * @param CreatedDate the created date of this premium type
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this premium type.
	 *
	 * @return the modified by of this premium type
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this premium type.
	 *
	 * @param ModifiedBy the modified by of this premium type
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this premium type.
	 *
	 * @return the modified date of this premium type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this premium type.
	 *
	 * @param ModifiedDate the modified date of this premium type
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the priority of this premium type.
	 *
	 * @return the priority of this premium type
	 */
	public int getPriority();

	/**
	 * Sets the priority of this premium type.
	 *
	 * @param Priority the priority of this premium type
	 */
	public void setPriority(int Priority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PremiumType premiumType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PremiumType> toCacheModel();

	@Override
	public PremiumType toEscapedModel();

	@Override
	public PremiumType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}