/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ProductFundMapping service. Represents a row in the &quot;product_fund_mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.ProductFundMappingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.ProductFundMappingImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see ProductFundMapping
 * @see com.ifli.rapid.model.impl.ProductFundMappingImpl
 * @see com.ifli.rapid.model.impl.ProductFundMappingModelImpl
 * @generated
 */
public interface ProductFundMappingModel extends BaseModel<ProductFundMapping> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product fund mapping model instance should use the {@link ProductFundMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this product fund mapping.
	 *
	 * @return the primary key of this product fund mapping
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this product fund mapping.
	 *
	 * @param primaryKey the primary key of this product fund mapping
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this product fund mapping.
	 *
	 * @return the i d of this product fund mapping
	 */
	public int getID();

	/**
	 * Sets the i d of this product fund mapping.
	 *
	 * @param ID the i d of this product fund mapping
	 */
	public void setID(int ID);

	/**
	 * Returns the p r o d u c t_ c o d e of this product fund mapping.
	 *
	 * @return the p r o d u c t_ c o d e of this product fund mapping
	 */
	@AutoEscape
	public String getPRODUCT_CODE();

	/**
	 * Sets the p r o d u c t_ c o d e of this product fund mapping.
	 *
	 * @param PRODUCT_CODE the p r o d u c t_ c o d e of this product fund mapping
	 */
	public void setPRODUCT_CODE(String PRODUCT_CODE);

	/**
	 * Returns the f u n d_ c o d e of this product fund mapping.
	 *
	 * @return the f u n d_ c o d e of this product fund mapping
	 */
	@AutoEscape
	public String getFUND_CODE();

	/**
	 * Sets the f u n d_ c o d e of this product fund mapping.
	 *
	 * @param FUND_CODE the f u n d_ c o d e of this product fund mapping
	 */
	public void setFUND_CODE(String FUND_CODE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProductFundMapping productFundMapping);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProductFundMapping> toCacheModel();

	@Override
	public ProductFundMapping toEscapedModel();

	@Override
	public ProductFundMapping toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}