/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RenewalDetails service. Represents a row in the &quot;renewal_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ifli.rapid.model.impl.RenewalDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ifli.rapid.model.impl.RenewalDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see RenewalDetails
 * @see com.ifli.rapid.model.impl.RenewalDetailsImpl
 * @see com.ifli.rapid.model.impl.RenewalDetailsModelImpl
 * @generated
 */
public interface RenewalDetailsModel extends BaseModel<RenewalDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a renewal details model instance should use the {@link RenewalDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this renewal details.
	 *
	 * @return the primary key of this renewal details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this renewal details.
	 *
	 * @param primaryKey the primary key of this renewal details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p o l i c y_ i d of this renewal details.
	 *
	 * @return the p o l i c y_ i d of this renewal details
	 */
	public long getPOLICY_ID();

	/**
	 * Sets the p o l i c y_ i d of this renewal details.
	 *
	 * @param POLICY_ID the p o l i c y_ i d of this renewal details
	 */
	public void setPOLICY_ID(long POLICY_ID);

	/**
	 * Returns the e m a i l_ i d of this renewal details.
	 *
	 * @return the e m a i l_ i d of this renewal details
	 */
	@AutoEscape
	public String getEMAIL_ID();

	/**
	 * Sets the e m a i l_ i d of this renewal details.
	 *
	 * @param EMAIL_ID the e m a i l_ i d of this renewal details
	 */
	public void setEMAIL_ID(String EMAIL_ID);

	/**
	 * Returns the m o b i l e_ n u m b e r of this renewal details.
	 *
	 * @return the m o b i l e_ n u m b e r of this renewal details
	 */
	@AutoEscape
	public String getMOBILE_NUMBER();

	/**
	 * Sets the m o b i l e_ n u m b e r of this renewal details.
	 *
	 * @param MOBILE_NUMBER the m o b i l e_ n u m b e r of this renewal details
	 */
	public void setMOBILE_NUMBER(String MOBILE_NUMBER);

	/**
	 * Returns the p o l i c y_ s t a t u s of this renewal details.
	 *
	 * @return the p o l i c y_ s t a t u s of this renewal details
	 */
	@AutoEscape
	public String getPOLICY_STATUS();

	/**
	 * Sets the p o l i c y_ s t a t u s of this renewal details.
	 *
	 * @param POLICY_STATUS the p o l i c y_ s t a t u s of this renewal details
	 */
	public void setPOLICY_STATUS(String POLICY_STATUS);

	/**
	 * Returns the p r o d u c t_ n a m e of this renewal details.
	 *
	 * @return the p r o d u c t_ n a m e of this renewal details
	 */
	@AutoEscape
	public String getPRODUCT_NAME();

	/**
	 * Sets the p r o d u c t_ n a m e of this renewal details.
	 *
	 * @param PRODUCT_NAME the p r o d u c t_ n a m e of this renewal details
	 */
	public void setPRODUCT_NAME(String PRODUCT_NAME);

	/**
	 * Returns the d a t e of this renewal details.
	 *
	 * @return the d a t e of this renewal details
	 */
	public Date getDATE();

	/**
	 * Sets the d a t e of this renewal details.
	 *
	 * @param DATE the d a t e of this renewal details
	 */
	public void setDATE(Date DATE);

	/**
	 * Returns the p o l i c y_ e x p i r y_ d a t e of this renewal details.
	 *
	 * @return the p o l i c y_ e x p i r y_ d a t e of this renewal details
	 */
	public Date getPOLICY_EXPIRY_DATE();

	/**
	 * Sets the p o l i c y_ e x p i r y_ d a t e of this renewal details.
	 *
	 * @param POLICY_EXPIRY_DATE the p o l i c y_ e x p i r y_ d a t e of this renewal details
	 */
	public void setPOLICY_EXPIRY_DATE(Date POLICY_EXPIRY_DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RenewalDetails renewalDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RenewalDetails> toCacheModel();

	@Override
	public RenewalDetails toEscapedModel();

	@Override
	public RenewalDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}