/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.ActiveServiceRequests;
import com.ifli.rapid.service.ActiveServiceRequestsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ActiveServiceRequests service. Represents a row in the &quot;QRC_ACTIVE_SERVICE_REQS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActiveServiceRequestsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see ActiveServiceRequestsImpl
 * @see com.ifli.rapid.model.ActiveServiceRequests
 * @generated
 */
public abstract class ActiveServiceRequestsBaseImpl
	extends ActiveServiceRequestsModelImpl implements ActiveServiceRequests {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a active service requests model instance should use the {@link ActiveServiceRequests} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ActiveServiceRequestsLocalServiceUtil.addActiveServiceRequests(this);
		}
		else {
			ActiveServiceRequestsLocalServiceUtil.updateActiveServiceRequests(this);
		}
	}
}