/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.ActiveServiceRequests;
import com.ifli.rapid.model.ActiveServiceRequestsModel;
import com.ifli.rapid.model.ActiveServiceRequestsSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ActiveServiceRequests service. Represents a row in the &quot;QRC_ACTIVE_SERVICE_REQS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.ActiveServiceRequestsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActiveServiceRequestsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see ActiveServiceRequestsImpl
 * @see com.ifli.rapid.model.ActiveServiceRequests
 * @see com.ifli.rapid.model.ActiveServiceRequestsModel
 * @generated
 */
@JSON(strict = true)
public class ActiveServiceRequestsModelImpl extends BaseModelImpl<ActiveServiceRequests>
	implements ActiveServiceRequestsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a active service requests model instance should use the {@link com.ifli.rapid.model.ActiveServiceRequests} interface instead.
	 */
	public static final String TABLE_NAME = "QRC_ACTIVE_SERVICE_REQS";
	public static final Object[][] TABLE_COLUMNS = {
			{ "QRC_ASR_ID", Types.INTEGER },
			{ "TYPE_ID", Types.INTEGER },
			{ "SUB_TYPE_ID", Types.INTEGER },
			{ "ASSIGNED_TO", Types.INTEGER },
			{ "HANDLED_BY", Types.INTEGER },
			{ "STATUS_ID", Types.INTEGER },
			{ "CUSTOMER_ID", Types.INTEGER },
			{ "CUST_SR_NUMBER", Types.VARCHAR },
			{ "ADDITIONAL_DATA_XML", Types.VARCHAR },
			{ "INSERTED_DATE", Types.TIMESTAMP },
			{ "INSERTED_BY", Types.VARCHAR },
			{ "UPDATED_DATE", Types.TIMESTAMP },
			{ "UPDATED_BY", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table QRC_ACTIVE_SERVICE_REQS (QRC_ASR_ID INTEGER not null primary key IDENTITY,TYPE_ID INTEGER,SUB_TYPE_ID INTEGER,ASSIGNED_TO INTEGER,HANDLED_BY INTEGER,STATUS_ID INTEGER,CUSTOMER_ID INTEGER,CUST_SR_NUMBER VARCHAR(75) null,ADDITIONAL_DATA_XML VARCHAR(75) null,INSERTED_DATE DATE null,INSERTED_BY VARCHAR(75) null,UPDATED_DATE DATE null,UPDATED_BY VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table QRC_ACTIVE_SERVICE_REQS";
	public static final String ORDER_BY_JPQL = " ORDER BY activeServiceRequests.QRC_ASR_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY QRC_ACTIVE_SERVICE_REQS.QRC_ASR_ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.ActiveServiceRequests"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.ActiveServiceRequests"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ActiveServiceRequests toModel(
		ActiveServiceRequestsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ActiveServiceRequests model = new ActiveServiceRequestsImpl();

		model.setQRC_ASR_ID(soapModel.getQRC_ASR_ID());
		model.setTYPE_ID(soapModel.getTYPE_ID());
		model.setSUB_TYPE_ID(soapModel.getSUB_TYPE_ID());
		model.setASSIGNED_TO(soapModel.getASSIGNED_TO());
		model.setHANDLED_BY(soapModel.getHANDLED_BY());
		model.setSTATUS_ID(soapModel.getSTATUS_ID());
		model.setCUSTOMER_ID(soapModel.getCUSTOMER_ID());
		model.setCUST_SR_NUMBER(soapModel.getCUST_SR_NUMBER());
		model.setADDITIONAL_DATA_XML(soapModel.getADDITIONAL_DATA_XML());
		model.setINSERTED_DATE(soapModel.getINSERTED_DATE());
		model.setINSERTED_BY(soapModel.getINSERTED_BY());
		model.setUPDATED_DATE(soapModel.getUPDATED_DATE());
		model.setUPDATED_BY(soapModel.getUPDATED_BY());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ActiveServiceRequests> toModels(
		ActiveServiceRequestsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ActiveServiceRequests> models = new ArrayList<ActiveServiceRequests>(soapModels.length);

		for (ActiveServiceRequestsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.ActiveServiceRequests"));

	public ActiveServiceRequestsModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _QRC_ASR_ID;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setQRC_ASR_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _QRC_ASR_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ActiveServiceRequests.class;
	}

	@Override
	public String getModelClassName() {
		return ActiveServiceRequests.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("QRC_ASR_ID", getQRC_ASR_ID());
		attributes.put("TYPE_ID", getTYPE_ID());
		attributes.put("SUB_TYPE_ID", getSUB_TYPE_ID());
		attributes.put("ASSIGNED_TO", getASSIGNED_TO());
		attributes.put("HANDLED_BY", getHANDLED_BY());
		attributes.put("STATUS_ID", getSTATUS_ID());
		attributes.put("CUSTOMER_ID", getCUSTOMER_ID());
		attributes.put("CUST_SR_NUMBER", getCUST_SR_NUMBER());
		attributes.put("ADDITIONAL_DATA_XML", getADDITIONAL_DATA_XML());
		attributes.put("INSERTED_DATE", getINSERTED_DATE());
		attributes.put("INSERTED_BY", getINSERTED_BY());
		attributes.put("UPDATED_DATE", getUPDATED_DATE());
		attributes.put("UPDATED_BY", getUPDATED_BY());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer QRC_ASR_ID = (Integer)attributes.get("QRC_ASR_ID");

		if (QRC_ASR_ID != null) {
			setQRC_ASR_ID(QRC_ASR_ID);
		}

		Integer TYPE_ID = (Integer)attributes.get("TYPE_ID");

		if (TYPE_ID != null) {
			setTYPE_ID(TYPE_ID);
		}

		Integer SUB_TYPE_ID = (Integer)attributes.get("SUB_TYPE_ID");

		if (SUB_TYPE_ID != null) {
			setSUB_TYPE_ID(SUB_TYPE_ID);
		}

		Integer ASSIGNED_TO = (Integer)attributes.get("ASSIGNED_TO");

		if (ASSIGNED_TO != null) {
			setASSIGNED_TO(ASSIGNED_TO);
		}

		Integer HANDLED_BY = (Integer)attributes.get("HANDLED_BY");

		if (HANDLED_BY != null) {
			setHANDLED_BY(HANDLED_BY);
		}

		Integer STATUS_ID = (Integer)attributes.get("STATUS_ID");

		if (STATUS_ID != null) {
			setSTATUS_ID(STATUS_ID);
		}

		Integer CUSTOMER_ID = (Integer)attributes.get("CUSTOMER_ID");

		if (CUSTOMER_ID != null) {
			setCUSTOMER_ID(CUSTOMER_ID);
		}

		String CUST_SR_NUMBER = (String)attributes.get("CUST_SR_NUMBER");

		if (CUST_SR_NUMBER != null) {
			setCUST_SR_NUMBER(CUST_SR_NUMBER);
		}

		String ADDITIONAL_DATA_XML = (String)attributes.get(
				"ADDITIONAL_DATA_XML");

		if (ADDITIONAL_DATA_XML != null) {
			setADDITIONAL_DATA_XML(ADDITIONAL_DATA_XML);
		}

		Date INSERTED_DATE = (Date)attributes.get("INSERTED_DATE");

		if (INSERTED_DATE != null) {
			setINSERTED_DATE(INSERTED_DATE);
		}

		String INSERTED_BY = (String)attributes.get("INSERTED_BY");

		if (INSERTED_BY != null) {
			setINSERTED_BY(INSERTED_BY);
		}

		Date UPDATED_DATE = (Date)attributes.get("UPDATED_DATE");

		if (UPDATED_DATE != null) {
			setUPDATED_DATE(UPDATED_DATE);
		}

		String UPDATED_BY = (String)attributes.get("UPDATED_BY");

		if (UPDATED_BY != null) {
			setUPDATED_BY(UPDATED_BY);
		}
	}

	@JSON
	@Override
	public int getQRC_ASR_ID() {
		return _QRC_ASR_ID;
	}

	@Override
	public void setQRC_ASR_ID(int QRC_ASR_ID) {
		_QRC_ASR_ID = QRC_ASR_ID;
	}

	@JSON
	@Override
	public int getTYPE_ID() {
		return _TYPE_ID;
	}

	@Override
	public void setTYPE_ID(int TYPE_ID) {
		_TYPE_ID = TYPE_ID;
	}

	@JSON
	@Override
	public int getSUB_TYPE_ID() {
		return _SUB_TYPE_ID;
	}

	@Override
	public void setSUB_TYPE_ID(int SUB_TYPE_ID) {
		_SUB_TYPE_ID = SUB_TYPE_ID;
	}

	@JSON
	@Override
	public int getASSIGNED_TO() {
		return _ASSIGNED_TO;
	}

	@Override
	public void setASSIGNED_TO(int ASSIGNED_TO) {
		_ASSIGNED_TO = ASSIGNED_TO;
	}

	@JSON
	@Override
	public int getHANDLED_BY() {
		return _HANDLED_BY;
	}

	@Override
	public void setHANDLED_BY(int HANDLED_BY) {
		_HANDLED_BY = HANDLED_BY;
	}

	@JSON
	@Override
	public int getSTATUS_ID() {
		return _STATUS_ID;
	}

	@Override
	public void setSTATUS_ID(int STATUS_ID) {
		_STATUS_ID = STATUS_ID;
	}

	@JSON
	@Override
	public int getCUSTOMER_ID() {
		return _CUSTOMER_ID;
	}

	@Override
	public void setCUSTOMER_ID(int CUSTOMER_ID) {
		_CUSTOMER_ID = CUSTOMER_ID;
	}

	@JSON
	@Override
	public String getCUST_SR_NUMBER() {
		if (_CUST_SR_NUMBER == null) {
			return StringPool.BLANK;
		}
		else {
			return _CUST_SR_NUMBER;
		}
	}

	@Override
	public void setCUST_SR_NUMBER(String CUST_SR_NUMBER) {
		_CUST_SR_NUMBER = CUST_SR_NUMBER;
	}

	@JSON
	@Override
	public String getADDITIONAL_DATA_XML() {
		if (_ADDITIONAL_DATA_XML == null) {
			return StringPool.BLANK;
		}
		else {
			return _ADDITIONAL_DATA_XML;
		}
	}

	@Override
	public void setADDITIONAL_DATA_XML(String ADDITIONAL_DATA_XML) {
		_ADDITIONAL_DATA_XML = ADDITIONAL_DATA_XML;
	}

	@JSON
	@Override
	public Date getINSERTED_DATE() {
		return _INSERTED_DATE;
	}

	@Override
	public void setINSERTED_DATE(Date INSERTED_DATE) {
		_INSERTED_DATE = INSERTED_DATE;
	}

	@JSON
	@Override
	public String getINSERTED_BY() {
		if (_INSERTED_BY == null) {
			return StringPool.BLANK;
		}
		else {
			return _INSERTED_BY;
		}
	}

	@Override
	public void setINSERTED_BY(String INSERTED_BY) {
		_INSERTED_BY = INSERTED_BY;
	}

	@JSON
	@Override
	public Date getUPDATED_DATE() {
		return _UPDATED_DATE;
	}

	@Override
	public void setUPDATED_DATE(Date UPDATED_DATE) {
		_UPDATED_DATE = UPDATED_DATE;
	}

	@JSON
	@Override
	public String getUPDATED_BY() {
		if (_UPDATED_BY == null) {
			return StringPool.BLANK;
		}
		else {
			return _UPDATED_BY;
		}
	}

	@Override
	public void setUPDATED_BY(String UPDATED_BY) {
		_UPDATED_BY = UPDATED_BY;
	}

	@Override
	public ActiveServiceRequests toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ActiveServiceRequests)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ActiveServiceRequestsImpl activeServiceRequestsImpl = new ActiveServiceRequestsImpl();

		activeServiceRequestsImpl.setQRC_ASR_ID(getQRC_ASR_ID());
		activeServiceRequestsImpl.setTYPE_ID(getTYPE_ID());
		activeServiceRequestsImpl.setSUB_TYPE_ID(getSUB_TYPE_ID());
		activeServiceRequestsImpl.setASSIGNED_TO(getASSIGNED_TO());
		activeServiceRequestsImpl.setHANDLED_BY(getHANDLED_BY());
		activeServiceRequestsImpl.setSTATUS_ID(getSTATUS_ID());
		activeServiceRequestsImpl.setCUSTOMER_ID(getCUSTOMER_ID());
		activeServiceRequestsImpl.setCUST_SR_NUMBER(getCUST_SR_NUMBER());
		activeServiceRequestsImpl.setADDITIONAL_DATA_XML(getADDITIONAL_DATA_XML());
		activeServiceRequestsImpl.setINSERTED_DATE(getINSERTED_DATE());
		activeServiceRequestsImpl.setINSERTED_BY(getINSERTED_BY());
		activeServiceRequestsImpl.setUPDATED_DATE(getUPDATED_DATE());
		activeServiceRequestsImpl.setUPDATED_BY(getUPDATED_BY());

		activeServiceRequestsImpl.resetOriginalValues();

		return activeServiceRequestsImpl;
	}

	@Override
	public int compareTo(ActiveServiceRequests activeServiceRequests) {
		int primaryKey = activeServiceRequests.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ActiveServiceRequests)) {
			return false;
		}

		ActiveServiceRequests activeServiceRequests = (ActiveServiceRequests)obj;

		int primaryKey = activeServiceRequests.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ActiveServiceRequests> toCacheModel() {
		ActiveServiceRequestsCacheModel activeServiceRequestsCacheModel = new ActiveServiceRequestsCacheModel();

		activeServiceRequestsCacheModel.QRC_ASR_ID = getQRC_ASR_ID();

		activeServiceRequestsCacheModel.TYPE_ID = getTYPE_ID();

		activeServiceRequestsCacheModel.SUB_TYPE_ID = getSUB_TYPE_ID();

		activeServiceRequestsCacheModel.ASSIGNED_TO = getASSIGNED_TO();

		activeServiceRequestsCacheModel.HANDLED_BY = getHANDLED_BY();

		activeServiceRequestsCacheModel.STATUS_ID = getSTATUS_ID();

		activeServiceRequestsCacheModel.CUSTOMER_ID = getCUSTOMER_ID();

		activeServiceRequestsCacheModel.CUST_SR_NUMBER = getCUST_SR_NUMBER();

		String CUST_SR_NUMBER = activeServiceRequestsCacheModel.CUST_SR_NUMBER;

		if ((CUST_SR_NUMBER != null) && (CUST_SR_NUMBER.length() == 0)) {
			activeServiceRequestsCacheModel.CUST_SR_NUMBER = null;
		}

		activeServiceRequestsCacheModel.ADDITIONAL_DATA_XML = getADDITIONAL_DATA_XML();

		String ADDITIONAL_DATA_XML = activeServiceRequestsCacheModel.ADDITIONAL_DATA_XML;

		if ((ADDITIONAL_DATA_XML != null) &&
				(ADDITIONAL_DATA_XML.length() == 0)) {
			activeServiceRequestsCacheModel.ADDITIONAL_DATA_XML = null;
		}

		Date INSERTED_DATE = getINSERTED_DATE();

		if (INSERTED_DATE != null) {
			activeServiceRequestsCacheModel.INSERTED_DATE = INSERTED_DATE.getTime();
		}
		else {
			activeServiceRequestsCacheModel.INSERTED_DATE = Long.MIN_VALUE;
		}

		activeServiceRequestsCacheModel.INSERTED_BY = getINSERTED_BY();

		String INSERTED_BY = activeServiceRequestsCacheModel.INSERTED_BY;

		if ((INSERTED_BY != null) && (INSERTED_BY.length() == 0)) {
			activeServiceRequestsCacheModel.INSERTED_BY = null;
		}

		Date UPDATED_DATE = getUPDATED_DATE();

		if (UPDATED_DATE != null) {
			activeServiceRequestsCacheModel.UPDATED_DATE = UPDATED_DATE.getTime();
		}
		else {
			activeServiceRequestsCacheModel.UPDATED_DATE = Long.MIN_VALUE;
		}

		activeServiceRequestsCacheModel.UPDATED_BY = getUPDATED_BY();

		String UPDATED_BY = activeServiceRequestsCacheModel.UPDATED_BY;

		if ((UPDATED_BY != null) && (UPDATED_BY.length() == 0)) {
			activeServiceRequestsCacheModel.UPDATED_BY = null;
		}

		return activeServiceRequestsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{QRC_ASR_ID=");
		sb.append(getQRC_ASR_ID());
		sb.append(", TYPE_ID=");
		sb.append(getTYPE_ID());
		sb.append(", SUB_TYPE_ID=");
		sb.append(getSUB_TYPE_ID());
		sb.append(", ASSIGNED_TO=");
		sb.append(getASSIGNED_TO());
		sb.append(", HANDLED_BY=");
		sb.append(getHANDLED_BY());
		sb.append(", STATUS_ID=");
		sb.append(getSTATUS_ID());
		sb.append(", CUSTOMER_ID=");
		sb.append(getCUSTOMER_ID());
		sb.append(", CUST_SR_NUMBER=");
		sb.append(getCUST_SR_NUMBER());
		sb.append(", ADDITIONAL_DATA_XML=");
		sb.append(getADDITIONAL_DATA_XML());
		sb.append(", INSERTED_DATE=");
		sb.append(getINSERTED_DATE());
		sb.append(", INSERTED_BY=");
		sb.append(getINSERTED_BY());
		sb.append(", UPDATED_DATE=");
		sb.append(getUPDATED_DATE());
		sb.append(", UPDATED_BY=");
		sb.append(getUPDATED_BY());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.ActiveServiceRequests");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>QRC_ASR_ID</column-name><column-value><![CDATA[");
		sb.append(getQRC_ASR_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TYPE_ID</column-name><column-value><![CDATA[");
		sb.append(getTYPE_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SUB_TYPE_ID</column-name><column-value><![CDATA[");
		sb.append(getSUB_TYPE_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ASSIGNED_TO</column-name><column-value><![CDATA[");
		sb.append(getASSIGNED_TO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>HANDLED_BY</column-name><column-value><![CDATA[");
		sb.append(getHANDLED_BY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>STATUS_ID</column-name><column-value><![CDATA[");
		sb.append(getSTATUS_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUSTOMER_ID</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUST_SR_NUMBER</column-name><column-value><![CDATA[");
		sb.append(getCUST_SR_NUMBER());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADDITIONAL_DATA_XML</column-name><column-value><![CDATA[");
		sb.append(getADDITIONAL_DATA_XML());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>INSERTED_DATE</column-name><column-value><![CDATA[");
		sb.append(getINSERTED_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>INSERTED_BY</column-name><column-value><![CDATA[");
		sb.append(getINSERTED_BY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATED_DATE</column-name><column-value><![CDATA[");
		sb.append(getUPDATED_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATED_BY</column-name><column-value><![CDATA[");
		sb.append(getUPDATED_BY());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ActiveServiceRequests.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ActiveServiceRequests.class
		};
	private int _QRC_ASR_ID;
	private int _TYPE_ID;
	private int _SUB_TYPE_ID;
	private int _ASSIGNED_TO;
	private int _HANDLED_BY;
	private int _STATUS_ID;
	private int _CUSTOMER_ID;
	private String _CUST_SR_NUMBER;
	private String _ADDITIONAL_DATA_XML;
	private Date _INSERTED_DATE;
	private String _INSERTED_BY;
	private Date _UPDATED_DATE;
	private String _UPDATED_BY;
	private ActiveServiceRequests _escapedModel;
}