/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.AddressType;
import com.ifli.rapid.model.AddressTypeModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AddressType service. Represents a row in the &quot;address_type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.AddressTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AddressTypeImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see AddressTypeImpl
 * @see com.ifli.rapid.model.AddressType
 * @see com.ifli.rapid.model.AddressTypeModel
 * @generated
 */
public class AddressTypeModelImpl extends BaseModelImpl<AddressType>
	implements AddressTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a address type model instance should use the {@link com.ifli.rapid.model.AddressType} interface instead.
	 */
	public static final String TABLE_NAME = "address_type";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ADDRESS_TYPE_ID", Types.INTEGER },
			{ "INSERTED_BY", Types.VARCHAR },
			{ "INSERTED_DATE", Types.TIMESTAMP },
			{ "UPDATED_BY", Types.VARCHAR },
			{ "UPDATED_DATE", Types.TIMESTAMP },
			{ "ACTIVE_FLAG", Types.VARCHAR },
			{ "ADDRESS_TYPE_DESC", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table address_type (ADDRESS_TYPE_ID INTEGER not null primary key,INSERTED_BY VARCHAR(75) null,INSERTED_DATE DATE null,UPDATED_BY VARCHAR(75) null,UPDATED_DATE DATE null,ACTIVE_FLAG VARCHAR(75) null,ADDRESS_TYPE_DESC VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table address_type";
	public static final String ORDER_BY_JPQL = " ORDER BY addressType.ADDRESS_TYPE_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY address_type.ADDRESS_TYPE_ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.AddressType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.AddressType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.AddressType"));

	public AddressTypeModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _ADDRESS_TYPE_ID;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setADDRESS_TYPE_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ADDRESS_TYPE_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AddressType.class;
	}

	@Override
	public String getModelClassName() {
		return AddressType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ADDRESS_TYPE_ID", getADDRESS_TYPE_ID());
		attributes.put("INSERTED_BY", getINSERTED_BY());
		attributes.put("INSERTED_DATE", getINSERTED_DATE());
		attributes.put("UPDATED_BY", getUPDATED_BY());
		attributes.put("UPDATED_DATE", getUPDATED_DATE());
		attributes.put("ACTIVE_FLAG", getACTIVE_FLAG());
		attributes.put("ADDRESS_TYPE_DESC", getADDRESS_TYPE_DESC());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer ADDRESS_TYPE_ID = (Integer)attributes.get("ADDRESS_TYPE_ID");

		if (ADDRESS_TYPE_ID != null) {
			setADDRESS_TYPE_ID(ADDRESS_TYPE_ID);
		}

		String INSERTED_BY = (String)attributes.get("INSERTED_BY");

		if (INSERTED_BY != null) {
			setINSERTED_BY(INSERTED_BY);
		}

		Date INSERTED_DATE = (Date)attributes.get("INSERTED_DATE");

		if (INSERTED_DATE != null) {
			setINSERTED_DATE(INSERTED_DATE);
		}

		String UPDATED_BY = (String)attributes.get("UPDATED_BY");

		if (UPDATED_BY != null) {
			setUPDATED_BY(UPDATED_BY);
		}

		Date UPDATED_DATE = (Date)attributes.get("UPDATED_DATE");

		if (UPDATED_DATE != null) {
			setUPDATED_DATE(UPDATED_DATE);
		}

		String ACTIVE_FLAG = (String)attributes.get("ACTIVE_FLAG");

		if (ACTIVE_FLAG != null) {
			setACTIVE_FLAG(ACTIVE_FLAG);
		}

		String ADDRESS_TYPE_DESC = (String)attributes.get("ADDRESS_TYPE_DESC");

		if (ADDRESS_TYPE_DESC != null) {
			setADDRESS_TYPE_DESC(ADDRESS_TYPE_DESC);
		}
	}

	@Override
	public int getADDRESS_TYPE_ID() {
		return _ADDRESS_TYPE_ID;
	}

	@Override
	public void setADDRESS_TYPE_ID(int ADDRESS_TYPE_ID) {
		_ADDRESS_TYPE_ID = ADDRESS_TYPE_ID;
	}

	@Override
	public String getINSERTED_BY() {
		if (_INSERTED_BY == null) {
			return StringPool.BLANK;
		}
		else {
			return _INSERTED_BY;
		}
	}

	@Override
	public void setINSERTED_BY(String INSERTED_BY) {
		_INSERTED_BY = INSERTED_BY;
	}

	@Override
	public Date getINSERTED_DATE() {
		return _INSERTED_DATE;
	}

	@Override
	public void setINSERTED_DATE(Date INSERTED_DATE) {
		_INSERTED_DATE = INSERTED_DATE;
	}

	@Override
	public String getUPDATED_BY() {
		if (_UPDATED_BY == null) {
			return StringPool.BLANK;
		}
		else {
			return _UPDATED_BY;
		}
	}

	@Override
	public void setUPDATED_BY(String UPDATED_BY) {
		_UPDATED_BY = UPDATED_BY;
	}

	@Override
	public Date getUPDATED_DATE() {
		return _UPDATED_DATE;
	}

	@Override
	public void setUPDATED_DATE(Date UPDATED_DATE) {
		_UPDATED_DATE = UPDATED_DATE;
	}

	@Override
	public String getACTIVE_FLAG() {
		if (_ACTIVE_FLAG == null) {
			return StringPool.BLANK;
		}
		else {
			return _ACTIVE_FLAG;
		}
	}

	@Override
	public void setACTIVE_FLAG(String ACTIVE_FLAG) {
		_ACTIVE_FLAG = ACTIVE_FLAG;
	}

	@Override
	public String getADDRESS_TYPE_DESC() {
		if (_ADDRESS_TYPE_DESC == null) {
			return StringPool.BLANK;
		}
		else {
			return _ADDRESS_TYPE_DESC;
		}
	}

	@Override
	public void setADDRESS_TYPE_DESC(String ADDRESS_TYPE_DESC) {
		_ADDRESS_TYPE_DESC = ADDRESS_TYPE_DESC;
	}

	@Override
	public AddressType toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AddressType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AddressTypeImpl addressTypeImpl = new AddressTypeImpl();

		addressTypeImpl.setADDRESS_TYPE_ID(getADDRESS_TYPE_ID());
		addressTypeImpl.setINSERTED_BY(getINSERTED_BY());
		addressTypeImpl.setINSERTED_DATE(getINSERTED_DATE());
		addressTypeImpl.setUPDATED_BY(getUPDATED_BY());
		addressTypeImpl.setUPDATED_DATE(getUPDATED_DATE());
		addressTypeImpl.setACTIVE_FLAG(getACTIVE_FLAG());
		addressTypeImpl.setADDRESS_TYPE_DESC(getADDRESS_TYPE_DESC());

		addressTypeImpl.resetOriginalValues();

		return addressTypeImpl;
	}

	@Override
	public int compareTo(AddressType addressType) {
		int primaryKey = addressType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AddressType)) {
			return false;
		}

		AddressType addressType = (AddressType)obj;

		int primaryKey = addressType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AddressType> toCacheModel() {
		AddressTypeCacheModel addressTypeCacheModel = new AddressTypeCacheModel();

		addressTypeCacheModel.ADDRESS_TYPE_ID = getADDRESS_TYPE_ID();

		addressTypeCacheModel.INSERTED_BY = getINSERTED_BY();

		String INSERTED_BY = addressTypeCacheModel.INSERTED_BY;

		if ((INSERTED_BY != null) && (INSERTED_BY.length() == 0)) {
			addressTypeCacheModel.INSERTED_BY = null;
		}

		Date INSERTED_DATE = getINSERTED_DATE();

		if (INSERTED_DATE != null) {
			addressTypeCacheModel.INSERTED_DATE = INSERTED_DATE.getTime();
		}
		else {
			addressTypeCacheModel.INSERTED_DATE = Long.MIN_VALUE;
		}

		addressTypeCacheModel.UPDATED_BY = getUPDATED_BY();

		String UPDATED_BY = addressTypeCacheModel.UPDATED_BY;

		if ((UPDATED_BY != null) && (UPDATED_BY.length() == 0)) {
			addressTypeCacheModel.UPDATED_BY = null;
		}

		Date UPDATED_DATE = getUPDATED_DATE();

		if (UPDATED_DATE != null) {
			addressTypeCacheModel.UPDATED_DATE = UPDATED_DATE.getTime();
		}
		else {
			addressTypeCacheModel.UPDATED_DATE = Long.MIN_VALUE;
		}

		addressTypeCacheModel.ACTIVE_FLAG = getACTIVE_FLAG();

		String ACTIVE_FLAG = addressTypeCacheModel.ACTIVE_FLAG;

		if ((ACTIVE_FLAG != null) && (ACTIVE_FLAG.length() == 0)) {
			addressTypeCacheModel.ACTIVE_FLAG = null;
		}

		addressTypeCacheModel.ADDRESS_TYPE_DESC = getADDRESS_TYPE_DESC();

		String ADDRESS_TYPE_DESC = addressTypeCacheModel.ADDRESS_TYPE_DESC;

		if ((ADDRESS_TYPE_DESC != null) && (ADDRESS_TYPE_DESC.length() == 0)) {
			addressTypeCacheModel.ADDRESS_TYPE_DESC = null;
		}

		return addressTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{ADDRESS_TYPE_ID=");
		sb.append(getADDRESS_TYPE_ID());
		sb.append(", INSERTED_BY=");
		sb.append(getINSERTED_BY());
		sb.append(", INSERTED_DATE=");
		sb.append(getINSERTED_DATE());
		sb.append(", UPDATED_BY=");
		sb.append(getUPDATED_BY());
		sb.append(", UPDATED_DATE=");
		sb.append(getUPDATED_DATE());
		sb.append(", ACTIVE_FLAG=");
		sb.append(getACTIVE_FLAG());
		sb.append(", ADDRESS_TYPE_DESC=");
		sb.append(getADDRESS_TYPE_DESC());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.AddressType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ADDRESS_TYPE_ID</column-name><column-value><![CDATA[");
		sb.append(getADDRESS_TYPE_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>INSERTED_BY</column-name><column-value><![CDATA[");
		sb.append(getINSERTED_BY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>INSERTED_DATE</column-name><column-value><![CDATA[");
		sb.append(getINSERTED_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATED_BY</column-name><column-value><![CDATA[");
		sb.append(getUPDATED_BY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATED_DATE</column-name><column-value><![CDATA[");
		sb.append(getUPDATED_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ACTIVE_FLAG</column-name><column-value><![CDATA[");
		sb.append(getACTIVE_FLAG());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADDRESS_TYPE_DESC</column-name><column-value><![CDATA[");
		sb.append(getADDRESS_TYPE_DESC());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AddressType.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			AddressType.class
		};
	private int _ADDRESS_TYPE_ID;
	private String _INSERTED_BY;
	private Date _INSERTED_DATE;
	private String _UPDATED_BY;
	private Date _UPDATED_DATE;
	private String _ACTIVE_FLAG;
	private String _ADDRESS_TYPE_DESC;
	private AddressType _escapedModel;
}