/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.CustomerTemp;
import com.ifli.rapid.model.CustomerTempModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CustomerTemp service. Represents a row in the &quot;customer_temp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.CustomerTempModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomerTempImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CustomerTempImpl
 * @see com.ifli.rapid.model.CustomerTemp
 * @see com.ifli.rapid.model.CustomerTempModel
 * @generated
 */
public class CustomerTempModelImpl extends BaseModelImpl<CustomerTemp>
	implements CustomerTempModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a customer temp model instance should use the {@link com.ifli.rapid.model.CustomerTemp} interface instead.
	 */
	public static final String TABLE_NAME = "customer_temp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "CUSTOMER_ID", Types.VARCHAR },
			{ "CUSTOMER_SALUTATION", Types.VARCHAR },
			{ "CUSTOMER_FIRST_NAME", Types.VARCHAR },
			{ "CUSTOMER_LAST_NAME", Types.VARCHAR },
			{ "CUSTOMER_MIDDLE_NAME", Types.VARCHAR },
			{ "CUSTOMER_DATE_OF_BIRTH", Types.VARCHAR },
			{ "CUSTOMER_EMAIL_ADDR", Types.VARCHAR },
			{ "PRIMARY_ADDRESS_LINE_1", Types.VARCHAR },
			{ "PRIMARY_ADDRESS_LINE_2", Types.VARCHAR },
			{ "PRIMARY_ADDRESS_LINE_3", Types.VARCHAR },
			{ "PRIMARY_ADDRESS_CITY", Types.VARCHAR },
			{ "PRIMARY_ADDRESS_STATE", Types.VARCHAR },
			{ "PIMARY_ADDRESS_PINCODE", Types.INTEGER },
			{ "PHONE_NUMBER_1", Types.VARCHAR },
			{ "PHONE_NUMBER_2", Types.VARCHAR },
			{ "PHONE_NUMBER_3", Types.VARCHAR },
			{ "LOGIN_NAME", Types.VARCHAR },
			{ "GENDER", Types.VARCHAR },
			{ "MARITAL_STATUS", Types.VARCHAR },
			{ "COUNTRY", Types.VARCHAR },
			{ "PRIMARY_ADDRESS_STATE_ID", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table customer_temp (CUSTOMER_ID VARCHAR(75) not null primary key,CUSTOMER_SALUTATION VARCHAR(75) null,CUSTOMER_FIRST_NAME VARCHAR(75) null,CUSTOMER_LAST_NAME VARCHAR(75) null,CUSTOMER_MIDDLE_NAME VARCHAR(75) null,CUSTOMER_DATE_OF_BIRTH VARCHAR(75) null,CUSTOMER_EMAIL_ADDR VARCHAR(75) null,PRIMARY_ADDRESS_LINE_1 VARCHAR(75) null,PRIMARY_ADDRESS_LINE_2 VARCHAR(75) null,PRIMARY_ADDRESS_LINE_3 VARCHAR(75) null,PRIMARY_ADDRESS_CITY VARCHAR(75) null,PRIMARY_ADDRESS_STATE VARCHAR(75) null,PIMARY_ADDRESS_PINCODE INTEGER,PHONE_NUMBER_1 VARCHAR(75) null,PHONE_NUMBER_2 VARCHAR(75) null,PHONE_NUMBER_3 VARCHAR(75) null,LOGIN_NAME VARCHAR(75) null,GENDER VARCHAR(75) null,MARITAL_STATUS VARCHAR(75) null,COUNTRY VARCHAR(75) null,PRIMARY_ADDRESS_STATE_ID INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table customer_temp";
	public static final String ORDER_BY_JPQL = " ORDER BY customerTemp.CUSTOMER_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY customer_temp.CUSTOMER_ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.CustomerTemp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.CustomerTemp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.CustomerTemp"));

	public CustomerTempModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _CUSTOMER_ID;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setCUSTOMER_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CUSTOMER_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return CustomerTemp.class;
	}

	@Override
	public String getModelClassName() {
		return CustomerTemp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("CUSTOMER_ID", getCUSTOMER_ID());
		attributes.put("CUSTOMER_SALUTATION", getCUSTOMER_SALUTATION());
		attributes.put("CUSTOMER_FIRST_NAME", getCUSTOMER_FIRST_NAME());
		attributes.put("CUSTOMER_LAST_NAME", getCUSTOMER_LAST_NAME());
		attributes.put("CUSTOMER_MIDDLE_NAME", getCUSTOMER_MIDDLE_NAME());
		attributes.put("CUSTOMER_DATE_OF_BIRTH", getCUSTOMER_DATE_OF_BIRTH());
		attributes.put("CUSTOMER_EMAIL_ADDR", getCUSTOMER_EMAIL_ADDR());
		attributes.put("PRIMARY_ADDRESS_LINE_1", getPRIMARY_ADDRESS_LINE_1());
		attributes.put("PRIMARY_ADDRESS_LINE_2", getPRIMARY_ADDRESS_LINE_2());
		attributes.put("PRIMARY_ADDRESS_LINE_3", getPRIMARY_ADDRESS_LINE_3());
		attributes.put("PRIMARY_ADDRESS_CITY", getPRIMARY_ADDRESS_CITY());
		attributes.put("PRIMARY_ADDRESS_STATE", getPRIMARY_ADDRESS_STATE());
		attributes.put("PIMARY_ADDRESS_PINCODE", getPIMARY_ADDRESS_PINCODE());
		attributes.put("PHONE_NUMBER_1", getPHONE_NUMBER_1());
		attributes.put("PHONE_NUMBER_2", getPHONE_NUMBER_2());
		attributes.put("PHONE_NUMBER_3", getPHONE_NUMBER_3());
		attributes.put("LOGIN_NAME", getLOGIN_NAME());
		attributes.put("GENDER", getGENDER());
		attributes.put("MARITAL_STATUS", getMARITAL_STATUS());
		attributes.put("COUNTRY", getCOUNTRY());
		attributes.put("PRIMARY_ADDRESS_STATE_ID", getPRIMARY_ADDRESS_STATE_ID());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String CUSTOMER_ID = (String)attributes.get("CUSTOMER_ID");

		if (CUSTOMER_ID != null) {
			setCUSTOMER_ID(CUSTOMER_ID);
		}

		String CUSTOMER_SALUTATION = (String)attributes.get(
				"CUSTOMER_SALUTATION");

		if (CUSTOMER_SALUTATION != null) {
			setCUSTOMER_SALUTATION(CUSTOMER_SALUTATION);
		}

		String CUSTOMER_FIRST_NAME = (String)attributes.get(
				"CUSTOMER_FIRST_NAME");

		if (CUSTOMER_FIRST_NAME != null) {
			setCUSTOMER_FIRST_NAME(CUSTOMER_FIRST_NAME);
		}

		String CUSTOMER_LAST_NAME = (String)attributes.get("CUSTOMER_LAST_NAME");

		if (CUSTOMER_LAST_NAME != null) {
			setCUSTOMER_LAST_NAME(CUSTOMER_LAST_NAME);
		}

		String CUSTOMER_MIDDLE_NAME = (String)attributes.get(
				"CUSTOMER_MIDDLE_NAME");

		if (CUSTOMER_MIDDLE_NAME != null) {
			setCUSTOMER_MIDDLE_NAME(CUSTOMER_MIDDLE_NAME);
		}

		String CUSTOMER_DATE_OF_BIRTH = (String)attributes.get(
				"CUSTOMER_DATE_OF_BIRTH");

		if (CUSTOMER_DATE_OF_BIRTH != null) {
			setCUSTOMER_DATE_OF_BIRTH(CUSTOMER_DATE_OF_BIRTH);
		}

		String CUSTOMER_EMAIL_ADDR = (String)attributes.get(
				"CUSTOMER_EMAIL_ADDR");

		if (CUSTOMER_EMAIL_ADDR != null) {
			setCUSTOMER_EMAIL_ADDR(CUSTOMER_EMAIL_ADDR);
		}

		String PRIMARY_ADDRESS_LINE_1 = (String)attributes.get(
				"PRIMARY_ADDRESS_LINE_1");

		if (PRIMARY_ADDRESS_LINE_1 != null) {
			setPRIMARY_ADDRESS_LINE_1(PRIMARY_ADDRESS_LINE_1);
		}

		String PRIMARY_ADDRESS_LINE_2 = (String)attributes.get(
				"PRIMARY_ADDRESS_LINE_2");

		if (PRIMARY_ADDRESS_LINE_2 != null) {
			setPRIMARY_ADDRESS_LINE_2(PRIMARY_ADDRESS_LINE_2);
		}

		String PRIMARY_ADDRESS_LINE_3 = (String)attributes.get(
				"PRIMARY_ADDRESS_LINE_3");

		if (PRIMARY_ADDRESS_LINE_3 != null) {
			setPRIMARY_ADDRESS_LINE_3(PRIMARY_ADDRESS_LINE_3);
		}

		String PRIMARY_ADDRESS_CITY = (String)attributes.get(
				"PRIMARY_ADDRESS_CITY");

		if (PRIMARY_ADDRESS_CITY != null) {
			setPRIMARY_ADDRESS_CITY(PRIMARY_ADDRESS_CITY);
		}

		String PRIMARY_ADDRESS_STATE = (String)attributes.get(
				"PRIMARY_ADDRESS_STATE");

		if (PRIMARY_ADDRESS_STATE != null) {
			setPRIMARY_ADDRESS_STATE(PRIMARY_ADDRESS_STATE);
		}

		Integer PIMARY_ADDRESS_PINCODE = (Integer)attributes.get(
				"PIMARY_ADDRESS_PINCODE");

		if (PIMARY_ADDRESS_PINCODE != null) {
			setPIMARY_ADDRESS_PINCODE(PIMARY_ADDRESS_PINCODE);
		}

		String PHONE_NUMBER_1 = (String)attributes.get("PHONE_NUMBER_1");

		if (PHONE_NUMBER_1 != null) {
			setPHONE_NUMBER_1(PHONE_NUMBER_1);
		}

		String PHONE_NUMBER_2 = (String)attributes.get("PHONE_NUMBER_2");

		if (PHONE_NUMBER_2 != null) {
			setPHONE_NUMBER_2(PHONE_NUMBER_2);
		}

		String PHONE_NUMBER_3 = (String)attributes.get("PHONE_NUMBER_3");

		if (PHONE_NUMBER_3 != null) {
			setPHONE_NUMBER_3(PHONE_NUMBER_3);
		}

		String LOGIN_NAME = (String)attributes.get("LOGIN_NAME");

		if (LOGIN_NAME != null) {
			setLOGIN_NAME(LOGIN_NAME);
		}

		String GENDER = (String)attributes.get("GENDER");

		if (GENDER != null) {
			setGENDER(GENDER);
		}

		String MARITAL_STATUS = (String)attributes.get("MARITAL_STATUS");

		if (MARITAL_STATUS != null) {
			setMARITAL_STATUS(MARITAL_STATUS);
		}

		String COUNTRY = (String)attributes.get("COUNTRY");

		if (COUNTRY != null) {
			setCOUNTRY(COUNTRY);
		}

		Integer PRIMARY_ADDRESS_STATE_ID = (Integer)attributes.get(
				"PRIMARY_ADDRESS_STATE_ID");

		if (PRIMARY_ADDRESS_STATE_ID != null) {
			setPRIMARY_ADDRESS_STATE_ID(PRIMARY_ADDRESS_STATE_ID);
		}
	}

	@Override
	public String getCUSTOMER_ID() {
		if (_CUSTOMER_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _CUSTOMER_ID;
		}
	}

	@Override
	public void setCUSTOMER_ID(String CUSTOMER_ID) {
		_CUSTOMER_ID = CUSTOMER_ID;
	}

	@Override
	public String getCUSTOMER_SALUTATION() {
		if (_CUSTOMER_SALUTATION == null) {
			return StringPool.BLANK;
		}
		else {
			return _CUSTOMER_SALUTATION;
		}
	}

	@Override
	public void setCUSTOMER_SALUTATION(String CUSTOMER_SALUTATION) {
		_CUSTOMER_SALUTATION = CUSTOMER_SALUTATION;
	}

	@Override
	public String getCUSTOMER_FIRST_NAME() {
		if (_CUSTOMER_FIRST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _CUSTOMER_FIRST_NAME;
		}
	}

	@Override
	public void setCUSTOMER_FIRST_NAME(String CUSTOMER_FIRST_NAME) {
		_CUSTOMER_FIRST_NAME = CUSTOMER_FIRST_NAME;
	}

	@Override
	public String getCUSTOMER_LAST_NAME() {
		if (_CUSTOMER_LAST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _CUSTOMER_LAST_NAME;
		}
	}

	@Override
	public void setCUSTOMER_LAST_NAME(String CUSTOMER_LAST_NAME) {
		_CUSTOMER_LAST_NAME = CUSTOMER_LAST_NAME;
	}

	@Override
	public String getCUSTOMER_MIDDLE_NAME() {
		if (_CUSTOMER_MIDDLE_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _CUSTOMER_MIDDLE_NAME;
		}
	}

	@Override
	public void setCUSTOMER_MIDDLE_NAME(String CUSTOMER_MIDDLE_NAME) {
		_CUSTOMER_MIDDLE_NAME = CUSTOMER_MIDDLE_NAME;
	}

	@Override
	public String getCUSTOMER_DATE_OF_BIRTH() {
		if (_CUSTOMER_DATE_OF_BIRTH == null) {
			return StringPool.BLANK;
		}
		else {
			return _CUSTOMER_DATE_OF_BIRTH;
		}
	}

	@Override
	public void setCUSTOMER_DATE_OF_BIRTH(String CUSTOMER_DATE_OF_BIRTH) {
		_CUSTOMER_DATE_OF_BIRTH = CUSTOMER_DATE_OF_BIRTH;
	}

	@Override
	public String getCUSTOMER_EMAIL_ADDR() {
		if (_CUSTOMER_EMAIL_ADDR == null) {
			return StringPool.BLANK;
		}
		else {
			return _CUSTOMER_EMAIL_ADDR;
		}
	}

	@Override
	public void setCUSTOMER_EMAIL_ADDR(String CUSTOMER_EMAIL_ADDR) {
		_CUSTOMER_EMAIL_ADDR = CUSTOMER_EMAIL_ADDR;
	}

	@Override
	public String getPRIMARY_ADDRESS_LINE_1() {
		if (_PRIMARY_ADDRESS_LINE_1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _PRIMARY_ADDRESS_LINE_1;
		}
	}

	@Override
	public void setPRIMARY_ADDRESS_LINE_1(String PRIMARY_ADDRESS_LINE_1) {
		_PRIMARY_ADDRESS_LINE_1 = PRIMARY_ADDRESS_LINE_1;
	}

	@Override
	public String getPRIMARY_ADDRESS_LINE_2() {
		if (_PRIMARY_ADDRESS_LINE_2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _PRIMARY_ADDRESS_LINE_2;
		}
	}

	@Override
	public void setPRIMARY_ADDRESS_LINE_2(String PRIMARY_ADDRESS_LINE_2) {
		_PRIMARY_ADDRESS_LINE_2 = PRIMARY_ADDRESS_LINE_2;
	}

	@Override
	public String getPRIMARY_ADDRESS_LINE_3() {
		if (_PRIMARY_ADDRESS_LINE_3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _PRIMARY_ADDRESS_LINE_3;
		}
	}

	@Override
	public void setPRIMARY_ADDRESS_LINE_3(String PRIMARY_ADDRESS_LINE_3) {
		_PRIMARY_ADDRESS_LINE_3 = PRIMARY_ADDRESS_LINE_3;
	}

	@Override
	public String getPRIMARY_ADDRESS_CITY() {
		if (_PRIMARY_ADDRESS_CITY == null) {
			return StringPool.BLANK;
		}
		else {
			return _PRIMARY_ADDRESS_CITY;
		}
	}

	@Override
	public void setPRIMARY_ADDRESS_CITY(String PRIMARY_ADDRESS_CITY) {
		_PRIMARY_ADDRESS_CITY = PRIMARY_ADDRESS_CITY;
	}

	@Override
	public String getPRIMARY_ADDRESS_STATE() {
		if (_PRIMARY_ADDRESS_STATE == null) {
			return StringPool.BLANK;
		}
		else {
			return _PRIMARY_ADDRESS_STATE;
		}
	}

	@Override
	public void setPRIMARY_ADDRESS_STATE(String PRIMARY_ADDRESS_STATE) {
		_PRIMARY_ADDRESS_STATE = PRIMARY_ADDRESS_STATE;
	}

	@Override
	public int getPIMARY_ADDRESS_PINCODE() {
		return _PIMARY_ADDRESS_PINCODE;
	}

	@Override
	public void setPIMARY_ADDRESS_PINCODE(int PIMARY_ADDRESS_PINCODE) {
		_PIMARY_ADDRESS_PINCODE = PIMARY_ADDRESS_PINCODE;
	}

	@Override
	public String getPHONE_NUMBER_1() {
		if (_PHONE_NUMBER_1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _PHONE_NUMBER_1;
		}
	}

	@Override
	public void setPHONE_NUMBER_1(String PHONE_NUMBER_1) {
		_PHONE_NUMBER_1 = PHONE_NUMBER_1;
	}

	@Override
	public String getPHONE_NUMBER_2() {
		if (_PHONE_NUMBER_2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _PHONE_NUMBER_2;
		}
	}

	@Override
	public void setPHONE_NUMBER_2(String PHONE_NUMBER_2) {
		_PHONE_NUMBER_2 = PHONE_NUMBER_2;
	}

	@Override
	public String getPHONE_NUMBER_3() {
		if (_PHONE_NUMBER_3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _PHONE_NUMBER_3;
		}
	}

	@Override
	public void setPHONE_NUMBER_3(String PHONE_NUMBER_3) {
		_PHONE_NUMBER_3 = PHONE_NUMBER_3;
	}

	@Override
	public String getLOGIN_NAME() {
		if (_LOGIN_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _LOGIN_NAME;
		}
	}

	@Override
	public void setLOGIN_NAME(String LOGIN_NAME) {
		_LOGIN_NAME = LOGIN_NAME;
	}

	@Override
	public String getGENDER() {
		if (_GENDER == null) {
			return StringPool.BLANK;
		}
		else {
			return _GENDER;
		}
	}

	@Override
	public void setGENDER(String GENDER) {
		_GENDER = GENDER;
	}

	@Override
	public String getMARITAL_STATUS() {
		if (_MARITAL_STATUS == null) {
			return StringPool.BLANK;
		}
		else {
			return _MARITAL_STATUS;
		}
	}

	@Override
	public void setMARITAL_STATUS(String MARITAL_STATUS) {
		_MARITAL_STATUS = MARITAL_STATUS;
	}

	@Override
	public String getCOUNTRY() {
		if (_COUNTRY == null) {
			return StringPool.BLANK;
		}
		else {
			return _COUNTRY;
		}
	}

	@Override
	public void setCOUNTRY(String COUNTRY) {
		_COUNTRY = COUNTRY;
	}

	@Override
	public int getPRIMARY_ADDRESS_STATE_ID() {
		return _PRIMARY_ADDRESS_STATE_ID;
	}

	@Override
	public void setPRIMARY_ADDRESS_STATE_ID(int PRIMARY_ADDRESS_STATE_ID) {
		_PRIMARY_ADDRESS_STATE_ID = PRIMARY_ADDRESS_STATE_ID;
	}

	@Override
	public CustomerTemp toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CustomerTemp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CustomerTempImpl customerTempImpl = new CustomerTempImpl();

		customerTempImpl.setCUSTOMER_ID(getCUSTOMER_ID());
		customerTempImpl.setCUSTOMER_SALUTATION(getCUSTOMER_SALUTATION());
		customerTempImpl.setCUSTOMER_FIRST_NAME(getCUSTOMER_FIRST_NAME());
		customerTempImpl.setCUSTOMER_LAST_NAME(getCUSTOMER_LAST_NAME());
		customerTempImpl.setCUSTOMER_MIDDLE_NAME(getCUSTOMER_MIDDLE_NAME());
		customerTempImpl.setCUSTOMER_DATE_OF_BIRTH(getCUSTOMER_DATE_OF_BIRTH());
		customerTempImpl.setCUSTOMER_EMAIL_ADDR(getCUSTOMER_EMAIL_ADDR());
		customerTempImpl.setPRIMARY_ADDRESS_LINE_1(getPRIMARY_ADDRESS_LINE_1());
		customerTempImpl.setPRIMARY_ADDRESS_LINE_2(getPRIMARY_ADDRESS_LINE_2());
		customerTempImpl.setPRIMARY_ADDRESS_LINE_3(getPRIMARY_ADDRESS_LINE_3());
		customerTempImpl.setPRIMARY_ADDRESS_CITY(getPRIMARY_ADDRESS_CITY());
		customerTempImpl.setPRIMARY_ADDRESS_STATE(getPRIMARY_ADDRESS_STATE());
		customerTempImpl.setPIMARY_ADDRESS_PINCODE(getPIMARY_ADDRESS_PINCODE());
		customerTempImpl.setPHONE_NUMBER_1(getPHONE_NUMBER_1());
		customerTempImpl.setPHONE_NUMBER_2(getPHONE_NUMBER_2());
		customerTempImpl.setPHONE_NUMBER_3(getPHONE_NUMBER_3());
		customerTempImpl.setLOGIN_NAME(getLOGIN_NAME());
		customerTempImpl.setGENDER(getGENDER());
		customerTempImpl.setMARITAL_STATUS(getMARITAL_STATUS());
		customerTempImpl.setCOUNTRY(getCOUNTRY());
		customerTempImpl.setPRIMARY_ADDRESS_STATE_ID(getPRIMARY_ADDRESS_STATE_ID());

		customerTempImpl.resetOriginalValues();

		return customerTempImpl;
	}

	@Override
	public int compareTo(CustomerTemp customerTemp) {
		String primaryKey = customerTemp.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CustomerTemp)) {
			return false;
		}

		CustomerTemp customerTemp = (CustomerTemp)obj;

		String primaryKey = customerTemp.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CustomerTemp> toCacheModel() {
		CustomerTempCacheModel customerTempCacheModel = new CustomerTempCacheModel();

		customerTempCacheModel.CUSTOMER_ID = getCUSTOMER_ID();

		String CUSTOMER_ID = customerTempCacheModel.CUSTOMER_ID;

		if ((CUSTOMER_ID != null) && (CUSTOMER_ID.length() == 0)) {
			customerTempCacheModel.CUSTOMER_ID = null;
		}

		customerTempCacheModel.CUSTOMER_SALUTATION = getCUSTOMER_SALUTATION();

		String CUSTOMER_SALUTATION = customerTempCacheModel.CUSTOMER_SALUTATION;

		if ((CUSTOMER_SALUTATION != null) &&
				(CUSTOMER_SALUTATION.length() == 0)) {
			customerTempCacheModel.CUSTOMER_SALUTATION = null;
		}

		customerTempCacheModel.CUSTOMER_FIRST_NAME = getCUSTOMER_FIRST_NAME();

		String CUSTOMER_FIRST_NAME = customerTempCacheModel.CUSTOMER_FIRST_NAME;

		if ((CUSTOMER_FIRST_NAME != null) &&
				(CUSTOMER_FIRST_NAME.length() == 0)) {
			customerTempCacheModel.CUSTOMER_FIRST_NAME = null;
		}

		customerTempCacheModel.CUSTOMER_LAST_NAME = getCUSTOMER_LAST_NAME();

		String CUSTOMER_LAST_NAME = customerTempCacheModel.CUSTOMER_LAST_NAME;

		if ((CUSTOMER_LAST_NAME != null) && (CUSTOMER_LAST_NAME.length() == 0)) {
			customerTempCacheModel.CUSTOMER_LAST_NAME = null;
		}

		customerTempCacheModel.CUSTOMER_MIDDLE_NAME = getCUSTOMER_MIDDLE_NAME();

		String CUSTOMER_MIDDLE_NAME = customerTempCacheModel.CUSTOMER_MIDDLE_NAME;

		if ((CUSTOMER_MIDDLE_NAME != null) &&
				(CUSTOMER_MIDDLE_NAME.length() == 0)) {
			customerTempCacheModel.CUSTOMER_MIDDLE_NAME = null;
		}

		customerTempCacheModel.CUSTOMER_DATE_OF_BIRTH = getCUSTOMER_DATE_OF_BIRTH();

		String CUSTOMER_DATE_OF_BIRTH = customerTempCacheModel.CUSTOMER_DATE_OF_BIRTH;

		if ((CUSTOMER_DATE_OF_BIRTH != null) &&
				(CUSTOMER_DATE_OF_BIRTH.length() == 0)) {
			customerTempCacheModel.CUSTOMER_DATE_OF_BIRTH = null;
		}

		customerTempCacheModel.CUSTOMER_EMAIL_ADDR = getCUSTOMER_EMAIL_ADDR();

		String CUSTOMER_EMAIL_ADDR = customerTempCacheModel.CUSTOMER_EMAIL_ADDR;

		if ((CUSTOMER_EMAIL_ADDR != null) &&
				(CUSTOMER_EMAIL_ADDR.length() == 0)) {
			customerTempCacheModel.CUSTOMER_EMAIL_ADDR = null;
		}

		customerTempCacheModel.PRIMARY_ADDRESS_LINE_1 = getPRIMARY_ADDRESS_LINE_1();

		String PRIMARY_ADDRESS_LINE_1 = customerTempCacheModel.PRIMARY_ADDRESS_LINE_1;

		if ((PRIMARY_ADDRESS_LINE_1 != null) &&
				(PRIMARY_ADDRESS_LINE_1.length() == 0)) {
			customerTempCacheModel.PRIMARY_ADDRESS_LINE_1 = null;
		}

		customerTempCacheModel.PRIMARY_ADDRESS_LINE_2 = getPRIMARY_ADDRESS_LINE_2();

		String PRIMARY_ADDRESS_LINE_2 = customerTempCacheModel.PRIMARY_ADDRESS_LINE_2;

		if ((PRIMARY_ADDRESS_LINE_2 != null) &&
				(PRIMARY_ADDRESS_LINE_2.length() == 0)) {
			customerTempCacheModel.PRIMARY_ADDRESS_LINE_2 = null;
		}

		customerTempCacheModel.PRIMARY_ADDRESS_LINE_3 = getPRIMARY_ADDRESS_LINE_3();

		String PRIMARY_ADDRESS_LINE_3 = customerTempCacheModel.PRIMARY_ADDRESS_LINE_3;

		if ((PRIMARY_ADDRESS_LINE_3 != null) &&
				(PRIMARY_ADDRESS_LINE_3.length() == 0)) {
			customerTempCacheModel.PRIMARY_ADDRESS_LINE_3 = null;
		}

		customerTempCacheModel.PRIMARY_ADDRESS_CITY = getPRIMARY_ADDRESS_CITY();

		String PRIMARY_ADDRESS_CITY = customerTempCacheModel.PRIMARY_ADDRESS_CITY;

		if ((PRIMARY_ADDRESS_CITY != null) &&
				(PRIMARY_ADDRESS_CITY.length() == 0)) {
			customerTempCacheModel.PRIMARY_ADDRESS_CITY = null;
		}

		customerTempCacheModel.PRIMARY_ADDRESS_STATE = getPRIMARY_ADDRESS_STATE();

		String PRIMARY_ADDRESS_STATE = customerTempCacheModel.PRIMARY_ADDRESS_STATE;

		if ((PRIMARY_ADDRESS_STATE != null) &&
				(PRIMARY_ADDRESS_STATE.length() == 0)) {
			customerTempCacheModel.PRIMARY_ADDRESS_STATE = null;
		}

		customerTempCacheModel.PIMARY_ADDRESS_PINCODE = getPIMARY_ADDRESS_PINCODE();

		customerTempCacheModel.PHONE_NUMBER_1 = getPHONE_NUMBER_1();

		String PHONE_NUMBER_1 = customerTempCacheModel.PHONE_NUMBER_1;

		if ((PHONE_NUMBER_1 != null) && (PHONE_NUMBER_1.length() == 0)) {
			customerTempCacheModel.PHONE_NUMBER_1 = null;
		}

		customerTempCacheModel.PHONE_NUMBER_2 = getPHONE_NUMBER_2();

		String PHONE_NUMBER_2 = customerTempCacheModel.PHONE_NUMBER_2;

		if ((PHONE_NUMBER_2 != null) && (PHONE_NUMBER_2.length() == 0)) {
			customerTempCacheModel.PHONE_NUMBER_2 = null;
		}

		customerTempCacheModel.PHONE_NUMBER_3 = getPHONE_NUMBER_3();

		String PHONE_NUMBER_3 = customerTempCacheModel.PHONE_NUMBER_3;

		if ((PHONE_NUMBER_3 != null) && (PHONE_NUMBER_3.length() == 0)) {
			customerTempCacheModel.PHONE_NUMBER_3 = null;
		}

		customerTempCacheModel.LOGIN_NAME = getLOGIN_NAME();

		String LOGIN_NAME = customerTempCacheModel.LOGIN_NAME;

		if ((LOGIN_NAME != null) && (LOGIN_NAME.length() == 0)) {
			customerTempCacheModel.LOGIN_NAME = null;
		}

		customerTempCacheModel.GENDER = getGENDER();

		String GENDER = customerTempCacheModel.GENDER;

		if ((GENDER != null) && (GENDER.length() == 0)) {
			customerTempCacheModel.GENDER = null;
		}

		customerTempCacheModel.MARITAL_STATUS = getMARITAL_STATUS();

		String MARITAL_STATUS = customerTempCacheModel.MARITAL_STATUS;

		if ((MARITAL_STATUS != null) && (MARITAL_STATUS.length() == 0)) {
			customerTempCacheModel.MARITAL_STATUS = null;
		}

		customerTempCacheModel.COUNTRY = getCOUNTRY();

		String COUNTRY = customerTempCacheModel.COUNTRY;

		if ((COUNTRY != null) && (COUNTRY.length() == 0)) {
			customerTempCacheModel.COUNTRY = null;
		}

		customerTempCacheModel.PRIMARY_ADDRESS_STATE_ID = getPRIMARY_ADDRESS_STATE_ID();

		return customerTempCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(43);

		sb.append("{CUSTOMER_ID=");
		sb.append(getCUSTOMER_ID());
		sb.append(", CUSTOMER_SALUTATION=");
		sb.append(getCUSTOMER_SALUTATION());
		sb.append(", CUSTOMER_FIRST_NAME=");
		sb.append(getCUSTOMER_FIRST_NAME());
		sb.append(", CUSTOMER_LAST_NAME=");
		sb.append(getCUSTOMER_LAST_NAME());
		sb.append(", CUSTOMER_MIDDLE_NAME=");
		sb.append(getCUSTOMER_MIDDLE_NAME());
		sb.append(", CUSTOMER_DATE_OF_BIRTH=");
		sb.append(getCUSTOMER_DATE_OF_BIRTH());
		sb.append(", CUSTOMER_EMAIL_ADDR=");
		sb.append(getCUSTOMER_EMAIL_ADDR());
		sb.append(", PRIMARY_ADDRESS_LINE_1=");
		sb.append(getPRIMARY_ADDRESS_LINE_1());
		sb.append(", PRIMARY_ADDRESS_LINE_2=");
		sb.append(getPRIMARY_ADDRESS_LINE_2());
		sb.append(", PRIMARY_ADDRESS_LINE_3=");
		sb.append(getPRIMARY_ADDRESS_LINE_3());
		sb.append(", PRIMARY_ADDRESS_CITY=");
		sb.append(getPRIMARY_ADDRESS_CITY());
		sb.append(", PRIMARY_ADDRESS_STATE=");
		sb.append(getPRIMARY_ADDRESS_STATE());
		sb.append(", PIMARY_ADDRESS_PINCODE=");
		sb.append(getPIMARY_ADDRESS_PINCODE());
		sb.append(", PHONE_NUMBER_1=");
		sb.append(getPHONE_NUMBER_1());
		sb.append(", PHONE_NUMBER_2=");
		sb.append(getPHONE_NUMBER_2());
		sb.append(", PHONE_NUMBER_3=");
		sb.append(getPHONE_NUMBER_3());
		sb.append(", LOGIN_NAME=");
		sb.append(getLOGIN_NAME());
		sb.append(", GENDER=");
		sb.append(getGENDER());
		sb.append(", MARITAL_STATUS=");
		sb.append(getMARITAL_STATUS());
		sb.append(", COUNTRY=");
		sb.append(getCOUNTRY());
		sb.append(", PRIMARY_ADDRESS_STATE_ID=");
		sb.append(getPRIMARY_ADDRESS_STATE_ID());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(67);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.CustomerTemp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>CUSTOMER_ID</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUSTOMER_SALUTATION</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_SALUTATION());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUSTOMER_FIRST_NAME</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_FIRST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUSTOMER_LAST_NAME</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_LAST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUSTOMER_MIDDLE_NAME</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_MIDDLE_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUSTOMER_DATE_OF_BIRTH</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_DATE_OF_BIRTH());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUSTOMER_EMAIL_ADDR</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_EMAIL_ADDR());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PRIMARY_ADDRESS_LINE_1</column-name><column-value><![CDATA[");
		sb.append(getPRIMARY_ADDRESS_LINE_1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PRIMARY_ADDRESS_LINE_2</column-name><column-value><![CDATA[");
		sb.append(getPRIMARY_ADDRESS_LINE_2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PRIMARY_ADDRESS_LINE_3</column-name><column-value><![CDATA[");
		sb.append(getPRIMARY_ADDRESS_LINE_3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PRIMARY_ADDRESS_CITY</column-name><column-value><![CDATA[");
		sb.append(getPRIMARY_ADDRESS_CITY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PRIMARY_ADDRESS_STATE</column-name><column-value><![CDATA[");
		sb.append(getPRIMARY_ADDRESS_STATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PIMARY_ADDRESS_PINCODE</column-name><column-value><![CDATA[");
		sb.append(getPIMARY_ADDRESS_PINCODE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PHONE_NUMBER_1</column-name><column-value><![CDATA[");
		sb.append(getPHONE_NUMBER_1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PHONE_NUMBER_2</column-name><column-value><![CDATA[");
		sb.append(getPHONE_NUMBER_2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PHONE_NUMBER_3</column-name><column-value><![CDATA[");
		sb.append(getPHONE_NUMBER_3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LOGIN_NAME</column-name><column-value><![CDATA[");
		sb.append(getLOGIN_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>GENDER</column-name><column-value><![CDATA[");
		sb.append(getGENDER());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MARITAL_STATUS</column-name><column-value><![CDATA[");
		sb.append(getMARITAL_STATUS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>COUNTRY</column-name><column-value><![CDATA[");
		sb.append(getCOUNTRY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PRIMARY_ADDRESS_STATE_ID</column-name><column-value><![CDATA[");
		sb.append(getPRIMARY_ADDRESS_STATE_ID());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CustomerTemp.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CustomerTemp.class
		};
	private String _CUSTOMER_ID;
	private String _CUSTOMER_SALUTATION;
	private String _CUSTOMER_FIRST_NAME;
	private String _CUSTOMER_LAST_NAME;
	private String _CUSTOMER_MIDDLE_NAME;
	private String _CUSTOMER_DATE_OF_BIRTH;
	private String _CUSTOMER_EMAIL_ADDR;
	private String _PRIMARY_ADDRESS_LINE_1;
	private String _PRIMARY_ADDRESS_LINE_2;
	private String _PRIMARY_ADDRESS_LINE_3;
	private String _PRIMARY_ADDRESS_CITY;
	private String _PRIMARY_ADDRESS_STATE;
	private int _PIMARY_ADDRESS_PINCODE;
	private String _PHONE_NUMBER_1;
	private String _PHONE_NUMBER_2;
	private String _PHONE_NUMBER_3;
	private String _LOGIN_NAME;
	private String _GENDER;
	private String _MARITAL_STATUS;
	private String _COUNTRY;
	private int _PRIMARY_ADDRESS_STATE_ID;
	private CustomerTemp _escapedModel;
}