/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.CustomerMobileNumbers;
import com.ifli.rapid.model.CustomerMobileNumbersModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CustomerMobileNumbers service. Represents a row in the &quot;customer_mobile_numbers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.CustomerMobileNumbersModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomerMobileNumbersImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see CustomerMobileNumbersImpl
 * @see com.ifli.rapid.model.CustomerMobileNumbers
 * @see com.ifli.rapid.model.CustomerMobileNumbersModel
 * @generated
 */
public class CustomerMobileNumbersModelImpl extends BaseModelImpl<CustomerMobileNumbers>
	implements CustomerMobileNumbersModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a customer mobile numbers model instance should use the {@link com.ifli.rapid.model.CustomerMobileNumbers} interface instead.
	 */
	public static final String TABLE_NAME = "customer_mobile_numbers";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "CUSTOMER_ID", Types.INTEGER },
			{ "MOBILE_NUMBER", Types.VARCHAR },
			{ "INSERTED_BY", Types.VARCHAR },
			{ "INSERTED_DATE", Types.TIMESTAMP },
			{ "UPDATED_BY", Types.VARCHAR },
			{ "UPDATED_DATE", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table customer_mobile_numbers (ID INTEGER not null primary key,CUSTOMER_ID INTEGER,MOBILE_NUMBER VARCHAR(75) null,INSERTED_BY VARCHAR(75) null,INSERTED_DATE DATE null,UPDATED_BY VARCHAR(75) null,UPDATED_DATE DATE null)";
	public static final String TABLE_SQL_DROP = "drop table customer_mobile_numbers";
	public static final String ORDER_BY_JPQL = " ORDER BY customerMobileNumbers.ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY customer_mobile_numbers.ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.CustomerMobileNumbers"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.CustomerMobileNumbers"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.CustomerMobileNumbers"));

	public CustomerMobileNumbersModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _ID;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CustomerMobileNumbers.class;
	}

	@Override
	public String getModelClassName() {
		return CustomerMobileNumbers.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ID", getID());
		attributes.put("CUSTOMER_ID", getCUSTOMER_ID());
		attributes.put("MOBILE_NUMBER", getMOBILE_NUMBER());
		attributes.put("INSERTED_BY", getINSERTED_BY());
		attributes.put("INSERTED_DATE", getINSERTED_DATE());
		attributes.put("UPDATED_BY", getUPDATED_BY());
		attributes.put("UPDATED_DATE", getUPDATED_DATE());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer ID = (Integer)attributes.get("ID");

		if (ID != null) {
			setID(ID);
		}

		Integer CUSTOMER_ID = (Integer)attributes.get("CUSTOMER_ID");

		if (CUSTOMER_ID != null) {
			setCUSTOMER_ID(CUSTOMER_ID);
		}

		String MOBILE_NUMBER = (String)attributes.get("MOBILE_NUMBER");

		if (MOBILE_NUMBER != null) {
			setMOBILE_NUMBER(MOBILE_NUMBER);
		}

		String INSERTED_BY = (String)attributes.get("INSERTED_BY");

		if (INSERTED_BY != null) {
			setINSERTED_BY(INSERTED_BY);
		}

		Date INSERTED_DATE = (Date)attributes.get("INSERTED_DATE");

		if (INSERTED_DATE != null) {
			setINSERTED_DATE(INSERTED_DATE);
		}

		String UPDATED_BY = (String)attributes.get("UPDATED_BY");

		if (UPDATED_BY != null) {
			setUPDATED_BY(UPDATED_BY);
		}

		Date UPDATED_DATE = (Date)attributes.get("UPDATED_DATE");

		if (UPDATED_DATE != null) {
			setUPDATED_DATE(UPDATED_DATE);
		}
	}

	@Override
	public int getID() {
		return _ID;
	}

	@Override
	public void setID(int ID) {
		_ID = ID;
	}

	@Override
	public int getCUSTOMER_ID() {
		return _CUSTOMER_ID;
	}

	@Override
	public void setCUSTOMER_ID(int CUSTOMER_ID) {
		_CUSTOMER_ID = CUSTOMER_ID;
	}

	@Override
	public String getMOBILE_NUMBER() {
		if (_MOBILE_NUMBER == null) {
			return StringPool.BLANK;
		}
		else {
			return _MOBILE_NUMBER;
		}
	}

	@Override
	public void setMOBILE_NUMBER(String MOBILE_NUMBER) {
		_MOBILE_NUMBER = MOBILE_NUMBER;
	}

	@Override
	public String getINSERTED_BY() {
		if (_INSERTED_BY == null) {
			return StringPool.BLANK;
		}
		else {
			return _INSERTED_BY;
		}
	}

	@Override
	public void setINSERTED_BY(String INSERTED_BY) {
		_INSERTED_BY = INSERTED_BY;
	}

	@Override
	public Date getINSERTED_DATE() {
		return _INSERTED_DATE;
	}

	@Override
	public void setINSERTED_DATE(Date INSERTED_DATE) {
		_INSERTED_DATE = INSERTED_DATE;
	}

	@Override
	public String getUPDATED_BY() {
		if (_UPDATED_BY == null) {
			return StringPool.BLANK;
		}
		else {
			return _UPDATED_BY;
		}
	}

	@Override
	public void setUPDATED_BY(String UPDATED_BY) {
		_UPDATED_BY = UPDATED_BY;
	}

	@Override
	public Date getUPDATED_DATE() {
		return _UPDATED_DATE;
	}

	@Override
	public void setUPDATED_DATE(Date UPDATED_DATE) {
		_UPDATED_DATE = UPDATED_DATE;
	}

	@Override
	public CustomerMobileNumbers toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CustomerMobileNumbers)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CustomerMobileNumbersImpl customerMobileNumbersImpl = new CustomerMobileNumbersImpl();

		customerMobileNumbersImpl.setID(getID());
		customerMobileNumbersImpl.setCUSTOMER_ID(getCUSTOMER_ID());
		customerMobileNumbersImpl.setMOBILE_NUMBER(getMOBILE_NUMBER());
		customerMobileNumbersImpl.setINSERTED_BY(getINSERTED_BY());
		customerMobileNumbersImpl.setINSERTED_DATE(getINSERTED_DATE());
		customerMobileNumbersImpl.setUPDATED_BY(getUPDATED_BY());
		customerMobileNumbersImpl.setUPDATED_DATE(getUPDATED_DATE());

		customerMobileNumbersImpl.resetOriginalValues();

		return customerMobileNumbersImpl;
	}

	@Override
	public int compareTo(CustomerMobileNumbers customerMobileNumbers) {
		int primaryKey = customerMobileNumbers.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CustomerMobileNumbers)) {
			return false;
		}

		CustomerMobileNumbers customerMobileNumbers = (CustomerMobileNumbers)obj;

		int primaryKey = customerMobileNumbers.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CustomerMobileNumbers> toCacheModel() {
		CustomerMobileNumbersCacheModel customerMobileNumbersCacheModel = new CustomerMobileNumbersCacheModel();

		customerMobileNumbersCacheModel.ID = getID();

		customerMobileNumbersCacheModel.CUSTOMER_ID = getCUSTOMER_ID();

		customerMobileNumbersCacheModel.MOBILE_NUMBER = getMOBILE_NUMBER();

		String MOBILE_NUMBER = customerMobileNumbersCacheModel.MOBILE_NUMBER;

		if ((MOBILE_NUMBER != null) && (MOBILE_NUMBER.length() == 0)) {
			customerMobileNumbersCacheModel.MOBILE_NUMBER = null;
		}

		customerMobileNumbersCacheModel.INSERTED_BY = getINSERTED_BY();

		String INSERTED_BY = customerMobileNumbersCacheModel.INSERTED_BY;

		if ((INSERTED_BY != null) && (INSERTED_BY.length() == 0)) {
			customerMobileNumbersCacheModel.INSERTED_BY = null;
		}

		Date INSERTED_DATE = getINSERTED_DATE();

		if (INSERTED_DATE != null) {
			customerMobileNumbersCacheModel.INSERTED_DATE = INSERTED_DATE.getTime();
		}
		else {
			customerMobileNumbersCacheModel.INSERTED_DATE = Long.MIN_VALUE;
		}

		customerMobileNumbersCacheModel.UPDATED_BY = getUPDATED_BY();

		String UPDATED_BY = customerMobileNumbersCacheModel.UPDATED_BY;

		if ((UPDATED_BY != null) && (UPDATED_BY.length() == 0)) {
			customerMobileNumbersCacheModel.UPDATED_BY = null;
		}

		Date UPDATED_DATE = getUPDATED_DATE();

		if (UPDATED_DATE != null) {
			customerMobileNumbersCacheModel.UPDATED_DATE = UPDATED_DATE.getTime();
		}
		else {
			customerMobileNumbersCacheModel.UPDATED_DATE = Long.MIN_VALUE;
		}

		return customerMobileNumbersCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{ID=");
		sb.append(getID());
		sb.append(", CUSTOMER_ID=");
		sb.append(getCUSTOMER_ID());
		sb.append(", MOBILE_NUMBER=");
		sb.append(getMOBILE_NUMBER());
		sb.append(", INSERTED_BY=");
		sb.append(getINSERTED_BY());
		sb.append(", INSERTED_DATE=");
		sb.append(getINSERTED_DATE());
		sb.append(", UPDATED_BY=");
		sb.append(getUPDATED_BY());
		sb.append(", UPDATED_DATE=");
		sb.append(getUPDATED_DATE());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.CustomerMobileNumbers");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ID</column-name><column-value><![CDATA[");
		sb.append(getID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUSTOMER_ID</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MOBILE_NUMBER</column-name><column-value><![CDATA[");
		sb.append(getMOBILE_NUMBER());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>INSERTED_BY</column-name><column-value><![CDATA[");
		sb.append(getINSERTED_BY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>INSERTED_DATE</column-name><column-value><![CDATA[");
		sb.append(getINSERTED_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATED_BY</column-name><column-value><![CDATA[");
		sb.append(getUPDATED_BY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATED_DATE</column-name><column-value><![CDATA[");
		sb.append(getUPDATED_DATE());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CustomerMobileNumbers.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CustomerMobileNumbers.class
		};
	private int _ID;
	private int _CUSTOMER_ID;
	private String _MOBILE_NUMBER;
	private String _INSERTED_BY;
	private Date _INSERTED_DATE;
	private String _UPDATED_BY;
	private Date _UPDATED_DATE;
	private CustomerMobileNumbers _escapedModel;
}