/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.PaymentOptionTypes;
import com.ifli.rapid.model.PaymentOptionTypesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PaymentOptionTypes service. Represents a row in the &quot;PaymentOptionTypes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.PaymentOptionTypesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PaymentOptionTypesImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PaymentOptionTypesImpl
 * @see com.ifli.rapid.model.PaymentOptionTypes
 * @see com.ifli.rapid.model.PaymentOptionTypesModel
 * @generated
 */
public class PaymentOptionTypesModelImpl extends BaseModelImpl<PaymentOptionTypes>
	implements PaymentOptionTypesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a payment option types model instance should use the {@link com.ifli.rapid.model.PaymentOptionTypes} interface instead.
	 */
	public static final String TABLE_NAME = "PaymentOptionTypes";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PaymentOptionTypesId", Types.VARCHAR },
			{ "PaymentOptionId", Types.VARCHAR },
			{ "OptionTypesKey", Types.VARCHAR },
			{ "IsActive", Types.BOOLEAN },
			{ "CreatedBy", Types.VARCHAR },
			{ "CreatedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "Priority", Types.INTEGER },
			{ "PaymentOptionTypeDesc", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table PaymentOptionTypes (PaymentOptionTypesId VARCHAR(75) not null primary key IDENTITY,PaymentOptionId VARCHAR(75) null,OptionTypesKey VARCHAR(75) null,IsActive BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null,Priority INTEGER,PaymentOptionTypeDesc VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table PaymentOptionTypes";
	public static final String ORDER_BY_JPQL = " ORDER BY paymentOptionTypes.Priority ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PaymentOptionTypes.Priority ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.PaymentOptionTypes"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.PaymentOptionTypes"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.PaymentOptionTypes"));

	public PaymentOptionTypesModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _PaymentOptionTypesId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setPaymentOptionTypesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PaymentOptionTypesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PaymentOptionTypes.class;
	}

	@Override
	public String getModelClassName() {
		return PaymentOptionTypes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PaymentOptionTypesId", getPaymentOptionTypesId());
		attributes.put("PaymentOptionId", getPaymentOptionId());
		attributes.put("OptionTypesKey", getOptionTypesKey());
		attributes.put("IsActive", getIsActive());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("CreatedDate", getCreatedDate());
		attributes.put("ModifiedBy", getModifiedBy());
		attributes.put("ModifiedDate", getModifiedDate());
		attributes.put("Priority", getPriority());
		attributes.put("PaymentOptionTypeDesc", getPaymentOptionTypeDesc());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String PaymentOptionTypesId = (String)attributes.get(
				"PaymentOptionTypesId");

		if (PaymentOptionTypesId != null) {
			setPaymentOptionTypesId(PaymentOptionTypesId);
		}

		String PaymentOptionId = (String)attributes.get("PaymentOptionId");

		if (PaymentOptionId != null) {
			setPaymentOptionId(PaymentOptionId);
		}

		String OptionTypesKey = (String)attributes.get("OptionTypesKey");

		if (OptionTypesKey != null) {
			setOptionTypesKey(OptionTypesKey);
		}

		Boolean IsActive = (Boolean)attributes.get("IsActive");

		if (IsActive != null) {
			setIsActive(IsActive);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date CreatedDate = (Date)attributes.get("CreatedDate");

		if (CreatedDate != null) {
			setCreatedDate(CreatedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}

		Integer Priority = (Integer)attributes.get("Priority");

		if (Priority != null) {
			setPriority(Priority);
		}

		String PaymentOptionTypeDesc = (String)attributes.get(
				"PaymentOptionTypeDesc");

		if (PaymentOptionTypeDesc != null) {
			setPaymentOptionTypeDesc(PaymentOptionTypeDesc);
		}
	}

	@Override
	public String getPaymentOptionTypesId() {
		if (_PaymentOptionTypesId == null) {
			return StringPool.BLANK;
		}
		else {
			return _PaymentOptionTypesId;
		}
	}

	@Override
	public void setPaymentOptionTypesId(String PaymentOptionTypesId) {
		_PaymentOptionTypesId = PaymentOptionTypesId;
	}

	@Override
	public String getPaymentOptionId() {
		if (_PaymentOptionId == null) {
			return StringPool.BLANK;
		}
		else {
			return _PaymentOptionId;
		}
	}

	@Override
	public void setPaymentOptionId(String PaymentOptionId) {
		_PaymentOptionId = PaymentOptionId;
	}

	@Override
	public String getOptionTypesKey() {
		if (_OptionTypesKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _OptionTypesKey;
		}
	}

	@Override
	public void setOptionTypesKey(String OptionTypesKey) {
		_OptionTypesKey = OptionTypesKey;
	}

	@Override
	public boolean getIsActive() {
		return _IsActive;
	}

	@Override
	public boolean isIsActive() {
		return _IsActive;
	}

	@Override
	public void setIsActive(boolean IsActive) {
		_IsActive = IsActive;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	@Override
	public int getPriority() {
		return _Priority;
	}

	@Override
	public void setPriority(int Priority) {
		_Priority = Priority;
	}

	@Override
	public String getPaymentOptionTypeDesc() {
		if (_PaymentOptionTypeDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _PaymentOptionTypeDesc;
		}
	}

	@Override
	public void setPaymentOptionTypeDesc(String PaymentOptionTypeDesc) {
		_PaymentOptionTypeDesc = PaymentOptionTypeDesc;
	}

	@Override
	public PaymentOptionTypes toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PaymentOptionTypes)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PaymentOptionTypesImpl paymentOptionTypesImpl = new PaymentOptionTypesImpl();

		paymentOptionTypesImpl.setPaymentOptionTypesId(getPaymentOptionTypesId());
		paymentOptionTypesImpl.setPaymentOptionId(getPaymentOptionId());
		paymentOptionTypesImpl.setOptionTypesKey(getOptionTypesKey());
		paymentOptionTypesImpl.setIsActive(getIsActive());
		paymentOptionTypesImpl.setCreatedBy(getCreatedBy());
		paymentOptionTypesImpl.setCreatedDate(getCreatedDate());
		paymentOptionTypesImpl.setModifiedBy(getModifiedBy());
		paymentOptionTypesImpl.setModifiedDate(getModifiedDate());
		paymentOptionTypesImpl.setPriority(getPriority());
		paymentOptionTypesImpl.setPaymentOptionTypeDesc(getPaymentOptionTypeDesc());

		paymentOptionTypesImpl.resetOriginalValues();

		return paymentOptionTypesImpl;
	}

	@Override
	public int compareTo(PaymentOptionTypes paymentOptionTypes) {
		int value = 0;

		if (getPriority() < paymentOptionTypes.getPriority()) {
			value = -1;
		}
		else if (getPriority() > paymentOptionTypes.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PaymentOptionTypes)) {
			return false;
		}

		PaymentOptionTypes paymentOptionTypes = (PaymentOptionTypes)obj;

		String primaryKey = paymentOptionTypes.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PaymentOptionTypes> toCacheModel() {
		PaymentOptionTypesCacheModel paymentOptionTypesCacheModel = new PaymentOptionTypesCacheModel();

		paymentOptionTypesCacheModel.PaymentOptionTypesId = getPaymentOptionTypesId();

		String PaymentOptionTypesId = paymentOptionTypesCacheModel.PaymentOptionTypesId;

		if ((PaymentOptionTypesId != null) &&
				(PaymentOptionTypesId.length() == 0)) {
			paymentOptionTypesCacheModel.PaymentOptionTypesId = null;
		}

		paymentOptionTypesCacheModel.PaymentOptionId = getPaymentOptionId();

		String PaymentOptionId = paymentOptionTypesCacheModel.PaymentOptionId;

		if ((PaymentOptionId != null) && (PaymentOptionId.length() == 0)) {
			paymentOptionTypesCacheModel.PaymentOptionId = null;
		}

		paymentOptionTypesCacheModel.OptionTypesKey = getOptionTypesKey();

		String OptionTypesKey = paymentOptionTypesCacheModel.OptionTypesKey;

		if ((OptionTypesKey != null) && (OptionTypesKey.length() == 0)) {
			paymentOptionTypesCacheModel.OptionTypesKey = null;
		}

		paymentOptionTypesCacheModel.IsActive = getIsActive();

		paymentOptionTypesCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = paymentOptionTypesCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			paymentOptionTypesCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			paymentOptionTypesCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			paymentOptionTypesCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		paymentOptionTypesCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = paymentOptionTypesCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			paymentOptionTypesCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			paymentOptionTypesCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			paymentOptionTypesCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		paymentOptionTypesCacheModel.Priority = getPriority();

		paymentOptionTypesCacheModel.PaymentOptionTypeDesc = getPaymentOptionTypeDesc();

		String PaymentOptionTypeDesc = paymentOptionTypesCacheModel.PaymentOptionTypeDesc;

		if ((PaymentOptionTypeDesc != null) &&
				(PaymentOptionTypeDesc.length() == 0)) {
			paymentOptionTypesCacheModel.PaymentOptionTypeDesc = null;
		}

		return paymentOptionTypesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{PaymentOptionTypesId=");
		sb.append(getPaymentOptionTypesId());
		sb.append(", PaymentOptionId=");
		sb.append(getPaymentOptionId());
		sb.append(", OptionTypesKey=");
		sb.append(getOptionTypesKey());
		sb.append(", IsActive=");
		sb.append(getIsActive());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", CreatedDate=");
		sb.append(getCreatedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", Priority=");
		sb.append(getPriority());
		sb.append(", PaymentOptionTypeDesc=");
		sb.append(getPaymentOptionTypeDesc());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.PaymentOptionTypes");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PaymentOptionTypesId</column-name><column-value><![CDATA[");
		sb.append(getPaymentOptionTypesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PaymentOptionId</column-name><column-value><![CDATA[");
		sb.append(getPaymentOptionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>OptionTypesKey</column-name><column-value><![CDATA[");
		sb.append(getOptionTypesKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IsActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Priority</column-name><column-value><![CDATA[");
		sb.append(getPriority());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PaymentOptionTypeDesc</column-name><column-value><![CDATA[");
		sb.append(getPaymentOptionTypeDesc());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PaymentOptionTypes.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PaymentOptionTypes.class
		};
	private String _PaymentOptionTypesId;
	private String _PaymentOptionId;
	private String _OptionTypesKey;
	private boolean _IsActive;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;
	private int _Priority;
	private String _PaymentOptionTypeDesc;
	private PaymentOptionTypes _escapedModel;
}