/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.PaymentMethodMaster;
import com.ifli.rapid.model.PaymentMethodMasterModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PaymentMethodMaster service. Represents a row in the &quot;PaymentMethodMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.PaymentMethodMasterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PaymentMethodMasterImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PaymentMethodMasterImpl
 * @see com.ifli.rapid.model.PaymentMethodMaster
 * @see com.ifli.rapid.model.PaymentMethodMasterModel
 * @generated
 */
public class PaymentMethodMasterModelImpl extends BaseModelImpl<PaymentMethodMaster>
	implements PaymentMethodMasterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a payment method master model instance should use the {@link com.ifli.rapid.model.PaymentMethodMaster} interface instead.
	 */
	public static final String TABLE_NAME = "PaymentMethodMaster";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PaymentMethodID", Types.VARCHAR },
			{ "PaymentMethodKey", Types.VARCHAR },
			{ "IsActive", Types.BOOLEAN },
			{ "CreatedBy", Types.VARCHAR },
			{ "CreatedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "Priority", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table PaymentMethodMaster (PaymentMethodID VARCHAR(75) not null primary key IDENTITY,PaymentMethodKey VARCHAR(75) null,IsActive BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null,Priority INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table PaymentMethodMaster";
	public static final String ORDER_BY_JPQL = " ORDER BY paymentMethodMaster.Priority ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PaymentMethodMaster.Priority ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.PaymentMethodMaster"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.PaymentMethodMaster"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.PaymentMethodMaster"));

	public PaymentMethodMasterModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _PaymentMethodID;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setPaymentMethodID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PaymentMethodID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PaymentMethodMaster.class;
	}

	@Override
	public String getModelClassName() {
		return PaymentMethodMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PaymentMethodID", getPaymentMethodID());
		attributes.put("PaymentMethodKey", getPaymentMethodKey());
		attributes.put("IsActive", getIsActive());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("CreatedDate", getCreatedDate());
		attributes.put("ModifiedBy", getModifiedBy());
		attributes.put("ModifiedDate", getModifiedDate());
		attributes.put("Priority", getPriority());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String PaymentMethodID = (String)attributes.get("PaymentMethodID");

		if (PaymentMethodID != null) {
			setPaymentMethodID(PaymentMethodID);
		}

		String PaymentMethodKey = (String)attributes.get("PaymentMethodKey");

		if (PaymentMethodKey != null) {
			setPaymentMethodKey(PaymentMethodKey);
		}

		Boolean IsActive = (Boolean)attributes.get("IsActive");

		if (IsActive != null) {
			setIsActive(IsActive);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date CreatedDate = (Date)attributes.get("CreatedDate");

		if (CreatedDate != null) {
			setCreatedDate(CreatedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}

		Integer Priority = (Integer)attributes.get("Priority");

		if (Priority != null) {
			setPriority(Priority);
		}
	}

	@Override
	public String getPaymentMethodID() {
		if (_PaymentMethodID == null) {
			return StringPool.BLANK;
		}
		else {
			return _PaymentMethodID;
		}
	}

	@Override
	public void setPaymentMethodID(String PaymentMethodID) {
		_PaymentMethodID = PaymentMethodID;
	}

	@Override
	public String getPaymentMethodKey() {
		if (_PaymentMethodKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _PaymentMethodKey;
		}
	}

	@Override
	public void setPaymentMethodKey(String PaymentMethodKey) {
		_PaymentMethodKey = PaymentMethodKey;
	}

	@Override
	public boolean getIsActive() {
		return _IsActive;
	}

	@Override
	public boolean isIsActive() {
		return _IsActive;
	}

	@Override
	public void setIsActive(boolean IsActive) {
		_IsActive = IsActive;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	@Override
	public int getPriority() {
		return _Priority;
	}

	@Override
	public void setPriority(int Priority) {
		_Priority = Priority;
	}

	@Override
	public PaymentMethodMaster toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PaymentMethodMaster)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PaymentMethodMasterImpl paymentMethodMasterImpl = new PaymentMethodMasterImpl();

		paymentMethodMasterImpl.setPaymentMethodID(getPaymentMethodID());
		paymentMethodMasterImpl.setPaymentMethodKey(getPaymentMethodKey());
		paymentMethodMasterImpl.setIsActive(getIsActive());
		paymentMethodMasterImpl.setCreatedBy(getCreatedBy());
		paymentMethodMasterImpl.setCreatedDate(getCreatedDate());
		paymentMethodMasterImpl.setModifiedBy(getModifiedBy());
		paymentMethodMasterImpl.setModifiedDate(getModifiedDate());
		paymentMethodMasterImpl.setPriority(getPriority());

		paymentMethodMasterImpl.resetOriginalValues();

		return paymentMethodMasterImpl;
	}

	@Override
	public int compareTo(PaymentMethodMaster paymentMethodMaster) {
		int value = 0;

		if (getPriority() < paymentMethodMaster.getPriority()) {
			value = -1;
		}
		else if (getPriority() > paymentMethodMaster.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PaymentMethodMaster)) {
			return false;
		}

		PaymentMethodMaster paymentMethodMaster = (PaymentMethodMaster)obj;

		String primaryKey = paymentMethodMaster.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PaymentMethodMaster> toCacheModel() {
		PaymentMethodMasterCacheModel paymentMethodMasterCacheModel = new PaymentMethodMasterCacheModel();

		paymentMethodMasterCacheModel.PaymentMethodID = getPaymentMethodID();

		String PaymentMethodID = paymentMethodMasterCacheModel.PaymentMethodID;

		if ((PaymentMethodID != null) && (PaymentMethodID.length() == 0)) {
			paymentMethodMasterCacheModel.PaymentMethodID = null;
		}

		paymentMethodMasterCacheModel.PaymentMethodKey = getPaymentMethodKey();

		String PaymentMethodKey = paymentMethodMasterCacheModel.PaymentMethodKey;

		if ((PaymentMethodKey != null) && (PaymentMethodKey.length() == 0)) {
			paymentMethodMasterCacheModel.PaymentMethodKey = null;
		}

		paymentMethodMasterCacheModel.IsActive = getIsActive();

		paymentMethodMasterCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = paymentMethodMasterCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			paymentMethodMasterCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			paymentMethodMasterCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			paymentMethodMasterCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		paymentMethodMasterCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = paymentMethodMasterCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			paymentMethodMasterCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			paymentMethodMasterCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			paymentMethodMasterCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		paymentMethodMasterCacheModel.Priority = getPriority();

		return paymentMethodMasterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{PaymentMethodID=");
		sb.append(getPaymentMethodID());
		sb.append(", PaymentMethodKey=");
		sb.append(getPaymentMethodKey());
		sb.append(", IsActive=");
		sb.append(getIsActive());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", CreatedDate=");
		sb.append(getCreatedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", Priority=");
		sb.append(getPriority());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.PaymentMethodMaster");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PaymentMethodID</column-name><column-value><![CDATA[");
		sb.append(getPaymentMethodID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PaymentMethodKey</column-name><column-value><![CDATA[");
		sb.append(getPaymentMethodKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IsActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Priority</column-name><column-value><![CDATA[");
		sb.append(getPriority());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PaymentMethodMaster.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PaymentMethodMaster.class
		};
	private String _PaymentMethodID;
	private String _PaymentMethodKey;
	private boolean _IsActive;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;
	private int _Priority;
	private PaymentMethodMaster _escapedModel;
}