/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.PincodeDetails;
import com.ifli.rapid.model.PincodeDetailsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PincodeDetails service. Represents a row in the &quot;pincode_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.PincodeDetailsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PincodeDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PincodeDetailsImpl
 * @see com.ifli.rapid.model.PincodeDetails
 * @see com.ifli.rapid.model.PincodeDetailsModel
 * @generated
 */
public class PincodeDetailsModelImpl extends BaseModelImpl<PincodeDetails>
	implements PincodeDetailsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pincode details model instance should use the {@link com.ifli.rapid.model.PincodeDetails} interface instead.
	 */
	public static final String TABLE_NAME = "pincode_details";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PIN_ID", Types.INTEGER },
			{ "CITY_ID", Types.INTEGER },
			{ "STATE_ID", Types.INTEGER },
			{ "PIN_CODE", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table pincode_details (PIN_ID INTEGER not null primary key,CITY_ID INTEGER,STATE_ID INTEGER,PIN_CODE VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table pincode_details";
	public static final String ORDER_BY_JPQL = " ORDER BY pincodeDetails.PIN_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY pincode_details.PIN_ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.PincodeDetails"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.PincodeDetails"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.PincodeDetails"));

	public PincodeDetailsModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _PIN_ID;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setPIN_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PIN_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PincodeDetails.class;
	}

	@Override
	public String getModelClassName() {
		return PincodeDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PIN_ID", getPIN_ID());
		attributes.put("CITY_ID", getCITY_ID());
		attributes.put("STATE_ID", getSTATE_ID());
		attributes.put("PIN_CODE", getPIN_CODE());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer PIN_ID = (Integer)attributes.get("PIN_ID");

		if (PIN_ID != null) {
			setPIN_ID(PIN_ID);
		}

		Integer CITY_ID = (Integer)attributes.get("CITY_ID");

		if (CITY_ID != null) {
			setCITY_ID(CITY_ID);
		}

		Integer STATE_ID = (Integer)attributes.get("STATE_ID");

		if (STATE_ID != null) {
			setSTATE_ID(STATE_ID);
		}

		String PIN_CODE = (String)attributes.get("PIN_CODE");

		if (PIN_CODE != null) {
			setPIN_CODE(PIN_CODE);
		}
	}

	@Override
	public int getPIN_ID() {
		return _PIN_ID;
	}

	@Override
	public void setPIN_ID(int PIN_ID) {
		_PIN_ID = PIN_ID;
	}

	@Override
	public int getCITY_ID() {
		return _CITY_ID;
	}

	@Override
	public void setCITY_ID(int CITY_ID) {
		_CITY_ID = CITY_ID;
	}

	@Override
	public int getSTATE_ID() {
		return _STATE_ID;
	}

	@Override
	public void setSTATE_ID(int STATE_ID) {
		_STATE_ID = STATE_ID;
	}

	@Override
	public String getPIN_CODE() {
		if (_PIN_CODE == null) {
			return StringPool.BLANK;
		}
		else {
			return _PIN_CODE;
		}
	}

	@Override
	public void setPIN_CODE(String PIN_CODE) {
		_PIN_CODE = PIN_CODE;
	}

	@Override
	public PincodeDetails toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PincodeDetails)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PincodeDetailsImpl pincodeDetailsImpl = new PincodeDetailsImpl();

		pincodeDetailsImpl.setPIN_ID(getPIN_ID());
		pincodeDetailsImpl.setCITY_ID(getCITY_ID());
		pincodeDetailsImpl.setSTATE_ID(getSTATE_ID());
		pincodeDetailsImpl.setPIN_CODE(getPIN_CODE());

		pincodeDetailsImpl.resetOriginalValues();

		return pincodeDetailsImpl;
	}

	@Override
	public int compareTo(PincodeDetails pincodeDetails) {
		int primaryKey = pincodeDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PincodeDetails)) {
			return false;
		}

		PincodeDetails pincodeDetails = (PincodeDetails)obj;

		int primaryKey = pincodeDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PincodeDetails> toCacheModel() {
		PincodeDetailsCacheModel pincodeDetailsCacheModel = new PincodeDetailsCacheModel();

		pincodeDetailsCacheModel.PIN_ID = getPIN_ID();

		pincodeDetailsCacheModel.CITY_ID = getCITY_ID();

		pincodeDetailsCacheModel.STATE_ID = getSTATE_ID();

		pincodeDetailsCacheModel.PIN_CODE = getPIN_CODE();

		String PIN_CODE = pincodeDetailsCacheModel.PIN_CODE;

		if ((PIN_CODE != null) && (PIN_CODE.length() == 0)) {
			pincodeDetailsCacheModel.PIN_CODE = null;
		}

		return pincodeDetailsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{PIN_ID=");
		sb.append(getPIN_ID());
		sb.append(", CITY_ID=");
		sb.append(getCITY_ID());
		sb.append(", STATE_ID=");
		sb.append(getSTATE_ID());
		sb.append(", PIN_CODE=");
		sb.append(getPIN_CODE());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.PincodeDetails");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PIN_ID</column-name><column-value><![CDATA[");
		sb.append(getPIN_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CITY_ID</column-name><column-value><![CDATA[");
		sb.append(getCITY_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>STATE_ID</column-name><column-value><![CDATA[");
		sb.append(getSTATE_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PIN_CODE</column-name><column-value><![CDATA[");
		sb.append(getPIN_CODE());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PincodeDetails.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PincodeDetails.class
		};
	private int _PIN_ID;
	private int _CITY_ID;
	private int _STATE_ID;
	private String _PIN_CODE;
	private PincodeDetails _escapedModel;
}