/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.PolicyPremPercentage;
import com.ifli.rapid.service.PolicyPremPercentageLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the PolicyPremPercentage service. Represents a row in the &quot;policy_prem_percentage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyPremPercentageImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PolicyPremPercentageImpl
 * @see com.ifli.rapid.model.PolicyPremPercentage
 * @generated
 */
public abstract class PolicyPremPercentageBaseImpl
	extends PolicyPremPercentageModelImpl implements PolicyPremPercentage {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy prem percentage model instance should use the {@link PolicyPremPercentage} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			PolicyPremPercentageLocalServiceUtil.addPolicyPremPercentage(this);
		}
		else {
			PolicyPremPercentageLocalServiceUtil.updatePolicyPremPercentage(this);
		}
	}
}