/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.PolicyPremPercentage;
import com.ifli.rapid.model.PolicyPremPercentageModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PolicyPremPercentage service. Represents a row in the &quot;policy_prem_percentage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.PolicyPremPercentageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyPremPercentageImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PolicyPremPercentageImpl
 * @see com.ifli.rapid.model.PolicyPremPercentage
 * @see com.ifli.rapid.model.PolicyPremPercentageModel
 * @generated
 */
public class PolicyPremPercentageModelImpl extends BaseModelImpl<PolicyPremPercentage>
	implements PolicyPremPercentageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy prem percentage model instance should use the {@link com.ifli.rapid.model.PolicyPremPercentage} interface instead.
	 */
	public static final String TABLE_NAME = "policy_prem_percentage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PREM_PERCENTAGE_ID", Types.INTEGER },
			{ "POLICY_ID", Types.VARCHAR },
			{ "FUND_ID", Types.INTEGER },
			{ "FUND_PERCENTAGE", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table policy_prem_percentage (PREM_PERCENTAGE_ID INTEGER not null primary key IDENTITY,POLICY_ID VARCHAR(75) null,FUND_ID INTEGER,FUND_PERCENTAGE INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table policy_prem_percentage";
	public static final String ORDER_BY_JPQL = " ORDER BY policyPremPercentage.PREM_PERCENTAGE_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY policy_prem_percentage.PREM_PERCENTAGE_ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.PolicyPremPercentage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.PolicyPremPercentage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.PolicyPremPercentage"));

	public PolicyPremPercentageModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _PREM_PERCENTAGE_ID;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setPREM_PERCENTAGE_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PREM_PERCENTAGE_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PolicyPremPercentage.class;
	}

	@Override
	public String getModelClassName() {
		return PolicyPremPercentage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PREM_PERCENTAGE_ID", getPREM_PERCENTAGE_ID());
		attributes.put("POLICY_ID", getPOLICY_ID());
		attributes.put("FUND_ID", getFUND_ID());
		attributes.put("FUND_PERCENTAGE", getFUND_PERCENTAGE());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer PREM_PERCENTAGE_ID = (Integer)attributes.get(
				"PREM_PERCENTAGE_ID");

		if (PREM_PERCENTAGE_ID != null) {
			setPREM_PERCENTAGE_ID(PREM_PERCENTAGE_ID);
		}

		String POLICY_ID = (String)attributes.get("POLICY_ID");

		if (POLICY_ID != null) {
			setPOLICY_ID(POLICY_ID);
		}

		Integer FUND_ID = (Integer)attributes.get("FUND_ID");

		if (FUND_ID != null) {
			setFUND_ID(FUND_ID);
		}

		Integer FUND_PERCENTAGE = (Integer)attributes.get("FUND_PERCENTAGE");

		if (FUND_PERCENTAGE != null) {
			setFUND_PERCENTAGE(FUND_PERCENTAGE);
		}
	}

	@Override
	public int getPREM_PERCENTAGE_ID() {
		return _PREM_PERCENTAGE_ID;
	}

	@Override
	public void setPREM_PERCENTAGE_ID(int PREM_PERCENTAGE_ID) {
		_PREM_PERCENTAGE_ID = PREM_PERCENTAGE_ID;
	}

	@Override
	public String getPOLICY_ID() {
		if (_POLICY_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_ID;
		}
	}

	@Override
	public void setPOLICY_ID(String POLICY_ID) {
		_POLICY_ID = POLICY_ID;
	}

	@Override
	public int getFUND_ID() {
		return _FUND_ID;
	}

	@Override
	public void setFUND_ID(int FUND_ID) {
		_FUND_ID = FUND_ID;
	}

	@Override
	public int getFUND_PERCENTAGE() {
		return _FUND_PERCENTAGE;
	}

	@Override
	public void setFUND_PERCENTAGE(int FUND_PERCENTAGE) {
		_FUND_PERCENTAGE = FUND_PERCENTAGE;
	}

	@Override
	public PolicyPremPercentage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PolicyPremPercentage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PolicyPremPercentageImpl policyPremPercentageImpl = new PolicyPremPercentageImpl();

		policyPremPercentageImpl.setPREM_PERCENTAGE_ID(getPREM_PERCENTAGE_ID());
		policyPremPercentageImpl.setPOLICY_ID(getPOLICY_ID());
		policyPremPercentageImpl.setFUND_ID(getFUND_ID());
		policyPremPercentageImpl.setFUND_PERCENTAGE(getFUND_PERCENTAGE());

		policyPremPercentageImpl.resetOriginalValues();

		return policyPremPercentageImpl;
	}

	@Override
	public int compareTo(PolicyPremPercentage policyPremPercentage) {
		int primaryKey = policyPremPercentage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PolicyPremPercentage)) {
			return false;
		}

		PolicyPremPercentage policyPremPercentage = (PolicyPremPercentage)obj;

		int primaryKey = policyPremPercentage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PolicyPremPercentage> toCacheModel() {
		PolicyPremPercentageCacheModel policyPremPercentageCacheModel = new PolicyPremPercentageCacheModel();

		policyPremPercentageCacheModel.PREM_PERCENTAGE_ID = getPREM_PERCENTAGE_ID();

		policyPremPercentageCacheModel.POLICY_ID = getPOLICY_ID();

		String POLICY_ID = policyPremPercentageCacheModel.POLICY_ID;

		if ((POLICY_ID != null) && (POLICY_ID.length() == 0)) {
			policyPremPercentageCacheModel.POLICY_ID = null;
		}

		policyPremPercentageCacheModel.FUND_ID = getFUND_ID();

		policyPremPercentageCacheModel.FUND_PERCENTAGE = getFUND_PERCENTAGE();

		return policyPremPercentageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{PREM_PERCENTAGE_ID=");
		sb.append(getPREM_PERCENTAGE_ID());
		sb.append(", POLICY_ID=");
		sb.append(getPOLICY_ID());
		sb.append(", FUND_ID=");
		sb.append(getFUND_ID());
		sb.append(", FUND_PERCENTAGE=");
		sb.append(getFUND_PERCENTAGE());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.PolicyPremPercentage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PREM_PERCENTAGE_ID</column-name><column-value><![CDATA[");
		sb.append(getPREM_PERCENTAGE_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_ID</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FUND_ID</column-name><column-value><![CDATA[");
		sb.append(getFUND_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FUND_PERCENTAGE</column-name><column-value><![CDATA[");
		sb.append(getFUND_PERCENTAGE());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PolicyPremPercentage.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PolicyPremPercentage.class
		};
	private int _PREM_PERCENTAGE_ID;
	private String _POLICY_ID;
	private int _FUND_ID;
	private int _FUND_PERCENTAGE;
	private PolicyPremPercentage _escapedModel;
}