/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.PolicyFund;
import com.ifli.rapid.model.PolicyFundModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PolicyFund service. Represents a row in the &quot;policy_fund&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.PolicyFundModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyFundImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PolicyFundImpl
 * @see com.ifli.rapid.model.PolicyFund
 * @see com.ifli.rapid.model.PolicyFundModel
 * @generated
 */
public class PolicyFundModelImpl extends BaseModelImpl<PolicyFund>
	implements PolicyFundModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy fund model instance should use the {@link com.ifli.rapid.model.PolicyFund} interface instead.
	 */
	public static final String TABLE_NAME = "policy_fund";
	public static final Object[][] TABLE_COLUMNS = {
			{ "POLICY_FUND_ID", Types.INTEGER },
			{ "POLICY_ID", Types.VARCHAR },
			{ "FUND_ID", Types.INTEGER },
			{ "FUND_UNITS", Types.DOUBLE },
			{ "NAV", Types.DOUBLE },
			{ "TOTAL_FUND", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table policy_fund (POLICY_FUND_ID INTEGER not null primary key IDENTITY,POLICY_ID VARCHAR(75) null,FUND_ID INTEGER,FUND_UNITS DOUBLE,NAV DOUBLE,TOTAL_FUND DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table policy_fund";
	public static final String ORDER_BY_JPQL = " ORDER BY policyFund.POLICY_FUND_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY policy_fund.POLICY_FUND_ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.PolicyFund"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.PolicyFund"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.PolicyFund"));

	public PolicyFundModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _POLICY_FUND_ID;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setPOLICY_FUND_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _POLICY_FUND_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PolicyFund.class;
	}

	@Override
	public String getModelClassName() {
		return PolicyFund.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("POLICY_FUND_ID", getPOLICY_FUND_ID());
		attributes.put("POLICY_ID", getPOLICY_ID());
		attributes.put("FUND_ID", getFUND_ID());
		attributes.put("FUND_UNITS", getFUND_UNITS());
		attributes.put("NAV", getNAV());
		attributes.put("TOTAL_FUND", getTOTAL_FUND());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer POLICY_FUND_ID = (Integer)attributes.get("POLICY_FUND_ID");

		if (POLICY_FUND_ID != null) {
			setPOLICY_FUND_ID(POLICY_FUND_ID);
		}

		String POLICY_ID = (String)attributes.get("POLICY_ID");

		if (POLICY_ID != null) {
			setPOLICY_ID(POLICY_ID);
		}

		Integer FUND_ID = (Integer)attributes.get("FUND_ID");

		if (FUND_ID != null) {
			setFUND_ID(FUND_ID);
		}

		Double FUND_UNITS = (Double)attributes.get("FUND_UNITS");

		if (FUND_UNITS != null) {
			setFUND_UNITS(FUND_UNITS);
		}

		Double NAV = (Double)attributes.get("NAV");

		if (NAV != null) {
			setNAV(NAV);
		}

		Double TOTAL_FUND = (Double)attributes.get("TOTAL_FUND");

		if (TOTAL_FUND != null) {
			setTOTAL_FUND(TOTAL_FUND);
		}
	}

	@Override
	public int getPOLICY_FUND_ID() {
		return _POLICY_FUND_ID;
	}

	@Override
	public void setPOLICY_FUND_ID(int POLICY_FUND_ID) {
		_POLICY_FUND_ID = POLICY_FUND_ID;
	}

	@Override
	public String getPOLICY_ID() {
		if (_POLICY_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_ID;
		}
	}

	@Override
	public void setPOLICY_ID(String POLICY_ID) {
		_POLICY_ID = POLICY_ID;
	}

	@Override
	public int getFUND_ID() {
		return _FUND_ID;
	}

	@Override
	public void setFUND_ID(int FUND_ID) {
		_FUND_ID = FUND_ID;
	}

	@Override
	public double getFUND_UNITS() {
		return _FUND_UNITS;
	}

	@Override
	public void setFUND_UNITS(double FUND_UNITS) {
		_FUND_UNITS = FUND_UNITS;
	}

	@Override
	public double getNAV() {
		return _NAV;
	}

	@Override
	public void setNAV(double NAV) {
		_NAV = NAV;
	}

	@Override
	public double getTOTAL_FUND() {
		return _TOTAL_FUND;
	}

	@Override
	public void setTOTAL_FUND(double TOTAL_FUND) {
		_TOTAL_FUND = TOTAL_FUND;
	}

	@Override
	public PolicyFund toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PolicyFund)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PolicyFundImpl policyFundImpl = new PolicyFundImpl();

		policyFundImpl.setPOLICY_FUND_ID(getPOLICY_FUND_ID());
		policyFundImpl.setPOLICY_ID(getPOLICY_ID());
		policyFundImpl.setFUND_ID(getFUND_ID());
		policyFundImpl.setFUND_UNITS(getFUND_UNITS());
		policyFundImpl.setNAV(getNAV());
		policyFundImpl.setTOTAL_FUND(getTOTAL_FUND());

		policyFundImpl.resetOriginalValues();

		return policyFundImpl;
	}

	@Override
	public int compareTo(PolicyFund policyFund) {
		int primaryKey = policyFund.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PolicyFund)) {
			return false;
		}

		PolicyFund policyFund = (PolicyFund)obj;

		int primaryKey = policyFund.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PolicyFund> toCacheModel() {
		PolicyFundCacheModel policyFundCacheModel = new PolicyFundCacheModel();

		policyFundCacheModel.POLICY_FUND_ID = getPOLICY_FUND_ID();

		policyFundCacheModel.POLICY_ID = getPOLICY_ID();

		String POLICY_ID = policyFundCacheModel.POLICY_ID;

		if ((POLICY_ID != null) && (POLICY_ID.length() == 0)) {
			policyFundCacheModel.POLICY_ID = null;
		}

		policyFundCacheModel.FUND_ID = getFUND_ID();

		policyFundCacheModel.FUND_UNITS = getFUND_UNITS();

		policyFundCacheModel.NAV = getNAV();

		policyFundCacheModel.TOTAL_FUND = getTOTAL_FUND();

		return policyFundCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{POLICY_FUND_ID=");
		sb.append(getPOLICY_FUND_ID());
		sb.append(", POLICY_ID=");
		sb.append(getPOLICY_ID());
		sb.append(", FUND_ID=");
		sb.append(getFUND_ID());
		sb.append(", FUND_UNITS=");
		sb.append(getFUND_UNITS());
		sb.append(", NAV=");
		sb.append(getNAV());
		sb.append(", TOTAL_FUND=");
		sb.append(getTOTAL_FUND());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.PolicyFund");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>POLICY_FUND_ID</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_FUND_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_ID</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FUND_ID</column-name><column-value><![CDATA[");
		sb.append(getFUND_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FUND_UNITS</column-name><column-value><![CDATA[");
		sb.append(getFUND_UNITS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NAV</column-name><column-value><![CDATA[");
		sb.append(getNAV());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TOTAL_FUND</column-name><column-value><![CDATA[");
		sb.append(getTOTAL_FUND());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PolicyFund.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PolicyFund.class
		};
	private int _POLICY_FUND_ID;
	private String _POLICY_ID;
	private int _FUND_ID;
	private double _FUND_UNITS;
	private double _NAV;
	private double _TOTAL_FUND;
	private PolicyFund _escapedModel;
}