/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.PolicyInfo;
import com.ifli.rapid.model.PolicyInfoModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PolicyInfo service. Represents a row in the &quot;policy_info&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.PolicyInfoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyInfoImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PolicyInfoImpl
 * @see com.ifli.rapid.model.PolicyInfo
 * @see com.ifli.rapid.model.PolicyInfoModel
 * @generated
 */
public class PolicyInfoModelImpl extends BaseModelImpl<PolicyInfo>
	implements PolicyInfoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy info model instance should use the {@link com.ifli.rapid.model.PolicyInfo} interface instead.
	 */
	public static final String TABLE_NAME = "policy_info";
	public static final Object[][] TABLE_COLUMNS = {
			{ "POLICY_ID", Types.VARCHAR },
			{ "CUSTOMER_ID", Types.INTEGER },
			{ "PRODUCT_ID", Types.INTEGER },
			{ "POLICY_DATE", Types.VARCHAR },
			{ "NEXT_PREMIUM_DUEDATE", Types.VARCHAR },
			{ "POLICY_HOLDER1_FIRST_NAME", Types.VARCHAR },
			{ "POLICY_HOLDER1_MIDDLE_NAME", Types.VARCHAR },
			{ "POLICY_HOLDER1_LAST_NAME", Types.VARCHAR },
			{ "SUM_ASSURED", Types.DOUBLE },
			{ "POLICY_HOLDER2_FIRST_NAME", Types.VARCHAR },
			{ "POLICY_HOLDER2_MIDDLE_NAME", Types.VARCHAR },
			{ "POLICY_HOLDER2_LAST_NAME", Types.VARCHAR },
			{ "CHILD_FIRST_NAME", Types.VARCHAR },
			{ "CHILD_DOB", Types.VARCHAR },
			{ "CHILD_LAST_NAME", Types.VARCHAR },
			{ "CURRENT_STATUS", Types.VARCHAR },
			{ "PREMIUM_AMOUNT", Types.INTEGER },
			{ "FREQUENCY", Types.VARCHAR },
			{ "BRANCH_CODE", Types.VARCHAR },
			{ "LG_CODE", Types.VARCHAR },
			{ "APPLICATION_NUMBER", Types.VARCHAR },
			{ "APPLICATION_DATE", Types.VARCHAR },
			{ "POLICY_HOLDER1_TITLE", Types.VARCHAR },
			{ "CRO_NAME", Types.VARCHAR },
			{ "CRO_NUMBER", Types.VARCHAR },
			{ "BRANCH_NAME", Types.VARCHAR },
			{ "PRODUCT_NAME", Types.VARCHAR },
			{ "REQUIREMENT_FLAG", Types.VARCHAR },
			{ "TERM", Types.INTEGER },
			{ "MATURITY_DATE", Types.TIMESTAMP },
			{ "AMOUNT_DEPOSITED", Types.DOUBLE },
			{ "TOTAL_DUE_AMT", Types.DOUBLE },
			{ "CHANNEL_TYPE", Types.VARCHAR },
			{ "LIFE_ASSURED_NAME", Types.VARCHAR },
			{ "LIFE_ASSURED_DOB", Types.TIMESTAMP },
			{ "POLICY_HOLDER1_EMAIL", Types.VARCHAR },
			{ "POLICY_HOLDER1_ADD1", Types.VARCHAR },
			{ "POLICY_HOLDER1_ADD2", Types.VARCHAR },
			{ "POLICY_HOLDER1_CONTACT1", Types.VARCHAR },
			{ "POLICY_HOLDER1_CONTACT2", Types.VARCHAR },
			{ "POLICY_HOLDER1_DOB", Types.VARCHAR },
			{ "RISK_COMMENCEMENT_DATE", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table policy_info (POLICY_ID VARCHAR(75) not null primary key,CUSTOMER_ID INTEGER,PRODUCT_ID INTEGER,POLICY_DATE VARCHAR(75) null,NEXT_PREMIUM_DUEDATE VARCHAR(75) null,POLICY_HOLDER1_FIRST_NAME VARCHAR(75) null,POLICY_HOLDER1_MIDDLE_NAME VARCHAR(75) null,POLICY_HOLDER1_LAST_NAME VARCHAR(75) null,SUM_ASSURED DOUBLE,POLICY_HOLDER2_FIRST_NAME VARCHAR(75) null,POLICY_HOLDER2_MIDDLE_NAME VARCHAR(75) null,POLICY_HOLDER2_LAST_NAME VARCHAR(75) null,CHILD_FIRST_NAME VARCHAR(75) null,CHILD_DOB VARCHAR(75) null,CHILD_LAST_NAME VARCHAR(75) null,CURRENT_STATUS VARCHAR(75) null,PREMIUM_AMOUNT INTEGER,FREQUENCY VARCHAR(75) null,BRANCH_CODE VARCHAR(75) null,LG_CODE VARCHAR(75) null,APPLICATION_NUMBER VARCHAR(75) null,APPLICATION_DATE VARCHAR(75) null,POLICY_HOLDER1_TITLE VARCHAR(75) null,CRO_NAME VARCHAR(75) null,CRO_NUMBER VARCHAR(75) null,BRANCH_NAME VARCHAR(75) null,PRODUCT_NAME VARCHAR(75) null,REQUIREMENT_FLAG VARCHAR(75) null,TERM INTEGER,MATURITY_DATE DATE null,AMOUNT_DEPOSITED DOUBLE,TOTAL_DUE_AMT DOUBLE,CHANNEL_TYPE VARCHAR(75) null,LIFE_ASSURED_NAME VARCHAR(75) null,LIFE_ASSURED_DOB DATE null,POLICY_HOLDER1_EMAIL VARCHAR(75) null,POLICY_HOLDER1_ADD1 VARCHAR(75) null,POLICY_HOLDER1_ADD2 VARCHAR(75) null,POLICY_HOLDER1_CONTACT1 VARCHAR(75) null,POLICY_HOLDER1_CONTACT2 VARCHAR(75) null,POLICY_HOLDER1_DOB VARCHAR(75) null,RISK_COMMENCEMENT_DATE DATE null)";
	public static final String TABLE_SQL_DROP = "drop table policy_info";
	public static final String ORDER_BY_JPQL = " ORDER BY policyInfo.POLICY_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY policy_info.POLICY_ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.PolicyInfo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.PolicyInfo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.PolicyInfo"));

	public PolicyInfoModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _POLICY_ID;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setPOLICY_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _POLICY_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PolicyInfo.class;
	}

	@Override
	public String getModelClassName() {
		return PolicyInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("POLICY_ID", getPOLICY_ID());
		attributes.put("CUSTOMER_ID", getCUSTOMER_ID());
		attributes.put("PRODUCT_ID", getPRODUCT_ID());
		attributes.put("POLICY_DATE", getPOLICY_DATE());
		attributes.put("NEXT_PREMIUM_DUEDATE", getNEXT_PREMIUM_DUEDATE());
		attributes.put("POLICY_HOLDER1_FIRST_NAME",
			getPOLICY_HOLDER1_FIRST_NAME());
		attributes.put("POLICY_HOLDER1_MIDDLE_NAME",
			getPOLICY_HOLDER1_MIDDLE_NAME());
		attributes.put("POLICY_HOLDER1_LAST_NAME", getPOLICY_HOLDER1_LAST_NAME());
		attributes.put("SUM_ASSURED", getSUM_ASSURED());
		attributes.put("POLICY_HOLDER2_FIRST_NAME",
			getPOLICY_HOLDER2_FIRST_NAME());
		attributes.put("POLICY_HOLDER2_MIDDLE_NAME",
			getPOLICY_HOLDER2_MIDDLE_NAME());
		attributes.put("POLICY_HOLDER2_LAST_NAME", getPOLICY_HOLDER2_LAST_NAME());
		attributes.put("CHILD_FIRST_NAME", getCHILD_FIRST_NAME());
		attributes.put("CHILD_DOB", getCHILD_DOB());
		attributes.put("CHILD_LAST_NAME", getCHILD_LAST_NAME());
		attributes.put("CURRENT_STATUS", getCURRENT_STATUS());
		attributes.put("PREMIUM_AMOUNT", getPREMIUM_AMOUNT());
		attributes.put("FREQUENCY", getFREQUENCY());
		attributes.put("BRANCH_CODE", getBRANCH_CODE());
		attributes.put("LG_CODE", getLG_CODE());
		attributes.put("APPLICATION_NUMBER", getAPPLICATION_NUMBER());
		attributes.put("APPLICATION_DATE", getAPPLICATION_DATE());
		attributes.put("POLICY_HOLDER1_TITLE", getPOLICY_HOLDER1_TITLE());
		attributes.put("CRO_NAME", getCRO_NAME());
		attributes.put("CRO_NUMBER", getCRO_NUMBER());
		attributes.put("BRANCH_NAME", getBRANCH_NAME());
		attributes.put("PRODUCT_NAME", getPRODUCT_NAME());
		attributes.put("REQUIREMENT_FLAG", getREQUIREMENT_FLAG());
		attributes.put("TERM", getTERM());
		attributes.put("MATURITY_DATE", getMATURITY_DATE());
		attributes.put("AMOUNT_DEPOSITED", getAMOUNT_DEPOSITED());
		attributes.put("TOTAL_DUE_AMT", getTOTAL_DUE_AMT());
		attributes.put("CHANNEL_TYPE", getCHANNEL_TYPE());
		attributes.put("LIFE_ASSURED_NAME", getLIFE_ASSURED_NAME());
		attributes.put("LIFE_ASSURED_DOB", getLIFE_ASSURED_DOB());
		attributes.put("POLICY_HOLDER1_EMAIL", getPOLICY_HOLDER1_EMAIL());
		attributes.put("POLICY_HOLDER1_ADD1", getPOLICY_HOLDER1_ADD1());
		attributes.put("POLICY_HOLDER1_ADD2", getPOLICY_HOLDER1_ADD2());
		attributes.put("POLICY_HOLDER1_CONTACT1", getPOLICY_HOLDER1_CONTACT1());
		attributes.put("POLICY_HOLDER1_CONTACT2", getPOLICY_HOLDER1_CONTACT2());
		attributes.put("POLICY_HOLDER1_DOB", getPOLICY_HOLDER1_DOB());
		attributes.put("RISK_COMMENCEMENT_DATE", getRISK_COMMENCEMENT_DATE());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String POLICY_ID = (String)attributes.get("POLICY_ID");

		if (POLICY_ID != null) {
			setPOLICY_ID(POLICY_ID);
		}

		Integer CUSTOMER_ID = (Integer)attributes.get("CUSTOMER_ID");

		if (CUSTOMER_ID != null) {
			setCUSTOMER_ID(CUSTOMER_ID);
		}

		Integer PRODUCT_ID = (Integer)attributes.get("PRODUCT_ID");

		if (PRODUCT_ID != null) {
			setPRODUCT_ID(PRODUCT_ID);
		}

		String POLICY_DATE = (String)attributes.get("POLICY_DATE");

		if (POLICY_DATE != null) {
			setPOLICY_DATE(POLICY_DATE);
		}

		String NEXT_PREMIUM_DUEDATE = (String)attributes.get(
				"NEXT_PREMIUM_DUEDATE");

		if (NEXT_PREMIUM_DUEDATE != null) {
			setNEXT_PREMIUM_DUEDATE(NEXT_PREMIUM_DUEDATE);
		}

		String POLICY_HOLDER1_FIRST_NAME = (String)attributes.get(
				"POLICY_HOLDER1_FIRST_NAME");

		if (POLICY_HOLDER1_FIRST_NAME != null) {
			setPOLICY_HOLDER1_FIRST_NAME(POLICY_HOLDER1_FIRST_NAME);
		}

		String POLICY_HOLDER1_MIDDLE_NAME = (String)attributes.get(
				"POLICY_HOLDER1_MIDDLE_NAME");

		if (POLICY_HOLDER1_MIDDLE_NAME != null) {
			setPOLICY_HOLDER1_MIDDLE_NAME(POLICY_HOLDER1_MIDDLE_NAME);
		}

		String POLICY_HOLDER1_LAST_NAME = (String)attributes.get(
				"POLICY_HOLDER1_LAST_NAME");

		if (POLICY_HOLDER1_LAST_NAME != null) {
			setPOLICY_HOLDER1_LAST_NAME(POLICY_HOLDER1_LAST_NAME);
		}

		Double SUM_ASSURED = (Double)attributes.get("SUM_ASSURED");

		if (SUM_ASSURED != null) {
			setSUM_ASSURED(SUM_ASSURED);
		}

		String POLICY_HOLDER2_FIRST_NAME = (String)attributes.get(
				"POLICY_HOLDER2_FIRST_NAME");

		if (POLICY_HOLDER2_FIRST_NAME != null) {
			setPOLICY_HOLDER2_FIRST_NAME(POLICY_HOLDER2_FIRST_NAME);
		}

		String POLICY_HOLDER2_MIDDLE_NAME = (String)attributes.get(
				"POLICY_HOLDER2_MIDDLE_NAME");

		if (POLICY_HOLDER2_MIDDLE_NAME != null) {
			setPOLICY_HOLDER2_MIDDLE_NAME(POLICY_HOLDER2_MIDDLE_NAME);
		}

		String POLICY_HOLDER2_LAST_NAME = (String)attributes.get(
				"POLICY_HOLDER2_LAST_NAME");

		if (POLICY_HOLDER2_LAST_NAME != null) {
			setPOLICY_HOLDER2_LAST_NAME(POLICY_HOLDER2_LAST_NAME);
		}

		String CHILD_FIRST_NAME = (String)attributes.get("CHILD_FIRST_NAME");

		if (CHILD_FIRST_NAME != null) {
			setCHILD_FIRST_NAME(CHILD_FIRST_NAME);
		}

		String CHILD_DOB = (String)attributes.get("CHILD_DOB");

		if (CHILD_DOB != null) {
			setCHILD_DOB(CHILD_DOB);
		}

		String CHILD_LAST_NAME = (String)attributes.get("CHILD_LAST_NAME");

		if (CHILD_LAST_NAME != null) {
			setCHILD_LAST_NAME(CHILD_LAST_NAME);
		}

		String CURRENT_STATUS = (String)attributes.get("CURRENT_STATUS");

		if (CURRENT_STATUS != null) {
			setCURRENT_STATUS(CURRENT_STATUS);
		}

		Integer PREMIUM_AMOUNT = (Integer)attributes.get("PREMIUM_AMOUNT");

		if (PREMIUM_AMOUNT != null) {
			setPREMIUM_AMOUNT(PREMIUM_AMOUNT);
		}

		String FREQUENCY = (String)attributes.get("FREQUENCY");

		if (FREQUENCY != null) {
			setFREQUENCY(FREQUENCY);
		}

		String BRANCH_CODE = (String)attributes.get("BRANCH_CODE");

		if (BRANCH_CODE != null) {
			setBRANCH_CODE(BRANCH_CODE);
		}

		String LG_CODE = (String)attributes.get("LG_CODE");

		if (LG_CODE != null) {
			setLG_CODE(LG_CODE);
		}

		String APPLICATION_NUMBER = (String)attributes.get("APPLICATION_NUMBER");

		if (APPLICATION_NUMBER != null) {
			setAPPLICATION_NUMBER(APPLICATION_NUMBER);
		}

		String APPLICATION_DATE = (String)attributes.get("APPLICATION_DATE");

		if (APPLICATION_DATE != null) {
			setAPPLICATION_DATE(APPLICATION_DATE);
		}

		String POLICY_HOLDER1_TITLE = (String)attributes.get(
				"POLICY_HOLDER1_TITLE");

		if (POLICY_HOLDER1_TITLE != null) {
			setPOLICY_HOLDER1_TITLE(POLICY_HOLDER1_TITLE);
		}

		String CRO_NAME = (String)attributes.get("CRO_NAME");

		if (CRO_NAME != null) {
			setCRO_NAME(CRO_NAME);
		}

		String CRO_NUMBER = (String)attributes.get("CRO_NUMBER");

		if (CRO_NUMBER != null) {
			setCRO_NUMBER(CRO_NUMBER);
		}

		String BRANCH_NAME = (String)attributes.get("BRANCH_NAME");

		if (BRANCH_NAME != null) {
			setBRANCH_NAME(BRANCH_NAME);
		}

		String PRODUCT_NAME = (String)attributes.get("PRODUCT_NAME");

		if (PRODUCT_NAME != null) {
			setPRODUCT_NAME(PRODUCT_NAME);
		}

		String REQUIREMENT_FLAG = (String)attributes.get("REQUIREMENT_FLAG");

		if (REQUIREMENT_FLAG != null) {
			setREQUIREMENT_FLAG(REQUIREMENT_FLAG);
		}

		Integer TERM = (Integer)attributes.get("TERM");

		if (TERM != null) {
			setTERM(TERM);
		}

		Date MATURITY_DATE = (Date)attributes.get("MATURITY_DATE");

		if (MATURITY_DATE != null) {
			setMATURITY_DATE(MATURITY_DATE);
		}

		Double AMOUNT_DEPOSITED = (Double)attributes.get("AMOUNT_DEPOSITED");

		if (AMOUNT_DEPOSITED != null) {
			setAMOUNT_DEPOSITED(AMOUNT_DEPOSITED);
		}

		Double TOTAL_DUE_AMT = (Double)attributes.get("TOTAL_DUE_AMT");

		if (TOTAL_DUE_AMT != null) {
			setTOTAL_DUE_AMT(TOTAL_DUE_AMT);
		}

		String CHANNEL_TYPE = (String)attributes.get("CHANNEL_TYPE");

		if (CHANNEL_TYPE != null) {
			setCHANNEL_TYPE(CHANNEL_TYPE);
		}

		String LIFE_ASSURED_NAME = (String)attributes.get("LIFE_ASSURED_NAME");

		if (LIFE_ASSURED_NAME != null) {
			setLIFE_ASSURED_NAME(LIFE_ASSURED_NAME);
		}

		Date LIFE_ASSURED_DOB = (Date)attributes.get("LIFE_ASSURED_DOB");

		if (LIFE_ASSURED_DOB != null) {
			setLIFE_ASSURED_DOB(LIFE_ASSURED_DOB);
		}

		String POLICY_HOLDER1_EMAIL = (String)attributes.get(
				"POLICY_HOLDER1_EMAIL");

		if (POLICY_HOLDER1_EMAIL != null) {
			setPOLICY_HOLDER1_EMAIL(POLICY_HOLDER1_EMAIL);
		}

		String POLICY_HOLDER1_ADD1 = (String)attributes.get(
				"POLICY_HOLDER1_ADD1");

		if (POLICY_HOLDER1_ADD1 != null) {
			setPOLICY_HOLDER1_ADD1(POLICY_HOLDER1_ADD1);
		}

		String POLICY_HOLDER1_ADD2 = (String)attributes.get(
				"POLICY_HOLDER1_ADD2");

		if (POLICY_HOLDER1_ADD2 != null) {
			setPOLICY_HOLDER1_ADD2(POLICY_HOLDER1_ADD2);
		}

		String POLICY_HOLDER1_CONTACT1 = (String)attributes.get(
				"POLICY_HOLDER1_CONTACT1");

		if (POLICY_HOLDER1_CONTACT1 != null) {
			setPOLICY_HOLDER1_CONTACT1(POLICY_HOLDER1_CONTACT1);
		}

		String POLICY_HOLDER1_CONTACT2 = (String)attributes.get(
				"POLICY_HOLDER1_CONTACT2");

		if (POLICY_HOLDER1_CONTACT2 != null) {
			setPOLICY_HOLDER1_CONTACT2(POLICY_HOLDER1_CONTACT2);
		}

		String POLICY_HOLDER1_DOB = (String)attributes.get("POLICY_HOLDER1_DOB");

		if (POLICY_HOLDER1_DOB != null) {
			setPOLICY_HOLDER1_DOB(POLICY_HOLDER1_DOB);
		}

		Date RISK_COMMENCEMENT_DATE = (Date)attributes.get(
				"RISK_COMMENCEMENT_DATE");

		if (RISK_COMMENCEMENT_DATE != null) {
			setRISK_COMMENCEMENT_DATE(RISK_COMMENCEMENT_DATE);
		}
	}

	@Override
	public String getPOLICY_ID() {
		if (_POLICY_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_ID;
		}
	}

	@Override
	public void setPOLICY_ID(String POLICY_ID) {
		_POLICY_ID = POLICY_ID;
	}

	@Override
	public int getCUSTOMER_ID() {
		return _CUSTOMER_ID;
	}

	@Override
	public void setCUSTOMER_ID(int CUSTOMER_ID) {
		_CUSTOMER_ID = CUSTOMER_ID;
	}

	@Override
	public int getPRODUCT_ID() {
		return _PRODUCT_ID;
	}

	@Override
	public void setPRODUCT_ID(int PRODUCT_ID) {
		_PRODUCT_ID = PRODUCT_ID;
	}

	@Override
	public String getPOLICY_DATE() {
		if (_POLICY_DATE == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_DATE;
		}
	}

	@Override
	public void setPOLICY_DATE(String POLICY_DATE) {
		_POLICY_DATE = POLICY_DATE;
	}

	@Override
	public String getNEXT_PREMIUM_DUEDATE() {
		if (_NEXT_PREMIUM_DUEDATE == null) {
			return StringPool.BLANK;
		}
		else {
			return _NEXT_PREMIUM_DUEDATE;
		}
	}

	@Override
	public void setNEXT_PREMIUM_DUEDATE(String NEXT_PREMIUM_DUEDATE) {
		_NEXT_PREMIUM_DUEDATE = NEXT_PREMIUM_DUEDATE;
	}

	@Override
	public String getPOLICY_HOLDER1_FIRST_NAME() {
		if (_POLICY_HOLDER1_FIRST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_FIRST_NAME;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_FIRST_NAME(String POLICY_HOLDER1_FIRST_NAME) {
		_POLICY_HOLDER1_FIRST_NAME = POLICY_HOLDER1_FIRST_NAME;
	}

	@Override
	public String getPOLICY_HOLDER1_MIDDLE_NAME() {
		if (_POLICY_HOLDER1_MIDDLE_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_MIDDLE_NAME;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_MIDDLE_NAME(String POLICY_HOLDER1_MIDDLE_NAME) {
		_POLICY_HOLDER1_MIDDLE_NAME = POLICY_HOLDER1_MIDDLE_NAME;
	}

	@Override
	public String getPOLICY_HOLDER1_LAST_NAME() {
		if (_POLICY_HOLDER1_LAST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_LAST_NAME;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_LAST_NAME(String POLICY_HOLDER1_LAST_NAME) {
		_POLICY_HOLDER1_LAST_NAME = POLICY_HOLDER1_LAST_NAME;
	}

	@Override
	public double getSUM_ASSURED() {
		return _SUM_ASSURED;
	}

	@Override
	public void setSUM_ASSURED(double SUM_ASSURED) {
		_SUM_ASSURED = SUM_ASSURED;
	}

	@Override
	public String getPOLICY_HOLDER2_FIRST_NAME() {
		if (_POLICY_HOLDER2_FIRST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER2_FIRST_NAME;
		}
	}

	@Override
	public void setPOLICY_HOLDER2_FIRST_NAME(String POLICY_HOLDER2_FIRST_NAME) {
		_POLICY_HOLDER2_FIRST_NAME = POLICY_HOLDER2_FIRST_NAME;
	}

	@Override
	public String getPOLICY_HOLDER2_MIDDLE_NAME() {
		if (_POLICY_HOLDER2_MIDDLE_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER2_MIDDLE_NAME;
		}
	}

	@Override
	public void setPOLICY_HOLDER2_MIDDLE_NAME(String POLICY_HOLDER2_MIDDLE_NAME) {
		_POLICY_HOLDER2_MIDDLE_NAME = POLICY_HOLDER2_MIDDLE_NAME;
	}

	@Override
	public String getPOLICY_HOLDER2_LAST_NAME() {
		if (_POLICY_HOLDER2_LAST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER2_LAST_NAME;
		}
	}

	@Override
	public void setPOLICY_HOLDER2_LAST_NAME(String POLICY_HOLDER2_LAST_NAME) {
		_POLICY_HOLDER2_LAST_NAME = POLICY_HOLDER2_LAST_NAME;
	}

	@Override
	public String getCHILD_FIRST_NAME() {
		if (_CHILD_FIRST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _CHILD_FIRST_NAME;
		}
	}

	@Override
	public void setCHILD_FIRST_NAME(String CHILD_FIRST_NAME) {
		_CHILD_FIRST_NAME = CHILD_FIRST_NAME;
	}

	@Override
	public String getCHILD_DOB() {
		if (_CHILD_DOB == null) {
			return StringPool.BLANK;
		}
		else {
			return _CHILD_DOB;
		}
	}

	@Override
	public void setCHILD_DOB(String CHILD_DOB) {
		_CHILD_DOB = CHILD_DOB;
	}

	@Override
	public String getCHILD_LAST_NAME() {
		if (_CHILD_LAST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _CHILD_LAST_NAME;
		}
	}

	@Override
	public void setCHILD_LAST_NAME(String CHILD_LAST_NAME) {
		_CHILD_LAST_NAME = CHILD_LAST_NAME;
	}

	@Override
	public String getCURRENT_STATUS() {
		if (_CURRENT_STATUS == null) {
			return StringPool.BLANK;
		}
		else {
			return _CURRENT_STATUS;
		}
	}

	@Override
	public void setCURRENT_STATUS(String CURRENT_STATUS) {
		_CURRENT_STATUS = CURRENT_STATUS;
	}

	@Override
	public int getPREMIUM_AMOUNT() {
		return _PREMIUM_AMOUNT;
	}

	@Override
	public void setPREMIUM_AMOUNT(int PREMIUM_AMOUNT) {
		_PREMIUM_AMOUNT = PREMIUM_AMOUNT;
	}

	@Override
	public String getFREQUENCY() {
		if (_FREQUENCY == null) {
			return StringPool.BLANK;
		}
		else {
			return _FREQUENCY;
		}
	}

	@Override
	public void setFREQUENCY(String FREQUENCY) {
		_FREQUENCY = FREQUENCY;
	}

	@Override
	public String getBRANCH_CODE() {
		if (_BRANCH_CODE == null) {
			return StringPool.BLANK;
		}
		else {
			return _BRANCH_CODE;
		}
	}

	@Override
	public void setBRANCH_CODE(String BRANCH_CODE) {
		_BRANCH_CODE = BRANCH_CODE;
	}

	@Override
	public String getLG_CODE() {
		if (_LG_CODE == null) {
			return StringPool.BLANK;
		}
		else {
			return _LG_CODE;
		}
	}

	@Override
	public void setLG_CODE(String LG_CODE) {
		_LG_CODE = LG_CODE;
	}

	@Override
	public String getAPPLICATION_NUMBER() {
		if (_APPLICATION_NUMBER == null) {
			return StringPool.BLANK;
		}
		else {
			return _APPLICATION_NUMBER;
		}
	}

	@Override
	public void setAPPLICATION_NUMBER(String APPLICATION_NUMBER) {
		_APPLICATION_NUMBER = APPLICATION_NUMBER;
	}

	@Override
	public String getAPPLICATION_DATE() {
		if (_APPLICATION_DATE == null) {
			return StringPool.BLANK;
		}
		else {
			return _APPLICATION_DATE;
		}
	}

	@Override
	public void setAPPLICATION_DATE(String APPLICATION_DATE) {
		_APPLICATION_DATE = APPLICATION_DATE;
	}

	@Override
	public String getPOLICY_HOLDER1_TITLE() {
		if (_POLICY_HOLDER1_TITLE == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_TITLE;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_TITLE(String POLICY_HOLDER1_TITLE) {
		_POLICY_HOLDER1_TITLE = POLICY_HOLDER1_TITLE;
	}

	@Override
	public String getCRO_NAME() {
		if (_CRO_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _CRO_NAME;
		}
	}

	@Override
	public void setCRO_NAME(String CRO_NAME) {
		_CRO_NAME = CRO_NAME;
	}

	@Override
	public String getCRO_NUMBER() {
		if (_CRO_NUMBER == null) {
			return StringPool.BLANK;
		}
		else {
			return _CRO_NUMBER;
		}
	}

	@Override
	public void setCRO_NUMBER(String CRO_NUMBER) {
		_CRO_NUMBER = CRO_NUMBER;
	}

	@Override
	public String getBRANCH_NAME() {
		if (_BRANCH_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _BRANCH_NAME;
		}
	}

	@Override
	public void setBRANCH_NAME(String BRANCH_NAME) {
		_BRANCH_NAME = BRANCH_NAME;
	}

	@Override
	public String getPRODUCT_NAME() {
		if (_PRODUCT_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _PRODUCT_NAME;
		}
	}

	@Override
	public void setPRODUCT_NAME(String PRODUCT_NAME) {
		_PRODUCT_NAME = PRODUCT_NAME;
	}

	@Override
	public String getREQUIREMENT_FLAG() {
		if (_REQUIREMENT_FLAG == null) {
			return StringPool.BLANK;
		}
		else {
			return _REQUIREMENT_FLAG;
		}
	}

	@Override
	public void setREQUIREMENT_FLAG(String REQUIREMENT_FLAG) {
		_REQUIREMENT_FLAG = REQUIREMENT_FLAG;
	}

	@Override
	public int getTERM() {
		return _TERM;
	}

	@Override
	public void setTERM(int TERM) {
		_TERM = TERM;
	}

	@Override
	public Date getMATURITY_DATE() {
		return _MATURITY_DATE;
	}

	@Override
	public void setMATURITY_DATE(Date MATURITY_DATE) {
		_MATURITY_DATE = MATURITY_DATE;
	}

	@Override
	public double getAMOUNT_DEPOSITED() {
		return _AMOUNT_DEPOSITED;
	}

	@Override
	public void setAMOUNT_DEPOSITED(double AMOUNT_DEPOSITED) {
		_AMOUNT_DEPOSITED = AMOUNT_DEPOSITED;
	}

	@Override
	public double getTOTAL_DUE_AMT() {
		return _TOTAL_DUE_AMT;
	}

	@Override
	public void setTOTAL_DUE_AMT(double TOTAL_DUE_AMT) {
		_TOTAL_DUE_AMT = TOTAL_DUE_AMT;
	}

	@Override
	public String getCHANNEL_TYPE() {
		if (_CHANNEL_TYPE == null) {
			return StringPool.BLANK;
		}
		else {
			return _CHANNEL_TYPE;
		}
	}

	@Override
	public void setCHANNEL_TYPE(String CHANNEL_TYPE) {
		_CHANNEL_TYPE = CHANNEL_TYPE;
	}

	@Override
	public String getLIFE_ASSURED_NAME() {
		if (_LIFE_ASSURED_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _LIFE_ASSURED_NAME;
		}
	}

	@Override
	public void setLIFE_ASSURED_NAME(String LIFE_ASSURED_NAME) {
		_LIFE_ASSURED_NAME = LIFE_ASSURED_NAME;
	}

	@Override
	public Date getLIFE_ASSURED_DOB() {
		return _LIFE_ASSURED_DOB;
	}

	@Override
	public void setLIFE_ASSURED_DOB(Date LIFE_ASSURED_DOB) {
		_LIFE_ASSURED_DOB = LIFE_ASSURED_DOB;
	}

	@Override
	public String getPOLICY_HOLDER1_EMAIL() {
		if (_POLICY_HOLDER1_EMAIL == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_EMAIL;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_EMAIL(String POLICY_HOLDER1_EMAIL) {
		_POLICY_HOLDER1_EMAIL = POLICY_HOLDER1_EMAIL;
	}

	@Override
	public String getPOLICY_HOLDER1_ADD1() {
		if (_POLICY_HOLDER1_ADD1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_ADD1;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_ADD1(String POLICY_HOLDER1_ADD1) {
		_POLICY_HOLDER1_ADD1 = POLICY_HOLDER1_ADD1;
	}

	@Override
	public String getPOLICY_HOLDER1_ADD2() {
		if (_POLICY_HOLDER1_ADD2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_ADD2;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_ADD2(String POLICY_HOLDER1_ADD2) {
		_POLICY_HOLDER1_ADD2 = POLICY_HOLDER1_ADD2;
	}

	@Override
	public String getPOLICY_HOLDER1_CONTACT1() {
		if (_POLICY_HOLDER1_CONTACT1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_CONTACT1;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_CONTACT1(String POLICY_HOLDER1_CONTACT1) {
		_POLICY_HOLDER1_CONTACT1 = POLICY_HOLDER1_CONTACT1;
	}

	@Override
	public String getPOLICY_HOLDER1_CONTACT2() {
		if (_POLICY_HOLDER1_CONTACT2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_CONTACT2;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_CONTACT2(String POLICY_HOLDER1_CONTACT2) {
		_POLICY_HOLDER1_CONTACT2 = POLICY_HOLDER1_CONTACT2;
	}

	@Override
	public String getPOLICY_HOLDER1_DOB() {
		if (_POLICY_HOLDER1_DOB == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_HOLDER1_DOB;
		}
	}

	@Override
	public void setPOLICY_HOLDER1_DOB(String POLICY_HOLDER1_DOB) {
		_POLICY_HOLDER1_DOB = POLICY_HOLDER1_DOB;
	}

	@Override
	public Date getRISK_COMMENCEMENT_DATE() {
		return _RISK_COMMENCEMENT_DATE;
	}

	@Override
	public void setRISK_COMMENCEMENT_DATE(Date RISK_COMMENCEMENT_DATE) {
		_RISK_COMMENCEMENT_DATE = RISK_COMMENCEMENT_DATE;
	}

	@Override
	public PolicyInfo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PolicyInfo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PolicyInfoImpl policyInfoImpl = new PolicyInfoImpl();

		policyInfoImpl.setPOLICY_ID(getPOLICY_ID());
		policyInfoImpl.setCUSTOMER_ID(getCUSTOMER_ID());
		policyInfoImpl.setPRODUCT_ID(getPRODUCT_ID());
		policyInfoImpl.setPOLICY_DATE(getPOLICY_DATE());
		policyInfoImpl.setNEXT_PREMIUM_DUEDATE(getNEXT_PREMIUM_DUEDATE());
		policyInfoImpl.setPOLICY_HOLDER1_FIRST_NAME(getPOLICY_HOLDER1_FIRST_NAME());
		policyInfoImpl.setPOLICY_HOLDER1_MIDDLE_NAME(getPOLICY_HOLDER1_MIDDLE_NAME());
		policyInfoImpl.setPOLICY_HOLDER1_LAST_NAME(getPOLICY_HOLDER1_LAST_NAME());
		policyInfoImpl.setSUM_ASSURED(getSUM_ASSURED());
		policyInfoImpl.setPOLICY_HOLDER2_FIRST_NAME(getPOLICY_HOLDER2_FIRST_NAME());
		policyInfoImpl.setPOLICY_HOLDER2_MIDDLE_NAME(getPOLICY_HOLDER2_MIDDLE_NAME());
		policyInfoImpl.setPOLICY_HOLDER2_LAST_NAME(getPOLICY_HOLDER2_LAST_NAME());
		policyInfoImpl.setCHILD_FIRST_NAME(getCHILD_FIRST_NAME());
		policyInfoImpl.setCHILD_DOB(getCHILD_DOB());
		policyInfoImpl.setCHILD_LAST_NAME(getCHILD_LAST_NAME());
		policyInfoImpl.setCURRENT_STATUS(getCURRENT_STATUS());
		policyInfoImpl.setPREMIUM_AMOUNT(getPREMIUM_AMOUNT());
		policyInfoImpl.setFREQUENCY(getFREQUENCY());
		policyInfoImpl.setBRANCH_CODE(getBRANCH_CODE());
		policyInfoImpl.setLG_CODE(getLG_CODE());
		policyInfoImpl.setAPPLICATION_NUMBER(getAPPLICATION_NUMBER());
		policyInfoImpl.setAPPLICATION_DATE(getAPPLICATION_DATE());
		policyInfoImpl.setPOLICY_HOLDER1_TITLE(getPOLICY_HOLDER1_TITLE());
		policyInfoImpl.setCRO_NAME(getCRO_NAME());
		policyInfoImpl.setCRO_NUMBER(getCRO_NUMBER());
		policyInfoImpl.setBRANCH_NAME(getBRANCH_NAME());
		policyInfoImpl.setPRODUCT_NAME(getPRODUCT_NAME());
		policyInfoImpl.setREQUIREMENT_FLAG(getREQUIREMENT_FLAG());
		policyInfoImpl.setTERM(getTERM());
		policyInfoImpl.setMATURITY_DATE(getMATURITY_DATE());
		policyInfoImpl.setAMOUNT_DEPOSITED(getAMOUNT_DEPOSITED());
		policyInfoImpl.setTOTAL_DUE_AMT(getTOTAL_DUE_AMT());
		policyInfoImpl.setCHANNEL_TYPE(getCHANNEL_TYPE());
		policyInfoImpl.setLIFE_ASSURED_NAME(getLIFE_ASSURED_NAME());
		policyInfoImpl.setLIFE_ASSURED_DOB(getLIFE_ASSURED_DOB());
		policyInfoImpl.setPOLICY_HOLDER1_EMAIL(getPOLICY_HOLDER1_EMAIL());
		policyInfoImpl.setPOLICY_HOLDER1_ADD1(getPOLICY_HOLDER1_ADD1());
		policyInfoImpl.setPOLICY_HOLDER1_ADD2(getPOLICY_HOLDER1_ADD2());
		policyInfoImpl.setPOLICY_HOLDER1_CONTACT1(getPOLICY_HOLDER1_CONTACT1());
		policyInfoImpl.setPOLICY_HOLDER1_CONTACT2(getPOLICY_HOLDER1_CONTACT2());
		policyInfoImpl.setPOLICY_HOLDER1_DOB(getPOLICY_HOLDER1_DOB());
		policyInfoImpl.setRISK_COMMENCEMENT_DATE(getRISK_COMMENCEMENT_DATE());

		policyInfoImpl.resetOriginalValues();

		return policyInfoImpl;
	}

	@Override
	public int compareTo(PolicyInfo policyInfo) {
		String primaryKey = policyInfo.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PolicyInfo)) {
			return false;
		}

		PolicyInfo policyInfo = (PolicyInfo)obj;

		String primaryKey = policyInfo.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PolicyInfo> toCacheModel() {
		PolicyInfoCacheModel policyInfoCacheModel = new PolicyInfoCacheModel();

		policyInfoCacheModel.POLICY_ID = getPOLICY_ID();

		String POLICY_ID = policyInfoCacheModel.POLICY_ID;

		if ((POLICY_ID != null) && (POLICY_ID.length() == 0)) {
			policyInfoCacheModel.POLICY_ID = null;
		}

		policyInfoCacheModel.CUSTOMER_ID = getCUSTOMER_ID();

		policyInfoCacheModel.PRODUCT_ID = getPRODUCT_ID();

		policyInfoCacheModel.POLICY_DATE = getPOLICY_DATE();

		String POLICY_DATE = policyInfoCacheModel.POLICY_DATE;

		if ((POLICY_DATE != null) && (POLICY_DATE.length() == 0)) {
			policyInfoCacheModel.POLICY_DATE = null;
		}

		policyInfoCacheModel.NEXT_PREMIUM_DUEDATE = getNEXT_PREMIUM_DUEDATE();

		String NEXT_PREMIUM_DUEDATE = policyInfoCacheModel.NEXT_PREMIUM_DUEDATE;

		if ((NEXT_PREMIUM_DUEDATE != null) &&
				(NEXT_PREMIUM_DUEDATE.length() == 0)) {
			policyInfoCacheModel.NEXT_PREMIUM_DUEDATE = null;
		}

		policyInfoCacheModel.POLICY_HOLDER1_FIRST_NAME = getPOLICY_HOLDER1_FIRST_NAME();

		String POLICY_HOLDER1_FIRST_NAME = policyInfoCacheModel.POLICY_HOLDER1_FIRST_NAME;

		if ((POLICY_HOLDER1_FIRST_NAME != null) &&
				(POLICY_HOLDER1_FIRST_NAME.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_FIRST_NAME = null;
		}

		policyInfoCacheModel.POLICY_HOLDER1_MIDDLE_NAME = getPOLICY_HOLDER1_MIDDLE_NAME();

		String POLICY_HOLDER1_MIDDLE_NAME = policyInfoCacheModel.POLICY_HOLDER1_MIDDLE_NAME;

		if ((POLICY_HOLDER1_MIDDLE_NAME != null) &&
				(POLICY_HOLDER1_MIDDLE_NAME.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_MIDDLE_NAME = null;
		}

		policyInfoCacheModel.POLICY_HOLDER1_LAST_NAME = getPOLICY_HOLDER1_LAST_NAME();

		String POLICY_HOLDER1_LAST_NAME = policyInfoCacheModel.POLICY_HOLDER1_LAST_NAME;

		if ((POLICY_HOLDER1_LAST_NAME != null) &&
				(POLICY_HOLDER1_LAST_NAME.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_LAST_NAME = null;
		}

		policyInfoCacheModel.SUM_ASSURED = getSUM_ASSURED();

		policyInfoCacheModel.POLICY_HOLDER2_FIRST_NAME = getPOLICY_HOLDER2_FIRST_NAME();

		String POLICY_HOLDER2_FIRST_NAME = policyInfoCacheModel.POLICY_HOLDER2_FIRST_NAME;

		if ((POLICY_HOLDER2_FIRST_NAME != null) &&
				(POLICY_HOLDER2_FIRST_NAME.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER2_FIRST_NAME = null;
		}

		policyInfoCacheModel.POLICY_HOLDER2_MIDDLE_NAME = getPOLICY_HOLDER2_MIDDLE_NAME();

		String POLICY_HOLDER2_MIDDLE_NAME = policyInfoCacheModel.POLICY_HOLDER2_MIDDLE_NAME;

		if ((POLICY_HOLDER2_MIDDLE_NAME != null) &&
				(POLICY_HOLDER2_MIDDLE_NAME.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER2_MIDDLE_NAME = null;
		}

		policyInfoCacheModel.POLICY_HOLDER2_LAST_NAME = getPOLICY_HOLDER2_LAST_NAME();

		String POLICY_HOLDER2_LAST_NAME = policyInfoCacheModel.POLICY_HOLDER2_LAST_NAME;

		if ((POLICY_HOLDER2_LAST_NAME != null) &&
				(POLICY_HOLDER2_LAST_NAME.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER2_LAST_NAME = null;
		}

		policyInfoCacheModel.CHILD_FIRST_NAME = getCHILD_FIRST_NAME();

		String CHILD_FIRST_NAME = policyInfoCacheModel.CHILD_FIRST_NAME;

		if ((CHILD_FIRST_NAME != null) && (CHILD_FIRST_NAME.length() == 0)) {
			policyInfoCacheModel.CHILD_FIRST_NAME = null;
		}

		policyInfoCacheModel.CHILD_DOB = getCHILD_DOB();

		String CHILD_DOB = policyInfoCacheModel.CHILD_DOB;

		if ((CHILD_DOB != null) && (CHILD_DOB.length() == 0)) {
			policyInfoCacheModel.CHILD_DOB = null;
		}

		policyInfoCacheModel.CHILD_LAST_NAME = getCHILD_LAST_NAME();

		String CHILD_LAST_NAME = policyInfoCacheModel.CHILD_LAST_NAME;

		if ((CHILD_LAST_NAME != null) && (CHILD_LAST_NAME.length() == 0)) {
			policyInfoCacheModel.CHILD_LAST_NAME = null;
		}

		policyInfoCacheModel.CURRENT_STATUS = getCURRENT_STATUS();

		String CURRENT_STATUS = policyInfoCacheModel.CURRENT_STATUS;

		if ((CURRENT_STATUS != null) && (CURRENT_STATUS.length() == 0)) {
			policyInfoCacheModel.CURRENT_STATUS = null;
		}

		policyInfoCacheModel.PREMIUM_AMOUNT = getPREMIUM_AMOUNT();

		policyInfoCacheModel.FREQUENCY = getFREQUENCY();

		String FREQUENCY = policyInfoCacheModel.FREQUENCY;

		if ((FREQUENCY != null) && (FREQUENCY.length() == 0)) {
			policyInfoCacheModel.FREQUENCY = null;
		}

		policyInfoCacheModel.BRANCH_CODE = getBRANCH_CODE();

		String BRANCH_CODE = policyInfoCacheModel.BRANCH_CODE;

		if ((BRANCH_CODE != null) && (BRANCH_CODE.length() == 0)) {
			policyInfoCacheModel.BRANCH_CODE = null;
		}

		policyInfoCacheModel.LG_CODE = getLG_CODE();

		String LG_CODE = policyInfoCacheModel.LG_CODE;

		if ((LG_CODE != null) && (LG_CODE.length() == 0)) {
			policyInfoCacheModel.LG_CODE = null;
		}

		policyInfoCacheModel.APPLICATION_NUMBER = getAPPLICATION_NUMBER();

		String APPLICATION_NUMBER = policyInfoCacheModel.APPLICATION_NUMBER;

		if ((APPLICATION_NUMBER != null) && (APPLICATION_NUMBER.length() == 0)) {
			policyInfoCacheModel.APPLICATION_NUMBER = null;
		}

		policyInfoCacheModel.APPLICATION_DATE = getAPPLICATION_DATE();

		String APPLICATION_DATE = policyInfoCacheModel.APPLICATION_DATE;

		if ((APPLICATION_DATE != null) && (APPLICATION_DATE.length() == 0)) {
			policyInfoCacheModel.APPLICATION_DATE = null;
		}

		policyInfoCacheModel.POLICY_HOLDER1_TITLE = getPOLICY_HOLDER1_TITLE();

		String POLICY_HOLDER1_TITLE = policyInfoCacheModel.POLICY_HOLDER1_TITLE;

		if ((POLICY_HOLDER1_TITLE != null) &&
				(POLICY_HOLDER1_TITLE.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_TITLE = null;
		}

		policyInfoCacheModel.CRO_NAME = getCRO_NAME();

		String CRO_NAME = policyInfoCacheModel.CRO_NAME;

		if ((CRO_NAME != null) && (CRO_NAME.length() == 0)) {
			policyInfoCacheModel.CRO_NAME = null;
		}

		policyInfoCacheModel.CRO_NUMBER = getCRO_NUMBER();

		String CRO_NUMBER = policyInfoCacheModel.CRO_NUMBER;

		if ((CRO_NUMBER != null) && (CRO_NUMBER.length() == 0)) {
			policyInfoCacheModel.CRO_NUMBER = null;
		}

		policyInfoCacheModel.BRANCH_NAME = getBRANCH_NAME();

		String BRANCH_NAME = policyInfoCacheModel.BRANCH_NAME;

		if ((BRANCH_NAME != null) && (BRANCH_NAME.length() == 0)) {
			policyInfoCacheModel.BRANCH_NAME = null;
		}

		policyInfoCacheModel.PRODUCT_NAME = getPRODUCT_NAME();

		String PRODUCT_NAME = policyInfoCacheModel.PRODUCT_NAME;

		if ((PRODUCT_NAME != null) && (PRODUCT_NAME.length() == 0)) {
			policyInfoCacheModel.PRODUCT_NAME = null;
		}

		policyInfoCacheModel.REQUIREMENT_FLAG = getREQUIREMENT_FLAG();

		String REQUIREMENT_FLAG = policyInfoCacheModel.REQUIREMENT_FLAG;

		if ((REQUIREMENT_FLAG != null) && (REQUIREMENT_FLAG.length() == 0)) {
			policyInfoCacheModel.REQUIREMENT_FLAG = null;
		}

		policyInfoCacheModel.TERM = getTERM();

		Date MATURITY_DATE = getMATURITY_DATE();

		if (MATURITY_DATE != null) {
			policyInfoCacheModel.MATURITY_DATE = MATURITY_DATE.getTime();
		}
		else {
			policyInfoCacheModel.MATURITY_DATE = Long.MIN_VALUE;
		}

		policyInfoCacheModel.AMOUNT_DEPOSITED = getAMOUNT_DEPOSITED();

		policyInfoCacheModel.TOTAL_DUE_AMT = getTOTAL_DUE_AMT();

		policyInfoCacheModel.CHANNEL_TYPE = getCHANNEL_TYPE();

		String CHANNEL_TYPE = policyInfoCacheModel.CHANNEL_TYPE;

		if ((CHANNEL_TYPE != null) && (CHANNEL_TYPE.length() == 0)) {
			policyInfoCacheModel.CHANNEL_TYPE = null;
		}

		policyInfoCacheModel.LIFE_ASSURED_NAME = getLIFE_ASSURED_NAME();

		String LIFE_ASSURED_NAME = policyInfoCacheModel.LIFE_ASSURED_NAME;

		if ((LIFE_ASSURED_NAME != null) && (LIFE_ASSURED_NAME.length() == 0)) {
			policyInfoCacheModel.LIFE_ASSURED_NAME = null;
		}

		Date LIFE_ASSURED_DOB = getLIFE_ASSURED_DOB();

		if (LIFE_ASSURED_DOB != null) {
			policyInfoCacheModel.LIFE_ASSURED_DOB = LIFE_ASSURED_DOB.getTime();
		}
		else {
			policyInfoCacheModel.LIFE_ASSURED_DOB = Long.MIN_VALUE;
		}

		policyInfoCacheModel.POLICY_HOLDER1_EMAIL = getPOLICY_HOLDER1_EMAIL();

		String POLICY_HOLDER1_EMAIL = policyInfoCacheModel.POLICY_HOLDER1_EMAIL;

		if ((POLICY_HOLDER1_EMAIL != null) &&
				(POLICY_HOLDER1_EMAIL.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_EMAIL = null;
		}

		policyInfoCacheModel.POLICY_HOLDER1_ADD1 = getPOLICY_HOLDER1_ADD1();

		String POLICY_HOLDER1_ADD1 = policyInfoCacheModel.POLICY_HOLDER1_ADD1;

		if ((POLICY_HOLDER1_ADD1 != null) &&
				(POLICY_HOLDER1_ADD1.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_ADD1 = null;
		}

		policyInfoCacheModel.POLICY_HOLDER1_ADD2 = getPOLICY_HOLDER1_ADD2();

		String POLICY_HOLDER1_ADD2 = policyInfoCacheModel.POLICY_HOLDER1_ADD2;

		if ((POLICY_HOLDER1_ADD2 != null) &&
				(POLICY_HOLDER1_ADD2.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_ADD2 = null;
		}

		policyInfoCacheModel.POLICY_HOLDER1_CONTACT1 = getPOLICY_HOLDER1_CONTACT1();

		String POLICY_HOLDER1_CONTACT1 = policyInfoCacheModel.POLICY_HOLDER1_CONTACT1;

		if ((POLICY_HOLDER1_CONTACT1 != null) &&
				(POLICY_HOLDER1_CONTACT1.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_CONTACT1 = null;
		}

		policyInfoCacheModel.POLICY_HOLDER1_CONTACT2 = getPOLICY_HOLDER1_CONTACT2();

		String POLICY_HOLDER1_CONTACT2 = policyInfoCacheModel.POLICY_HOLDER1_CONTACT2;

		if ((POLICY_HOLDER1_CONTACT2 != null) &&
				(POLICY_HOLDER1_CONTACT2.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_CONTACT2 = null;
		}

		policyInfoCacheModel.POLICY_HOLDER1_DOB = getPOLICY_HOLDER1_DOB();

		String POLICY_HOLDER1_DOB = policyInfoCacheModel.POLICY_HOLDER1_DOB;

		if ((POLICY_HOLDER1_DOB != null) && (POLICY_HOLDER1_DOB.length() == 0)) {
			policyInfoCacheModel.POLICY_HOLDER1_DOB = null;
		}

		Date RISK_COMMENCEMENT_DATE = getRISK_COMMENCEMENT_DATE();

		if (RISK_COMMENCEMENT_DATE != null) {
			policyInfoCacheModel.RISK_COMMENCEMENT_DATE = RISK_COMMENCEMENT_DATE.getTime();
		}
		else {
			policyInfoCacheModel.RISK_COMMENCEMENT_DATE = Long.MIN_VALUE;
		}

		return policyInfoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(85);

		sb.append("{POLICY_ID=");
		sb.append(getPOLICY_ID());
		sb.append(", CUSTOMER_ID=");
		sb.append(getCUSTOMER_ID());
		sb.append(", PRODUCT_ID=");
		sb.append(getPRODUCT_ID());
		sb.append(", POLICY_DATE=");
		sb.append(getPOLICY_DATE());
		sb.append(", NEXT_PREMIUM_DUEDATE=");
		sb.append(getNEXT_PREMIUM_DUEDATE());
		sb.append(", POLICY_HOLDER1_FIRST_NAME=");
		sb.append(getPOLICY_HOLDER1_FIRST_NAME());
		sb.append(", POLICY_HOLDER1_MIDDLE_NAME=");
		sb.append(getPOLICY_HOLDER1_MIDDLE_NAME());
		sb.append(", POLICY_HOLDER1_LAST_NAME=");
		sb.append(getPOLICY_HOLDER1_LAST_NAME());
		sb.append(", SUM_ASSURED=");
		sb.append(getSUM_ASSURED());
		sb.append(", POLICY_HOLDER2_FIRST_NAME=");
		sb.append(getPOLICY_HOLDER2_FIRST_NAME());
		sb.append(", POLICY_HOLDER2_MIDDLE_NAME=");
		sb.append(getPOLICY_HOLDER2_MIDDLE_NAME());
		sb.append(", POLICY_HOLDER2_LAST_NAME=");
		sb.append(getPOLICY_HOLDER2_LAST_NAME());
		sb.append(", CHILD_FIRST_NAME=");
		sb.append(getCHILD_FIRST_NAME());
		sb.append(", CHILD_DOB=");
		sb.append(getCHILD_DOB());
		sb.append(", CHILD_LAST_NAME=");
		sb.append(getCHILD_LAST_NAME());
		sb.append(", CURRENT_STATUS=");
		sb.append(getCURRENT_STATUS());
		sb.append(", PREMIUM_AMOUNT=");
		sb.append(getPREMIUM_AMOUNT());
		sb.append(", FREQUENCY=");
		sb.append(getFREQUENCY());
		sb.append(", BRANCH_CODE=");
		sb.append(getBRANCH_CODE());
		sb.append(", LG_CODE=");
		sb.append(getLG_CODE());
		sb.append(", APPLICATION_NUMBER=");
		sb.append(getAPPLICATION_NUMBER());
		sb.append(", APPLICATION_DATE=");
		sb.append(getAPPLICATION_DATE());
		sb.append(", POLICY_HOLDER1_TITLE=");
		sb.append(getPOLICY_HOLDER1_TITLE());
		sb.append(", CRO_NAME=");
		sb.append(getCRO_NAME());
		sb.append(", CRO_NUMBER=");
		sb.append(getCRO_NUMBER());
		sb.append(", BRANCH_NAME=");
		sb.append(getBRANCH_NAME());
		sb.append(", PRODUCT_NAME=");
		sb.append(getPRODUCT_NAME());
		sb.append(", REQUIREMENT_FLAG=");
		sb.append(getREQUIREMENT_FLAG());
		sb.append(", TERM=");
		sb.append(getTERM());
		sb.append(", MATURITY_DATE=");
		sb.append(getMATURITY_DATE());
		sb.append(", AMOUNT_DEPOSITED=");
		sb.append(getAMOUNT_DEPOSITED());
		sb.append(", TOTAL_DUE_AMT=");
		sb.append(getTOTAL_DUE_AMT());
		sb.append(", CHANNEL_TYPE=");
		sb.append(getCHANNEL_TYPE());
		sb.append(", LIFE_ASSURED_NAME=");
		sb.append(getLIFE_ASSURED_NAME());
		sb.append(", LIFE_ASSURED_DOB=");
		sb.append(getLIFE_ASSURED_DOB());
		sb.append(", POLICY_HOLDER1_EMAIL=");
		sb.append(getPOLICY_HOLDER1_EMAIL());
		sb.append(", POLICY_HOLDER1_ADD1=");
		sb.append(getPOLICY_HOLDER1_ADD1());
		sb.append(", POLICY_HOLDER1_ADD2=");
		sb.append(getPOLICY_HOLDER1_ADD2());
		sb.append(", POLICY_HOLDER1_CONTACT1=");
		sb.append(getPOLICY_HOLDER1_CONTACT1());
		sb.append(", POLICY_HOLDER1_CONTACT2=");
		sb.append(getPOLICY_HOLDER1_CONTACT2());
		sb.append(", POLICY_HOLDER1_DOB=");
		sb.append(getPOLICY_HOLDER1_DOB());
		sb.append(", RISK_COMMENCEMENT_DATE=");
		sb.append(getRISK_COMMENCEMENT_DATE());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(130);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.PolicyInfo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>POLICY_ID</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CUSTOMER_ID</column-name><column-value><![CDATA[");
		sb.append(getCUSTOMER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PRODUCT_ID</column-name><column-value><![CDATA[");
		sb.append(getPRODUCT_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_DATE</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NEXT_PREMIUM_DUEDATE</column-name><column-value><![CDATA[");
		sb.append(getNEXT_PREMIUM_DUEDATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_FIRST_NAME</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_FIRST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_MIDDLE_NAME</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_MIDDLE_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_LAST_NAME</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_LAST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SUM_ASSURED</column-name><column-value><![CDATA[");
		sb.append(getSUM_ASSURED());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER2_FIRST_NAME</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER2_FIRST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER2_MIDDLE_NAME</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER2_MIDDLE_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER2_LAST_NAME</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER2_LAST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CHILD_FIRST_NAME</column-name><column-value><![CDATA[");
		sb.append(getCHILD_FIRST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CHILD_DOB</column-name><column-value><![CDATA[");
		sb.append(getCHILD_DOB());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CHILD_LAST_NAME</column-name><column-value><![CDATA[");
		sb.append(getCHILD_LAST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CURRENT_STATUS</column-name><column-value><![CDATA[");
		sb.append(getCURRENT_STATUS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PREMIUM_AMOUNT</column-name><column-value><![CDATA[");
		sb.append(getPREMIUM_AMOUNT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FREQUENCY</column-name><column-value><![CDATA[");
		sb.append(getFREQUENCY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>BRANCH_CODE</column-name><column-value><![CDATA[");
		sb.append(getBRANCH_CODE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LG_CODE</column-name><column-value><![CDATA[");
		sb.append(getLG_CODE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>APPLICATION_NUMBER</column-name><column-value><![CDATA[");
		sb.append(getAPPLICATION_NUMBER());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>APPLICATION_DATE</column-name><column-value><![CDATA[");
		sb.append(getAPPLICATION_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_TITLE</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_TITLE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CRO_NAME</column-name><column-value><![CDATA[");
		sb.append(getCRO_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CRO_NUMBER</column-name><column-value><![CDATA[");
		sb.append(getCRO_NUMBER());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>BRANCH_NAME</column-name><column-value><![CDATA[");
		sb.append(getBRANCH_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PRODUCT_NAME</column-name><column-value><![CDATA[");
		sb.append(getPRODUCT_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>REQUIREMENT_FLAG</column-name><column-value><![CDATA[");
		sb.append(getREQUIREMENT_FLAG());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TERM</column-name><column-value><![CDATA[");
		sb.append(getTERM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MATURITY_DATE</column-name><column-value><![CDATA[");
		sb.append(getMATURITY_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AMOUNT_DEPOSITED</column-name><column-value><![CDATA[");
		sb.append(getAMOUNT_DEPOSITED());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TOTAL_DUE_AMT</column-name><column-value><![CDATA[");
		sb.append(getTOTAL_DUE_AMT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CHANNEL_TYPE</column-name><column-value><![CDATA[");
		sb.append(getCHANNEL_TYPE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LIFE_ASSURED_NAME</column-name><column-value><![CDATA[");
		sb.append(getLIFE_ASSURED_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LIFE_ASSURED_DOB</column-name><column-value><![CDATA[");
		sb.append(getLIFE_ASSURED_DOB());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_EMAIL</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_EMAIL());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_ADD1</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_ADD1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_ADD2</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_ADD2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_CONTACT1</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_CONTACT1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_CONTACT2</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_CONTACT2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_HOLDER1_DOB</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_HOLDER1_DOB());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RISK_COMMENCEMENT_DATE</column-name><column-value><![CDATA[");
		sb.append(getRISK_COMMENCEMENT_DATE());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PolicyInfo.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PolicyInfo.class
		};
	private String _POLICY_ID;
	private int _CUSTOMER_ID;
	private int _PRODUCT_ID;
	private String _POLICY_DATE;
	private String _NEXT_PREMIUM_DUEDATE;
	private String _POLICY_HOLDER1_FIRST_NAME;
	private String _POLICY_HOLDER1_MIDDLE_NAME;
	private String _POLICY_HOLDER1_LAST_NAME;
	private double _SUM_ASSURED;
	private String _POLICY_HOLDER2_FIRST_NAME;
	private String _POLICY_HOLDER2_MIDDLE_NAME;
	private String _POLICY_HOLDER2_LAST_NAME;
	private String _CHILD_FIRST_NAME;
	private String _CHILD_DOB;
	private String _CHILD_LAST_NAME;
	private String _CURRENT_STATUS;
	private int _PREMIUM_AMOUNT;
	private String _FREQUENCY;
	private String _BRANCH_CODE;
	private String _LG_CODE;
	private String _APPLICATION_NUMBER;
	private String _APPLICATION_DATE;
	private String _POLICY_HOLDER1_TITLE;
	private String _CRO_NAME;
	private String _CRO_NUMBER;
	private String _BRANCH_NAME;
	private String _PRODUCT_NAME;
	private String _REQUIREMENT_FLAG;
	private int _TERM;
	private Date _MATURITY_DATE;
	private double _AMOUNT_DEPOSITED;
	private double _TOTAL_DUE_AMT;
	private String _CHANNEL_TYPE;
	private String _LIFE_ASSURED_NAME;
	private Date _LIFE_ASSURED_DOB;
	private String _POLICY_HOLDER1_EMAIL;
	private String _POLICY_HOLDER1_ADD1;
	private String _POLICY_HOLDER1_ADD2;
	private String _POLICY_HOLDER1_CONTACT1;
	private String _POLICY_HOLDER1_CONTACT2;
	private String _POLICY_HOLDER1_DOB;
	private Date _RISK_COMMENCEMENT_DATE;
	private PolicyInfo _escapedModel;
}