/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.PolicyTopupDetails;
import com.ifli.rapid.model.PolicyTopupDetailsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PolicyTopupDetails service. Represents a row in the &quot;policy_topup_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.PolicyTopupDetailsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyTopupDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PolicyTopupDetailsImpl
 * @see com.ifli.rapid.model.PolicyTopupDetails
 * @see com.ifli.rapid.model.PolicyTopupDetailsModel
 * @generated
 */
public class PolicyTopupDetailsModelImpl extends BaseModelImpl<PolicyTopupDetails>
	implements PolicyTopupDetailsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy topup details model instance should use the {@link com.ifli.rapid.model.PolicyTopupDetails} interface instead.
	 */
	public static final String TABLE_NAME = "policy_topup_details";
	public static final Object[][] TABLE_COLUMNS = {
			{ "TOPUP_ID", Types.INTEGER },
			{ "POLICY_ID", Types.VARCHAR },
			{ "QRC_ASR_ID", Types.INTEGER },
			{ "FUND_ID", Types.INTEGER },
			{ "FUND_VALUE", Types.DOUBLE },
			{ "TOPUP_VALUE", Types.DOUBLE },
			{ "TOT_VALUE", Types.DOUBLE },
			{ "TOPUP_PERCENTAGE", Types.DOUBLE },
			{ "CreatedBy", Types.VARCHAR },
			{ "CreatedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR },
			{ "ModifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table policy_topup_details (TOPUP_ID INTEGER not null primary key IDENTITY,POLICY_ID VARCHAR(75) null,QRC_ASR_ID INTEGER,FUND_ID INTEGER,FUND_VALUE DOUBLE,TOPUP_VALUE DOUBLE,TOT_VALUE DOUBLE,TOPUP_PERCENTAGE DOUBLE,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table policy_topup_details";
	public static final String ORDER_BY_JPQL = " ORDER BY policyTopupDetails.TOPUP_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY policy_topup_details.TOPUP_ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.PolicyTopupDetails"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.PolicyTopupDetails"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.PolicyTopupDetails"));

	public PolicyTopupDetailsModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _TOPUP_ID;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setTOPUP_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _TOPUP_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PolicyTopupDetails.class;
	}

	@Override
	public String getModelClassName() {
		return PolicyTopupDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("TOPUP_ID", getTOPUP_ID());
		attributes.put("POLICY_ID", getPOLICY_ID());
		attributes.put("QRC_ASR_ID", getQRC_ASR_ID());
		attributes.put("FUND_ID", getFUND_ID());
		attributes.put("FUND_VALUE", getFUND_VALUE());
		attributes.put("TOPUP_VALUE", getTOPUP_VALUE());
		attributes.put("TOT_VALUE", getTOT_VALUE());
		attributes.put("TOPUP_PERCENTAGE", getTOPUP_PERCENTAGE());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("CreatedDate", getCreatedDate());
		attributes.put("ModifiedBy", getModifiedBy());
		attributes.put("ModifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer TOPUP_ID = (Integer)attributes.get("TOPUP_ID");

		if (TOPUP_ID != null) {
			setTOPUP_ID(TOPUP_ID);
		}

		String POLICY_ID = (String)attributes.get("POLICY_ID");

		if (POLICY_ID != null) {
			setPOLICY_ID(POLICY_ID);
		}

		Integer QRC_ASR_ID = (Integer)attributes.get("QRC_ASR_ID");

		if (QRC_ASR_ID != null) {
			setQRC_ASR_ID(QRC_ASR_ID);
		}

		Integer FUND_ID = (Integer)attributes.get("FUND_ID");

		if (FUND_ID != null) {
			setFUND_ID(FUND_ID);
		}

		Double FUND_VALUE = (Double)attributes.get("FUND_VALUE");

		if (FUND_VALUE != null) {
			setFUND_VALUE(FUND_VALUE);
		}

		Double TOPUP_VALUE = (Double)attributes.get("TOPUP_VALUE");

		if (TOPUP_VALUE != null) {
			setTOPUP_VALUE(TOPUP_VALUE);
		}

		Double TOT_VALUE = (Double)attributes.get("TOT_VALUE");

		if (TOT_VALUE != null) {
			setTOT_VALUE(TOT_VALUE);
		}

		Double TOPUP_PERCENTAGE = (Double)attributes.get("TOPUP_PERCENTAGE");

		if (TOPUP_PERCENTAGE != null) {
			setTOPUP_PERCENTAGE(TOPUP_PERCENTAGE);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date CreatedDate = (Date)attributes.get("CreatedDate");

		if (CreatedDate != null) {
			setCreatedDate(CreatedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}
	}

	@Override
	public int getTOPUP_ID() {
		return _TOPUP_ID;
	}

	@Override
	public void setTOPUP_ID(int TOPUP_ID) {
		_TOPUP_ID = TOPUP_ID;
	}

	@Override
	public String getPOLICY_ID() {
		if (_POLICY_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _POLICY_ID;
		}
	}

	@Override
	public void setPOLICY_ID(String POLICY_ID) {
		_POLICY_ID = POLICY_ID;
	}

	@Override
	public int getQRC_ASR_ID() {
		return _QRC_ASR_ID;
	}

	@Override
	public void setQRC_ASR_ID(int QRC_ASR_ID) {
		_QRC_ASR_ID = QRC_ASR_ID;
	}

	@Override
	public int getFUND_ID() {
		return _FUND_ID;
	}

	@Override
	public void setFUND_ID(int FUND_ID) {
		_FUND_ID = FUND_ID;
	}

	@Override
	public double getFUND_VALUE() {
		return _FUND_VALUE;
	}

	@Override
	public void setFUND_VALUE(double FUND_VALUE) {
		_FUND_VALUE = FUND_VALUE;
	}

	@Override
	public double getTOPUP_VALUE() {
		return _TOPUP_VALUE;
	}

	@Override
	public void setTOPUP_VALUE(double TOPUP_VALUE) {
		_TOPUP_VALUE = TOPUP_VALUE;
	}

	@Override
	public double getTOT_VALUE() {
		return _TOT_VALUE;
	}

	@Override
	public void setTOT_VALUE(double TOT_VALUE) {
		_TOT_VALUE = TOT_VALUE;
	}

	@Override
	public double getTOPUP_PERCENTAGE() {
		return _TOPUP_PERCENTAGE;
	}

	@Override
	public void setTOPUP_PERCENTAGE(double TOPUP_PERCENTAGE) {
		_TOPUP_PERCENTAGE = TOPUP_PERCENTAGE;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	@Override
	public PolicyTopupDetails toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PolicyTopupDetails)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PolicyTopupDetailsImpl policyTopupDetailsImpl = new PolicyTopupDetailsImpl();

		policyTopupDetailsImpl.setTOPUP_ID(getTOPUP_ID());
		policyTopupDetailsImpl.setPOLICY_ID(getPOLICY_ID());
		policyTopupDetailsImpl.setQRC_ASR_ID(getQRC_ASR_ID());
		policyTopupDetailsImpl.setFUND_ID(getFUND_ID());
		policyTopupDetailsImpl.setFUND_VALUE(getFUND_VALUE());
		policyTopupDetailsImpl.setTOPUP_VALUE(getTOPUP_VALUE());
		policyTopupDetailsImpl.setTOT_VALUE(getTOT_VALUE());
		policyTopupDetailsImpl.setTOPUP_PERCENTAGE(getTOPUP_PERCENTAGE());
		policyTopupDetailsImpl.setCreatedBy(getCreatedBy());
		policyTopupDetailsImpl.setCreatedDate(getCreatedDate());
		policyTopupDetailsImpl.setModifiedBy(getModifiedBy());
		policyTopupDetailsImpl.setModifiedDate(getModifiedDate());

		policyTopupDetailsImpl.resetOriginalValues();

		return policyTopupDetailsImpl;
	}

	@Override
	public int compareTo(PolicyTopupDetails policyTopupDetails) {
		int primaryKey = policyTopupDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PolicyTopupDetails)) {
			return false;
		}

		PolicyTopupDetails policyTopupDetails = (PolicyTopupDetails)obj;

		int primaryKey = policyTopupDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PolicyTopupDetails> toCacheModel() {
		PolicyTopupDetailsCacheModel policyTopupDetailsCacheModel = new PolicyTopupDetailsCacheModel();

		policyTopupDetailsCacheModel.TOPUP_ID = getTOPUP_ID();

		policyTopupDetailsCacheModel.POLICY_ID = getPOLICY_ID();

		String POLICY_ID = policyTopupDetailsCacheModel.POLICY_ID;

		if ((POLICY_ID != null) && (POLICY_ID.length() == 0)) {
			policyTopupDetailsCacheModel.POLICY_ID = null;
		}

		policyTopupDetailsCacheModel.QRC_ASR_ID = getQRC_ASR_ID();

		policyTopupDetailsCacheModel.FUND_ID = getFUND_ID();

		policyTopupDetailsCacheModel.FUND_VALUE = getFUND_VALUE();

		policyTopupDetailsCacheModel.TOPUP_VALUE = getTOPUP_VALUE();

		policyTopupDetailsCacheModel.TOT_VALUE = getTOT_VALUE();

		policyTopupDetailsCacheModel.TOPUP_PERCENTAGE = getTOPUP_PERCENTAGE();

		policyTopupDetailsCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = policyTopupDetailsCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			policyTopupDetailsCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			policyTopupDetailsCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			policyTopupDetailsCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		policyTopupDetailsCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = policyTopupDetailsCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			policyTopupDetailsCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			policyTopupDetailsCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			policyTopupDetailsCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return policyTopupDetailsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{TOPUP_ID=");
		sb.append(getTOPUP_ID());
		sb.append(", POLICY_ID=");
		sb.append(getPOLICY_ID());
		sb.append(", QRC_ASR_ID=");
		sb.append(getQRC_ASR_ID());
		sb.append(", FUND_ID=");
		sb.append(getFUND_ID());
		sb.append(", FUND_VALUE=");
		sb.append(getFUND_VALUE());
		sb.append(", TOPUP_VALUE=");
		sb.append(getTOPUP_VALUE());
		sb.append(", TOT_VALUE=");
		sb.append(getTOT_VALUE());
		sb.append(", TOPUP_PERCENTAGE=");
		sb.append(getTOPUP_PERCENTAGE());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", CreatedDate=");
		sb.append(getCreatedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.PolicyTopupDetails");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>TOPUP_ID</column-name><column-value><![CDATA[");
		sb.append(getTOPUP_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POLICY_ID</column-name><column-value><![CDATA[");
		sb.append(getPOLICY_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>QRC_ASR_ID</column-name><column-value><![CDATA[");
		sb.append(getQRC_ASR_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FUND_ID</column-name><column-value><![CDATA[");
		sb.append(getFUND_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FUND_VALUE</column-name><column-value><![CDATA[");
		sb.append(getFUND_VALUE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TOPUP_VALUE</column-name><column-value><![CDATA[");
		sb.append(getTOPUP_VALUE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TOT_VALUE</column-name><column-value><![CDATA[");
		sb.append(getTOT_VALUE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TOPUP_PERCENTAGE</column-name><column-value><![CDATA[");
		sb.append(getTOPUP_PERCENTAGE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PolicyTopupDetails.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PolicyTopupDetails.class
		};
	private int _TOPUP_ID;
	private String _POLICY_ID;
	private int _QRC_ASR_ID;
	private int _FUND_ID;
	private double _FUND_VALUE;
	private double _TOPUP_VALUE;
	private double _TOT_VALUE;
	private double _TOPUP_PERCENTAGE;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;
	private PolicyTopupDetails _escapedModel;
}