/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.PolicyTopupDetails;
import com.ifli.rapid.service.PolicyTopupDetailsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the PolicyTopupDetails service. Represents a row in the &quot;policy_topup_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyTopupDetailsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see PolicyTopupDetailsImpl
 * @see com.ifli.rapid.model.PolicyTopupDetails
 * @generated
 */
public abstract class PolicyTopupDetailsBaseImpl
	extends PolicyTopupDetailsModelImpl implements PolicyTopupDetails {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy topup details model instance should use the {@link PolicyTopupDetails} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			PolicyTopupDetailsLocalServiceUtil.addPolicyTopupDetails(this);
		}
		else {
			PolicyTopupDetailsLocalServiceUtil.updatePolicyTopupDetails(this);
		}
	}
}