/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.ProofDocs;
import com.ifli.rapid.model.ProofDocsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ProofDocs service. Represents a row in the &quot;proof_docs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.ProofDocsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProofDocsImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see ProofDocsImpl
 * @see com.ifli.rapid.model.ProofDocs
 * @see com.ifli.rapid.model.ProofDocsModel
 * @generated
 */
public class ProofDocsModelImpl extends BaseModelImpl<ProofDocs>
	implements ProofDocsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a proof docs model instance should use the {@link com.ifli.rapid.model.ProofDocs} interface instead.
	 */
	public static final String TABLE_NAME = "proof_docs";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "DOC_TYPE", Types.VARCHAR },
			{ "DOC_NAME", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table proof_docs (ID LONG not null primary key,DOC_TYPE VARCHAR(75) null,DOC_NAME VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table proof_docs";
	public static final String ORDER_BY_JPQL = " ORDER BY proofDocs.ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY proof_docs.ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.ProofDocs"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.ProofDocs"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.ProofDocs"));

	public ProofDocsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProofDocs.class;
	}

	@Override
	public String getModelClassName() {
		return ProofDocs.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ID", getID());
		attributes.put("DOC_TYPE", getDOC_TYPE());
		attributes.put("DOC_NAME", getDOC_NAME());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ID = (Long)attributes.get("ID");

		if (ID != null) {
			setID(ID);
		}

		String DOC_TYPE = (String)attributes.get("DOC_TYPE");

		if (DOC_TYPE != null) {
			setDOC_TYPE(DOC_TYPE);
		}

		String DOC_NAME = (String)attributes.get("DOC_NAME");

		if (DOC_NAME != null) {
			setDOC_NAME(DOC_NAME);
		}
	}

	@Override
	public long getID() {
		return _ID;
	}

	@Override
	public void setID(long ID) {
		_ID = ID;
	}

	@Override
	public String getDOC_TYPE() {
		if (_DOC_TYPE == null) {
			return StringPool.BLANK;
		}
		else {
			return _DOC_TYPE;
		}
	}

	@Override
	public void setDOC_TYPE(String DOC_TYPE) {
		_DOC_TYPE = DOC_TYPE;
	}

	@Override
	public String getDOC_NAME() {
		if (_DOC_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _DOC_NAME;
		}
	}

	@Override
	public void setDOC_NAME(String DOC_NAME) {
		_DOC_NAME = DOC_NAME;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ProofDocs.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProofDocs toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ProofDocs)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProofDocsImpl proofDocsImpl = new ProofDocsImpl();

		proofDocsImpl.setID(getID());
		proofDocsImpl.setDOC_TYPE(getDOC_TYPE());
		proofDocsImpl.setDOC_NAME(getDOC_NAME());

		proofDocsImpl.resetOriginalValues();

		return proofDocsImpl;
	}

	@Override
	public int compareTo(ProofDocs proofDocs) {
		long primaryKey = proofDocs.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ProofDocs)) {
			return false;
		}

		ProofDocs proofDocs = (ProofDocs)obj;

		long primaryKey = proofDocs.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ProofDocs> toCacheModel() {
		ProofDocsCacheModel proofDocsCacheModel = new ProofDocsCacheModel();

		proofDocsCacheModel.ID = getID();

		proofDocsCacheModel.DOC_TYPE = getDOC_TYPE();

		String DOC_TYPE = proofDocsCacheModel.DOC_TYPE;

		if ((DOC_TYPE != null) && (DOC_TYPE.length() == 0)) {
			proofDocsCacheModel.DOC_TYPE = null;
		}

		proofDocsCacheModel.DOC_NAME = getDOC_NAME();

		String DOC_NAME = proofDocsCacheModel.DOC_NAME;

		if ((DOC_NAME != null) && (DOC_NAME.length() == 0)) {
			proofDocsCacheModel.DOC_NAME = null;
		}

		return proofDocsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{ID=");
		sb.append(getID());
		sb.append(", DOC_TYPE=");
		sb.append(getDOC_TYPE());
		sb.append(", DOC_NAME=");
		sb.append(getDOC_NAME());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.ProofDocs");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ID</column-name><column-value><![CDATA[");
		sb.append(getID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DOC_TYPE</column-name><column-value><![CDATA[");
		sb.append(getDOC_TYPE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DOC_NAME</column-name><column-value><![CDATA[");
		sb.append(getDOC_NAME());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ProofDocs.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ProofDocs.class
		};
	private long _ID;
	private String _DOC_TYPE;
	private String _DOC_NAME;
	private ProofDocs _escapedModel;
}