/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.QRCSubTypeMaster;
import com.ifli.rapid.model.QRCSubTypeMasterModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the QRCSubTypeMaster service. Represents a row in the &quot;QRC_SUBTYPE_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.QRCSubTypeMasterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QRCSubTypeMasterImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see QRCSubTypeMasterImpl
 * @see com.ifli.rapid.model.QRCSubTypeMaster
 * @see com.ifli.rapid.model.QRCSubTypeMasterModel
 * @generated
 */
public class QRCSubTypeMasterModelImpl extends BaseModelImpl<QRCSubTypeMaster>
	implements QRCSubTypeMasterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a q r c sub type master model instance should use the {@link com.ifli.rapid.model.QRCSubTypeMaster} interface instead.
	 */
	public static final String TABLE_NAME = "QRC_SUBTYPE_MASTER";
	public static final Object[][] TABLE_COLUMNS = {
			{ "QRC_SUB_TYPE_ID", Types.INTEGER },
			{ "QRC_TYPE_ID", Types.INTEGER },
			{ "SUB_TYPE_DESC", Types.VARCHAR },
			{ "ACTIVE_FLAG", Types.VARCHAR },
			{ "INSERTED_DATE", Types.TIMESTAMP },
			{ "INSERTED_BY", Types.VARCHAR },
			{ "UPDATED_DATE", Types.TIMESTAMP },
			{ "UPDATED_BY", Types.VARCHAR },
			{ "DELETED_DATE", Types.TIMESTAMP },
			{ "DELETED_BY", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table QRC_SUBTYPE_MASTER (QRC_SUB_TYPE_ID INTEGER not null primary key IDENTITY,QRC_TYPE_ID INTEGER,SUB_TYPE_DESC VARCHAR(75) null,ACTIVE_FLAG VARCHAR(75) null,INSERTED_DATE DATE null,INSERTED_BY VARCHAR(75) null,UPDATED_DATE DATE null,UPDATED_BY VARCHAR(75) null,DELETED_DATE DATE null,DELETED_BY VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table QRC_SUBTYPE_MASTER";
	public static final String ORDER_BY_JPQL = " ORDER BY qrcSubTypeMaster.QRC_SUB_TYPE_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY QRC_SUBTYPE_MASTER.QRC_SUB_TYPE_ID ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.QRCSubTypeMaster"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.QRCSubTypeMaster"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.QRCSubTypeMaster"));

	public QRCSubTypeMasterModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _QRC_SUB_TYPE_ID;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setQRC_SUB_TYPE_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _QRC_SUB_TYPE_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QRCSubTypeMaster.class;
	}

	@Override
	public String getModelClassName() {
		return QRCSubTypeMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("QRC_SUB_TYPE_ID", getQRC_SUB_TYPE_ID());
		attributes.put("QRC_TYPE_ID", getQRC_TYPE_ID());
		attributes.put("SUB_TYPE_DESC", getSUB_TYPE_DESC());
		attributes.put("ACTIVE_FLAG", getACTIVE_FLAG());
		attributes.put("INSERTED_DATE", getINSERTED_DATE());
		attributes.put("INSERTED_BY", getINSERTED_BY());
		attributes.put("UPDATED_DATE", getUPDATED_DATE());
		attributes.put("UPDATED_BY", getUPDATED_BY());
		attributes.put("DELETED_DATE", getDELETED_DATE());
		attributes.put("DELETED_BY", getDELETED_BY());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer QRC_SUB_TYPE_ID = (Integer)attributes.get("QRC_SUB_TYPE_ID");

		if (QRC_SUB_TYPE_ID != null) {
			setQRC_SUB_TYPE_ID(QRC_SUB_TYPE_ID);
		}

		Integer QRC_TYPE_ID = (Integer)attributes.get("QRC_TYPE_ID");

		if (QRC_TYPE_ID != null) {
			setQRC_TYPE_ID(QRC_TYPE_ID);
		}

		String SUB_TYPE_DESC = (String)attributes.get("SUB_TYPE_DESC");

		if (SUB_TYPE_DESC != null) {
			setSUB_TYPE_DESC(SUB_TYPE_DESC);
		}

		String ACTIVE_FLAG = (String)attributes.get("ACTIVE_FLAG");

		if (ACTIVE_FLAG != null) {
			setACTIVE_FLAG(ACTIVE_FLAG);
		}

		Date INSERTED_DATE = (Date)attributes.get("INSERTED_DATE");

		if (INSERTED_DATE != null) {
			setINSERTED_DATE(INSERTED_DATE);
		}

		String INSERTED_BY = (String)attributes.get("INSERTED_BY");

		if (INSERTED_BY != null) {
			setINSERTED_BY(INSERTED_BY);
		}

		Date UPDATED_DATE = (Date)attributes.get("UPDATED_DATE");

		if (UPDATED_DATE != null) {
			setUPDATED_DATE(UPDATED_DATE);
		}

		String UPDATED_BY = (String)attributes.get("UPDATED_BY");

		if (UPDATED_BY != null) {
			setUPDATED_BY(UPDATED_BY);
		}

		Date DELETED_DATE = (Date)attributes.get("DELETED_DATE");

		if (DELETED_DATE != null) {
			setDELETED_DATE(DELETED_DATE);
		}

		String DELETED_BY = (String)attributes.get("DELETED_BY");

		if (DELETED_BY != null) {
			setDELETED_BY(DELETED_BY);
		}
	}

	@Override
	public int getQRC_SUB_TYPE_ID() {
		return _QRC_SUB_TYPE_ID;
	}

	@Override
	public void setQRC_SUB_TYPE_ID(int QRC_SUB_TYPE_ID) {
		_QRC_SUB_TYPE_ID = QRC_SUB_TYPE_ID;
	}

	@Override
	public int getQRC_TYPE_ID() {
		return _QRC_TYPE_ID;
	}

	@Override
	public void setQRC_TYPE_ID(int QRC_TYPE_ID) {
		_QRC_TYPE_ID = QRC_TYPE_ID;
	}

	@Override
	public String getSUB_TYPE_DESC() {
		if (_SUB_TYPE_DESC == null) {
			return StringPool.BLANK;
		}
		else {
			return _SUB_TYPE_DESC;
		}
	}

	@Override
	public void setSUB_TYPE_DESC(String SUB_TYPE_DESC) {
		_SUB_TYPE_DESC = SUB_TYPE_DESC;
	}

	@Override
	public String getACTIVE_FLAG() {
		if (_ACTIVE_FLAG == null) {
			return StringPool.BLANK;
		}
		else {
			return _ACTIVE_FLAG;
		}
	}

	@Override
	public void setACTIVE_FLAG(String ACTIVE_FLAG) {
		_ACTIVE_FLAG = ACTIVE_FLAG;
	}

	@Override
	public Date getINSERTED_DATE() {
		return _INSERTED_DATE;
	}

	@Override
	public void setINSERTED_DATE(Date INSERTED_DATE) {
		_INSERTED_DATE = INSERTED_DATE;
	}

	@Override
	public String getINSERTED_BY() {
		if (_INSERTED_BY == null) {
			return StringPool.BLANK;
		}
		else {
			return _INSERTED_BY;
		}
	}

	@Override
	public void setINSERTED_BY(String INSERTED_BY) {
		_INSERTED_BY = INSERTED_BY;
	}

	@Override
	public Date getUPDATED_DATE() {
		return _UPDATED_DATE;
	}

	@Override
	public void setUPDATED_DATE(Date UPDATED_DATE) {
		_UPDATED_DATE = UPDATED_DATE;
	}

	@Override
	public String getUPDATED_BY() {
		if (_UPDATED_BY == null) {
			return StringPool.BLANK;
		}
		else {
			return _UPDATED_BY;
		}
	}

	@Override
	public void setUPDATED_BY(String UPDATED_BY) {
		_UPDATED_BY = UPDATED_BY;
	}

	@Override
	public Date getDELETED_DATE() {
		return _DELETED_DATE;
	}

	@Override
	public void setDELETED_DATE(Date DELETED_DATE) {
		_DELETED_DATE = DELETED_DATE;
	}

	@Override
	public String getDELETED_BY() {
		if (_DELETED_BY == null) {
			return StringPool.BLANK;
		}
		else {
			return _DELETED_BY;
		}
	}

	@Override
	public void setDELETED_BY(String DELETED_BY) {
		_DELETED_BY = DELETED_BY;
	}

	@Override
	public QRCSubTypeMaster toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QRCSubTypeMaster)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QRCSubTypeMasterImpl qrcSubTypeMasterImpl = new QRCSubTypeMasterImpl();

		qrcSubTypeMasterImpl.setQRC_SUB_TYPE_ID(getQRC_SUB_TYPE_ID());
		qrcSubTypeMasterImpl.setQRC_TYPE_ID(getQRC_TYPE_ID());
		qrcSubTypeMasterImpl.setSUB_TYPE_DESC(getSUB_TYPE_DESC());
		qrcSubTypeMasterImpl.setACTIVE_FLAG(getACTIVE_FLAG());
		qrcSubTypeMasterImpl.setINSERTED_DATE(getINSERTED_DATE());
		qrcSubTypeMasterImpl.setINSERTED_BY(getINSERTED_BY());
		qrcSubTypeMasterImpl.setUPDATED_DATE(getUPDATED_DATE());
		qrcSubTypeMasterImpl.setUPDATED_BY(getUPDATED_BY());
		qrcSubTypeMasterImpl.setDELETED_DATE(getDELETED_DATE());
		qrcSubTypeMasterImpl.setDELETED_BY(getDELETED_BY());

		qrcSubTypeMasterImpl.resetOriginalValues();

		return qrcSubTypeMasterImpl;
	}

	@Override
	public int compareTo(QRCSubTypeMaster qrcSubTypeMaster) {
		int primaryKey = qrcSubTypeMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QRCSubTypeMaster)) {
			return false;
		}

		QRCSubTypeMaster qrcSubTypeMaster = (QRCSubTypeMaster)obj;

		int primaryKey = qrcSubTypeMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QRCSubTypeMaster> toCacheModel() {
		QRCSubTypeMasterCacheModel qrcSubTypeMasterCacheModel = new QRCSubTypeMasterCacheModel();

		qrcSubTypeMasterCacheModel.QRC_SUB_TYPE_ID = getQRC_SUB_TYPE_ID();

		qrcSubTypeMasterCacheModel.QRC_TYPE_ID = getQRC_TYPE_ID();

		qrcSubTypeMasterCacheModel.SUB_TYPE_DESC = getSUB_TYPE_DESC();

		String SUB_TYPE_DESC = qrcSubTypeMasterCacheModel.SUB_TYPE_DESC;

		if ((SUB_TYPE_DESC != null) && (SUB_TYPE_DESC.length() == 0)) {
			qrcSubTypeMasterCacheModel.SUB_TYPE_DESC = null;
		}

		qrcSubTypeMasterCacheModel.ACTIVE_FLAG = getACTIVE_FLAG();

		String ACTIVE_FLAG = qrcSubTypeMasterCacheModel.ACTIVE_FLAG;

		if ((ACTIVE_FLAG != null) && (ACTIVE_FLAG.length() == 0)) {
			qrcSubTypeMasterCacheModel.ACTIVE_FLAG = null;
		}

		Date INSERTED_DATE = getINSERTED_DATE();

		if (INSERTED_DATE != null) {
			qrcSubTypeMasterCacheModel.INSERTED_DATE = INSERTED_DATE.getTime();
		}
		else {
			qrcSubTypeMasterCacheModel.INSERTED_DATE = Long.MIN_VALUE;
		}

		qrcSubTypeMasterCacheModel.INSERTED_BY = getINSERTED_BY();

		String INSERTED_BY = qrcSubTypeMasterCacheModel.INSERTED_BY;

		if ((INSERTED_BY != null) && (INSERTED_BY.length() == 0)) {
			qrcSubTypeMasterCacheModel.INSERTED_BY = null;
		}

		Date UPDATED_DATE = getUPDATED_DATE();

		if (UPDATED_DATE != null) {
			qrcSubTypeMasterCacheModel.UPDATED_DATE = UPDATED_DATE.getTime();
		}
		else {
			qrcSubTypeMasterCacheModel.UPDATED_DATE = Long.MIN_VALUE;
		}

		qrcSubTypeMasterCacheModel.UPDATED_BY = getUPDATED_BY();

		String UPDATED_BY = qrcSubTypeMasterCacheModel.UPDATED_BY;

		if ((UPDATED_BY != null) && (UPDATED_BY.length() == 0)) {
			qrcSubTypeMasterCacheModel.UPDATED_BY = null;
		}

		Date DELETED_DATE = getDELETED_DATE();

		if (DELETED_DATE != null) {
			qrcSubTypeMasterCacheModel.DELETED_DATE = DELETED_DATE.getTime();
		}
		else {
			qrcSubTypeMasterCacheModel.DELETED_DATE = Long.MIN_VALUE;
		}

		qrcSubTypeMasterCacheModel.DELETED_BY = getDELETED_BY();

		String DELETED_BY = qrcSubTypeMasterCacheModel.DELETED_BY;

		if ((DELETED_BY != null) && (DELETED_BY.length() == 0)) {
			qrcSubTypeMasterCacheModel.DELETED_BY = null;
		}

		return qrcSubTypeMasterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{QRC_SUB_TYPE_ID=");
		sb.append(getQRC_SUB_TYPE_ID());
		sb.append(", QRC_TYPE_ID=");
		sb.append(getQRC_TYPE_ID());
		sb.append(", SUB_TYPE_DESC=");
		sb.append(getSUB_TYPE_DESC());
		sb.append(", ACTIVE_FLAG=");
		sb.append(getACTIVE_FLAG());
		sb.append(", INSERTED_DATE=");
		sb.append(getINSERTED_DATE());
		sb.append(", INSERTED_BY=");
		sb.append(getINSERTED_BY());
		sb.append(", UPDATED_DATE=");
		sb.append(getUPDATED_DATE());
		sb.append(", UPDATED_BY=");
		sb.append(getUPDATED_BY());
		sb.append(", DELETED_DATE=");
		sb.append(getDELETED_DATE());
		sb.append(", DELETED_BY=");
		sb.append(getDELETED_BY());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.QRCSubTypeMaster");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>QRC_SUB_TYPE_ID</column-name><column-value><![CDATA[");
		sb.append(getQRC_SUB_TYPE_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>QRC_TYPE_ID</column-name><column-value><![CDATA[");
		sb.append(getQRC_TYPE_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SUB_TYPE_DESC</column-name><column-value><![CDATA[");
		sb.append(getSUB_TYPE_DESC());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ACTIVE_FLAG</column-name><column-value><![CDATA[");
		sb.append(getACTIVE_FLAG());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>INSERTED_DATE</column-name><column-value><![CDATA[");
		sb.append(getINSERTED_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>INSERTED_BY</column-name><column-value><![CDATA[");
		sb.append(getINSERTED_BY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATED_DATE</column-name><column-value><![CDATA[");
		sb.append(getUPDATED_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATED_BY</column-name><column-value><![CDATA[");
		sb.append(getUPDATED_BY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DELETED_DATE</column-name><column-value><![CDATA[");
		sb.append(getDELETED_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DELETED_BY</column-name><column-value><![CDATA[");
		sb.append(getDELETED_BY());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QRCSubTypeMaster.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QRCSubTypeMaster.class
		};
	private int _QRC_SUB_TYPE_ID;
	private int _QRC_TYPE_ID;
	private String _SUB_TYPE_DESC;
	private String _ACTIVE_FLAG;
	private Date _INSERTED_DATE;
	private String _INSERTED_BY;
	private Date _UPDATED_DATE;
	private String _UPDATED_BY;
	private Date _DELETED_DATE;
	private String _DELETED_BY;
	private QRCSubTypeMaster _escapedModel;
}