/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ifli.rapid.model.impl;

import com.ifli.rapid.model.RENEWAL_PREMIUM;
import com.ifli.rapid.model.RENEWAL_PREMIUMModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the RENEWAL_PREMIUM service. Represents a row in the &quot;HPRMRCP1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ifli.rapid.model.RENEWAL_PREMIUMModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RENEWAL_PREMIUMImpl}.
 * </p>
 *
 * @author Satya Kola
 * @see RENEWAL_PREMIUMImpl
 * @see com.ifli.rapid.model.RENEWAL_PREMIUM
 * @see com.ifli.rapid.model.RENEWAL_PREMIUMModel
 * @generated
 */
public class RENEWAL_PREMIUMModelImpl extends BaseModelImpl<RENEWAL_PREMIUM>
	implements RENEWAL_PREMIUMModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a r e n e w a l_ p r e m i u m model instance should use the {@link com.ifli.rapid.model.RENEWAL_PREMIUM} interface instead.
	 */
	public static final String TABLE_NAME = "HPRMRCP1";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID_old", Types.BIGINT },
			{ "LETTERCT", Types.VARCHAR },
			{ "LOCPATH", Types.VARCHAR },
			{ "DOCIDNUM", Types.VARCHAR },
			{ "CLNTNUM", Types.VARCHAR },
			{ "OwnerName", Types.VARCHAR },
			{ "Addrs5", Types.VARCHAR },
			{ "Postcode", Types.VARCHAR },
			{ "Document_Number", Types.VARCHAR },
			{ "ContrNo", Types.VARCHAR },
			{ "Next_Premium_due_Date", Types.VARCHAR },
			{ "Total_Premium", Types.VARCHAR },
			{ "MainCovr_Risk_Cess_Term", Types.VARCHAR },
			{ "MainCovr_Prem_Cess_Term", Types.VARCHAR },
			{ "Contract_Commencement_Date", Types.VARCHAR },
			{ "Billing_Date", Types.VARCHAR },
			{ "Payment_Desc", Types.VARCHAR },
			{ "Receipt_Date", Types.VARCHAR },
			{ "Payment_Mode", Types.VARCHAR },
			{ "Payment_Description", Types.VARCHAR },
			{ "Receipt_Amount", Types.VARCHAR },
			{ "Contract_Type", Types.VARCHAR },
			{ "Contract_Type_Desc", Types.VARCHAR },
			{ "Current_Bill_Frequency", Types.VARCHAR },
			{ "Suspense_Amount", Types.VARCHAR },
			{ "Footer_Details", Types.VARCHAR },
			{ "Addrs1", Types.VARCHAR },
			{ "Addrs2", Types.VARCHAR },
			{ "Addrs3", Types.VARCHAR },
			{ "Addrs4", Types.VARCHAR },
			{ "Temp_Rcptno", Types.VARCHAR },
			{ "Life_Name", Types.VARCHAR },
			{ "CAMPAIGN", Types.VARCHAR },
			{ "Agent_Bank_Branch_Code", Types.VARCHAR },
			{ "Agent_Branch_name", Types.VARCHAR },
			{ "Agent_Bank_name", Types.VARCHAR },
			{ "Mobile_phone", Types.VARCHAR },
			{ "Email_id", Types.VARCHAR },
			{ "CreateDate", Types.VARCHAR },
			{ "BatchMode", Types.VARCHAR },
			{ "Status", Types.VARCHAR },
			{ "LastProcessedDate", Types.VARCHAR },
			{ "MobilePhoneNo", Types.VARCHAR },
			{ "Cheque_Number", Types.VARCHAR },
			{ "Bank_Name", Types.VARCHAR },
			{ "EmailAddr", Types.VARCHAR },
			{ "ID", Types.INTEGER },
			{ "BDM", Types.VARCHAR },
			{ "Term", Types.VARCHAR },
			{ "Campaign_Code", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table HPRMRCP1 (ID_old LONG not null primary key,LETTERCT VARCHAR(75) null,LOCPATH VARCHAR(75) null,DOCIDNUM VARCHAR(75) null,CLNTNUM VARCHAR(75) null,OwnerName VARCHAR(75) null,Addrs5 VARCHAR(75) null,Postcode VARCHAR(75) null,Document_Number VARCHAR(75) null,ContrNo VARCHAR(75) null,Next_Premium_due_Date VARCHAR(75) null,Total_Premium VARCHAR(75) null,MainCovr_Risk_Cess_Term VARCHAR(75) null,MainCovr_Prem_Cess_Term VARCHAR(75) null,Contract_Commencement_Date VARCHAR(75) null,Billing_Date VARCHAR(75) null,Payment_Desc VARCHAR(75) null,Receipt_Date VARCHAR(75) null,Payment_Mode VARCHAR(75) null,Payment_Description VARCHAR(75) null,Receipt_Amount VARCHAR(75) null,Contract_Type VARCHAR(75) null,Contract_Type_Desc VARCHAR(75) null,Current_Bill_Frequency VARCHAR(75) null,Suspense_Amount VARCHAR(75) null,Footer_Details VARCHAR(75) null,Addrs1 VARCHAR(75) null,Addrs2 VARCHAR(75) null,Addrs3 VARCHAR(75) null,Addrs4 VARCHAR(75) null,Temp_Rcptno VARCHAR(75) null,Life_Name VARCHAR(75) null,CAMPAIGN VARCHAR(75) null,Agent_Bank_Branch_Code VARCHAR(75) null,Agent_Branch_name VARCHAR(75) null,Agent_Bank_name VARCHAR(75) null,Mobile_phone VARCHAR(75) null,Email_id VARCHAR(75) null,CreateDate VARCHAR(75) null,BatchMode VARCHAR(75) null,Status VARCHAR(75) null,LastProcessedDate VARCHAR(75) null,MobilePhoneNo VARCHAR(75) null,Cheque_Number VARCHAR(75) null,Bank_Name VARCHAR(75) null,EmailAddr VARCHAR(75) null,ID INTEGER,BDM VARCHAR(75) null,Term VARCHAR(75) null,Campaign_Code VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table HPRMRCP1";
	public static final String ORDER_BY_JPQL = " ORDER BY renewal_premium.ID_old ASC";
	public static final String ORDER_BY_SQL = " ORDER BY HPRMRCP1.ID_old ASC";
	public static final String DATA_SOURCE = "servicesDataSource";
	public static final String SESSION_FACTORY = "servicesSessionFactory";
	public static final String TX_MANAGER = "servicesTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ifli.rapid.model.RENEWAL_PREMIUM"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ifli.rapid.model.RENEWAL_PREMIUM"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ifli.rapid.model.RENEWAL_PREMIUM"),
			true);
	public static long CONTRNO_COLUMN_BITMASK = 1L;
	public static long RECEIPT_DATE_COLUMN_BITMASK = 2L;
	public static long ID_OLD_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ifli.rapid.model.RENEWAL_PREMIUM"));

	public RENEWAL_PREMIUMModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ID_old;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setID_old(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ID_old;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RENEWAL_PREMIUM.class;
	}

	@Override
	public String getModelClassName() {
		return RENEWAL_PREMIUM.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ID_old", getID_old());
		attributes.put("LETTERCT", getLETTERCT());
		attributes.put("LOCPATH", getLOCPATH());
		attributes.put("DOCIDNUM", getDOCIDNUM());
		attributes.put("CLNTNUM", getCLNTNUM());
		attributes.put("OwnerName", getOwnerName());
		attributes.put("Addrs5", getAddrs5());
		attributes.put("Postcode", getPostcode());
		attributes.put("Document_Number", getDocument_Number());
		attributes.put("ContrNo", getContrNo());
		attributes.put("Next_Premium_due_Date", getNext_Premium_due_Date());
		attributes.put("Total_Premium", getTotal_Premium());
		attributes.put("MainCovr_Risk_Cess_Term", getMainCovr_Risk_Cess_Term());
		attributes.put("MainCovr_Prem_Cess_Term", getMainCovr_Prem_Cess_Term());
		attributes.put("Contract_Commencement_Date",
			getContract_Commencement_Date());
		attributes.put("Billing_Date", getBilling_Date());
		attributes.put("Payment_Desc", getPayment_Desc());
		attributes.put("Receipt_Date", getReceipt_Date());
		attributes.put("Payment_Mode", getPayment_Mode());
		attributes.put("Payment_Description", getPayment_Description());
		attributes.put("Receipt_Amount", getReceipt_Amount());
		attributes.put("Contract_Type", getContract_Type());
		attributes.put("Contract_Type_Desc", getContract_Type_Desc());
		attributes.put("Current_Bill_Frequency", getCurrent_Bill_Frequency());
		attributes.put("Suspense_Amount", getSuspense_Amount());
		attributes.put("Footer_Details", getFooter_Details());
		attributes.put("Addrs1", getAddrs1());
		attributes.put("Addrs2", getAddrs2());
		attributes.put("Addrs3", getAddrs3());
		attributes.put("Addrs4", getAddrs4());
		attributes.put("Temp_Rcptno", getTemp_Rcptno());
		attributes.put("Life_Name", getLife_Name());
		attributes.put("CAMPAIGN", getCAMPAIGN());
		attributes.put("Agent_Bank_Branch_Code", getAgent_Bank_Branch_Code());
		attributes.put("Agent_Branch_name", getAgent_Branch_name());
		attributes.put("Agent_Bank_name", getAgent_Bank_name());
		attributes.put("Mobile_phone", getMobile_phone());
		attributes.put("Email_id", getEmail_id());
		attributes.put("CreateDate", getCreateDate());
		attributes.put("BatchMode", getBatchMode());
		attributes.put("Status", getStatus());
		attributes.put("LastProcessedDate", getLastProcessedDate());
		attributes.put("MobilePhoneNo", getMobilePhoneNo());
		attributes.put("Cheque_Number", getCheque_Number());
		attributes.put("Bank_Name", getBank_Name());
		attributes.put("EmailAddr", getEmailAddr());
		attributes.put("ID", getID());
		attributes.put("BDM", getBDM());
		attributes.put("Term", getTerm());
		attributes.put("Campaign_Code", getCampaign_Code());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ID_old = (Long)attributes.get("ID_old");

		if (ID_old != null) {
			setID_old(ID_old);
		}

		String LETTERCT = (String)attributes.get("LETTERCT");

		if (LETTERCT != null) {
			setLETTERCT(LETTERCT);
		}

		String LOCPATH = (String)attributes.get("LOCPATH");

		if (LOCPATH != null) {
			setLOCPATH(LOCPATH);
		}

		String DOCIDNUM = (String)attributes.get("DOCIDNUM");

		if (DOCIDNUM != null) {
			setDOCIDNUM(DOCIDNUM);
		}

		String CLNTNUM = (String)attributes.get("CLNTNUM");

		if (CLNTNUM != null) {
			setCLNTNUM(CLNTNUM);
		}

		String OwnerName = (String)attributes.get("OwnerName");

		if (OwnerName != null) {
			setOwnerName(OwnerName);
		}

		String Addrs5 = (String)attributes.get("Addrs5");

		if (Addrs5 != null) {
			setAddrs5(Addrs5);
		}

		String Postcode = (String)attributes.get("Postcode");

		if (Postcode != null) {
			setPostcode(Postcode);
		}

		String Document_Number = (String)attributes.get("Document_Number");

		if (Document_Number != null) {
			setDocument_Number(Document_Number);
		}

		String ContrNo = (String)attributes.get("ContrNo");

		if (ContrNo != null) {
			setContrNo(ContrNo);
		}

		String Next_Premium_due_Date = (String)attributes.get(
				"Next_Premium_due_Date");

		if (Next_Premium_due_Date != null) {
			setNext_Premium_due_Date(Next_Premium_due_Date);
		}

		String Total_Premium = (String)attributes.get("Total_Premium");

		if (Total_Premium != null) {
			setTotal_Premium(Total_Premium);
		}

		String MainCovr_Risk_Cess_Term = (String)attributes.get(
				"MainCovr_Risk_Cess_Term");

		if (MainCovr_Risk_Cess_Term != null) {
			setMainCovr_Risk_Cess_Term(MainCovr_Risk_Cess_Term);
		}

		String MainCovr_Prem_Cess_Term = (String)attributes.get(
				"MainCovr_Prem_Cess_Term");

		if (MainCovr_Prem_Cess_Term != null) {
			setMainCovr_Prem_Cess_Term(MainCovr_Prem_Cess_Term);
		}

		String Contract_Commencement_Date = (String)attributes.get(
				"Contract_Commencement_Date");

		if (Contract_Commencement_Date != null) {
			setContract_Commencement_Date(Contract_Commencement_Date);
		}

		String Billing_Date = (String)attributes.get("Billing_Date");

		if (Billing_Date != null) {
			setBilling_Date(Billing_Date);
		}

		String Payment_Desc = (String)attributes.get("Payment_Desc");

		if (Payment_Desc != null) {
			setPayment_Desc(Payment_Desc);
		}

		String Receipt_Date = (String)attributes.get("Receipt_Date");

		if (Receipt_Date != null) {
			setReceipt_Date(Receipt_Date);
		}

		String Payment_Mode = (String)attributes.get("Payment_Mode");

		if (Payment_Mode != null) {
			setPayment_Mode(Payment_Mode);
		}

		String Payment_Description = (String)attributes.get(
				"Payment_Description");

		if (Payment_Description != null) {
			setPayment_Description(Payment_Description);
		}

		String Receipt_Amount = (String)attributes.get("Receipt_Amount");

		if (Receipt_Amount != null) {
			setReceipt_Amount(Receipt_Amount);
		}

		String Contract_Type = (String)attributes.get("Contract_Type");

		if (Contract_Type != null) {
			setContract_Type(Contract_Type);
		}

		String Contract_Type_Desc = (String)attributes.get("Contract_Type_Desc");

		if (Contract_Type_Desc != null) {
			setContract_Type_Desc(Contract_Type_Desc);
		}

		String Current_Bill_Frequency = (String)attributes.get(
				"Current_Bill_Frequency");

		if (Current_Bill_Frequency != null) {
			setCurrent_Bill_Frequency(Current_Bill_Frequency);
		}

		String Suspense_Amount = (String)attributes.get("Suspense_Amount");

		if (Suspense_Amount != null) {
			setSuspense_Amount(Suspense_Amount);
		}

		String Footer_Details = (String)attributes.get("Footer_Details");

		if (Footer_Details != null) {
			setFooter_Details(Footer_Details);
		}

		String Addrs1 = (String)attributes.get("Addrs1");

		if (Addrs1 != null) {
			setAddrs1(Addrs1);
		}

		String Addrs2 = (String)attributes.get("Addrs2");

		if (Addrs2 != null) {
			setAddrs2(Addrs2);
		}

		String Addrs3 = (String)attributes.get("Addrs3");

		if (Addrs3 != null) {
			setAddrs3(Addrs3);
		}

		String Addrs4 = (String)attributes.get("Addrs4");

		if (Addrs4 != null) {
			setAddrs4(Addrs4);
		}

		String Temp_Rcptno = (String)attributes.get("Temp_Rcptno");

		if (Temp_Rcptno != null) {
			setTemp_Rcptno(Temp_Rcptno);
		}

		String Life_Name = (String)attributes.get("Life_Name");

		if (Life_Name != null) {
			setLife_Name(Life_Name);
		}

		String CAMPAIGN = (String)attributes.get("CAMPAIGN");

		if (CAMPAIGN != null) {
			setCAMPAIGN(CAMPAIGN);
		}

		String Agent_Bank_Branch_Code = (String)attributes.get(
				"Agent_Bank_Branch_Code");

		if (Agent_Bank_Branch_Code != null) {
			setAgent_Bank_Branch_Code(Agent_Bank_Branch_Code);
		}

		String Agent_Branch_name = (String)attributes.get("Agent_Branch_name");

		if (Agent_Branch_name != null) {
			setAgent_Branch_name(Agent_Branch_name);
		}

		String Agent_Bank_name = (String)attributes.get("Agent_Bank_name");

		if (Agent_Bank_name != null) {
			setAgent_Bank_name(Agent_Bank_name);
		}

		String Mobile_phone = (String)attributes.get("Mobile_phone");

		if (Mobile_phone != null) {
			setMobile_phone(Mobile_phone);
		}

		String Email_id = (String)attributes.get("Email_id");

		if (Email_id != null) {
			setEmail_id(Email_id);
		}

		String CreateDate = (String)attributes.get("CreateDate");

		if (CreateDate != null) {
			setCreateDate(CreateDate);
		}

		String BatchMode = (String)attributes.get("BatchMode");

		if (BatchMode != null) {
			setBatchMode(BatchMode);
		}

		String Status = (String)attributes.get("Status");

		if (Status != null) {
			setStatus(Status);
		}

		String LastProcessedDate = (String)attributes.get("LastProcessedDate");

		if (LastProcessedDate != null) {
			setLastProcessedDate(LastProcessedDate);
		}

		String MobilePhoneNo = (String)attributes.get("MobilePhoneNo");

		if (MobilePhoneNo != null) {
			setMobilePhoneNo(MobilePhoneNo);
		}

		String Cheque_Number = (String)attributes.get("Cheque_Number");

		if (Cheque_Number != null) {
			setCheque_Number(Cheque_Number);
		}

		String Bank_Name = (String)attributes.get("Bank_Name");

		if (Bank_Name != null) {
			setBank_Name(Bank_Name);
		}

		String EmailAddr = (String)attributes.get("EmailAddr");

		if (EmailAddr != null) {
			setEmailAddr(EmailAddr);
		}

		Integer ID = (Integer)attributes.get("ID");

		if (ID != null) {
			setID(ID);
		}

		String BDM = (String)attributes.get("BDM");

		if (BDM != null) {
			setBDM(BDM);
		}

		String Term = (String)attributes.get("Term");

		if (Term != null) {
			setTerm(Term);
		}

		String Campaign_Code = (String)attributes.get("Campaign_Code");

		if (Campaign_Code != null) {
			setCampaign_Code(Campaign_Code);
		}
	}

	@Override
	public long getID_old() {
		return _ID_old;
	}

	@Override
	public void setID_old(long ID_old) {
		_ID_old = ID_old;
	}

	@Override
	public String getLETTERCT() {
		if (_LETTERCT == null) {
			return StringPool.BLANK;
		}
		else {
			return _LETTERCT;
		}
	}

	@Override
	public void setLETTERCT(String LETTERCT) {
		_LETTERCT = LETTERCT;
	}

	@Override
	public String getLOCPATH() {
		if (_LOCPATH == null) {
			return StringPool.BLANK;
		}
		else {
			return _LOCPATH;
		}
	}

	@Override
	public void setLOCPATH(String LOCPATH) {
		_LOCPATH = LOCPATH;
	}

	@Override
	public String getDOCIDNUM() {
		if (_DOCIDNUM == null) {
			return StringPool.BLANK;
		}
		else {
			return _DOCIDNUM;
		}
	}

	@Override
	public void setDOCIDNUM(String DOCIDNUM) {
		_DOCIDNUM = DOCIDNUM;
	}

	@Override
	public String getCLNTNUM() {
		if (_CLNTNUM == null) {
			return StringPool.BLANK;
		}
		else {
			return _CLNTNUM;
		}
	}

	@Override
	public void setCLNTNUM(String CLNTNUM) {
		_CLNTNUM = CLNTNUM;
	}

	@Override
	public String getOwnerName() {
		if (_OwnerName == null) {
			return StringPool.BLANK;
		}
		else {
			return _OwnerName;
		}
	}

	@Override
	public void setOwnerName(String OwnerName) {
		_OwnerName = OwnerName;
	}

	@Override
	public String getAddrs5() {
		if (_Addrs5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _Addrs5;
		}
	}

	@Override
	public void setAddrs5(String Addrs5) {
		_Addrs5 = Addrs5;
	}

	@Override
	public String getPostcode() {
		if (_Postcode == null) {
			return StringPool.BLANK;
		}
		else {
			return _Postcode;
		}
	}

	@Override
	public void setPostcode(String Postcode) {
		_Postcode = Postcode;
	}

	@Override
	public String getDocument_Number() {
		if (_Document_Number == null) {
			return StringPool.BLANK;
		}
		else {
			return _Document_Number;
		}
	}

	@Override
	public void setDocument_Number(String Document_Number) {
		_Document_Number = Document_Number;
	}

	@Override
	public String getContrNo() {
		if (_ContrNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _ContrNo;
		}
	}

	@Override
	public void setContrNo(String ContrNo) {
		_columnBitmask |= CONTRNO_COLUMN_BITMASK;

		if (_originalContrNo == null) {
			_originalContrNo = _ContrNo;
		}

		_ContrNo = ContrNo;
	}

	public String getOriginalContrNo() {
		return GetterUtil.getString(_originalContrNo);
	}

	@Override
	public String getNext_Premium_due_Date() {
		if (_Next_Premium_due_Date == null) {
			return StringPool.BLANK;
		}
		else {
			return _Next_Premium_due_Date;
		}
	}

	@Override
	public void setNext_Premium_due_Date(String Next_Premium_due_Date) {
		_Next_Premium_due_Date = Next_Premium_due_Date;
	}

	@Override
	public String getTotal_Premium() {
		if (_Total_Premium == null) {
			return StringPool.BLANK;
		}
		else {
			return _Total_Premium;
		}
	}

	@Override
	public void setTotal_Premium(String Total_Premium) {
		_Total_Premium = Total_Premium;
	}

	@Override
	public String getMainCovr_Risk_Cess_Term() {
		if (_MainCovr_Risk_Cess_Term == null) {
			return StringPool.BLANK;
		}
		else {
			return _MainCovr_Risk_Cess_Term;
		}
	}

	@Override
	public void setMainCovr_Risk_Cess_Term(String MainCovr_Risk_Cess_Term) {
		_MainCovr_Risk_Cess_Term = MainCovr_Risk_Cess_Term;
	}

	@Override
	public String getMainCovr_Prem_Cess_Term() {
		if (_MainCovr_Prem_Cess_Term == null) {
			return StringPool.BLANK;
		}
		else {
			return _MainCovr_Prem_Cess_Term;
		}
	}

	@Override
	public void setMainCovr_Prem_Cess_Term(String MainCovr_Prem_Cess_Term) {
		_MainCovr_Prem_Cess_Term = MainCovr_Prem_Cess_Term;
	}

	@Override
	public String getContract_Commencement_Date() {
		if (_Contract_Commencement_Date == null) {
			return StringPool.BLANK;
		}
		else {
			return _Contract_Commencement_Date;
		}
	}

	@Override
	public void setContract_Commencement_Date(String Contract_Commencement_Date) {
		_Contract_Commencement_Date = Contract_Commencement_Date;
	}

	@Override
	public String getBilling_Date() {
		if (_Billing_Date == null) {
			return StringPool.BLANK;
		}
		else {
			return _Billing_Date;
		}
	}

	@Override
	public void setBilling_Date(String Billing_Date) {
		_Billing_Date = Billing_Date;
	}

	@Override
	public String getPayment_Desc() {
		if (_Payment_Desc == null) {
			return StringPool.BLANK;
		}
		else {
			return _Payment_Desc;
		}
	}

	@Override
	public void setPayment_Desc(String Payment_Desc) {
		_Payment_Desc = Payment_Desc;
	}

	@Override
	public String getReceipt_Date() {
		if (_Receipt_Date == null) {
			return StringPool.BLANK;
		}
		else {
			return _Receipt_Date;
		}
	}

	@Override
	public void setReceipt_Date(String Receipt_Date) {
		_columnBitmask |= RECEIPT_DATE_COLUMN_BITMASK;

		if (_originalReceipt_Date == null) {
			_originalReceipt_Date = _Receipt_Date;
		}

		_Receipt_Date = Receipt_Date;
	}

	public String getOriginalReceipt_Date() {
		return GetterUtil.getString(_originalReceipt_Date);
	}

	@Override
	public String getPayment_Mode() {
		if (_Payment_Mode == null) {
			return StringPool.BLANK;
		}
		else {
			return _Payment_Mode;
		}
	}

	@Override
	public void setPayment_Mode(String Payment_Mode) {
		_Payment_Mode = Payment_Mode;
	}

	@Override
	public String getPayment_Description() {
		if (_Payment_Description == null) {
			return StringPool.BLANK;
		}
		else {
			return _Payment_Description;
		}
	}

	@Override
	public void setPayment_Description(String Payment_Description) {
		_Payment_Description = Payment_Description;
	}

	@Override
	public String getReceipt_Amount() {
		if (_Receipt_Amount == null) {
			return StringPool.BLANK;
		}
		else {
			return _Receipt_Amount;
		}
	}

	@Override
	public void setReceipt_Amount(String Receipt_Amount) {
		_Receipt_Amount = Receipt_Amount;
	}

	@Override
	public String getContract_Type() {
		if (_Contract_Type == null) {
			return StringPool.BLANK;
		}
		else {
			return _Contract_Type;
		}
	}

	@Override
	public void setContract_Type(String Contract_Type) {
		_Contract_Type = Contract_Type;
	}

	@Override
	public String getContract_Type_Desc() {
		if (_Contract_Type_Desc == null) {
			return StringPool.BLANK;
		}
		else {
			return _Contract_Type_Desc;
		}
	}

	@Override
	public void setContract_Type_Desc(String Contract_Type_Desc) {
		_Contract_Type_Desc = Contract_Type_Desc;
	}

	@Override
	public String getCurrent_Bill_Frequency() {
		if (_Current_Bill_Frequency == null) {
			return StringPool.BLANK;
		}
		else {
			return _Current_Bill_Frequency;
		}
	}

	@Override
	public void setCurrent_Bill_Frequency(String Current_Bill_Frequency) {
		_Current_Bill_Frequency = Current_Bill_Frequency;
	}

	@Override
	public String getSuspense_Amount() {
		if (_Suspense_Amount == null) {
			return StringPool.BLANK;
		}
		else {
			return _Suspense_Amount;
		}
	}

	@Override
	public void setSuspense_Amount(String Suspense_Amount) {
		_Suspense_Amount = Suspense_Amount;
	}

	@Override
	public String getFooter_Details() {
		if (_Footer_Details == null) {
			return StringPool.BLANK;
		}
		else {
			return _Footer_Details;
		}
	}

	@Override
	public void setFooter_Details(String Footer_Details) {
		_Footer_Details = Footer_Details;
	}

	@Override
	public String getAddrs1() {
		if (_Addrs1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _Addrs1;
		}
	}

	@Override
	public void setAddrs1(String Addrs1) {
		_Addrs1 = Addrs1;
	}

	@Override
	public String getAddrs2() {
		if (_Addrs2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _Addrs2;
		}
	}

	@Override
	public void setAddrs2(String Addrs2) {
		_Addrs2 = Addrs2;
	}

	@Override
	public String getAddrs3() {
		if (_Addrs3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _Addrs3;
		}
	}

	@Override
	public void setAddrs3(String Addrs3) {
		_Addrs3 = Addrs3;
	}

	@Override
	public String getAddrs4() {
		if (_Addrs4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _Addrs4;
		}
	}

	@Override
	public void setAddrs4(String Addrs4) {
		_Addrs4 = Addrs4;
	}

	@Override
	public String getTemp_Rcptno() {
		if (_Temp_Rcptno == null) {
			return StringPool.BLANK;
		}
		else {
			return _Temp_Rcptno;
		}
	}

	@Override
	public void setTemp_Rcptno(String Temp_Rcptno) {
		_Temp_Rcptno = Temp_Rcptno;
	}

	@Override
	public String getLife_Name() {
		if (_Life_Name == null) {
			return StringPool.BLANK;
		}
		else {
			return _Life_Name;
		}
	}

	@Override
	public void setLife_Name(String Life_Name) {
		_Life_Name = Life_Name;
	}

	@Override
	public String getCAMPAIGN() {
		if (_CAMPAIGN == null) {
			return StringPool.BLANK;
		}
		else {
			return _CAMPAIGN;
		}
	}

	@Override
	public void setCAMPAIGN(String CAMPAIGN) {
		_CAMPAIGN = CAMPAIGN;
	}

	@Override
	public String getAgent_Bank_Branch_Code() {
		if (_Agent_Bank_Branch_Code == null) {
			return StringPool.BLANK;
		}
		else {
			return _Agent_Bank_Branch_Code;
		}
	}

	@Override
	public void setAgent_Bank_Branch_Code(String Agent_Bank_Branch_Code) {
		_Agent_Bank_Branch_Code = Agent_Bank_Branch_Code;
	}

	@Override
	public String getAgent_Branch_name() {
		if (_Agent_Branch_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _Agent_Branch_name;
		}
	}

	@Override
	public void setAgent_Branch_name(String Agent_Branch_name) {
		_Agent_Branch_name = Agent_Branch_name;
	}

	@Override
	public String getAgent_Bank_name() {
		if (_Agent_Bank_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _Agent_Bank_name;
		}
	}

	@Override
	public void setAgent_Bank_name(String Agent_Bank_name) {
		_Agent_Bank_name = Agent_Bank_name;
	}

	@Override
	public String getMobile_phone() {
		if (_Mobile_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _Mobile_phone;
		}
	}

	@Override
	public void setMobile_phone(String Mobile_phone) {
		_Mobile_phone = Mobile_phone;
	}

	@Override
	public String getEmail_id() {
		if (_Email_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _Email_id;
		}
	}

	@Override
	public void setEmail_id(String Email_id) {
		_Email_id = Email_id;
	}

	@Override
	public String getCreateDate() {
		if (_CreateDate == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreateDate;
		}
	}

	@Override
	public void setCreateDate(String CreateDate) {
		_CreateDate = CreateDate;
	}

	@Override
	public String getBatchMode() {
		if (_BatchMode == null) {
			return StringPool.BLANK;
		}
		else {
			return _BatchMode;
		}
	}

	@Override
	public void setBatchMode(String BatchMode) {
		_BatchMode = BatchMode;
	}

	@Override
	public String getStatus() {
		if (_Status == null) {
			return StringPool.BLANK;
		}
		else {
			return _Status;
		}
	}

	@Override
	public void setStatus(String Status) {
		_Status = Status;
	}

	@Override
	public String getLastProcessedDate() {
		if (_LastProcessedDate == null) {
			return StringPool.BLANK;
		}
		else {
			return _LastProcessedDate;
		}
	}

	@Override
	public void setLastProcessedDate(String LastProcessedDate) {
		_LastProcessedDate = LastProcessedDate;
	}

	@Override
	public String getMobilePhoneNo() {
		if (_MobilePhoneNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _MobilePhoneNo;
		}
	}

	@Override
	public void setMobilePhoneNo(String MobilePhoneNo) {
		_MobilePhoneNo = MobilePhoneNo;
	}

	@Override
	public String getCheque_Number() {
		if (_Cheque_Number == null) {
			return StringPool.BLANK;
		}
		else {
			return _Cheque_Number;
		}
	}

	@Override
	public void setCheque_Number(String Cheque_Number) {
		_Cheque_Number = Cheque_Number;
	}

	@Override
	public String getBank_Name() {
		if (_Bank_Name == null) {
			return StringPool.BLANK;
		}
		else {
			return _Bank_Name;
		}
	}

	@Override
	public void setBank_Name(String Bank_Name) {
		_Bank_Name = Bank_Name;
	}

	@Override
	public String getEmailAddr() {
		if (_EmailAddr == null) {
			return StringPool.BLANK;
		}
		else {
			return _EmailAddr;
		}
	}

	@Override
	public void setEmailAddr(String EmailAddr) {
		_EmailAddr = EmailAddr;
	}

	@Override
	public int getID() {
		return _ID;
	}

	@Override
	public void setID(int ID) {
		_ID = ID;
	}

	@Override
	public String getBDM() {
		if (_BDM == null) {
			return StringPool.BLANK;
		}
		else {
			return _BDM;
		}
	}

	@Override
	public void setBDM(String BDM) {
		_BDM = BDM;
	}

	@Override
	public String getTerm() {
		if (_Term == null) {
			return StringPool.BLANK;
		}
		else {
			return _Term;
		}
	}

	@Override
	public void setTerm(String Term) {
		_Term = Term;
	}

	@Override
	public String getCampaign_Code() {
		if (_Campaign_Code == null) {
			return StringPool.BLANK;
		}
		else {
			return _Campaign_Code;
		}
	}

	@Override
	public void setCampaign_Code(String Campaign_Code) {
		_Campaign_Code = Campaign_Code;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RENEWAL_PREMIUM.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RENEWAL_PREMIUM toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RENEWAL_PREMIUM)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RENEWAL_PREMIUMImpl renewal_premiumImpl = new RENEWAL_PREMIUMImpl();

		renewal_premiumImpl.setID_old(getID_old());
		renewal_premiumImpl.setLETTERCT(getLETTERCT());
		renewal_premiumImpl.setLOCPATH(getLOCPATH());
		renewal_premiumImpl.setDOCIDNUM(getDOCIDNUM());
		renewal_premiumImpl.setCLNTNUM(getCLNTNUM());
		renewal_premiumImpl.setOwnerName(getOwnerName());
		renewal_premiumImpl.setAddrs5(getAddrs5());
		renewal_premiumImpl.setPostcode(getPostcode());
		renewal_premiumImpl.setDocument_Number(getDocument_Number());
		renewal_premiumImpl.setContrNo(getContrNo());
		renewal_premiumImpl.setNext_Premium_due_Date(getNext_Premium_due_Date());
		renewal_premiumImpl.setTotal_Premium(getTotal_Premium());
		renewal_premiumImpl.setMainCovr_Risk_Cess_Term(getMainCovr_Risk_Cess_Term());
		renewal_premiumImpl.setMainCovr_Prem_Cess_Term(getMainCovr_Prem_Cess_Term());
		renewal_premiumImpl.setContract_Commencement_Date(getContract_Commencement_Date());
		renewal_premiumImpl.setBilling_Date(getBilling_Date());
		renewal_premiumImpl.setPayment_Desc(getPayment_Desc());
		renewal_premiumImpl.setReceipt_Date(getReceipt_Date());
		renewal_premiumImpl.setPayment_Mode(getPayment_Mode());
		renewal_premiumImpl.setPayment_Description(getPayment_Description());
		renewal_premiumImpl.setReceipt_Amount(getReceipt_Amount());
		renewal_premiumImpl.setContract_Type(getContract_Type());
		renewal_premiumImpl.setContract_Type_Desc(getContract_Type_Desc());
		renewal_premiumImpl.setCurrent_Bill_Frequency(getCurrent_Bill_Frequency());
		renewal_premiumImpl.setSuspense_Amount(getSuspense_Amount());
		renewal_premiumImpl.setFooter_Details(getFooter_Details());
		renewal_premiumImpl.setAddrs1(getAddrs1());
		renewal_premiumImpl.setAddrs2(getAddrs2());
		renewal_premiumImpl.setAddrs3(getAddrs3());
		renewal_premiumImpl.setAddrs4(getAddrs4());
		renewal_premiumImpl.setTemp_Rcptno(getTemp_Rcptno());
		renewal_premiumImpl.setLife_Name(getLife_Name());
		renewal_premiumImpl.setCAMPAIGN(getCAMPAIGN());
		renewal_premiumImpl.setAgent_Bank_Branch_Code(getAgent_Bank_Branch_Code());
		renewal_premiumImpl.setAgent_Branch_name(getAgent_Branch_name());
		renewal_premiumImpl.setAgent_Bank_name(getAgent_Bank_name());
		renewal_premiumImpl.setMobile_phone(getMobile_phone());
		renewal_premiumImpl.setEmail_id(getEmail_id());
		renewal_premiumImpl.setCreateDate(getCreateDate());
		renewal_premiumImpl.setBatchMode(getBatchMode());
		renewal_premiumImpl.setStatus(getStatus());
		renewal_premiumImpl.setLastProcessedDate(getLastProcessedDate());
		renewal_premiumImpl.setMobilePhoneNo(getMobilePhoneNo());
		renewal_premiumImpl.setCheque_Number(getCheque_Number());
		renewal_premiumImpl.setBank_Name(getBank_Name());
		renewal_premiumImpl.setEmailAddr(getEmailAddr());
		renewal_premiumImpl.setID(getID());
		renewal_premiumImpl.setBDM(getBDM());
		renewal_premiumImpl.setTerm(getTerm());
		renewal_premiumImpl.setCampaign_Code(getCampaign_Code());

		renewal_premiumImpl.resetOriginalValues();

		return renewal_premiumImpl;
	}

	@Override
	public int compareTo(RENEWAL_PREMIUM renewal_premium) {
		long primaryKey = renewal_premium.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RENEWAL_PREMIUM)) {
			return false;
		}

		RENEWAL_PREMIUM renewal_premium = (RENEWAL_PREMIUM)obj;

		long primaryKey = renewal_premium.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		RENEWAL_PREMIUMModelImpl renewal_premiumModelImpl = this;

		renewal_premiumModelImpl._originalContrNo = renewal_premiumModelImpl._ContrNo;

		renewal_premiumModelImpl._originalReceipt_Date = renewal_premiumModelImpl._Receipt_Date;

		renewal_premiumModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<RENEWAL_PREMIUM> toCacheModel() {
		RENEWAL_PREMIUMCacheModel renewal_premiumCacheModel = new RENEWAL_PREMIUMCacheModel();

		renewal_premiumCacheModel.ID_old = getID_old();

		renewal_premiumCacheModel.LETTERCT = getLETTERCT();

		String LETTERCT = renewal_premiumCacheModel.LETTERCT;

		if ((LETTERCT != null) && (LETTERCT.length() == 0)) {
			renewal_premiumCacheModel.LETTERCT = null;
		}

		renewal_premiumCacheModel.LOCPATH = getLOCPATH();

		String LOCPATH = renewal_premiumCacheModel.LOCPATH;

		if ((LOCPATH != null) && (LOCPATH.length() == 0)) {
			renewal_premiumCacheModel.LOCPATH = null;
		}

		renewal_premiumCacheModel.DOCIDNUM = getDOCIDNUM();

		String DOCIDNUM = renewal_premiumCacheModel.DOCIDNUM;

		if ((DOCIDNUM != null) && (DOCIDNUM.length() == 0)) {
			renewal_premiumCacheModel.DOCIDNUM = null;
		}

		renewal_premiumCacheModel.CLNTNUM = getCLNTNUM();

		String CLNTNUM = renewal_premiumCacheModel.CLNTNUM;

		if ((CLNTNUM != null) && (CLNTNUM.length() == 0)) {
			renewal_premiumCacheModel.CLNTNUM = null;
		}

		renewal_premiumCacheModel.OwnerName = getOwnerName();

		String OwnerName = renewal_premiumCacheModel.OwnerName;

		if ((OwnerName != null) && (OwnerName.length() == 0)) {
			renewal_premiumCacheModel.OwnerName = null;
		}

		renewal_premiumCacheModel.Addrs5 = getAddrs5();

		String Addrs5 = renewal_premiumCacheModel.Addrs5;

		if ((Addrs5 != null) && (Addrs5.length() == 0)) {
			renewal_premiumCacheModel.Addrs5 = null;
		}

		renewal_premiumCacheModel.Postcode = getPostcode();

		String Postcode = renewal_premiumCacheModel.Postcode;

		if ((Postcode != null) && (Postcode.length() == 0)) {
			renewal_premiumCacheModel.Postcode = null;
		}

		renewal_premiumCacheModel.Document_Number = getDocument_Number();

		String Document_Number = renewal_premiumCacheModel.Document_Number;

		if ((Document_Number != null) && (Document_Number.length() == 0)) {
			renewal_premiumCacheModel.Document_Number = null;
		}

		renewal_premiumCacheModel.ContrNo = getContrNo();

		String ContrNo = renewal_premiumCacheModel.ContrNo;

		if ((ContrNo != null) && (ContrNo.length() == 0)) {
			renewal_premiumCacheModel.ContrNo = null;
		}

		renewal_premiumCacheModel.Next_Premium_due_Date = getNext_Premium_due_Date();

		String Next_Premium_due_Date = renewal_premiumCacheModel.Next_Premium_due_Date;

		if ((Next_Premium_due_Date != null) &&
				(Next_Premium_due_Date.length() == 0)) {
			renewal_premiumCacheModel.Next_Premium_due_Date = null;
		}

		renewal_premiumCacheModel.Total_Premium = getTotal_Premium();

		String Total_Premium = renewal_premiumCacheModel.Total_Premium;

		if ((Total_Premium != null) && (Total_Premium.length() == 0)) {
			renewal_premiumCacheModel.Total_Premium = null;
		}

		renewal_premiumCacheModel.MainCovr_Risk_Cess_Term = getMainCovr_Risk_Cess_Term();

		String MainCovr_Risk_Cess_Term = renewal_premiumCacheModel.MainCovr_Risk_Cess_Term;

		if ((MainCovr_Risk_Cess_Term != null) &&
				(MainCovr_Risk_Cess_Term.length() == 0)) {
			renewal_premiumCacheModel.MainCovr_Risk_Cess_Term = null;
		}

		renewal_premiumCacheModel.MainCovr_Prem_Cess_Term = getMainCovr_Prem_Cess_Term();

		String MainCovr_Prem_Cess_Term = renewal_premiumCacheModel.MainCovr_Prem_Cess_Term;

		if ((MainCovr_Prem_Cess_Term != null) &&
				(MainCovr_Prem_Cess_Term.length() == 0)) {
			renewal_premiumCacheModel.MainCovr_Prem_Cess_Term = null;
		}

		renewal_premiumCacheModel.Contract_Commencement_Date = getContract_Commencement_Date();

		String Contract_Commencement_Date = renewal_premiumCacheModel.Contract_Commencement_Date;

		if ((Contract_Commencement_Date != null) &&
				(Contract_Commencement_Date.length() == 0)) {
			renewal_premiumCacheModel.Contract_Commencement_Date = null;
		}

		renewal_premiumCacheModel.Billing_Date = getBilling_Date();

		String Billing_Date = renewal_premiumCacheModel.Billing_Date;

		if ((Billing_Date != null) && (Billing_Date.length() == 0)) {
			renewal_premiumCacheModel.Billing_Date = null;
		}

		renewal_premiumCacheModel.Payment_Desc = getPayment_Desc();

		String Payment_Desc = renewal_premiumCacheModel.Payment_Desc;

		if ((Payment_Desc != null) && (Payment_Desc.length() == 0)) {
			renewal_premiumCacheModel.Payment_Desc = null;
		}

		renewal_premiumCacheModel.Receipt_Date = getReceipt_Date();

		String Receipt_Date = renewal_premiumCacheModel.Receipt_Date;

		if ((Receipt_Date != null) && (Receipt_Date.length() == 0)) {
			renewal_premiumCacheModel.Receipt_Date = null;
		}

		renewal_premiumCacheModel.Payment_Mode = getPayment_Mode();

		String Payment_Mode = renewal_premiumCacheModel.Payment_Mode;

		if ((Payment_Mode != null) && (Payment_Mode.length() == 0)) {
			renewal_premiumCacheModel.Payment_Mode = null;
		}

		renewal_premiumCacheModel.Payment_Description = getPayment_Description();

		String Payment_Description = renewal_premiumCacheModel.Payment_Description;

		if ((Payment_Description != null) &&
				(Payment_Description.length() == 0)) {
			renewal_premiumCacheModel.Payment_Description = null;
		}

		renewal_premiumCacheModel.Receipt_Amount = getReceipt_Amount();

		String Receipt_Amount = renewal_premiumCacheModel.Receipt_Amount;

		if ((Receipt_Amount != null) && (Receipt_Amount.length() == 0)) {
			renewal_premiumCacheModel.Receipt_Amount = null;
		}

		renewal_premiumCacheModel.Contract_Type = getContract_Type();

		String Contract_Type = renewal_premiumCacheModel.Contract_Type;

		if ((Contract_Type != null) && (Contract_Type.length() == 0)) {
			renewal_premiumCacheModel.Contract_Type = null;
		}

		renewal_premiumCacheModel.Contract_Type_Desc = getContract_Type_Desc();

		String Contract_Type_Desc = renewal_premiumCacheModel.Contract_Type_Desc;

		if ((Contract_Type_Desc != null) && (Contract_Type_Desc.length() == 0)) {
			renewal_premiumCacheModel.Contract_Type_Desc = null;
		}

		renewal_premiumCacheModel.Current_Bill_Frequency = getCurrent_Bill_Frequency();

		String Current_Bill_Frequency = renewal_premiumCacheModel.Current_Bill_Frequency;

		if ((Current_Bill_Frequency != null) &&
				(Current_Bill_Frequency.length() == 0)) {
			renewal_premiumCacheModel.Current_Bill_Frequency = null;
		}

		renewal_premiumCacheModel.Suspense_Amount = getSuspense_Amount();

		String Suspense_Amount = renewal_premiumCacheModel.Suspense_Amount;

		if ((Suspense_Amount != null) && (Suspense_Amount.length() == 0)) {
			renewal_premiumCacheModel.Suspense_Amount = null;
		}

		renewal_premiumCacheModel.Footer_Details = getFooter_Details();

		String Footer_Details = renewal_premiumCacheModel.Footer_Details;

		if ((Footer_Details != null) && (Footer_Details.length() == 0)) {
			renewal_premiumCacheModel.Footer_Details = null;
		}

		renewal_premiumCacheModel.Addrs1 = getAddrs1();

		String Addrs1 = renewal_premiumCacheModel.Addrs1;

		if ((Addrs1 != null) && (Addrs1.length() == 0)) {
			renewal_premiumCacheModel.Addrs1 = null;
		}

		renewal_premiumCacheModel.Addrs2 = getAddrs2();

		String Addrs2 = renewal_premiumCacheModel.Addrs2;

		if ((Addrs2 != null) && (Addrs2.length() == 0)) {
			renewal_premiumCacheModel.Addrs2 = null;
		}

		renewal_premiumCacheModel.Addrs3 = getAddrs3();

		String Addrs3 = renewal_premiumCacheModel.Addrs3;

		if ((Addrs3 != null) && (Addrs3.length() == 0)) {
			renewal_premiumCacheModel.Addrs3 = null;
		}

		renewal_premiumCacheModel.Addrs4 = getAddrs4();

		String Addrs4 = renewal_premiumCacheModel.Addrs4;

		if ((Addrs4 != null) && (Addrs4.length() == 0)) {
			renewal_premiumCacheModel.Addrs4 = null;
		}

		renewal_premiumCacheModel.Temp_Rcptno = getTemp_Rcptno();

		String Temp_Rcptno = renewal_premiumCacheModel.Temp_Rcptno;

		if ((Temp_Rcptno != null) && (Temp_Rcptno.length() == 0)) {
			renewal_premiumCacheModel.Temp_Rcptno = null;
		}

		renewal_premiumCacheModel.Life_Name = getLife_Name();

		String Life_Name = renewal_premiumCacheModel.Life_Name;

		if ((Life_Name != null) && (Life_Name.length() == 0)) {
			renewal_premiumCacheModel.Life_Name = null;
		}

		renewal_premiumCacheModel.CAMPAIGN = getCAMPAIGN();

		String CAMPAIGN = renewal_premiumCacheModel.CAMPAIGN;

		if ((CAMPAIGN != null) && (CAMPAIGN.length() == 0)) {
			renewal_premiumCacheModel.CAMPAIGN = null;
		}

		renewal_premiumCacheModel.Agent_Bank_Branch_Code = getAgent_Bank_Branch_Code();

		String Agent_Bank_Branch_Code = renewal_premiumCacheModel.Agent_Bank_Branch_Code;

		if ((Agent_Bank_Branch_Code != null) &&
				(Agent_Bank_Branch_Code.length() == 0)) {
			renewal_premiumCacheModel.Agent_Bank_Branch_Code = null;
		}

		renewal_premiumCacheModel.Agent_Branch_name = getAgent_Branch_name();

		String Agent_Branch_name = renewal_premiumCacheModel.Agent_Branch_name;

		if ((Agent_Branch_name != null) && (Agent_Branch_name.length() == 0)) {
			renewal_premiumCacheModel.Agent_Branch_name = null;
		}

		renewal_premiumCacheModel.Agent_Bank_name = getAgent_Bank_name();

		String Agent_Bank_name = renewal_premiumCacheModel.Agent_Bank_name;

		if ((Agent_Bank_name != null) && (Agent_Bank_name.length() == 0)) {
			renewal_premiumCacheModel.Agent_Bank_name = null;
		}

		renewal_premiumCacheModel.Mobile_phone = getMobile_phone();

		String Mobile_phone = renewal_premiumCacheModel.Mobile_phone;

		if ((Mobile_phone != null) && (Mobile_phone.length() == 0)) {
			renewal_premiumCacheModel.Mobile_phone = null;
		}

		renewal_premiumCacheModel.Email_id = getEmail_id();

		String Email_id = renewal_premiumCacheModel.Email_id;

		if ((Email_id != null) && (Email_id.length() == 0)) {
			renewal_premiumCacheModel.Email_id = null;
		}

		renewal_premiumCacheModel.CreateDate = getCreateDate();

		String CreateDate = renewal_premiumCacheModel.CreateDate;

		if ((CreateDate != null) && (CreateDate.length() == 0)) {
			renewal_premiumCacheModel.CreateDate = null;
		}

		renewal_premiumCacheModel.BatchMode = getBatchMode();

		String BatchMode = renewal_premiumCacheModel.BatchMode;

		if ((BatchMode != null) && (BatchMode.length() == 0)) {
			renewal_premiumCacheModel.BatchMode = null;
		}

		renewal_premiumCacheModel.Status = getStatus();

		String Status = renewal_premiumCacheModel.Status;

		if ((Status != null) && (Status.length() == 0)) {
			renewal_premiumCacheModel.Status = null;
		}

		renewal_premiumCacheModel.LastProcessedDate = getLastProcessedDate();

		String LastProcessedDate = renewal_premiumCacheModel.LastProcessedDate;

		if ((LastProcessedDate != null) && (LastProcessedDate.length() == 0)) {
			renewal_premiumCacheModel.LastProcessedDate = null;
		}

		renewal_premiumCacheModel.MobilePhoneNo = getMobilePhoneNo();

		String MobilePhoneNo = renewal_premiumCacheModel.MobilePhoneNo;

		if ((MobilePhoneNo != null) && (MobilePhoneNo.length() == 0)) {
			renewal_premiumCacheModel.MobilePhoneNo = null;
		}

		renewal_premiumCacheModel.Cheque_Number = getCheque_Number();

		String Cheque_Number = renewal_premiumCacheModel.Cheque_Number;

		if ((Cheque_Number != null) && (Cheque_Number.length() == 0)) {
			renewal_premiumCacheModel.Cheque_Number = null;
		}

		renewal_premiumCacheModel.Bank_Name = getBank_Name();

		String Bank_Name = renewal_premiumCacheModel.Bank_Name;

		if ((Bank_Name != null) && (Bank_Name.length() == 0)) {
			renewal_premiumCacheModel.Bank_Name = null;
		}

		renewal_premiumCacheModel.EmailAddr = getEmailAddr();

		String EmailAddr = renewal_premiumCacheModel.EmailAddr;

		if ((EmailAddr != null) && (EmailAddr.length() == 0)) {
			renewal_premiumCacheModel.EmailAddr = null;
		}

		renewal_premiumCacheModel.ID = getID();

		renewal_premiumCacheModel.BDM = getBDM();

		String BDM = renewal_premiumCacheModel.BDM;

		if ((BDM != null) && (BDM.length() == 0)) {
			renewal_premiumCacheModel.BDM = null;
		}

		renewal_premiumCacheModel.Term = getTerm();

		String Term = renewal_premiumCacheModel.Term;

		if ((Term != null) && (Term.length() == 0)) {
			renewal_premiumCacheModel.Term = null;
		}

		renewal_premiumCacheModel.Campaign_Code = getCampaign_Code();

		String Campaign_Code = renewal_premiumCacheModel.Campaign_Code;

		if ((Campaign_Code != null) && (Campaign_Code.length() == 0)) {
			renewal_premiumCacheModel.Campaign_Code = null;
		}

		return renewal_premiumCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(101);

		sb.append("{ID_old=");
		sb.append(getID_old());
		sb.append(", LETTERCT=");
		sb.append(getLETTERCT());
		sb.append(", LOCPATH=");
		sb.append(getLOCPATH());
		sb.append(", DOCIDNUM=");
		sb.append(getDOCIDNUM());
		sb.append(", CLNTNUM=");
		sb.append(getCLNTNUM());
		sb.append(", OwnerName=");
		sb.append(getOwnerName());
		sb.append(", Addrs5=");
		sb.append(getAddrs5());
		sb.append(", Postcode=");
		sb.append(getPostcode());
		sb.append(", Document_Number=");
		sb.append(getDocument_Number());
		sb.append(", ContrNo=");
		sb.append(getContrNo());
		sb.append(", Next_Premium_due_Date=");
		sb.append(getNext_Premium_due_Date());
		sb.append(", Total_Premium=");
		sb.append(getTotal_Premium());
		sb.append(", MainCovr_Risk_Cess_Term=");
		sb.append(getMainCovr_Risk_Cess_Term());
		sb.append(", MainCovr_Prem_Cess_Term=");
		sb.append(getMainCovr_Prem_Cess_Term());
		sb.append(", Contract_Commencement_Date=");
		sb.append(getContract_Commencement_Date());
		sb.append(", Billing_Date=");
		sb.append(getBilling_Date());
		sb.append(", Payment_Desc=");
		sb.append(getPayment_Desc());
		sb.append(", Receipt_Date=");
		sb.append(getReceipt_Date());
		sb.append(", Payment_Mode=");
		sb.append(getPayment_Mode());
		sb.append(", Payment_Description=");
		sb.append(getPayment_Description());
		sb.append(", Receipt_Amount=");
		sb.append(getReceipt_Amount());
		sb.append(", Contract_Type=");
		sb.append(getContract_Type());
		sb.append(", Contract_Type_Desc=");
		sb.append(getContract_Type_Desc());
		sb.append(", Current_Bill_Frequency=");
		sb.append(getCurrent_Bill_Frequency());
		sb.append(", Suspense_Amount=");
		sb.append(getSuspense_Amount());
		sb.append(", Footer_Details=");
		sb.append(getFooter_Details());
		sb.append(", Addrs1=");
		sb.append(getAddrs1());
		sb.append(", Addrs2=");
		sb.append(getAddrs2());
		sb.append(", Addrs3=");
		sb.append(getAddrs3());
		sb.append(", Addrs4=");
		sb.append(getAddrs4());
		sb.append(", Temp_Rcptno=");
		sb.append(getTemp_Rcptno());
		sb.append(", Life_Name=");
		sb.append(getLife_Name());
		sb.append(", CAMPAIGN=");
		sb.append(getCAMPAIGN());
		sb.append(", Agent_Bank_Branch_Code=");
		sb.append(getAgent_Bank_Branch_Code());
		sb.append(", Agent_Branch_name=");
		sb.append(getAgent_Branch_name());
		sb.append(", Agent_Bank_name=");
		sb.append(getAgent_Bank_name());
		sb.append(", Mobile_phone=");
		sb.append(getMobile_phone());
		sb.append(", Email_id=");
		sb.append(getEmail_id());
		sb.append(", CreateDate=");
		sb.append(getCreateDate());
		sb.append(", BatchMode=");
		sb.append(getBatchMode());
		sb.append(", Status=");
		sb.append(getStatus());
		sb.append(", LastProcessedDate=");
		sb.append(getLastProcessedDate());
		sb.append(", MobilePhoneNo=");
		sb.append(getMobilePhoneNo());
		sb.append(", Cheque_Number=");
		sb.append(getCheque_Number());
		sb.append(", Bank_Name=");
		sb.append(getBank_Name());
		sb.append(", EmailAddr=");
		sb.append(getEmailAddr());
		sb.append(", ID=");
		sb.append(getID());
		sb.append(", BDM=");
		sb.append(getBDM());
		sb.append(", Term=");
		sb.append(getTerm());
		sb.append(", Campaign_Code=");
		sb.append(getCampaign_Code());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(154);

		sb.append("<model><model-name>");
		sb.append("com.ifli.rapid.model.RENEWAL_PREMIUM");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ID_old</column-name><column-value><![CDATA[");
		sb.append(getID_old());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LETTERCT</column-name><column-value><![CDATA[");
		sb.append(getLETTERCT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LOCPATH</column-name><column-value><![CDATA[");
		sb.append(getLOCPATH());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DOCIDNUM</column-name><column-value><![CDATA[");
		sb.append(getDOCIDNUM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CLNTNUM</column-name><column-value><![CDATA[");
		sb.append(getCLNTNUM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>OwnerName</column-name><column-value><![CDATA[");
		sb.append(getOwnerName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Addrs5</column-name><column-value><![CDATA[");
		sb.append(getAddrs5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Postcode</column-name><column-value><![CDATA[");
		sb.append(getPostcode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Document_Number</column-name><column-value><![CDATA[");
		sb.append(getDocument_Number());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ContrNo</column-name><column-value><![CDATA[");
		sb.append(getContrNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Next_Premium_due_Date</column-name><column-value><![CDATA[");
		sb.append(getNext_Premium_due_Date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Total_Premium</column-name><column-value><![CDATA[");
		sb.append(getTotal_Premium());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MainCovr_Risk_Cess_Term</column-name><column-value><![CDATA[");
		sb.append(getMainCovr_Risk_Cess_Term());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MainCovr_Prem_Cess_Term</column-name><column-value><![CDATA[");
		sb.append(getMainCovr_Prem_Cess_Term());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Contract_Commencement_Date</column-name><column-value><![CDATA[");
		sb.append(getContract_Commencement_Date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Billing_Date</column-name><column-value><![CDATA[");
		sb.append(getBilling_Date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Payment_Desc</column-name><column-value><![CDATA[");
		sb.append(getPayment_Desc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Receipt_Date</column-name><column-value><![CDATA[");
		sb.append(getReceipt_Date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Payment_Mode</column-name><column-value><![CDATA[");
		sb.append(getPayment_Mode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Payment_Description</column-name><column-value><![CDATA[");
		sb.append(getPayment_Description());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Receipt_Amount</column-name><column-value><![CDATA[");
		sb.append(getReceipt_Amount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Contract_Type</column-name><column-value><![CDATA[");
		sb.append(getContract_Type());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Contract_Type_Desc</column-name><column-value><![CDATA[");
		sb.append(getContract_Type_Desc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Current_Bill_Frequency</column-name><column-value><![CDATA[");
		sb.append(getCurrent_Bill_Frequency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Suspense_Amount</column-name><column-value><![CDATA[");
		sb.append(getSuspense_Amount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Footer_Details</column-name><column-value><![CDATA[");
		sb.append(getFooter_Details());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Addrs1</column-name><column-value><![CDATA[");
		sb.append(getAddrs1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Addrs2</column-name><column-value><![CDATA[");
		sb.append(getAddrs2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Addrs3</column-name><column-value><![CDATA[");
		sb.append(getAddrs3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Addrs4</column-name><column-value><![CDATA[");
		sb.append(getAddrs4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Temp_Rcptno</column-name><column-value><![CDATA[");
		sb.append(getTemp_Rcptno());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Life_Name</column-name><column-value><![CDATA[");
		sb.append(getLife_Name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CAMPAIGN</column-name><column-value><![CDATA[");
		sb.append(getCAMPAIGN());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Agent_Bank_Branch_Code</column-name><column-value><![CDATA[");
		sb.append(getAgent_Bank_Branch_Code());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Agent_Branch_name</column-name><column-value><![CDATA[");
		sb.append(getAgent_Branch_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Agent_Bank_name</column-name><column-value><![CDATA[");
		sb.append(getAgent_Bank_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Mobile_phone</column-name><column-value><![CDATA[");
		sb.append(getMobile_phone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Email_id</column-name><column-value><![CDATA[");
		sb.append(getEmail_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreateDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>BatchMode</column-name><column-value><![CDATA[");
		sb.append(getBatchMode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LastProcessedDate</column-name><column-value><![CDATA[");
		sb.append(getLastProcessedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MobilePhoneNo</column-name><column-value><![CDATA[");
		sb.append(getMobilePhoneNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Cheque_Number</column-name><column-value><![CDATA[");
		sb.append(getCheque_Number());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Bank_Name</column-name><column-value><![CDATA[");
		sb.append(getBank_Name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>EmailAddr</column-name><column-value><![CDATA[");
		sb.append(getEmailAddr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ID</column-name><column-value><![CDATA[");
		sb.append(getID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>BDM</column-name><column-value><![CDATA[");
		sb.append(getBDM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Term</column-name><column-value><![CDATA[");
		sb.append(getTerm());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Campaign_Code</column-name><column-value><![CDATA[");
		sb.append(getCampaign_Code());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = RENEWAL_PREMIUM.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			RENEWAL_PREMIUM.class
		};
	private long _ID_old;
	private String _LETTERCT;
	private String _LOCPATH;
	private String _DOCIDNUM;
	private String _CLNTNUM;
	private String _OwnerName;
	private String _Addrs5;
	private String _Postcode;
	private String _Document_Number;
	private String _ContrNo;
	private String _originalContrNo;
	private String _Next_Premium_due_Date;
	private String _Total_Premium;
	private String _MainCovr_Risk_Cess_Term;
	private String _MainCovr_Prem_Cess_Term;
	private String _Contract_Commencement_Date;
	private String _Billing_Date;
	private String _Payment_Desc;
	private String _Receipt_Date;
	private String _originalReceipt_Date;
	private String _Payment_Mode;
	private String _Payment_Description;
	private String _Receipt_Amount;
	private String _Contract_Type;
	private String _Contract_Type_Desc;
	private String _Current_Bill_Frequency;
	private String _Suspense_Amount;
	private String _Footer_Details;
	private String _Addrs1;
	private String _Addrs2;
	private String _Addrs3;
	private String _Addrs4;
	private String _Temp_Rcptno;
	private String _Life_Name;
	private String _CAMPAIGN;
	private String _Agent_Bank_Branch_Code;
	private String _Agent_Branch_name;
	private String _Agent_Bank_name;
	private String _Mobile_phone;
	private String _Email_id;
	private String _CreateDate;
	private String _BatchMode;
	private String _Status;
	private String _LastProcessedDate;
	private String _MobilePhoneNo;
	private String _Cheque_Number;
	private String _Bank_Name;
	private String _EmailAddr;
	private int _ID;
	private String _BDM;
	private String _Term;
	private String _Campaign_Code;
	private long _columnBitmask;
	private RENEWAL_PREMIUM _escapedModel;
}